### ISSUE TITLE
I've lost my up/down arrows (git push/pull) - anyone with any advice?

### ISSUE THREAD

**Issue by dstroot** [sindresorhus/pure#101]
Not sure how to track this down - it worked initially.  Now it doesn't.  Not very helpful I know...

```sh
skeleton git/master
❯ git-wtf
Local branch: master
[ ] NOT in sync with remote (you should push)
    - Updated Dependencies [4a1896f]
Remote branch: origin/master (https://github.com/dstroot/skeleton.git)
[x] in sync with local

skeleton git/master
❯
```

It does recognize a dirty repository:
```sh
.dotfiles/ruby git/master*
❯
```

**Comment by sindresorhus** [comment]
After a upgrade of Pure? What version/commit of Pure are you using?

**Comment by dstroot** [comment]
From package.json:  "version": "2.67.0",

Full disclosure:
- I am using .oh-my-zsh with pure symlinked in from my global npm directory.
- I am using zsh-syntax-highlighting as recommended. Cloned into .oh-my-zsh/custom/plugins.  I disabled it to see if it was an issue but no change.  
- Font is "source code pro-light"

**Comment by dstroot** [comment]
I am officially an idiot today.  My link broke so zsh was picking up the "pure" lookalike included with .oh-my-zsh!  I fixed my link and all is well:

```
~/.dotfiles master*    ⇡
❯
```
