### ISSUE TITLE
Pure is very slow when using in cdnjs' repo

### ISSUE THREAD

**Issue by nesk** [sindresorhus/pure#102]
I just forked [cdnjs' repo](https://github.com/cdnjs/cdnjs) and each command takes ~25s to execute when using pure. I disabled remote checking (`PURE_GIT_PULL`) and untracked files checking (`PURE_GIT_UNTRACKED_DIRTY `) but it doesn't bring any improvements.

Am I missing something?

**Comment by sindresorhus** [comment]
Yeah, that's painful. git get's really slow on large repos. That option only enables a faster mode, it doesn't disable dirty checking all together.

I've been thinking and instead of introducing yet another option I could make the dirty-checking timeout after some predefined time, like 1 second. That way it would never annoyingly block for a long time, but also don't require an option.

**Comment by Nesk** [comment]
I'm totally for this timeout, but the user should be aware when it has been reached (for example, with a yellow prompt character).

It seems like there is a “not-so-complex” solution [on this page](https://digitalelf.net/2013/08/timeout-in-a-shell-script/), however I doesn't seem to work very well with zsh, unlike the author is saying.

**Comment by sindresorhus** [comment]
> I'm totally for this timeout, but the user should be aware when it has been reached (for example, with a yellow prompt character).

Agreed.

**Comment by paulirish** [comment]
Dirty checking is about 2.6x faster with this:

```sh
git diff --no-ext-diff --quiet --exit-code
```

ref: https://github.com/git/git/blob/355d4e1739d1e88561ac04d2a2423c2aa93693d9/contrib/completion/git-prompt.sh#L475

**Comment by arthurvr** [comment]
Thanks, @paulirish! Awesomesauce! Makes sense when working with this kind of repos (chromium repo is even worse). I'm +1 on a timeout.

**Comment by paulirish** [comment]
in my case i'm going to blacklist chromium & blink for dirty checking. less
robust but easier to manage.​

**Comment by sindresorhus** [comment]
This should be a faster in 1.0.0:
https://github.com/sindresorhus/pure/releases/tag/1.0.0

If a git status takes longer than 2 second, it will rely on cached result for 30 minutes. This is configurable: https://github.com/sindresorhus/pure#pure_git_delay_dirty_check

Though I opened a new issue about improving the dirty check: https://github.com/sindresorhus/pure/issues/115

-

// @mafredri
