### ISSUE TITLE
Pure won't allow GIT_TERMINAL_PROMPT to persist or be overriden

### ISSUE THREAD

**Issue by kevinSuttle** [sindresorhus/pure#111]
See: https://github.com/github/git-lfs/issues/209#issuecomment-93778291

**Comment by kevinSuttle** [comment]
Example, after full uninstall, shell logout/login, and reinstall via NPM.
````
❯ export GIT_TERMINAL_PROMPT=1

❯ echo $GIT_TERMINAL_PROMPT
0
```

**Comment by mafredri** [comment]
I cannot reproduce this, could it be something else that you have in your zsh configuration? Like running prompt setup every time?

**Comment by kevinSuttle** [comment]
Not sure. Here are my dotfiles. https://github.com/kevinSuttle/dotfiles/blob/master/zshenv#L33

**Comment by mafredri** [comment]
Here's your problem: https://github.com/kevinSuttle/dotfiles/blob/master/zshrc#L63

You reinitialize prompt pure at every new line. Please move it out of your precmd.

**Comment by kevinSuttle** [comment]
YES! Worked! Thanks @mafredri cc: @technoweenie.
