### ISSUE TITLE
Command name printed right after command execution

### ISSUE THREAD

**Issue by axyz** [sindresorhus/pure#113]
I'm not sure if it is a `pure` issue, it may be due to some conflicting option on zsh, however it started when I've activated pure as an `oh-my-zsh` extension.

essentially every command I write I get it printed as the firs part of the output

e.g.

```
~ master*
❯ uname
unameLinux
~
```

this is very ugly.

Any idea on how to avoid it will be really welcome.
thanks.

**Comment by sindresorhus** [comment]
Did you follow this description? https://github.com/sindresorhus/pure#oh-my-zsh

I know there's a modified outdated bundled version of Pure bundled with `oh-my-zsh`.

**Comment by axyz** [comment]
yes, my  `pure.zsh-theme` is symlinked to the file in this repo

**Comment by axyz** [comment]
I'm quite sure that is a zsh issue (I've tried disabling the pure theme on .zshrc) and the problem persists it was just an unlucky coincidence that it started  with my new config with pure.

I'm closing the issue, I will eventually post a solution when I'll find it.

**Comment by axyz** [comment]
here the fix:
https://github.com/robbyrussell/oh-my-zsh/issues/1338
