### ISSUE TITLE
Fastest git dirty check

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/pure#115]
I did a [quick benchmark](https://gist.github.com/sindresorhus/3898739) some years ago to find the fastest way to find out if a git repo is dirty. I think it's time to revisit this with latest git. Things might have changed. Anyone interested in doing such benchmark? It could be beneficial for a lot of other prompts and shell scripts too.

-

@paulirish [suggested](https://github.com/sindresorhus/pure/issues/102#issuecomment-75649344) the following taken from the [git completion](https://github.com/git/git/blob/355d4e1739d1e88561ac04d2a2423c2aa93693d9/contrib/completion/git-prompt.sh#L475):

```
git diff --no-ext-diff --quiet --exit-code
```

**Comment by mafredri** [comment]
I've also done some benchmarking of my own, but I came to the conclusion that on really large repos there's not a whole lot you can do to make it tolerable. This [Git Speed](https://gist.github.com/emanuelez/1758346) article explains the problem pretty well.

There's also the fact that most alternatives comes with some drawback, e.g. not detecting all changes.

I do believe, however, that the suggestion by @paulirish is slightly faster than the current one used in Pure.

**Comment by sindresorhus** [comment]
@mafredri For now we can just implement the dirty check Paul recommended.

**Comment by mafredri** [comment]
@sindresorhus `git diff --no-ext-diff --quiet --exit-code` does not however take into account untracked files, if we are to change it, I'd propose the following:

```diff
diff --git a/pure.zsh b/pure.zsh
index 222eb67..2daf472 100644
--- a/pure.zsh
+++ b/pure.zsh
@@ -145,13 +145,17 @@ prompt_pure_precmd() {
 # fastest possible way to check if repo is dirty
 prompt_pure_async_git_dirty() {
        local untracked_dirty=$1; shift
-       local umode="-unormal"
-       [[ "$untracked_dirty" == "0" ]] && umode="-uno"
 
        # use cd -q to avoid side effects of changing directory, e.g. chpwd hooks
        cd -q "$*"
-       command test -n "$(git status --porcelain --ignore-submodules ${umode})" &>/dev/null
-       (($? == 0)) && echo "*"
+
+       if [[ "$untracked_dirty" == "0" ]]; then
+               git diff --no-ext-diff --quiet --exit-code
+       else
+               command test -z "$(git status --porcelain --ignore-submodules)"
+       fi
+
+       (( $? )) && echo "*"
 }
```

**Comment by sindresorhus** [comment]
:+1: And prefix the `git` commands with `command git ...` so git wrappers like `hub` won't interfere.

**Comment by mafredri** [comment]
Good catch, I'll submit it as a PR.

**Comment by camilonova** [comment]
@mafredri that means this can be closed?

**Comment by mafredri** [comment]
Good question, I for one, have not come across ways to make dirty checking faster. The underlying issue still remains (for large repos), but I'm not sure what we can do about it.

**Comment by sindresorhus** [comment]
Yeah me neither.

**Comment by paulirish** [comment]
Aye. For the chromium repo I just disable dirty checking for the prompt. And use `git diff .` and `git status -- .` from a subfolder to keep it scoped and fast

**Comment by sindresorhus** [comment]
@mafredri Could we maybe implement some sort of timeout? Like, if it takes more than 2 seconds, cancel it and show some kind of symbol or text indicating it was too slow. That way we wouldn't have to manually disable dirty checking for some repos.

**Comment by mafredri** [comment]
We already have a 2 second timeout that lets the command run and caches the result. But I've been told (and I've experienced it myself) that when a system is running slow it can unnecessarily prevent updates on the repo.

So I'm all for rethinking this logic. I think blocking updates after a one time execution of >2s is too strict, though. Maybe it could be triggered when the command takes >2s, N times in a row or something (in this case the command would not be given a chance to run for longer than the allotted, e.g. 2s.

**Comment by sindresorhus** [comment]
:+1:

**Comment by MestreLion** [comment]
minor nitpick: `--quiet` in `git diff` already implies `--exit-code`, so no need to use both. Current git completion uses only `git diff --no-ext-diff --quiet`
