### ISSUE TITLE
`prompt pure` fails in OS X Yosemite

### ISSUE THREAD

**Issue by UltCombo** [sindresorhus/pure#116]
Looks like the `pure` theme is not available after `npm install --global pure-prompt`.

```
prompt -l
Currently available prompt themes:
adam1 adam2 bart bigfade clint elite2 elite fade fire off oliver pws redhat suse walters zefram
```

**Comment by mafredri** [comment]
It should be available after opening a new login session of running the command `promptinit`.

**Comment by UltCombo** [comment]
I have `autoload -U promptinit && promptinit` in my `.zshrc` and I've opened up a new terminal through iTerm2.

**Comment by mafredri** [comment]
Are you modifying your `fpath` somewhere perhaps and removing the defaults?

```

# echo $fpath

/usr/local/share/zsh/site-functions
/usr/local/Cellar/zsh/5.0.7/share/zsh/functions
```

**Comment by mafredri** [comment]
Are you modifying your `fpath` somewhere perhaps and removing the defaults?

```
# echo $fpath
/usr/local/share/zsh/site-functions /usr/local/Cellar/zsh/5.0.7/share/zsh/functions
```

**Comment by UltCombo** [comment]
```
fabricio-matte% echo $fpath
/usr/share/zsh/site-functions /usr/share/zsh/5.0.5/functions
fabricio-matte% prompt -l
Currently available prompt themes:
adam1 adam2 bart bigfade clint elite2 elite fade fire off oliver pws redhat suse walters zefram
```

Perhaps the install didn't copy the necessary files?

**Comment by mafredri** [comment]
Ah, now it makes sense. The difference between using zsh bundled with OSX
and the one installed through homebrew. Please
add /usr/local/share/zsh/site-functions to your fpath and you'll be good to
go (for now).

**Comment by UltCombo** [comment]
That did it, thanks!
If anyone else faces this issue, add this to your `.zshrc` before `prompt pure`:
```
fpath+=("/usr/local/share/zsh/site-functions")
```

**Comment by sindresorhus** [comment]
@mafredri Is there any way we can make the experience with this better?

**Comment by mafredri** [comment]
@UltCombo happy to hear! Let's see if we can't make this more smooth for others as well.

@sindresorhus It's not entirely trivial since `/usr/share/zsh/site-functions` requires root permissions, by default. Could we do a post-install message, e.g. like so:
```
Please ensure that your $fpath contains "/usr/local/share/zsh/site-functions" so that pure is accessible by zsh:
    echo 'fpath+=("/usr/local/share/zsh/site-functions")' >> ~/.zshrc
```
It's a bit crude, but I can't think of any reliable (automated and unintrusive) way at the moment.

**Comment by sindresorhus** [comment]
Yeah, I can't think of anything else right now either, but I'll keep this open so I don't forget.

**Comment by nbari** [comment]
You guys have made a really nice work, I just upgraded my prompt based on this new updates and works just great, Mac OS X & FreeBSD

In my case to avoid issues I use to create a ``~/.zsh`` dir, there I crate a ``functions`` and ``plugins`` dir. so that way I can move across any system with [my own conf/plugins](https://github.com/nbari/dotfiles/tree/develop/my-dotfiles/.zsh).

At the top of my .zshrc I just add this:

    fpath=( "$HOME/.zsh/functions" ${fpath[@]} )

**Comment by zeke** [comment]
I just got bit by this, but @UltCombo's recommendation of prepending `fpath+=("/usr/local/share/zsh/site-functions")` to `.zshrc` did the trick.

**Comment by mafredri** [comment]
I'm thinking the best solution we can do for this (without requiring root permissions to install `pure`) is a post-install instruction with
```
sudo ln -s /usr/local/share/zsh/site-functions/{async,prompt_pure_setup} /usr/share/zsh/site-functions
```
depending on the environment, e.g. no `/usr/local/bin/zsh` present.

**Comment by abecko** [comment]
Hi guys,
can you help with the problem at the installation? 

thx!

```bash
abe-mbp% npm install --global pure-prompt
/
> pure-prompt@1.1.0 postinstall /usr/local/lib/node_modules/pure-prompt
> dest=/usr/local/share/zsh/site-functions/; mkdir -p $dest && ln -sf "$PWD/pure.zsh" $dest/prompt_pure_setup && ln -sf "$PWD/async.zsh" $dest/async || echo 'Could not automagically symlink the prompt. Check out the readme on how to do it manually: https://github.com/sindresorhus/pure#manually'

pure-prompt@1.1.0 /usr/local/lib/node_modules/pure-prompt
abe-mbp%
```

**Comment by mafredri** [comment]
Hmm, I don't see a problem though, could you clarify what it is?

**Comment by thatryan** [comment]
Just found this and @UltCombo fix of adding 
```fpath+=("/usr/local/share/zsh/site-functions")```
worked for me as well.

**Comment by nkpgardose** [comment]
@UltCombo :+1: adding `fpath+=("/usr/local/share/zsh/site-functions")` worked for me as well.

**Comment by collegeimprovements** [comment]
I'm using nvm, and I tried `fpath+=("/usr/local/share/zsh/site-functions")` but even after that, I got this error! What can I do ?

```node
➜  ~  npm install --global pure-prompt
-
> pure-prompt@1.2.0 postinstall /Users/arpit/.nvm/versions/node/v4.2.1/lib/node_modules/pure-prompt
> dest=/usr/local/share/zsh/site-functions/; mkdir -p $dest && ln -sf "$PWD/pure.zsh" $dest/prompt_pure_setup && ln -sf "$PWD/async.zsh" $dest/async || echo 'Could not automagically symlink the prompt. Check out the readme on how to do it manually: https://github.com/sindresorhus/pure#manually'

pure-prompt@1.2.0 /Users/arpit/.nvm/versions/node/v4.2.1/lib/node_modules/pure-prompt
```

**Comment by mafredri** [comment]
I see no error. Only the command run which did not result in an error.

**Comment by mariojuniorjp** [comment]
Hi. I installed the zhs on mavericks, but the "prompt pure" not work. Now, prompinit not work too.

﻿ ~  prompt pure
zsh: command not found: prompt

➜  ~  promptinit
zsh: command not found: promptinit

**Comment by Alex-ray** [comment]
@collegeimprovements have you found a workaround for this yet?

**Comment by Alex-ray** [comment]
@collegeimprovements I found a fix for this ...

First make sure you have zsh installed _as well as oh-my-zsh_ 

Also make sure the `pure.zsh` and `async.zsh` are in the `$PWD` directory.

i.e. for your case run 
`cp /Users/arpit/.nvm/versions/node/v4.2.1/lib/node_modules/pure-prompt/async.zsh $PWD/async.zsh` 
and then run
 `cp /Users/arpit/.nvm/versions/node/v4.2.1/lib/node_modules/pure-prompt/pure.zsh $PWD/pure.zsh` 

then try running the post script command again...

`dest=/usr/local/share/zsh/site-functions/; mkdir -p $dest && ln -sf "$PWD/pure.zsh" $dest/prompt_pure_setup && ln -sf "$PWD/async.zsh" $dest/async || echo 'Could not automagically symlink the prompt. Check out the readme on how to do it manually: https://github.com/sindresorhus/pure#manually'`

**Comment by jose4125** [comment]
hi, pure doesn't work for me :( I got
Usage: prompt <options>
Options:
    -c              Show currently selected theme and parameters
    -l              List currently available prompt themes
    -p [<themes>]   Preview given themes (defaults to all)
    -h [<theme>]    Display help (for given theme)
    -s <theme>      Set and save theme
    <theme>         Switch to new theme immediately (changes not saved)

Use prompt -h <theme> for help on specific themes.

then I ran a command and I got

Currently available prompt themes:
adam1 adam2 bart bigfade clint elite2 elite fade fire off oliver pws redhat suse walters zefram

I added this line in my .zshrc
fpath+=("/usr/local/share/zsh/site-functions")

but is not working

**Comment by mafredri** [comment]
@jose4125 did you install Pure manually or via `npm`? What was the output? If Pure fails to install via `npm` there should be an error message with two options, one suggesting manual install and the other allows you to use the `npm` installed version.

**Comment by juliocanares** [comment]
@mafredri same @jose4125 issue here. I've installed pure using npm.

every time I open a new tab is logs

```
Usage: prompt <options>
Options:
    -c              Show currently selected theme and parameters
    -l              List currently available prompt themes
    -p [<themes>]   Preview given themes (defaults to all)
    -h [<theme>]    Display help (for given theme)
    -s <theme>      Set and save theme
    <theme>         Switch to new theme immediately (changes not saved)

Use prompt -h <theme> for help on specific themes.
```

**Comment by mafredri** [comment]
@juliocanares would you mind opening a new issue and providing some more information? Would be helpful if you included the npm install output/log as well. Not much to go on at the moment.

**Comment by juliocanares** [comment]
@mafredri I just did install again and it worked 👍
