### ISSUE TITLE
antigen is not working anymore

### ISSUE THREAD

**Issue by caarlos0** [sindresorhus/pure#118]
To make it work in antigen, I had to do something like this:

```sh
PURE_PATH=~/.antigen/repos/https-COLON--SLASH--SLASH-github.com-SLASH-sindresorhus-SLASH-pure.git

antigen bundle sindresorhus/pure
antigen apply

ln -sf "$PURE_PATH/pure.zsh" "$PURE_PATH/prompt_pure_setup"

autoload -U promptinit && promptinit
prompt pure
```

Until those last updates, only the antigen bundle/apply combo was enough... 

BTW: yes, `~/.antigen/repos/https-COLON--SLASH--SLASH-github.com-SLASH-sindresorhus-SLASH-pure.git` is in my `fpath`, but seems that `prompt` was ignoring it until I linked it to `prompt_pure_setup`.

My point is: we might need to fix documentation or fix the problem. I don't know what is the problem, but I will be glad to help testing!

**Comment by mafredri** [comment]
Reading the antigen documentation it looks to me like it will only source on *.plugin.zsh from the target repository, so my adding the async.plugin.zsh probably causes antigen to load it or only one of the *.plugin.zsh files. I'll have a better look at this later.

**Comment by danez** [comment]
Have the same problem

**Comment by caarlos0** [comment]
@mafredri yes, looks like it loads only the async plugin.

**Comment by mafredri** [comment]
Does anyone know if the `*.plugin.zsh` syntax is used by anything other than antigen, I'm thinking it could be modified into a file that sources both async.zsh and pure.zsh instead of a symlink? Ping @sindresorhus?

**Comment by caarlos0** [comment]
I think that one file that source both files is a good option...

**Comment by mafredri** [comment]
I settled for a different solution than sourcing both files, it felt kind of hackish.
README has been updated with proper instructions for antigen, closing this now.

**Comment by caarlos0** [comment]
@mafredri nice, many thanks!
