### ISSUE TITLE
Command not found : async

### ISSUE THREAD

**Issue by sajadabedi** [sindresorhus/pure#120]
Hi.
When i install pure with npm and set config show me this error before run any command  in iterm.
How i can fix this?
![screen shot 1394-03-05 at 11 19 32 pm](https://cloud.githubusercontent.com/assets/5726597/7820437/b8bdab78-03fd-11e5-94ee-cb34861ffda4.png)

**Comment by mafredri** [comment]
To me it looks like `pure` is loading before `async`. Could you go through your `$fpath` and see if you have any other references to `pure` in them?

**Comment by sajadabedi** [comment]
I run command and print this output: @mafredri 
```
/Users/sajad/.oh-my-zsh/plugins/sublime
/Users/sajad/.oh-my-zsh/plugins/git
/Users/sajad/.oh-my-zsh/functions
ls: /Users/sajad/.oh-my-zsh/functions: No such file or directory
/Users/sajad/.oh-my-zsh/completions
ls: /Users/sajad/.oh-my-zsh/completions: No such file or directory
/usr/share/zsh/site-functions
/usr/share/zsh/5.0.5/functions
```

**Comment by mafredri** [comment]
Ok, so looks like you are also using OSX ZSH (not the Homebrew one), so you need to add `/usr/local/share/zsh/site-functions` to your `fpath`

```
fpath+=("/usr/local/share/zsh/site-functions")
```

**Comment by victormejia** [comment]
Having same issue here, pure is running since it was added as a custom theme to oh-my-zsh.

**Comment by michaelryancaputo** [comment]
getting a similar issue:

```/Users/mike/.oh-my-zsh/plugins/cp
/Users/mike/.oh-my-zsh/plugins/bower
/Users/mike/.oh-my-zsh/plugins/npm
/Users/mike/.oh-my-zsh/plugins/brew
/Users/mike/.oh-my-zsh/plugins/git
/Users/mike/.oh-my-zsh/functions
ls: /Users/mike/.oh-my-zsh/functions: No such file or directory
/Users/mike/.oh-my-zsh/completions
ls: /Users/mike/.oh-my-zsh/completions: No such file or directory
/usr/share/zsh/site-functions
/usr/share/zsh/5.0.5/functions
```

**Comment by alem0lars** [comment]
@victormejia @michaelryancaputo @sajadabedi Can you check if both the files `async` and `pure` are in the fpath?

**Comment by mafredri** [comment]
Yes, the install instructions are no longer sufficient for oh-my-zsh. You will need to symlink async.zsh to somewhere in your `$fpath`.

@sajadabedi:
`ln -s /path/to/pure/async.zsh /Users/sajad/.oh-my-zsh/functions/async`
or
`cp /path/to/pure/async.zsh /Users/sajad/.oh-my-zsh/functions/async`

@michaelryancaputo:
`ln -s /path/to/pure/async.zsh /Users/mike/.oh-my-zsh/functions/async`
or
`cp /path/to/pure/async.zsh /Users/mike/.oh-my-zsh/functions/async`

@victormejia I'm sure you get the idea :).

**Comment by michaelryancaputo** [comment]
@mafredri thank you, that helped :dancer:

**Comment by mafredri** [comment]
README has been updated with proper instructions for oh-my-zsh.

**Comment by victormejia** [comment]
thanks! :+1:

**Comment by tjfwalker** [comment]
I'm doing this with [zplug](https://github.com/zplug/zplug) and am getting `prompt_pure_setup:13: async: function definition file not found` on new instances. Let's say part of my `.zshrc` looks like:

```
export ZPLUG_HOME=/usr/local/opt/zplug                                                                 
export ZPLUG_LOADFILE=~/.zplug.zsh                                                                     
source $ZPLUG_HOME/init.zsh      

zplug "mafredri/zsh-async", nice:11                                                                    
zplug "sindresorhus/pure"
                                                                      
zplug load
```

Thoughts?

**Comment by mafredri** [comment]
@tjfwalker why are you loading async with `nice` later than pure? It likely needs to be loaded before pure.

Also, zplug seems to have other issues as well, see #223.

**Comment by jt3k** [comment]
i have same issue , and copy to ~/.oh-my-zsh/functions/ is not helps

![](https://i.imgur.com/o4yN2Gi.png)

**Comment by mafredri** [comment]
This doesn't look like the same issue to me @jt3k. Try following the oh-my-zsh instructions in the readme. If that doesn't help, open a new issue and fill in the issue template.

**Comment by jt3k** [comment]
thanx i fix it  after readme read )

**Comment by tjohlenburg** [comment]
Hi there, I get a similar issue:

When I start zsh then it does start, but shows the following:

prompt_pure_setup:17: async: function definition file not found
   
prompt_pure_async_tasks:5: command not found: async_start_worker
prompt_pure_async_tasks:6: command not found: async_register_callback

~
❯ 


I check for async and pure references in $fpath and get the following:
❯ for i in $fpath; do echo $i; ls -l $i | egrep -i "(async|pure)"; done
/home/tim/.oh-my-zsh/plugins/git
/home/tim/.oh-my-zsh/functions
ls: cannot access '/home/tim/.oh-my-zsh/functions': No such file or directory
/home/tim/.oh-my-zsh/completions
ls: cannot access '/home/tim/.oh-my-zsh/completions': No such file or directory
/usr/local/share/zsh/site-functions
/usr/share/zsh/vendor-functions
ls: cannot access '/usr/share/zsh/vendor-functions': No such file or directory
/usr/share/zsh/vendor-completions
/usr/share/zsh/functions/Calendar
/usr/share/zsh/functions/Chpwd
/usr/share/zsh/functions/Completion
/usr/share/zsh/functions/Completion/AIX
/usr/share/zsh/functions/Completion/BSD
/usr/share/zsh/functions/Completion/Base
/usr/share/zsh/functions/Completion/Cygwin
/usr/share/zsh/functions/Completion/Darwin
/usr/share/zsh/functions/Completion/Debian
/usr/share/zsh/functions/Completion/Linux
/usr/share/zsh/functions/Completion/Mandriva
/usr/share/zsh/functions/Completion/Redhat
/usr/share/zsh/functions/Completion/Solaris
/usr/share/zsh/functions/Completion/Unix
/usr/share/zsh/functions/Completion/X
/usr/share/zsh/functions/Completion/Zsh
/usr/share/zsh/functions/Completion/openSUSE
/usr/share/zsh/functions/Exceptions
/usr/share/zsh/functions/MIME
/usr/share/zsh/functions/Misc
/usr/share/zsh/functions/Newuser
/usr/share/zsh/functions/Prompts
/usr/share/zsh/functions/TCP
/usr/share/zsh/functions/VCS_Info
/usr/share/zsh/functions/VCS_Info/Backends
/usr/share/zsh/functions/Zftp
/usr/share/zsh/functions/Zle

What can I do to get rid of the opening warnings?

**Comment by mafredri** [comment]
There is no async in your path, you need to follow the installation
instructions in the readme.
