### ISSUE TITLE
It's not working with Prezto

### ISSUE THREAD

**Issue by jitendravyas** [sindresorhus/pure#121]
I have set `style ':prezto:module:prompt' theme 'pure'`

and After I quit and restarted my iterm2 and getting this

![1 zsh 2015-05-27 09-28-37](https://cloud.githubusercontent.com/assets/77309/7828573/d210aabc-0452-11e5-87a6-63405c163313.png)

**Comment by mafredri** [comment]
What happens if you type just `prompt pure`? Anyway, I'll have a look at prezto integration later today and see what I can do.

**Comment by jitendravyas** [comment]
If i run `prompt pure` it activates `pure` but if I quit and start iterm again I get the same thing again (as above screenshot)

**Comment by mafredri** [comment]
Hmm, you did write that you have set `style ':prezto:module:prompt' theme 'pure'`. It should be `zstyle ':prezto:module:prompt' theme 'pure'`.

**Comment by jitendravyas** [comment]
it was my mistake to type here. it's `zstyle` only in an actual file. By the way, I changed `pure` to `sorin` now and still getting the same error.

**Comment by mafredri** [comment]
Obviously prompt is running with incorrect paramteres somewhere in your zsh config. I recommend starting zsh with the debug option and go through the output (it's very verbose) to see where it's happening:

`zsh -x`

**Comment by jitendravyas** [comment]
output of `zsh -x` http://hastebin.com/axizirinet.diff

**Comment by mafredri** [comment]
You are modifying your fpath too late. First zpresto is initialized without and your themes are not yet available in the fpath but you are still setting the theme through presto:

`+/Users/jitendravyas/.zshrc:15> fpath+=( /usr/local/share/zsh/site-functions )`

Then you add the folder to your fpath, reinitialize promptinit and this is why the themes are available.

Not a `pure` bug.

**Comment by jitendravyas** [comment]
There was no fpath in my .zshrc file. I copied from this post https://github.com/sindresorhus/pure/issues/116 and added to my file. 

This was my .zshrc before any modification and it was working fine.

```````````
#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#
# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

``````````````

Now can you help me, what to add in it to make Pure work?
After adding `zstyle ':prezto:module:prompt' theme 'pure'`in .zpreztorc`

**Comment by mafredri** [comment]
Add `fpath+=( /usr/local/share/zsh/site-functions )` at the top of your `.zshrc`.

**Comment by jitendravyas** [comment]
I did. And restarted iterm. but getting the same output as I posted in first comment

**Comment by mafredri** [comment]
Ok, I'll get back once I have tested in zpresto myself.

**Comment by mafredri** [comment]
Prezto integration is broken for the moment being. I've opened an issue on the prezto issue tracker (https://github.com/sorin-ionescu/prezto/issues/892) to discuss potential solutions.

**Comment by mafredri** [comment]
@jitendravyas if you wish to fix `pure` loading in prezto, for the time beeing you can use
```
cd ~/.zprezto/tree/master/modules/prompt/functions
ln -s ../external/pure/async.zsh async
```

**Comment by mafredri** [comment]
This has been fixed in https://github.com/sorin-ionescu/prezto/commit/02c5f776fc3ebbc5eee6dc74e84be25542983e26, closing!

**Comment by jitendravyas** [comment]
ok what are the steps after updating prezto to have pure

**Comment by mafredri** [comment]
Just the one step, as in the readme, under prezto integration.

**Comment by jitendravyas** [comment]
I updated Prezto by running this command inside my .zprezto folder

`````````
git pull && git submodule update --init --recursive
-------------

and then Set zstyle `:prezto:module:prompt` theme `pure` in ~/.zpreztorc.


`````````````
#
# Prompt
#

# Set the prompt theme to load.
# Setting it to 'random' loads a random theme.
# Auto set to 'off' on dumb terminals.
zstyle ':prezto:module:prompt' theme ‘pure’
`````````````

but still getting the same output

![image](https://cloud.githubusercontent.com/assets/77309/7902738/e4e07bfe-07e0-11e5-9e60-d04a85c2bffb.png)


And this is my .zshrc


```````````

#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#
fpath+=( /usr/local/share/zsh/site-functions )

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

``````````````

**Comment by mafredri** [comment]
It looks like `pure` has weird quotes around it in your `.zpreztorc`, please make sure they are normal single or double quotes.

Also, don't use `prompt -s`, just type `prompt pure`. As the output says, `-s` is not implemented.

**Comment by jitendravyas** [comment]
So are you saying that each time to start pure I will have to type 'prompt pure' when iterms starts ?

**Comment by mafredri** [comment]
That is not what I'm saying.

> Just the one step, as in the readme, under prezto integration.

What I'm saying is that the README is correct, and I belive you have an error in your .zpreztorc. Please copy paste the line from the README into your .zpreztorc (do not try to type it yourself or copy it from anywhere else).

**Comment by mafredri** [comment]
To clarify:

> It looks like pure has weird quotes around it in your .zpreztorc, please make sure they are normal single or double quotes.

Please take a close look at the line you pasted
```
zstyle ':prezto:module:prompt' theme ‘pure’
```
Those quotes around pure: `‘pure’` are invalid.

If i try to use that in the terminal:
```
~
❯ echo ‘pure’
‘pure’
```
See the problem? With correct quotes, it's:
```
~
❯ echo 'pure'
pure
```
> Also, don't use `prompt -s`, just type `prompt pure`. As the output says, `-s` is not implemented.

This was just a TIP to using prompt, unrelated to the issue at hand.

**Comment by jitendravyas** [comment]
Thanks. my iterm is loading `pure` by default upon loading after copying and pasting from readme

![image](https://cloud.githubusercontent.com/assets/77309/7902943/99962898-07e9-11e5-8f1d-3f84b4ef0c64.png)

**Comment by mafredri** [comment]
Glad it's working for you, enjoy~!
