### ISSUE TITLE
git status output being included in preprompt

### ISSUE THREAD

**Issue by alexwh** [sindresorhus/pure#122]
Just had this start happening with 94ccd58: 
![git status output](https://cloud.githubusercontent.com/assets/1723612/7838838/0bfe3df0-0487-11e5-9d87-5d7ce4dbf7f2.png)
Not sure if it's the same bug or not, but cding into a git dir that has a directory with spaces above it also results in this bug:
![spaces](https://cloud.githubusercontent.com/assets/1723612/7838887/4bd4ecb2-0487-11e5-8079-8f049b2a96ad.png)

**Comment by mafredri** [comment]
Does https://github.com/sindresorhus/pure/commit/a57987499be0b5bfa14a861d075f809dc3b99f8e resolve your issues? Could've sworn I had addressed this but I guess I only did it in the async lib :disappointed:.

**Comment by alexwh** [comment]
Seems to have fixed the space issue, but not the git status one. Looks like the first one now: 
![1432741817](https://cloud.githubusercontent.com/assets/1723612/7840701/8738a81c-0490-11e5-82bc-f80586674bad.png)

**Comment by mafredri** [comment]
And https://github.com/sindresorhus/pure/commit/e46c59ff4589acfc822c7ec61034c5be39e8d410?

**Comment by alexwh** [comment]
Nope, still seems to be happening.
I looked into it a bit more - the working tree in at least the dotfiles project is clean - when I run `git status --porcelain --ignore-submodules -unormal`, nothing is returned. It seems this problem is coming from my [chpwd](https://github.com/alexwh/dotfiles/blob/8e172234a67245dc076205a1e2e212f2bf4f41e0/zsh/functions.zsh#L2) zsh function - it runs ls when [line 151](https://github.com/sindresorhus/pure/blob/e46c59ff4589acfc822c7ec61034c5be39e8d410/pure.zsh#L151) cd's.

**Comment by mafredri** [comment]
Makes sense. I couldn't understand why there would've been any git status leakage before, since the command was run in a sub-shell, but this explains it. If you want to solve your problem, initialize pure before defining your `chpwd` hook ;).

**Comment by alexwh** [comment]
functions.zsh is already called after setting up pure - it seems to still have effect due to the cd command in prompt_pure_async_git_dirty running "after" chpwd has been defined (when the user is in the shell). Would passing cd -q not be acceptable?

**Comment by mafredri** [comment]
It seems you are right, just researching how to disable a hook. One option would be to define chpwd() {} in the function that is executed, but that would not prevent custom hooks via `add-zsh-hook` from running. `cd -q` does not seem to help.

**Comment by alexwh** [comment]
Changing line 151 to `cd -q "$*"` on my system seems to fix the problem. Not on yours?

**Comment by mafredri** [comment]
My initial test was faulty, which is why I thought it didn't work. But you're welcome to test out https://github.com/sindresorhus/pure/commit/d766c8b8d90a4bd748aef0873322611bc253b110 now. Should work fine.

**Comment by alexwh** [comment]
Yep, seems to work fine now. Thanks for the quick replies and fixes :)

**Comment by mafredri** [comment]
You're welcome, and I appreciate you being standby to test the fixes :)!

**Comment by onemanstartup** [comment]
I am too had overwritten cd and had the same problem.

**Comment by alexwh** [comment]
Did d766c8b fix it?

**Comment by onemanstartup** [comment]
@alexwh i removed my overwrite of cd :)
