### ISSUE TITLE
There are lots of extra spaces in terminal output (caused by PROMPT_CR)

### ISSUE THREAD

**Issue by mafredri** [sindresorhus/pure#127]
Defining `cr` in `prompt_opts` causes zsh to print a carriage return (basically #`$COLUMN` of spaces) after the last output line to make sure the prompt does not overwrite output in the terminal. Since `pure` uses a newline in it's pre-prompt this is a non-issue and the spaces are a nuisance when copying text from the terminal.

> PROMPT_CR (+V)
Print a carriage return just before printing a prompt in the line editor.
[See here](http://bolyai.cs.elte.hu/zsh-manual/zsh_16.html)

Sample with `cr`:
![](https://www.dropbox.com/s/1510cw5aotl5oi9/Screenshot%202015-06-02%2013.23.58.png?dl=1)

Sample without `cr`:
![](https://www.dropbox.com/s/xlqcvr69jvyugrh/Screenshot%202015-06-02%2013.28.26.png?dl=1)

Between the two samples we see that if the output doesn't end with a newline as with `echo -n` then there's no breathing space between the output and the new prompt. In my opinion this is actually more correct behavior as it tells the user the output was missing a newline at the end.

I will try to run this for a while locally for a while and see if I spot any unwanted side-effects.

**Comment by sindresorhus** [comment]
I actually added because I was so annoyed that so many tools didn't print the trailing newline.

**Comment by mafredri** [comment]
Ah, I see. It should be possible to read the cursor position from the terminal though, if it's not the first character, print an extra newline.

**Comment by sindresorhus** [comment]
:+1:

**Comment by mafredri** [comment]
I found a solution to this, but I don't think I want to merge it as it requires toggling echo of the terminal (`stty -echo`, only required to prevent accidental output in tmux). It just feels a bit absurd that your zsh theme does this, not to mention potential repocussions.

```patch
diff --git a/pure.zsh b/pure.zsh
index f6fd34d..82ba2f4 100644
--- a/pure.zsh
+++ b/pure.zsh
@@ -98,6 +98,21 @@ prompt_pure_preprompt_render() {
 
 	# if executing through precmd, do not perform fancy terminal editing
 	if [[ "$1" == "precmd" ]]; then
+		{
+			local cursor_position
+			local IFS=";"
+			# stty -echo prevent output from being echoed to terminal
+			stty -echo
+			# printing \033[6n to the terminal outputs current cursor position
+			print -n "\033[6n"
+			# re-enable echo
+			stty echo
+			# read output from print command and prevent outputting to terminal
+			read -s -r -d "R" -A cursor_position
+			# if cursor position is not 1, then output is missing a newline at the end, print it
+			[[ "${cursor_position[2]}" != "1" ]] && print
+		}
+
 		print -P "\n${prompt}"
 	else
 		# only redraw if prompt has changed
@@ -243,7 +258,7 @@ prompt_pure_setup() {
 	# if output doesn't end with a newline
 	export PROMPT_EOL_MARK=''
 
-	prompt_opts=(cr subst percent)
+	prompt_opts=(subst percent)
 
 	zmodload zsh/datetime
 	autoload -Uz add-zsh-hook
```

**Comment by sindresorhus** [comment]
Yeah, looks too hacky. Gonna git us at some point. I guess it would be better to just remove `cr` then...

**Comment by forivall** [comment]
~~I remember when I first switched to zsh and used other prompts, that `^M` would be printed if the command didn't end with a newline~~ nvm that's `PROMPT_EOL_MARK`.

**Comment by mafredri** [comment]
Or we could just close this issue because this can easily be achieved by setting
```sh
unsetopt prompt_cr
```

after

```sh
prompt pure
```

**Comment by mafredri** [comment]
@forivall sorry for not responding to your comment. Regarding `PROMPT_EOL_MARK` nothing smart can be done with it AFAIK, it doesn't get applied without `cr` and you can't e.g. put newlines in it :(.

@sindresorhus I'll leave it up to you to decide if we remove `cr` or leave it up to the user to use `unsetopt prompt_cr`.

**Comment by zmwangx** [comment]
> Regarding `PROMPT_EOL_MARK` nothing smart can be done with it AFAIK, it doesn't get applied without cr and you can't e.g. put newlines in it :(.

I totally hate it. Probably worth submitting a patch to Zsh.

**Comment by sindresorhus** [comment]
> Probably worth submitting a patch to Zsh.

:+1: Or even just opening an issue over there ;)

> I'll leave it up to you to decide if we remove cr

Remove it.
