### ISSUE TITLE
PURE_GIT_PULL no longer working

### ISSUE THREAD

**Issue by cocreature** [sindresorhus/pure#128]
Since the big update with all the async stuff in it, I keep getting asked for my ssh password despite having set `PURE_GIT_PULL` to `0`. I am not sure if there is now some other place where this is needed, but imho there should be an option to disable any remote work because having to enter your ssh password every few minutes can get annoying.

**Comment by mafredri** [comment]
What's your git version? Also, please post a screenshot.

**Comment by cocreature** [comment]
I am using git 2.4.2. I can't easily post a screenshot since `pinentry` which is called by gpg-agent which manages my ssh keys grabs focus. If you really think a screenshot helps, I can make a photo, but it's just the prompt and the pinentry dialog.

**Comment by mafredri** [comment]
Well, first problem I supposed is that `pinentry` doesn't respect the git no prompt option. But second of all, whoa, you spotted a big miss on my part. Currently the `PURE_GIT_PULL` affects the checking of dirtyness which is completely wrong. So it does work, it just toggles the wrong option. Sorry about that!

**Comment by cocreature** [comment]
You might be right anyway, killing gpg-agent results in no password being asked for.

**Comment by mafredri** [comment]
I've fixed `PURE_GIT_PULL` with https://github.com/sindresorhus/pure/commit/b55776e7aa7cb4db2e782285fa35473c51de6940, sorry about the confusion.

**Comment by cocreature** [comment]
Thanks for the quick fix! Works just fine now.
