### ISSUE TITLE
Showing virtualenv info 

### ISSUE THREAD

**Issue by ahmedelgabri** [sindresorhus/pure#129]
I have this function that I added inside `pure.zsh` file

```zsh
virtualenv_prompt_info(){
  if [[ -n $VIRTUAL_ENV ]]; then
    printf "[%s]" ${${VIRTUAL_ENV}:t}
  fi
}
```
And I'm using it inside the `prompt_pure_preprompt_render()` like so 

```zsh
prompt_pure_preprompt_render() {
...
	# git info
	prompt+="%F{$git_color}${vcs_info_msg_0_}%F{red}${prompt_pure_git_dirty}"

    # venv info
    prompt+="%F{009}${virtualenv_prompt_info}%f"
...
}
```

The same function used to work before updating to the latest `pure.zsh` version, so any ideas how to fix this?

**Comment by mafredri** [comment]
You are using your function as a variable. Try changing {} to ()

**Comment by ahmedelgabri** [comment]
@mafredri Thanks!

**Comment by mafredri** [comment]
You're welcome :)!
