### ISSUE TITLE
Question: why use [ instead of [[ and prefix the paths

### ISSUE THREAD

**Issue by zmwangx** [sindresorhus/pure#131]
I was trying to migrate my own prompt to async through learning from `pure`'s source (immensely helpful :+1:). However, there's [one piece of code](https://github.com/sindresorhus/pure/blob/b55776e7aa7cb4db2e782285fa35473c51de6940/pure.zsh#L188-L199) that I found rather strange:

```zsh
	# check if the working tree changed, it is prefixed with "x" to prevent variable resolution in path
	if [ "${prompt_pure_current_working_tree:-x}" != "x${working_tree}" ]; then
		# stop any running async jobs
		async_flush_jobs "prompt_pure"

		# reset git preprompt variables, switching working tree
		unset prompt_pure_git_dirty
		unset prompt_pure_git_delay_dirty_check

		# set the new working tree, prefixed with "x"
		prompt_pure_current_working_tree="x${working_tree}"
	fi
```

My question is: why don't we use `[[` instead of `[`? That way the paths don't need any prefix, everything is more natural, and the coding style is more consistent (as this is the only occasion where `[` is used instead of `[[`):

```zsh
	# check if the working tree changed
	if [[ "${prompt_pure_current_working_tree}" != "${working_tree}" ]]; then
		# stop any running async jobs
		async_flush_jobs "prompt_pure"

		# reset git preprompt variables, switching working tree
		unset prompt_pure_git_dirty
		unset prompt_pure_git_delay_dirty_check

		# set the new working tree
		prompt_pure_current_working_tree="${working_tree}"
	fi
```

Did I miss something here? I guess the real question is, what does

> it is prefixed with "x" to prevent variable resolution in path

mean? I can understand the need to prefix it when using `[`, because an empty parameter will be expanded and dropped, leading to syntax error; but `[[` doesn't have this problem, and in fact [Zsh docs](http://zsh.sourceforge.net/Doc/Release/Shell-Builtin-Commands.html) says the following about `test`:

> Like the system version of `test`. Added for compatibility; use conditional expressions instead (see [Conditional Expressions](http://zsh.sourceforge.net/Doc/Release/Conditional-Expressions.html)). The main differences between the conditional expression syntax and the `test` and `[` builtins are: these commands are not handled syntactically, so for example an empty variable expansion may cause an argument to be omitted; ...

Did I miss anything else? AFIAK `$prompt_pure_current_working_tree` inside `[[` will only experience parameter expansion and nothing else, so it's perfectly safe.

@mafredri Would you please kindly answer this question? Thanks.

**Comment by mafredri** [comment]
Good question! Actually the usage of `x` is kind of unrelated to using `[` in this case, perhaps this screenshot better illustrates the problem:

![](https://www.dropbox.com/s/fxw9vcdnswf2scs/Screenshot%202015-06-13%2011.29.41.png?dl=1)

Now imagine `myvar` being `prompt_pure_current_working_tree`.

As for the usage if `[` over `[[` I guess it wouldn't hurt to use `[[` instead. My reasoning for `[` over `[[` is usually that I don't need the additional features, but in zsh it does probably make sense to use `[[`.

**Comment by sindresorhus** [comment]
I think we should standardize on `[[` as it's more flexible.

**Comment by mafredri** [comment]
I agree, `[[` is the standard for zsh anyway. Bad habit from sometimes writing `sh` compatible scripts. :)

**Comment by zmwangx** [comment]
> Now imagine `myvar` being `prompt_pure_current_working_tree`.

Good point, didn't think of that.

However, I have the expression that it will only happen if you set the `AUTO_NAME_DIRS` option and export `prompt_pure_current_working_tree`? In this case `prompt_pure_current_working_tree` isn't and shouldn't be exported, so IMO it should be safe to do without the prefix.

**Comment by mafredri** [comment]
Yes, `AUTO_NAME_DIRS` is required, but I don't want to make that choice other for people. Also, since `prompt_pure_current_working_tree` isn't local, it's actually on the global scope for your shell, as can be seen by typing `print $prompt_pure_current_working_tree` in your terminal. It doesn't need to be exported in this case.

**Comment by zmwangx** [comment]
Uh I see, the key isn't export; any variable defined (and holds the path to an absolute dir) after `AUTO_NAME_DIRS` is set will be available for collapse. Now it makes perfect sense.

**Comment by mafredri** [comment]
Ah, it seems my reasoning for why it didn't need `export` is incorrect. Thanks for looking that up :).

**Comment by zmwangx** [comment]
I guess this issue could be closed now?

**Comment by zmwangx** [comment]
And thanks for the explanation! :+1:

**Comment by mafredri** [comment]
With https://github.com/sindresorhus/pure/commit/58167f1879f47bf47785cc3c959f30375d54da42, I think we can consider this closed! :)
