### ISSUE TITLE
symbolic link causes problems, if using dropbox

### ISSUE THREAD

**Issue by jeffkowalski** [sindresorhus/pure#132]
If the files from this repo are contained in a Dropbox folder (common to sync configs across machines), an unfortunate condition arises.
Dropbox doesn't respect symbolic links, and so will copy "pure.zsh" to "pure.plugin.zsh" on all other folders on synced clients.  This means the file type and mode is therefore different on those clients, and the working directory will be "dirty" in the github sense.
Is there any way to avoid the symbolic link entirely and have just one file - either pure.zsh or pure.plugin.zsh?

**Comment by mafredri** [comment]
You could just maintain your own branch of pure, with the symbolic link removed. I don't quite understand how the file modes will be incorrect since they don't matter when sourcing a file.

Not much else to do, maybe request symbolic link support from Dropbox? :)
