### ISSUE TITLE
Problems with spaces in git repo path

### ISSUE THREAD

**Issue by felixjung** [sindresorhus/pure#133]
Hi,

I noticed some weird error, today. Apparently ``prompt_pure_async_git_dirty()`` fails when there's a space in the path to a git repo. As a result you get an ugly error string instead of the dirty symbol. Here's an example:
```
~/Some Folder/some.repo masterprompt_pure_async_git_dirty:cd:5: no such file or directory: /Users/felix/Somerepo master
```
I've never noticed this before. I find it weird that the part of the repo name after the dot in "some.repo" gets attached in the error message.

Any ideas?

**Comment by mafredri** [comment]
What version of pure are you running? This should have been fixed in https://github.com/sindresorhus/pure/commit/a57987499be0b5bfa14a861d075f809dc3b99f8e.

**Comment by sindresorhus** [comment]
Closing for lack of response. It was most likely fixed in https://github.com/sindresorhus/pure/commit/a57987499be0b5bfa14a861d075f809dc3b99f8e.

**Comment by felixjung** [comment]
Oups sorry, did not catch that response! My bad! Will try again.
