### ISSUE TITLE
async_job:zpty:2: no such pty command: prompt_pure

### ISSUE THREAD

**Issue by pierot** [sindresorhus/pure#135]
New issue for comment: https://github.com/sindresorhus/pure/issues/117#issuecomment-117505595

```
(zpty):zpty:2: can't open pseudo terminal: device not configured
async_job:zpty:2: no such pty command: prompt_pure
async_job:zpty:2: no such pty command: prompt_pure
```

OS: OSX 10.10.3.
zsh: 5.0.8 (installed via Homebrew)
tmux: 2.0
using iTerm 2.1.1

```
❯ find /usr/share/zsh -newermt "2014-10-22"
/usr/share/zsh/5.0.5/help
/usr/share/zsh/5.0.5/help/autoload
/usr/share/zsh/5.0.5/help/bye
/usr/share/zsh/5.0.5/help/chdir
/usr/share/zsh/5.0.5/help/declare
/usr/share/zsh/5.0.5/help/float
/usr/share/zsh/5.0.5/help/history
/usr/share/zsh/5.0.5/help/integer
/usr/share/zsh/5.0.5/help/local
/usr/share/zsh/5.0.5/help/logout
/usr/share/zsh/5.0.5/help/pushln
/usr/share/zsh/5.0.5/help/r
/usr/share/zsh/5.0.5/help/readonly
/usr/share/zsh/5.0.5/help/rehash
/usr/share/zsh/5.0.5/help/type
/usr/share/zsh/5.0.5/help/unalias
/usr/share/zsh/5.0.5/help/unfunction
/usr/share/zsh/5.0.5/help/where
/usr/share/zsh/5.0.5/help/which
```

**Comment by mafredri** [comment]
Need to see your zsh configuration.

**Comment by pierot** [comment]
I use oh-my-zsh.
This is my .zshrc: https://github.com/pierot/termieter/blob/master/symlinks/zshrc

**Comment by mafredri** [comment]
How have you installed pure, npm? If so, have you also followed the instructions for oh-my-zsh integration in the README? The two methods might conflict with each other.

For example, if you have copied/symlinked ` ~/.oh-my-zsh/custom/async.zsh` you should remove it (assuming npm installation).

**Comment by pierot** [comment]
I didn't install it through npm. Just manually copying and symlinking the files.

**Comment by mafredri** [comment]
Where did you symlink them?

**Comment by pierot** [comment]
![9iozwii4dgkfpg79qzhgvqyt_iderezmqn8a1agmsmu](https://cloud.githubusercontent.com/assets/46622/8480928/d24b7a66-20e0-11e5-8e94-61a044bbd19d.png)

**Comment by mafredri** [comment]
Ok, that kind of looks fine but not sure what oh-my-zsh does in the background. So let's start with the basics. Can you get zpty working at all? Try the following commands:

```sh
zmodload zsh/zpty
zpty cat cat
zpty -L  # list zpty instances
zpty -w cat hello world
zpty -rt cat
```

The final command should print `hello world`.

**Comment by pierot** [comment]
```
➜  tmp  zmodload zsh/zpty
➜  tmp  zpty cat cat
➜  tmp  zpty -L
^Czpty cat cat
➜  tmp  zpty -w cat hello world
➜  tmp  zpty -rt cat
➜  tmp
```

You  can see I had to `CTRL+C` the `zpty -L` command as it kept blank for over an hour.
Also, there is no `hello world` ...

**Comment by mafredri** [comment]
Do you experience the same behavior even if you completely disable your zsh modifications? E.g. rename your `.zshrc` so that it isn't sourced.

**Comment by pierot** [comment]
Strangely enough, all seems well no. I cancelled pure for a couple of days.
Yesterday I tried to re-enable it and see and now everything works as before ..

**Comment by mafredri** [comment]
Maybe you've rebooted your computer in between? Anyhow, that's great. Love it when things sort themselves out :v: !

**Comment by raffylopez** [comment]
You might have hit the resource limit for processes/open files. This happened to me when I had so many zsh and tmux processes open, up to the point that tmux won't even allow me to create additional panes, and pure would unexplainably give me the same `async_job:zpty:2: no such pty command: prompt_pure` error at the same time. Check [(https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard/issues/30)]

As an extreme measure, just forcibly close down your processes (albeit ungracefully):
`sudo \ps -ef | awk '{print $1}' | tail -n +2 | awk '{system("pkill -u " $1)}'`

**Comment by scmx** [comment]
I had the same error this morning. It disappeared when I closed my 20+ tmux sessions :man_shrugging:

**Comment by cjayross** [comment]
I'm having this same issue, yet it happens when I am only using a single terminal session. Particularly, it happens when I am working within a git repo.
