### ISSUE TITLE
Server hostname while on SSH

### ISSUE THREAD

**Issue by aspyatkin** [sindresorhus/pure#136]
Hello, I don't know if it's an issue, but I have encountered the following:
<img width="794" alt="screenshot" src="https://cloud.githubusercontent.com/assets/4273812/8502070/db1c479c-21bc-11e5-87eb-045724b32270.png">
I am connecting to my server with installed oh-my-zsh and pure, and it seems I don't get the full server hostname (aspyatkin.com) in prompt, only part of it (aspyatkin).

**Comment by mafredri** [comment]
Hi, this is because `pure` is actually displaying the short hostname, `hostname -s`.

**Comment by arthurvr** [comment]
Is this something we plan to change? I actually like that it displays the short version.

**Comment by sindresorhus** [comment]
No. Happy to receive doc improvements if this is unclear though.
