### ISSUE TITLE
Customize Git arrow symbols

### ISSUE THREAD

**Issue by aspyatkin** [sindresorhus/pure#139]
Hello!
I suggest adding an ability to customize git arrows (currently `⇣` and `⇡`). Customization can be made  via environment variables `PURE_GIT_ARROW_DOWN_SYMBOL` and `PURE_GIT_ARROW_UP_SYMBOL`.

**P.S.** I would be proud to make a contribution, if you like the idea.

**Comment by sindresorhus** [comment]
Why?

**Comment by aspyatkin** [comment]
Some fonts may not be supporting that characters. E.g. Source Code Pro, Consolas.

**Comment by yveslaroche** [comment]
@sindresorhus on Windows for example PuTTY doesn't support displaying these. Luckily I don't use Windows at work anymore :)

**Comment by sindresorhus** [comment]
Is there a way to detect if a character is supported? I would prefer to keep Pure simple and not add all kinds of options.

**Comment by aspyatkin** [comment]
@sindresorhus Somehow `pure` will be needing to detect which font is used. And I suppose that's not so easy and possible in all cases.
E.g. You have standard Terminal app, and iTerm2 on OS X. How could zsh know under what terminal is it running?
How could zsh on server machine detect your font settings on client machine if you are connecting over SSH?

**Comment by mafredri** [comment]
In light of the prompt symbol already being configurable, I'm not totally against this. I can't think of any other way to support limited charsets.

**Comment by sindresorhus** [comment]
I guess it's the only way then. Ugh, I hate computers so much...

**Comment by rdubaiev** [comment]
Hi. This may sound very stupid, but I'm a newbie toying around with pure and I was trying to add those arrows to the prompt. Any way you could explain me how I could add them? I have tried for hours now and it doesn't seem to work.
