### ISSUE TITLE
Reduce visual glitches when pre-prompt is same length as the terminal has columns

### ISSUE THREAD

**Issue by mafredri** [sindresorhus/pure#145]
When the preprompt line of pure is dangerously close to `$COLUMNS` of the terminal, the following can happen when updating it.

![](https://www.dropbox.com/s/n1gco44l5n3fxgs/Screenshot%202015-07-15%2016.22.15.png?dl=1)

There are two edge cases that are triggered when async jobs are done, and the pre-prompt is rendered (as can be seen in the screenshot):

1. Pre-prompt length goes from `$length <= $COLUMNS` to `$length > $COLUMNS`. This results in the spacing between commands disappearing.
2. Pre-prompt length goes from `$length > $COLUMNS` to `$length <= $COLUMNS`. This results in a "dead line" above the pre-prompt, with part of the old pre-prompt remaining.

**Potential solution**

Store the length of the previous pre-prompt, compare it to current `$COLUMNS` and for `1.` decide if we need to add one or more newlines at top, and for `2.` decide if you should erase any lines above the new pre-prompt.

**Comment by zmwangx** [comment]
While we are at it, I would mention a related area where the place to update/whether to update can be fine-grained, namely, when the user clears screen before the preprompt is updated. See screencast:

[![asciicast](https://asciinema.org/a/23484.png)](https://asciinema.org/a/23484)

To address this, we need to detect the absolute terminal line we are on.

Do you want a separate issue for this?

**Comment by mafredri** [comment]
I don't mind keeping it to one issue, even if this is a slightly different problem. Something like this could be used to know if the screen has been cleared. But I'm not so sure I like hijacking the users keybindings :/. Can we get any other useful details out of ZLE re: which line the cursor is on?

```zsh
typeset -gi clear
capture-clear() {
	zle clear-screen
	clear=1
}
zle -N capture-clear
bindkey '^l' capture-clear
```

**Comment by mafredri** [comment]
Actually, this clearing case seems pretty simple unless you can find any negatives / downsides with this implementation (works without any extra modifications)

```zsh
prompt_pure_clear_screen() {
	zle .clear-screen
	# enable output to terminal
	zle -I
	# clear the initial prompt and move cursor to beginning
	print -Pn "\e[1A\e[1G\e[K"
	# print precmd
	prompt_pure_preprompt_render precmd
}
zle -N clear-screen prompt_pure_clear_screen
```

**Comment by zmwangx** [comment]
> I don't mind keeping it to one issue, even if this is a slightly different problem.

Well, now that I think about it, it's actually vastly different, and closer to #145.

Anyway,

> Can we get any other useful details out of ZLE re: which line the cursor is on? PS. I'm a ZLE noob, don't know much about what's possible there :).

I'm also not a veteran at ZLE. Whenever I need something, I go search [the documentation](http://zsh.sourceforge.net/Doc/Release/Zsh-Line-Editor.html) :wink: However, maybe I'm wrong, but I think ZLE generally only knows about what's happening inside its buffer, but little about the terminal, except `BAUD`, `COLUMNS` and `LINES`, so I doubt we can extort absolute cursor position out of ZLE. After all ZLE isn't curses...

What I had in mind is a completely different approach using termcap. A patch:

```diff
diff --git a/pure.zsh b/pure.zsh
index db3ab21..fff1e3b 100644
--- a/pure.zsh
+++ b/pure.zsh
@@ -79,6 +79,26 @@ prompt_pure_string_length() {
        echo $(( ${#${(S%%)1//(\%([KF1]|)\{*\}|\%[Bbkf])}} ))
 }

+# sets prompt_pure_cursor_line and prompt_pure_cursor_column if terminal supports cursor reporting,
+# or empty these two parameters if there's no such termcap
+prompt_pure_query_cursor_location() {
+       setopt localoptions noksharrays nobashrematch
+       local line_column_report
+       # For a terminal with cursor reporting capability, when it receives \e[6n it would echo back \e[row;colR where
+       # row and col are numbers; for a terminal lacking such capability, it would print \e[6n as is (in theory).
+       # Therefore, by using R and n as delimiters in the silent read, line_column_report would either receive \e[row;col
+       # or \e[6, and we may extract the row (line) and column with a regex match.
+       echo -ne '\e[6n'
+       read -s -d 'Rn' line_column_report
+       if [[ $line_column_report =~ $'^\e\\[([0-9]+);([0-9]+)$' ]]; then
+           prompt_pure_cursor_line=$match[1]
+           prompt_pure_cursor_column=$match[2]
+       else
+           prompt_pure_cursor_line=
+           prompt_pure_cursor_column=
+       fi
+}
+
 prompt_pure_preprompt_render() {
        # check that no command is currently running, the preprompt will otherwise be rendered in the wrong place
        [[ -n ${prompt_pure_cmd_timestamp+x} && "$1" != "precmd" ]] && return
@@ -109,6 +129,10 @@ prompt_pure_preprompt_render() {
                local preprompt_length=$(prompt_pure_string_length $preprompt)
                local lines=$(( ($preprompt_length - 1) / $COLUMNS + 1 ))

+               prompt_pure_query_cursor_location
+               # if cursor location info is available, and there are not enough lines to move up, then do not render
+               [[ -n $prompt_pure_cursor_line ]] && (( prompt_pure_cursor_line <= lines )) && return
+
                # disable clearing of line if last char of preprompt is last column of terminal
                local clr="\e[K"
                (( $COLUMNS * $lines == $preprompt_length )) && clr=""
```

**Comment by zmwangx** [comment]
> Actually, this clearing case seems pretty simple unless you can find any negatives / downsides with this implementation (works without any extra modifications)

Ah missed this. On second thought this might be better. I'll report back in a few minutes.

**Comment by mafredri** [comment]
> What I had in mind is a completely different approach using termcap. A patch:

Before you venture too far down that road, check: https://github.com/sindresorhus/pure/issues/127#issuecomment-111813242

I also tried reading the output from `\e[6` but it proved unreliable (bleeding in tmux), attempted to use `stty` to circumvent that but it had other problems (much slowdown, occasional missed updated, etc).

**Comment by zmwangx** [comment]
> Actually, this clearing case seems pretty simple unless you can find any negatives / downsides with this implementation (works without any extra modifications).

I'm not a fan of the blank line on top, otherwise it's great :+1:

**Comment by mafredri** [comment]
> I'm not a fan of the blank line on top, otherwise it's great :+1: 

I did it like that because I thought I'd mimic the behavior of opening a new terminal window, easily fixable. 

This still suffers from https://github.com/sindresorhus/pure/issues/143 though, I'll have to get more intimate with that as soon as I have some more time :).

**Comment by zmwangx** [comment]
> I also tried reading the output from \e[6 but it proved unreliable (bleeding in tmux)

Could you please elaborate on that? Tried in tmux but can't reproduce, seems to be working just fine for me. Not that I like my solution; having a preprompt after screen clearing is nice.

> I did it like that because I thought I'd mimic the behavior of opening a new terminal window,

You got a point. I'm not really a `pure` user (although my logic is highly modeled on pure, so I suffer from mostly the same issues), so actual pure users got to decide.

One thing to keep in mind though: a user customized `clear-screen` will break the binding. If we do this, then we need to instruct users in README to customize `clear-screen` based on `prompt_pure_clear_screen`, rather than `.clear-screen`.

**Comment by zmwangx** [comment]
One more thing: might as well do

```zsh
prompt_pure_clear_screen() {
    # enable output to terminal from ZLE
    zle -I
    # clear screen and move to (0, 0)
    print -n "\e[2J\e[0;0H"
    # print precmd
    prompt_pure_preprompt_render precmd
}
```

I suppose terminals with cursor movement support should recognize these codes; after all we are already using a bunch of these ANSI escape sequences. This has the additional advantage of making a difference in iTerm2 with shell integration:

* With `print -n "\e[2J\e[0;0H"`:

  ![screen shot 2015-07-15 at 3 39 38 pm](https://cloud.githubusercontent.com/assets/4149852/8711560/f69ed8f0-2b07-11e5-8bcb-617d93acac1d.png)

* With `zle .clear-screen`:

  ![screen shot 2015-07-15 at 3 40 55 pm](https://cloud.githubusercontent.com/assets/4149852/8711559/f69a9ac4-2b07-11e5-8a3f-8dfb91e45551.png)

**Comment by zmwangx** [comment]
> Tried in tmux but can't reproduce, seems to be working just fine for me.

Okay, saw the leaks. Happens once every few dozen calls.

**Comment by mafredri** [comment]
> `print -n "\e[2J\e[0;0H"`

Yeah, that's better!

**Comment by mafredri** [comment]
Reopening this since the clear screen was actually a separate issue, but was only discussed here. The original problem remains.

**Comment by zmwangx** [comment]
> Reopening this since the clear screen was actually a separate issue, but was only discussed here. The original problem remains.

Sorry for hijacking the thread...
