### ISSUE TITLE
Improve performance

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/pure#150]
Inspired by https://github.com/sindresorhus/pure/pull/149.

Not sure if this is even an issue, but faster is always nice.

I've used `zprof` in the past.
- [ ] Fastest git dirty check: #115

What else? Suggestions welcome.

**Comment by ff2000** [comment]
I would like to see some sort of blacklist...
My use case: I use the git repo for my gentoo main tree (besides some other large repos like kde). The way to check one package's ChangeLog - e.g. in case an update introduced some breakage - is to inspect the git log. As soon as I enter the directory my computer goes down (heavy disc usage), it is completely unusable (mouse cursor doesn't move, window focus doesn't change) and also caches got emptied, so going back to the browser will likely take some time.
So I would like to blacklist "/var/repositpories/*"

Running iotop I saw several instances of git diff running. Is that expected?

**Comment by mafredri** [comment]
@ff2000 I don't think this request is relevant to this issue, in the future you should open a new issue :)

This is actually a feature under planning, I'm not quite sure how to formulate, or implement, it yet, which is why I haven't created an issue for it either.

For now you will be able to do this like so:

```console
zstyle ':vcs_info:*' disable-patterns "/var/repositpories/(|/*)"
```

**Comment by mafredri** [comment]
I did a quick performance test of capturing output (via `print` and `$()`) vs. the method we currently use in pure (`typeset -g "$1"=value`). The difference is pretty extreme, as evident from [this gist](https://gist.github.com/mafredri/93b01fd0384a737da213e6b9bba205a6).

Didn't remember if we had this documented anywhere, but this should be motivation enough to keep `typeset -g` around.

**Comment by sindresorhus** [comment]
Alright. Gonna close this issue now. We can open more focused issues if we come up with any more ideas for performance improvements.
