### ISSUE TITLE
Trouble with preprompt

### ISSUE THREAD

**Issue by nicinabox** [sindresorhus/pure#154]
I got it working on one machine, but having trouble with the other. The preprompt goes missing when I clear the screen. I have gone through the tips in the readme (which worked for one machine), but I can't seem to get anything to change.

* I am using the same dotfiles and config on both
* I have the same versions of `brew`, `git`, `zsh`, and `zsh-syntax-highlighting` on both
* I have `zsh-syntax-highlighting` sourced as the last item in my `.zshrc`
* I am using `oh-my-zsh`
* `zle -l | grep clear-screen` returns `clear-screen (_zsh_highlight_widget_clear-screen)`, but if I remove the `zsh-syntax-highlighting` source it returns nothing, but also nothing changes with the preprompt.

So any ideas where I should look next?

**Comment by mafredri** [comment]
Would it be possible your other machine is running an old version of pure? I'd recommend  starting with a clean oh-my-zsh, install pure and see if you can reproduce. Also make sure you don't have pure installed in multiple ways: e.g. Through npm and again in oh my Zsh, etc.

**Comment by nicinabox** [comment]
I installed pure the same day, on both, but just to double check I ran `npm update -g pure-prompt` on both. I'm not sure what you mean by "installed in multiple ways". I did npm install + [oh my zsh integration](https://github.com/sindresorhus/pure#oh-my-zsh).

Here's my full [zshrc](https://github.com/nicinabox/dotfiles/blob/master/src/zshrc) if that helps.

**Comment by nicinabox** [comment]
Installed off master and now it works! That must have been what I did on the other machine.
