### ISSUE TITLE
Custom Colors

### ISSUE THREAD

**Issue by mcallan83** [sindresorhus/pure#155]
It would be great if we could somehow setup different colors for portions of the prompt via ENV variables or another method. For example, I would love to be able to change the color of the ssh user and host from the defaults. Right now it defaults to gray, which doesn't stand out enough for me. Any ideas?

**Comment by mafredri** [comment]
This is actually something we want to fix, see #126. Let's continue this discussion there, suggestions are welcome :).

The thing about `pure`, though, is that we want to keep configuration options to a minimum. Making one color configurable would kind of require us to make them all configurable, which we don't want.

**Comment by mcallan83** [comment]
Thanks, I posted there and the issue was promptly closed before anyone could discuss it. Apparently this is not something that will be fixed and isn't open for discussion, which is totally different from your comment above.

**Comment by mafredri** [comment]
I'm confused by what you mean, issue #126 is still open and hasn't been closed. This issue was closed because rather than allowing custom colors, we would like to solve the aforementioned issue.

**Comment by mcallan83** [comment]
My bad, I apologize. I saw the response to my comment as well as the "closed" tag above it, that was in reference to this issue, not #126.

**Comment by mafredri** [comment]
No worries :)
