### ISSUE TITLE
Different directory colors

### ISSUE THREAD

**Issue by jfreimer** [sindresorhus/pure#156]
I'm trying to use the pure theme with the solarized color scheme on OS X. I'm using zgen to load the theme: 
zgen load mafredri/zsh-async
zgen load sindresorhus/pure

However, when I do that the directory colors appears light grey rather than light blue. However, if I instead load the pure theme from oh-my-zsh "zgen oh-my-zsh themes/pure" then the directories appear blue, but other elements are a little outdated. Is there anyway to get the blue directories with the latest version?

<img width="389" alt="screen shot 2015-07-30 at 12 16 57 am" src="https://cloud.githubusercontent.com/assets/7303848/8977805/341a5cf0-3651-11e5-91ad-04ba595e0647.png">
<img width="582" alt="screen shot 2015-07-30 at 12 14 45 am" src="https://cloud.githubusercontent.com/assets/7303848/8977806/343634d4-3651-11e5-95c9-e9032d7f8004.png">

**Comment by mafredri** [comment]
Pure doesn't make any changes to ls behavior. This is controllable through
the `lscolors` variable. I'm sure oh-my-zsh changes it somewhere. That's
why you're seeing the different colors.
