### ISSUE TITLE
Add option to prevent setting terminal title

### ISSUE THREAD

**Issue by alem0lars** [sindresorhus/pure#160]
Sometimes you need to **not set** the terminal title automatically.

For example when you use ZSH inside tmux or screen, it's a common practice to name tabs in a comfortable way to remember what's going on on each tab.

Is it possible to introduce a environment variable (or zstyle) to prevent automatic setting of the terminal title?

Thanks :)

**Comment by mafredri** [comment]
Is there a way to detect if the title has been modified or some such? Or is
there a way to tell tmux to ignore the title when you set one manually?
Honestly that's where I think it belongs.

On vacation at the moment, but can take a look when I get back.

**Comment by alem0lars** [comment]
Tmux does nothing particular.. It just picks the terminal title and when you manually set the title it just sets the terminal title to the new value.

I've tried commenting the zsh-add-hook lines and then I am able to manually set the title but ofc it's not a solution since I think it those hooks do other things and sometimes is good to have title automatically set. 

Alessandro Molari

**Comment by mafredri** [comment]
I can't actually reproduce the issue with tmux, after naming the window, it stays named that way:

![](https://www.dropbox.com/s/kus6x6ogk4jwhal/Screenshot%202015-09-09%2013.16.38.png?dl=1)

Are you sure your issue isn't solved by setting `set -g set-titles on` in your tmux.conf ?

**Comment by alem0lars** [comment]
Yes it's not working.
I have that option enabled and also I've tried to manually set it:


![2015-09-09-134517_1440x900_scrot](https://cloud.githubusercontent.com/assets/336957/9763449/15df8a44-56f9-11e5-9994-2753c6ca1b03.png)

![2015-09-09-134651_1440x900_scrot](https://cloud.githubusercontent.com/assets/336957/9763476/3db07d3a-56f9-11e5-9617-9c7557d0da31.png)

![2015-09-09-134531_1440x900_scrot](https://cloud.githubusercontent.com/assets/336957/9763456/1c426d0c-56f9-11e5-929c-6593f3aac128.png)

![2015-09-09-134538_1440x900_scrot](https://cloud.githubusercontent.com/assets/336957/9763458/1f17996c-56f9-11e5-8c0b-824923da0928.png)

----

Instead, when I comment the hooks it works correctly

**Comment by mafredri** [comment]
It's a bit hard to look at your huge screenshots, but the message you're trying to convey is that *helloworld* was replaced with *vim*? I really cannot reproduce this in tmux (2.0) though. Does it happen with anything other than vim as well?

**Comment by alem0lars** [comment]
Sorry for huge screenshots :)

Yes it also works with other programs

**Comment by mafredri** [comment]
I saw this, perhaps it could be a solution to your problems? https://github.com/tmuxinator/tmuxinator/issues/141

Essentially `set-window-option -g allow-rename off`?

If I run `:set automatic-rename on` I get the unwanted tab renaming behavior you're talking about.

**Comment by alem0lars** [comment]
I've tried to run both of the commands you mentioned but they doesn't work.

Plus, that would be just a workaround to the issue.

In any case, it doesn't work

**Comment by mafredri** [comment]
You say this is a issue of pure, but as I see it it's an issue of `tmux` leaking the current title. I'm not quite sure how you're suggesting the behavior of `pure` should change.

For example: I definitely want pure to set the titles in tmux so that I can from the title spot what command is running. For me there is no issue with naming tmux tabs and getting the benefit of both: having a named tab and seeing the title.

What change are you suggesting we make to pure to accommodate you're use-case, and if this change requires feature detection, how do we do it? Is the screenshot I posted above not the best of both worlds?

**Comment by alem0lars** [comment]
I suggest to give the user an option to enable or disable automatic renaming of the terminal title.

If the user disables the renaming, the terminal title is never touched; otherwise, the behaviour is the current one.

This can be accomplished with an environment variable or (better) a zstyle configuration.

The zstyle configuration allows the user to dynamically turn on/off that feature.

The implementation should check that zstyle option every time it tries to rename the terminal title.

**Comment by sindresorhus** [comment]
Not going to add an option in Pure for this. Happy to consider other solutions.

**Comment by alem0lars** [comment]
Why?

**Comment by sindresorhus** [comment]
It's not an issue with Pure. The bar to add an option in Pure is very high as we're trying to keep it simple. "Just add another option" is the lazy way out.

**Comment by alem0lars** [comment]
Ok, if you don't care about the issue close it as won't fix.

But this is **definitely** an issue with Pure, because Pure overwrites the terminal title not some one else.

**Comment by sindresorhus** [comment]
We've been trying to be accommodating but this is going nowhere.

-

Please read https://github.com/sindresorhus/pure/issues/160#issuecomment-140706292 again.

**Comment by forivall** [comment]
If you really want, you can easily maintain your own fork; I'm doing it for https://github.com/forivall/pure/tree/underline-repo-name

**Comment by alem0lars** [comment]
That's what I'm going to do. I've thought it is really dumb to maintain different forks for so small differences, but with these maintainers it's the only thing I can do.

**Comment by mafredri** [comment]
It's pretty hard to help you when you're fighting us every step of the way. At least I'm happy you're now showing some interest in solving this yourself, good luck :)!

**Comment by repoles** [comment]
I use macOS Terminal that already has a better option to set the window title. Unfortunately I can't use that feature with pure, since latter doesn't have a simple way to stop setting the title. A new variable to enable or disable this would be really useful. Sad to see this issue won't be fixed.

**Comment by mafredri** [comment]
@repoles it's not official, but: https://github.com/sindresorhus/pure/wiki#disable-pure-terminal-title-updates.

**Comment by repoles** [comment]
Thank you very much, @mafredri! I should have read the wiki ;)
