### ISSUE TITLE
Pure does not show my git status

### ISSUE THREAD

**Issue by ababol** [sindresorhus/pure#161]
I am using pure with `zgen` and `oh-my-zsh` and my git status isn't displayed if my git is dirty.

Here is my configuration:

```bash
❯ zsh --version
zsh 5.0.8 (x86_64-apple-darwin14.4.0)
❯ git --version
git version 2.5.1
```

```bash
# theme
zgen load mafredri/zsh-async
zgen load sindresorhus/pure
```

<img width="544" alt="screen shot 2015-08-30 at 20 12 48" src="https://cloud.githubusercontent.com/assets/1850538/9568744/881cde8e-4f53-11e5-9f24-60c3ba5c186a.png">

Note that when I am doing a commit, it is correctly working:
<img width="392" alt="screen shot 2015-08-30 at 20 19 32" src="https://cloud.githubusercontent.com/assets/1850538/9568770/92042956-4f54-11e5-9c75-f402b2f0b11f.png">

Everything is correctly working with the default oh-my-zsh theme (arrow, robbyrussel...) but not with pure :/.

Here is my `.zshrc`:
https://github.com/ababol/dotfiles/blob/dotfiles/zsh/zshrc.symlink#L29-L31

**Comment by ababol** [comment]
Resolved, https://github.com/ababol/dotfiles/commit/10a65795e42f071e83337750ca2d8ccda3879ca1

**Comment by mafredri** [comment]
Glad you solved it! I'll try to investigate this further as it's probably a
problem with zsh-async when local traps are set.

**Comment by ababol** [comment]
Yep thanks and good luck :four_leaf_clover: !
