### ISSUE TITLE
"Cannot rebase onto multiple branches" when git pull

### ISSUE THREAD

**Issue by MoOx** [sindresorhus/pure#162]
When I do "git pull" (too quickly I guess) I get this annoying error. It's probably because pure is doing some stuff on the git repo as well as I am.
Any idea how we can make this better to avoid this issue?

**Comment by sindresorhus** [comment]
:+1: I've been annoyed by this too. Not sure what we can do about it though. Maybe have Pure cancel the background `git fetch` if we do `git pull` interactively.

**Comment by mafredri** [comment]
This is a valid issue and has bugged me too. Question is how to reliably
detect what command is being run. It's easy enough to check what command
was entered at the cmdline and I think perhaps any git command at all
should cancel all background git activity. This of course isn't very
reliable if git is aliased and the command being run is something like:
"gpull".

**Comment by sindresorhus** [comment]
> This of course isn't very
reliable if git is aliased and the command being run is something like:
"gpull".

You can see if it's aliased with `which gpull` or `alias gpull`.

**Comment by mafredri** [comment]
That's true, but there could be multiple levels of aliases, although there
is probably a way to have whence show the final command behind all aliases.
One tricky part is catching all possible scenarios when entering the
command, it doesn't need to be the first command to be valid either, so we
might end up having to check every command / parameter entered on the
cmdline.

One kinky example I can think of is:

_git() {
  #pre code here
  command git $@
}
alias git=_git

It's not trivial (AFAIK) figuring out that git is being run.

It would be nice if we could define some git hooks (environmental) to
cancel the pure git fetch (haven't investigated).

**Comment by mafredri** [comment]
I've been looking into solving this for a while now, and I think I've finally found a solution that should turn this from an issue to a non-issue. I've pushed a [new branch](https://github.com/sindresorhus/pure/tree/nice-git-fetch), I would appreciate if you could test it and see if it resolves your issues.

Here is an illustration (by adding a `&& print kill` to the relevant part of the code) why it's not a perfect solution:

```
~/Projects/pure nice-git-fetch*
❯ alias gpull='git pull'
kill

~/Projects/pure nice-git-fetch*
❯ gpull
kill
Already up-to-date.

~/Projects/pure nice-git-fetch*
❯ git fetch
kill

~/Projects/pure nice-git-fetch*
❯ sleep 1 && git fetch
kill

~/Projects/pure nice-git-fetch*
❯ gfetch() { git fetch }

~/Projects/pure nice-git-fetch*
❯ gfetch

~/Projects/pure nice-git-fetch*
❯ sleep 1; git fetch
kill
```

**Comment by zmwangx** [comment]
:+1:

**Comment by mafredri** [comment]
@zmwangx in case you missed it, the change to `zsh-async` is also necessary to actually kill the processes, I've not yet pushed them to the async repo :P.

**Comment by forivall** [comment]
In case someone is creating a more complex function-style git alias, they should just be instructed to use `async_flush_jobs 'prompt_pure'`, or a simpler alias for that command.

**Comment by zmwangx** [comment]
> I've not yet pushed them to the async repo.

Yeah waiting for that, don't want to fork the repo and make my own commit. I have it patched locally though.

**Comment by mafredri** [comment]
@forivall I support that idea, but maybe it's not a common enough problem to warrant a FAQ entry? I don't really foresee anyone running into this. Also, it's not really a hard case to detect either, just extra overhead (maybe?)

```zsh
~/Projects/zsh-async master
❯ gpull() { git pull }

~/Projects/zsh-async master
❯ [[ $(typeset -f gpull) =~ git\ .*(pull|fetch) ]] && print "pong"
pong

~/Projects/zsh-async master
❯ gpull() { gitpull }

~/Projects/zsh-async master
❯ [[ $(typeset -f gpull) =~ git\ .*(pull|fetch) ]] && print "pong"
```
---
@zmwangx I created a test case for it to verify that it actually performs as expected and pushed it to the `zsh-async` repo! :)

**Comment by zmwangx** [comment]
> maybe it's not a common enough problem to warrant a FAQ entry?

Probably not. Also, people with this problem will probably be able to find this issue, so no need to bloat the FAQ.

By the way, if one is using a function/script wrapper, then they surely know what the wrapper is doing without expanding it, so `[[ $2 =~ gpull ]]` will be enough... I can totally imagine people adding the case for `hub`, actually.

**Comment by mafredri** [comment]
> By the way, if one is using a function/script wrapper, then they surely know what the wrapper is doing without expanding it, so `[[ $2 =~ gpull ]]` will be enough... I can totally imagine people adding the case for `hub`, actually.

I don't quite follow? If you're referring to the `typeset -f gpull` stuff above, that was just an example. It would actually be something closer to `typeset -f $2`

**Comment by zmwangx** [comment]
> It would actually be something closer to `typeset -f $2`

In my opinion this issue is rare enough, so rather than trying to expand everything (and still not cover case — say you have a binary wrapper) it would be more productive and performant for people who use wrappers to add individual cases.

**Comment by mafredri** [comment]
> In my opinion this issue is rare enough, so rather than trying to expand everything (and still not cover every case — say you have a binary wrapper) it would be more productive and performant for people who use wrappers to add individual cases.

Yep, agree, I'm not arguing that we should do it, just that it's possible :)! I think capturing the most common case (and also aliases, since we get that for free) is good enough.

**Comment by mafredri** [comment]
There would also be the case of git aliases where `git p` could be the same as `git pull`. I'm not very interested in trying to work around that case either.
