### ISSUE TITLE
Just updated, now getting two directory outputs

### ISSUE THREAD

**Issue by trevordmiller** [sindresorhus/pure#163]
Just updated, now getting two directory outputs listed on each directory change or entered command; for example,

![screen shot 2015-09-14 at 9 56 21 pm](https://cloud.githubusercontent.com/assets/5497885/9867478/7a2495cc-5b2b-11e5-9c1e-1568174bb3bb.png)

![screen shot 2015-09-14 at 9 56 14 pm](https://cloud.githubusercontent.com/assets/5497885/9867479/7a27e7ae-5b2b-11e5-8e2d-bd17c66cad90.png)

**Comment by sindresorhus** [comment]
How did you update? `npm install -g pure` or manually? What system are you on? ZSH version?

**Comment by mafredri** [comment]
Looks to me like you might have a custom precmd that prints the extra path.
How does this look when you're inside a git directory?

**Comment by mafredri** [comment]
I took a look at this and it doesn't seem like it can be the `precmd`. It must almost certainly be that a variable used internally by pure has been modified from the outside.

The output of these commands could help:

```zsh
typeset -p vcs_info_msg_0_
typeset -p prompt_pure_git_dirty
typeset -p prompt_pure_username
```

I don't think it can be any other variable, since all colors are terminated (reset to default) and it looks from your screenshots like the extra path is colored by `%F{242}`.

**Comment by trevordmiller** [comment]
@sindresorhus Brand new computer, just installed oh-my-zsh and copied over `pure.zsh-theme` and `async.zsh` to `custom` as shown in the pure `README.md`. I haven't customized or changed anything other than adding `pure` as the theme in my `.zshrc`.

@mafredri It works as expected in a Git directory - shows the directory (not duplicated) and the branch name + git status:
![screen shot 2015-09-16 at 9 14 43 am](https://cloud.githubusercontent.com/assets/5497885/9908985/665e1e68-5c53-11e5-82c4-37ce862b8af7.png)

Here is the output from the three commands you mentioned:

```
❯ typeset -p vcs_info_msg_0_
typeset -x vcs_info_msg_0_=' mobile-web/refactor/js-linting'

❯ typeset -p prompt_pure_git_dirty
typeset prompt_pure_git_dirty='*'

❯ typeset -p prompt_pure_username
typeset: no such variable: prompt_pure_username
```

Thank you.

**Comment by mafredri** [comment]
All this looks very weird, like you have both a older version of pure and the newer one or something... How is your git branch blue? And it seems like it is showing `$vcs_info_msg_1_` where it should be showing `$vcs_info_msg_0_`... I will need to know all modifications you have made to zsh, e.g. your `.zshrc`. Also, have you installed pure through `npm`?

**Comment by mafredri** [comment]
Ah, I read your comment a bit sloppily, I see now that you hadn't made any changes to `.zshrc`, so I investigated... it looks like pure is included in `oh-my-zsh`, or at least a very old version of it, as can be seen [here](https://github.com/robbyrussell/oh-my-zsh/commit/2c56345917624bd94bfc05fe7bdbb2051421d5e7). You should go ahead and either delete `oh-my-zsh/themes/pure.zsh-theme` or replace it with the new one `mv oh-my-zsh/custom/pure.zsh-theme oh-my-zsh/themes/pure.zsh-theme`

**Comment by trevordmiller** [comment]
@mafredri Removing the pre-installed `pure.zsh-theme` in `oh-my-zsh/themes/pure.zsh-theme` did the trick. Thank you for catching that!
