### ISSUE TITLE
`prompt_pure_async_git_dirty` return echo not working (for me)

### ISSUE THREAD

**Issue by themartorana** [sindresorhus/pure#168]
When the last line of `prompt_pure_async_git_dirty` is 

    (( $? )) && echo "*"

I never see the * for a dirty git repo. If I change it to:

    if  [[ "$?" == "1" ]]; then
        echo "*"
    fi

It Works For Me. Maybe this is a shortcoming of my own environment?

**Comment by mafredri** [comment]
That's very, very odd. Would you post the output of `setopt`? Also, what's the output of `(( 1 )) && echo hi`.

**Comment by themartorana** [comment]
In all inexplicable madness, after playing with it for a while (trying to understand what was happening) and then reverting my changes by checking out from git... it works. :(

I'll close this ticket. Sorry for wasting your time.

**Comment by mafredri** [comment]
Oh, well glad it's not an issue any more, was really weirding me out :D!
