### ISSUE TITLE
RPROMPT on first row

### ISSUE THREAD

**Issue by nbari** [sindresorhus/pure#170]
Could it be posible to have the **RPROMPT** on the first row, in my case I would like to have the date at the right something like:

    nbari ~/projects/violetear develop                        21:45:22
    > 

Currently I am using this ``RPROMPT="%F{8}%*"`` but is set on the second row:

    nbari ~/projects/violetear develop                        
    >                                                         21:45:22

Any ideas ?

**Comment by mafredri** [comment]
It would should be possible to implement in pure for the prepromt. But using RPROMPT for it is not possible.

Not quite sure how to do it at the moment. One method might involve filling the prepromt with spaces between the dir and the time (easy since we know the prepromt length and terminal size). Another could use ansi escape codes to draw the time there afterwards.

**Comment by mafredri** [comment]
Like a so:

```patch
diff --git a/pure.zsh b/pure.zsh
index b7acaee..f5330ba 100644
--- a/pure.zsh
+++ b/pure.zsh
@@ -116,6 +116,12 @@ prompt_pure_string_length_to_var() {
 	typeset -g "${var}"="${length}"
 }
 
+prompt_pure_apply_rprompt() {
+	str='%F{blue}%*%f'
+	pos=$(( COLUMNS - 7 ))
+	print -Pn "\e7\e[1A\e[${pos}G${str}\e8"
+}
+
 prompt_pure_preprompt_render() {
 	# check that no command is currently running, the preprompt will otherwise be rendered in the wrong place
 	[[ -n ${prompt_pure_cmd_timestamp+x} && "$1" != "precmd" ]] && return
@@ -184,6 +190,8 @@ prompt_pure_preprompt_render() {
 		print -Pn "\e7${clr_prev_preprompt}\e[${lines}A\e[1G${preprompt}${clr}\e8"
 	fi
 
+	prompt_pure_apply_rprompt
+
 	# store previous preprompt for comparison
 	prompt_pure_last_preprompt=$preprompt
 }
```

It's basically updated everytime the prompt is updated, so if you only want an update during `precmd`, you need to cache the date in a variable. It's also not smart in the sense that it will overwrite anything under it if the terminal is too small to fit the entire preprompt, for example. It's also possible to make it auto update using `zsh/sched` but I'll leave that as an exercise :).

**Comment by nbari** [comment]
many thanks :100:

**Comment by nbari** [comment]
@mafredri 2 years after and now with a small terminal I start to have issues by updating the `rpromt` since it basically overwrites what I type.

this is how my current prompt looks like:

    nbari ~/path master               14:18:30
    $

Works nice but the problem I am facing now is that if I want to type in multi lines:

    nbari ~/path master               14:18:30
    $ echo "\                         14:18:31
    dquote>

The time appears in the new line instead of just refreshing the original position, therefore I would like to know if you have any idea of about how to refresh it only in its current position, instead of just printing it on each subsequent line

Thanks in advance.

**Comment by mafredri** [comment]
@nbari should work fine if you add some guards against the update:

```zsh
prompt_pure_at_ps1=1
prompt_pure_update_guard() {
	if [[ $CONTEXT = start ]]; then
		prompt_pure_at_ps1=1
	else
		prompt_pure_at_ps1=0
	fi
}
zle -N prompt_pure_update_guard

prompt_pure_apply_rprompt() {
	zle && prompt_pure_update_guard || return 0
	if (( ! prompt_pure_at_ps1 )); then
		return 0
	fi

	str='%F{blue}%*%f'
	pos=$(( COLUMNS - 7 ))
	print -Pn "\e7\e[1A\e[${pos}G${str}\e8"
}

TMOUT=1
TRAPALRM() {
    prompt_pure_apply_rprompt
}
```

**Comment by mafredri** [comment]
Making it any smarter than this is tremendous work (to get to work correctly), but if you're interested you can consult #143.

**Comment by nbari** [comment]
@mafredri many thanks, it is working,  prints the date with a 1-second delay but I think is because of the check, I will check in detail the issue you post to get a better understanding. 👍

**Comment by nbari** [comment]
@mafredri I need some more help please, my only purpose of having the time is to measure some scripts, therefore wondering if there is a way to only print the time after pressing the enter, so in case the command is huge, nothing will get printed until submitted, so with this, I can avoid overwriting the command line etc, idea? many thanks in advance

**Comment by mafredri** [comment]
@nbari In that case you could use the zsh `preexec` hook, e.g.: `preexec() { date; }`

**Comment by nbari** [comment]
@mafredri many thanks that will work 👍
