### ISSUE TITLE
Can't show correct path when I use RVM

### ISSUE THREAD

**Issue by ycavatars** [sindresorhus/pure#172]
hi, I use rvm to manage my ruby version. When I enter my ruby project folder, the prompt shows `~RVM_PROJECT_PATH` instead of `~/project_name`. How do I fix the issue? I use this theme in `prezto` which runs on OSX El Captain. Thanks.

**Comment by sindresorhus** [comment]
Does this happen if you use any other prompt? Sounds like a config issue on your part.

**Comment by mafredri** [comment]
That's because the zsh option auto_name_dirs is turned on.

unsetopt auto_name_dirs

**Comment by ycavatars** [comment]
@sindresorhus But another theme like `paradox` in prezto works correctly. However, I add the `unsetopt` option to fix the problem. Thank you!
@mafredri Thanks, I add it to .zshrc and it works well.

**Comment by mafredri** [comment]
[This](https://github.com/sorin-ionescu/prezto/blob/master/modules/prompt/functions/prompt_paradox_setup#L58) is the reason paradox worked for you, the don't use regular path expansion for the prompt (aka `%~`). Pure does, personally I like `autonamedirs`, and with some tinkering you can work around it, e.g. pure uses an `x`-prefix for vars containing full paths (`var="x/path/to/dir`). I could've sworn there was an option for hiding a var from autonamedirs, but I can't find it now.

Anyway, glad it's solved!

**Comment by novohispano** [comment]
I had the same issue. Just to add onto this, you have to add the `unsetopt auto_name_dirs` line in your shell file before you source RVM.

You can find more information here: https://rvm.io/integration/zsh
