### ISSUE TITLE
Brackets showing up on completed prompt in OS X El Capitan (10.11.1) Terminal

### ISSUE THREAD

**Issue by jrajav** [sindresorhus/pure#173]
Since upgrading to El Capitan I've seen light grey brackets surrounding the second line of the prompt after it completes (that is after pressing enter):

<img width="737" alt="screen shot 2015-11-24 at 14 11 23" src="https://cloud.githubusercontent.com/assets/2074135/11379360/9876998c-92b5-11e5-9c79-3d97ce4d21f5.png">

Could be a problem with the way Terminal interprets escapes now?

**Comment by mafredri** [comment]
See #166.

**Comment by jrajav** [comment]
My bad! Thank you! I hastily assumed it was a bug, having written escape-code prompts myself in the past with many a `[` and a `]`. Sorry to take your time.

**Comment by mafredri** [comment]
No worries! Hope you enjoy pure :-)
