### ISSUE TITLE
Spaces in repo path cause "no such file or directory"

### ISSUE THREAD

**Issue by herrbischoff** [sindresorhus/pure#180]
I have already checked https://github.com/sindresorhus/pure/issues/133 and the commit that should fix the issue. However, in my situation it unfortunately does not. There's a Git repository located at `~/Library/Application Support/Übersicht/widgets/some.widget`. Switching to this directory, immediately results in:

```
masterprompt_pure_async_git_dirty:cd:5: no such file or directory: /Users/[REDACTED]/Library/Application
fatal: Not a git repository (or any of the parent directories): .git
```

Just to be sure, I have already tried to manually patch in commit https://github.com/sindresorhus/pure/commit/2fcf5251b4873c36205e5e032d592ec24737e78d to no avail.

I'm using version 1.3.0 installed via `npm`.

**Comment by mafredri** [comment]
Do you have any other versions of zsh-async installed (in your $fpath for example)? Do you use any zsh "framework" for configuration?

**Comment by herrbischoff** [comment]
To my knowledge I do not use another zsh-async but I wouldn't swear on it. Here's my `$fpath`:

```bash
❯ echo $fpath
/usr/local/Cellar/task/2.5.0/share/zsh/site-functions/_task /Users/[REDACTED]/.zprezto/modules/helper/functions /Users/[REDACTED]/.zprezto/modules/completion/external/src /Users/[REDACTED]/.zprezto/modules/helper/functions /Users/[REDACTED]/.zprezto/modules/utility/functions /Users/[REDACTED]/.zprezto/modules/git/functions /Users/[REDACTED]/.zprezto/modules/node/functions /Users/[REDACTED]/.zprezto/modules/prompt/functions /usr/local/share/zsh/site-functions /usr/local/Cellar/zsh/5.2/share/zsh/functions
```

For configuration I use Prezto.

Zsh version:

```bash
❯ zsh --version
zsh 5.2 (x86_64-apple-darwin15.2.0)
```

**Comment by mafredri** [comment]
Prezto bundles async, are you running the latest git of prezto? If not you might have an old version. Prezto also include pure, no need to install through npm.

Also, you need to check your fpath yourself for a file (or symlink) named`async`, to me the contents says nothing :)

**Comment by herrbischoff** [comment]
Interesting, I totally overlooked this. Now that I have removed the `npm` package along with its symlink in `/usr/local/share/zsh/site-functions/`, it works like a charm. Thanks!

Would you care to elaborate a bit on why that is?

**Comment by mafredri** [comment]
I don't really see why there would have been a problem if your prezto is up-to-date. In the newer versions of zsh-async, the error stream is separated from the output stream and errors such as this should not happen. So the only thing I can think of is that an older zsh-async was loaded for some reason. If that's from npm or prezto, I do not now.
