### ISSUE TITLE
Listing of ports

### ISSUE THREAD

**Issue by edouard-lopez** [sindresorhus/pure#183]
Hi @sindresorhus, 

I'm contributing to a [`fish` port of your theme](rafaelrinaldi/pure) and as yours theme is aimed at `zsh` I was wondering if there is already a place to list ports of your theme? 

Otherwise I will create  `awesome-pure` or similar.

**Comment by sindresorhus** [comment]
In the wiki, but I think we can make it more obvious, like linking to it from the readme. I don't think it's worth having an awesome list for this.

**Comment by edouard-lopez** [comment]
Good for me, I submited a PR (see #186 ).
