### ISSUE TITLE
Wiki: change prompt in vi mode issue: prompt disappears in `tmux` session

### ISSUE THREAD

**Issue by srustamo** [sindresorhus/pure#184]
Wiki suggests [this](https://github.com/sindresorhus/pure/wiki#a-generic-way-of-showing-current-mode-in-vi-mode) solution to changing prompt depending on a vi mode. 

All's well, works great, except in a `tmux` session. The prompt is there initially, but disappears after running any command. After running a command, the prompt remains in insert mode, hitting <kbd>Esc</kbd> or any other key restores the prompt character (in `normal` or `insert` mode respectively).

**Comment by mafredri** [comment]
I'm pretty sure this problem is related to vi-mode moving the cursor and the preprompt updating can't calculate the correct position to redraw. If you could provide a screencast that would be very helpful (and key combinations used would make it even better)!

**Comment by srustamo** [comment]
[Here's](https://gist.github.com/srustamo/93b9b9fc16bde207d80b) a gist with my `.zshrc`. 
[Here's](http://www.screencast.com/t/j8fiXfxJ9u) the screencast.

I should've mentioned before, that if `pwd` is git controlled, then there are no problems with prompt character in tmux. This is also shown in the screencast.

**Comment by mafredri** [comment]
Thanks for screencasts! I can't reproduce this myself, but I do see some problems in your zshrc.

First off: you should put these at the very end of your .zshrc, they must be last (it's stated in their readmes but are a very common error none-the-less).

```zsh
source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /usr/local/opt/zsh-history-substring-search/zsh-history-substring-search.zsh
```

Secondly, you might also want to use this function instead:

```zsh
function zle-line-init zle-keymap-select {
    zle .reset-prompt
}
```

The `.` in front of `reset-prompt` ensures the original reset-prompt is called and not an aliased one.

Sidenote: Also, there really isn't any need to redefine prompt in the zle functions, once above (but after `prompt pure`) is enough.

Finally, if none of this helps, what version of iTerm are you running? I notice it says just `iTerm` on your machine, not `iTerm2`. Might be worth looking at upgrading.

**Comment by srustamo** [comment]
Thanks! Following your advice fixed the problem.
About iTerm says it is iTerm2, Build 2.1.4. 

If I may expand this thread a bit, the only time when the prompt char still disappears is when resizing the iTerm2 window (after applying the changes to `.zshrc` you suggested).

Creating or deleting `tmux` panes does not affect the prompt char.

**Comment by mafredri** [comment]
> Thanks! Following your advice fixed the problem.

Great! 

> About iTerm says it is iTerm2, Build 2.1.4.

Oh, my bad. I guess only the beta / nightly says iTerm2.

> If I may expand this thread a bit, the only time when the prompt char still disappears is when resizing the iTerm2 window

If you're using zsh >= 5.1.1 you might try adding to your zshrc (without affecting pure functionality). 

```zsh
TRAPWINCH() {
    zle && zle .reset-prompt && zle -R
}
```

It will trigger on window resize. Not sure if the zle -R is required though.

**Comment by srustamo** [comment]
Works perfectly. Thank you so much!

**Comment by srustamo** [comment]
Hello. The problem of missing prompt char in `tmux` session reappeared. The problem is exactly as described in the first message in this thread.

No changes were made to `zsh`. I installed `fzf`, which added `[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
` to the end of `.zshrc`, but moving it elsewhere did not help.  

An OSX security updated package was installed, though.  

I updated today `pure` with ` npm install --global pure-prompt`, to no effect. The prompt works as expected outside of `tmux`. Any idea what might be wrong?

[Here](https://gist.github.com/srustamo/93b9b9fc16bde207d80b) is the gist with `.zshrc`.

**Comment by mafredri** [comment]
You have double entries of:

```
source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /usr/local/opt/zsh-history-substring-search/zsh-history-substring-search.zsh
```

Remove the ones that are before the bottom, also experiment with having them in different order.

Other than that, have you tried removing stuff from your zshrc until it works again, e.g. does removing the sourcing of `.fzf.zsh` help?

**Comment by srustamo** [comment]
I keep `.zshrc` under git, and reverted to the version just before `fzf` related addition. So, I know that this revision was the one working (the changes before this revision irrelevant to this issue). Alas, the problem it seems is not related to `.zshrc`.

Playing with the order of last two lines did not help. Checked `.tmux.conf` revision history - no changes in the last 3 month. 

Very confusing. The only major change which happened was the OSX security update. Reverting that would take a lot of effort.

**Comment by mafredri** [comment]
Did you also remove the duplicate lines sourcings of zsh syntax highlighting and zsh hss? You didn't mention it so I'm just confirming.

I realize that this config was working before, I was just suggesting that you could try to narrow down the issue and see if it's possible that any part of it is conflicting by removing / commenting parts and seeing if it starts working.

**Comment by mafredri** [comment]
Somehow I suspect this is due to something external. I can reproduce if I just use

```zsh
PROMPT='%(?.%F{green}.%F{red})${${KEYMAP/vicmd/❮%f}/(main|viins)/❯}%f '
```

But the second I add:

```zsh
function zle-line-init zle-keymap-select {
	zle .reset-prompt
}
zle -N zle-line-init
zle -N zle-keymap-select
```

The problem is gone.

**Comment by srustamo** [comment]
It looks like I narrowed it down to `.tmux.conf`. If I remove it completely, and run `tmux` without it, there are no problems with the prompt. Would you mind having a look at [.tmux.conf](https://gist.github.com/srustamo/04934232a6a33268722bbda9c429c178) for any obvious issues?

**Comment by mafredri** [comment]
Nothing immediately sticks out, maybe [this](https://gist.github.com/srustamo/04934232a6a33268722bbda9c429c178#file-tmux-conf-L126-L138) does something funky, or perhaps [this](https://gist.github.com/srustamo/04934232a6a33268722bbda9c429c178#file-tmux-conf-L93) (no idea what this does)?

PS. This is just a hunch, but would you mind doing a `zsh --version` both outside and inside tmux? Just wondering if you're using a different zsh inside the tmux.

**Comment by srustamo** [comment]
The culprit is indeed this line `set-option -g default-command "reattach-to-user-namespace -l zsh"`.

This is a [wrapper](https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard) for `tmux` accessing OSX system clipboard. I just remembered that it was updated a couple to days ago.

Commenting that line out restores the prompt char behaviour, but alas breaks the access from `tmux` to system clipboard. 

If you don't mind, let me leave this issue open for a while, perhaps some OSX users can chime in.

**Comment by srustamo** [comment]
FWIW, `zsh --version` in both cases is `zsh 5.2 (x86_64-apple-darwin13.4.0)`. 
`which  zsh` in both cases is `/usr/local/bin/zsh`.

Many thanks for you time and support!

**Comment by srustamo** [comment]
[Here](https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard/issues/48#issuecomment-204156645) is a rather detailed analysis of a possible cause(s). 

Perhaps it sheds some light?

**Comment by mafredri** [comment]
I believe ChrisJohnsen is correct in that the prompt is the wrong place to check for `KEYMAP`. Making this small change should alleviate your issues if that's all there's to it:

```zsh
VIM_PROMPT="❯"
PROMPT='%(?.%F{green}.%F{red})${VIM_PROMPT}%f '

function zle-line-init zle-keymap-select { 
    VIM_PROMPT=${(S%%)${KEYMAP/vicmd/❮}/(main|viins)/❯} # Expand string in place
    zle .reset-prompt
}
zle -N zle-line-init
zle -N zle-keymap-select
```

Now the VIM_PROMPT parameter is only evaluated during `zle-line-init` and `zle-keymap-select` and is set to either `❮` or `❯`.

**Comment by mafredri** [comment]
@srustamo from your comment on the issue over at tmux-MacOSX-pasteboard I take it this solved the issue (PS. did you notice I also updated the code in my post above).

I'll update the wiki to reflect this.

**Comment by srustamo** [comment]
Thank you!
