### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by chikamichi** [sindresorhus/pure#187]
Hi,

I simply want to **thank you** for this brilliant theme. :gift_heart: 

*You may consider keeping that "issue" open for people to share their lovely feelings with you ;)*

**Comment by tomauty** [comment]
💖

**Comment by zckrs** [comment]
💘

**Comment by veggiemonk** [comment]
**Thank you** Using pure everywhere and daily!!!

**Comment by dmerejkowsky** [comment]
Ditto. I was quickly able to hack this and make my own little changes.

A suggestion: you should put somewhere in the README that the git data if fetched asynchronously. This is THE killer feature of this prompt, and one of the main reasons I've switched to it.

Keep up the good work !

**Comment by sindresorhus** [comment]
> A suggestion: you should put somewhere in the README that the git data if fetched asynchronously. This is THE killer feature of this prompt, and one of the main reasons I've switched to it.

Done. https://github.com/sindresorhus/pure/commit/74dbfba33ec31c50b3b41071d13a01e7c0de6517

**Comment by sindresorhus** [comment]
Thanks for all the ❤️ people. @mafredri and I really appriciate it :)
