### ISSUE TITLE
extraneous characters when used in ansi-term in emacs

### ISSUE THREAD

**Issue by randre03** [sindresorhus/pure#188]
I'm using Pure inside slimzsh https://github.com/changs/slimzsh as my terminal, but also with ansi-term in emacs. In ansi-term it results in extra characters being returned between prompts. This blog post - http://blog.refu.co/?p=1277 - describes exactly the issue as well as a solution for another zsh framework. I reached out to slimzsh's creator @changs for a fix, but after some assistance he indicated this issue would need to be resolved in the code for Pure.

I tried something along the lines of the suggested workaround in the provided blog post wherein I enclosed the "prompt_pure_set_title" function inside a conditional to check if it's running in emacs terminal, but that did not work. Any thoughts? Thanks

**Comment by mafredri** [comment]
Since I don't know how to reproduce this (I don't use emacs), let's start slow. Does it work if you add this to your `.zshrc` (after `prompt pure`)?

```zsh
# Disable set title
prompt_pure_set_title() {}
```

**Comment by randre03** [comment]
Heavens to Betsy! That  worked. Thanks chap!

**Comment by mafredri** [comment]
Gald it works for you! Keep in mind this disables the set title altogether, if you still want to keep it in other terminals then put it inside a conditional statement that can properly determine the terminal being used :+1: .
