### ISSUE TITLE
emacs shell 

### ISSUE THREAD

**Issue by Fetz** [sindresorhus/pure#191]
weird 7 and 8 symbols in emacs shell (spacemacs)

<img width="415" alt="screen shot 2016-01-29 at 11 43 13" src="https://cloud.githubusercontent.com/assets/1071113/12674796/87de1d2e-c67d-11e5-8ff9-b5347522f247.png">

**Comment by mafredri** [comment]
Does the solution in #188 help?

**Comment by Fetz** [comment]
I put in .zshrc after pure but still doesn't work

```
prompt pure
prompt_pure_set_title() {}
```

I notice it only happens when pure updates git status

**Comment by mafredri** [comment]
Ok. Since I see the 7 at the beginning and 8 at the end I suspect your terminal isn't supporting saving the current cursor position:

```
# \e7   => save cursor position
# \e8   => restore cursor position
```

I believe the offending line is in [pure.zsh#L187](https://github.com/sindresorhus/pure/blob/master/pure.zsh#L187).

Without these it is impossible to update the prompt and return the cursor to it's original position :/

**Comment by mafredri** [comment]
Actually I lied about it not being possible to return the cursor to it's original position.

This change should work for you (at least as a band-aid, assuming the rest of the ansi codes are supported), not sure what other repercussions it could have. There are lots of states the terminal could be in that should be taken into consideration.

```diff
diff --git a/pure.zsh b/pure.zsh
index a061851..6b1a10c 100644
--- a/pure.zsh
+++ b/pure.zsh
@@ -184,7 +184,8 @@ prompt_pure_preprompt_render() {
                (( COLUMNS * lines == preprompt_length )) && clr=

                # modify previous preprompt
-               print -Pn "\e7${clr_prev_preprompt}\e[${lines}A\e[1G${preprompt}${clr}\e8"
+               print -Pn "${clr_prev_preprompt}\e[${lines}A\e[1G${preprompt}${clr}\n"
+               zle && zle .reset-prompt
        fi

        # store previous preprompt for comparison
```

**Comment by sindresorhus** [comment]
This prompt is for ZSH, not Emacs shell.

**Comment by mafredri** [comment]
@sindresorhus The problem is that you can run ZSH inside emacs, I guess :P

**Comment by sindresorhus** [comment]
@mafredri And people are free to do that, but anything other than running ZSH is IMHO unsupported from our perspective. It's hard enough maintaining something that works fine on just vanilla ZSH.

**Comment by mafredri** [comment]
@sindresorhus I don't quite follow, I assume he is running ZSH, the difference lies in the actual terminal program, e.g. this would be like comparing Terminal vs iTerm vs "Emacs shell" (or whatever it is).

**Comment by Fetz** [comment]
By the way, yes I'm using zsh in emacs

**Comment by Fetz** [comment]
@mafredri yes is that line, I patched using like this:

```
if [ -n "$INSIDE_EMACS" ]; then
    print -Pn "${clr_prev_preprompt}\e[${lines}A\e[1G${preprompt}${clr}\n"
    zle && zle .reset-prompt
else
    print -Pn "\e7${clr_prev_preprompt}\e[${lines}A\e[1G${preprompt}${clr}\e8"
fi
```

**Comment by srustamo** [comment]
@Fetz I have updated to the latest commit (judging by `package.json` in the install dir), and hoped that it will fix the prompt in Emacs. It maybe an unrelated to this issue, please guide me if it is not. 

My Emacs pure prompt looks like this:
![image](https://cloud.githubusercontent.com/assets/749813/13243946/654460e2-da24-11e5-8307-2ac55d0c7187.png)

Any idea which way to dig to fix this?

Sorry for resurrecting a closed issue.

**Comment by siawyoung** [comment]
I also the above issue - will try to see if there's a way to resolve it
