### ISSUE TITLE
Prompt character not working with locale=en_GB.UTF-8

### ISSUE THREAD

**Issue by dhanjit** [sindresorhus/pure#193]
❯ uname -r
4.3.3-3-ARCH

❯ cat /etc/locale.conf
LANG=en_US.UTF-8

prompt if fine.
But with LANG=en_GB.UTF-8, the prompt arrow breaks.

**Comment by sindresorhus** [comment]
Breaks how?

**Comment by dhanjit** [comment]
```
~
â¯ 

```
This is what i get

**Comment by mafredri** [comment]
I don't believe this is a issue with `pure`. Either look into the configuration of your font or system locales.

You always have the option to change the prompt character if you wish to use an incompatible font, e.g. `PURE_PROMPT_SYMBOL=">"`.

**Comment by dhanjit** [comment]
Fixed, had to do sudo locale-gen "en_GB.UTF-8"
