### ISSUE TITLE
remove newline after preprompt

### ISSUE THREAD

**Issue by james2doyle** [sindresorhus/pure#195]
Hey I like this alot, but I want to remove the line break before the `❯` symbol.

How can I do this?

**Comment by mafredri** [comment]
The answer is, don't use `pure`. Feel free to modify it though! You can have a look at #109 for reference.

**Comment by james2doyle** [comment]
Yeah I am trying to modify it. I already have a few things changed but the line break before the caret character is the last thing I am tweaking

**Comment by mafredri** [comment]
To accomplish that everything has been laid out in the issue I referenced. From those I recommend the method I posted since it simplifies `pure` a lot (there is no longer a need to use ansi codes to update the prompt when keeping it as a single line).

**Comment by james2doyle** [comment]
Ok thanks I see now. If I figure it out I can post the results
