### ISSUE TITLE
pure hangs the zsh in msys2 environment

### ISSUE THREAD

**Issue by kunxi** [sindresorhus/pure#198]
I currently running the MSYS2 on Windows 10 with:

- zsh
- prezto
- pure theme

It works like a charm, but I encounter on minor issue: every time I close the shell, mintty for my case, with either `exit` or `Ctrl-D`, I see the good bye message from `.zlogout`, then it hangs. If I try to close the mintty window, a dialog will pop out like:

```
Process are running in session:
UID PID PPID TTY STIME COMMAND
Kun 1136 2600 pyt0 22:11:38 /usr/bin/zsh

Close anyway?
```

And nothing happens regardless I press OK or Cancel.

With Process Explorer, there are up to 6 zsh processes:

![Process Explorer screenshot](http://i.imgur.com/vWpTfwZ.png)

I have to manually kill all the processes to close the session.

I think this is caused by the async feature, since if I use other theme, such sorin, the bug does not repro.

I am pretty sure the combination of zsh, prezto and pure theme is *NOT* officially supported in Windows environment, but I like this configuration in my Mac, and hope to use it even extra miles to go.

Thanks.

**Comment by sindresorhus** [comment]
Sorry, not supported on Windows.

**Comment by kunxi** [comment]
I understand, I just try to dig the rabbit hole by myself. Do you have suggest some manual to read, debugging tips to share?

**Comment by kunxi** [comment]
Ok, just for the record, do not use `exit` or `Ctrl-D`, just close the mintty.exe window will cleanly exit the terminal. This will be the work around.

**Comment by mafredri** [comment]
Would it by chance exit cleanly if you executed `async_stop_worker prompt_pure` before running `exit` ?

**Comment by kunxi** [comment]
@mafredri  it hangs with `T0`

```
~
❯ async_stop_worker prompt_pure
▒T0▒
```

And the async worker is still alive.

**Comment by mafredri** [comment]
Alright, then it's as as I suspected. The zsh module [zsh/zpty](http://zsh.sourceforge.net/Doc/Release/Zsh-Modules.html#The-zsh_002fzpty-Module) seems to be the problematic one on windows. If you wish to explore this further then I'd say that's your best bet.

If I'm right you'd encounter this same hang with just trying to simply create a zpty and then delete it:

```console
zpty test cat
zpty -d test
```

**Comment by Restia666Ashdoll** [comment]
So, how do you even run this on MSYS2. Works fine on wsl.

**Comment by romkatv** [comment]
> So, how do you even run this on MSYS2.

The same way as anything else.

FWIW, [pure10k](https://gist.github.com/romkatv/7cbab80dcbc639003066bb68b9ae0bbf) (one of the ports mentioned on the Pure home page) works fine on MSYS2.

**Comment by Restia666Ashdoll** [comment]
thanks that works
