### ISSUE TITLE
Feature request: ls the directory contents on cd

### ISSUE THREAD

**Issue by vbauerster** [sindresorhus/pure#199]
Whenever I change directory, I always find myself entering ls in order to see its content.
Could you please implement such a feature, that upon cd, ls is executed automatically?
I know [another](https://github.com/chauncey-garrett/zsh-prompt-garrett#ls-the-directory-contents-on-cd) prompt theme, where it is implemented, but I prefer stay with pure because of its minimalism.
In my opinion it is very useful feature to be included and on by default.

**Comment by mafredri** [comment]
I'm sorry, but I don't consider this a helpful feature, it's also extremely impractical in directories that contain a large amount of files, not to mention that the rendering the content of such a directory over SSH can be extremely slow.

It is, however, super easy to do yourself. Just add this to your zshrc:

```zsh
chpwd() { ls }
```

It uses the zsh chpwd hook to execute a command on directory change.

**Comment by vbauerster** [comment]
Thanks for hint!
