### ISSUE TITLE
Bracket before prompt symbol

### ISSUE THREAD

**Issue by Plastix** [sindresorhus/pure#203]
After hitting enter a bracket appears before my prompt symbol. Any idea what is causing this? I'm running zsh `5.0.8` and OSX `10.11.3` with the regular Apple Terminal. 
<img width="132" alt="screen shot 2016-03-24 at 11 07 46 am" src="https://cloud.githubusercontent.com/assets/1526881/14021152/ab7177b4-f1b0-11e5-9bae-23a83a79eaf5.png">

**Comment by mafredri** [comment]
See #166.

**Comment by Plastix** [comment]
Thanks!
