### ISSUE TITLE
[Enhancement] Request to add live/current vi-mode

### ISSUE THREAD

**Issue by megalithic** [sindresorhus/pure#208]
Enhancement request for adding a live updating vi-mode indicator to the primary prompt (not the r[ight]prompt).

So, I've been tinkering with adding a vi-mode indicator, and thanks to those that have come before me, I have it working and live-updating in the rprompt, however, I don't use the rprompt for anything, and would prefer to keep  a small indicator (letter, unicode, whatever) in the primary prompt. I've been able to add this, however, am not fully grokking the zsh life cycle/events going on am just don't seem to be assigning the variable content at the right time, perhaps?

Anyway, I'd love to see this added to Pure at some point. I'll keep tinkering with it, and if I get it, I'll definitely  submit a PR.

Thanks.

**Comment by mafredri** [comment]
Have you seen the suggestion in [the wiki](https://github.com/sindresorhus/pure/wiki#a-generic-way-of-showing-current-mode-in-vi-mode)?

**Comment by megalithic** [comment]
@mafredri sheesh; how embarrassing. :( haven't ever even looked to see that pure had a wiki. thanks much. closing.

**Comment by mafredri** [comment]
Don't sweat it, glad it was what you were looking for 👍 !
