### ISSUE TITLE
pure fails in Zsh on Linux subsystem (beta), Windows 10

### ISSUE THREAD

**Issue by fredrikaverpil** [sindresorhus/pure#210]
I realize this is a corner case...

So, I have zsh installed in [bash on Windows](https://msdn.microsoft.com/commandline/wsl/about) and all is well so far. I tried to also run pure, but I'm getting errors such as this when I `cd` into a git repository:

```bash
~
❯ cd .dotfiles
async_job:zpty:4: no such pty command: prompt_pure
async_job:zpty:4: no such pty command: prompt_pure

~/.dotfiles master
❯
```
Not sure why. Could it be that I'm missing some prerequisites?

My zsh setup can be seen [here](https://github.com/fredrikaverpil/dotfiles/tree/master/zsh). The `async` and `prompt_pure_setup` are being created/symlinked by [the prompt.zsh script](https://github.com/fredrikaverpil/dotfiles/blob/master/zsh/prompt.zsh).

**Comment by mafredri** [comment]
Would you mind running the following commands and displaying the output?

```
❯ zpty -b test cat

❯ zpty -w test hi

❯ zpty -r test
hi

❯ zpty -d test

❯ zpty -L
zpty -b prompt_pure _async_worker -p 94857 -u -n
```

**Comment by fredrikaverpil** [comment]
Sure!

> zpty -b test cat

    zpty: can't open pseudo terminal: exec format error

> zpty -w test hi

    zpty: no such pty command: test

> zpty -r test

    zpty: no such pty command: test

> zpty -d test

    zpty: no such pty command: test

> zpty -L

...did not return anything at all.

**Comment by mafredri** [comment]
Ok, so the problem is that your version of zsh is not capable of opening up a zpty instance. There have always been problems on Windows, as can be seen in #141. Although the Babun shell did seem to be capable of opening zpty instances, which does not seem to be the case here.

Is this some special version of zsh? I'm afraid I'm not very familiar with the new Bash@Windows stuff.

**Comment by fredrikaverpil** [comment]
Aha. No, this is just what you get when you `apt-get install zsh`.

I'll give babun a go and report back.

**Comment by mafredri** [comment]
Alright, then it seems the Windows environment is incompatible with zsh. I would recommend opening an issue with [BashOnWindows](https://github.com/Microsoft/BashOnWindows/issues) and perhaps also reporting it on the zsh mailing list.

Sorry I can't be of more help! And also, if you find there's anything we can do to fix this, feel free to re-open.

**Comment by fredrikaverpil** [comment]
@mafredri I'll jump over to [BashOnWindows](https://github.com/Microsoft/BashOnWindows/issues). Thanks for taking the time to look into this!
