### ISSUE TITLE
Odd rendering issues in iTerm after expansion

### ISSUE THREAD

**Issue by briangonzalez** [sindresorhus/pure#212]
When I expand panes in iTerm and then I contract the pane, pure renders really oddly.

See attached screenshot.

<img width="1984" alt="screen shot 2016-05-31 at 21 53 49" src="https://cloud.githubusercontent.com/assets/659829/15698528/6ade8a34-277a-11e6-93b9-60f7785f3e55.png">

**Comment by mafredri** [comment]
I have `iTerm Build 2.9.20160531-nightly` and cannot reproduce with either the OS X zsh or Homebrew zsh version.

Could you provide the following?

* `zsh --version`
* iTerm version
* zsh config (.zshrc and whatever else is relevant)

**Comment by briangonzalez** [comment]
Here you go!

```
❯ zsh --version
zsh 5.2 (x86_64-apple-darwin15.4.0)
```

An easy test case is to 

- Run the command in one of the panes: `sleep 10`
- Hit `CMD + SHIFT + ENTER` to expand an adjacent pane
- Wait 10 seconds then exit expanded pane mode
- Notice rendering issue

**Comment by mafredri** [comment]
You missed a couple of points there ;). Still cannot reproduce.

**Comment by briangonzalez** [comment]
Oops, sorry @mafredri. Was too late.

```
iTerm Version: http://d.pr/i/14lMQ
```

My `.zshrc` is barebones.

**Comment by mafredri** [comment]
This is not reproducible for me, I didn't ask for your `.zshrc` just for lulz, I believe it's key to reproducing this. E.g. do you use iTerm shell integration? I need to know these things to debug the issue.

**Comment by mafredri** [comment]
@briangonzalez did you manage to resolve your issue? To debug this further I would still require more information, preferably the minimum configuration that reproduces the issue.

**Comment by mafredri** [comment]
Closing due to lack of response.
