### ISSUE TITLE
Pure preprompt doesn't redraw on reset-prompt

### ISSUE THREAD

**Issue by Jerry-Ma** [sindresorhus/pure#213]
Hi

Thank you for this fantastic theme. I like it so much.

Recently, I noticed that it does not play well with the `dircycle` plugin from oh-my-zsh.

Basically, when invoking the cycling of the directories, the current directory changes as expected, but the prompt text is not updating to show the new current directory. I believe this is because the `reset-prompt` command only redraw the `PROMPT`, not including the `preprompt` part. I verified this by inserting `%~` at the beginning of the `PROMPT` line and it indeed changes when cycling the directories, while the `preprompt` line remains the same.

Do you have a quick fix on this?

**Comment by Jerry-Ma** [comment]
I am able to work around it by adding this before the `reset-prompt ` call in dircycle:

    	prompt_pure_preprompt_render "precmd"

**Comment by mafredri** [comment]
The reason you have to comment that out is that the path isn't stored in the prompt, so it's never considered when updating the prompt. It looks like this `typeset prompt_pure_last_preprompt='%F{blue}%~%f%F{242} master*%f%F{cyan}%f%F{yellow}%f'`.

Also, there's no reason to call reset-prompt in `dircycle` when using the pure render function.

I'll try to think of a solution, it would be easy if I introduced a new variable to contain the expanded path or prompt, but I'd like to avoid that.

**Comment by mafredri** [comment]
Could you try me PR above?

You should get a way with this kind of function now:

```console
insert-cycledleft () {
	emulate -L zsh
	setopt nopushdminus

	builtin pushd -q +1 &>/dev/null || true
	prompt_pure_preprompt_render 
}
```

**Comment by Jerry-Ma** [comment]
@mafredri  Thank you for the PR. However I am getting the following error:

prompt_pure_preprompt_render:69: unknown file attribute: {

it is about the `typeset ...` line

**Comment by mafredri** [comment]
Does it help if you change it to

typeset -g -a variablename

?

**Comment by Jerry-Ma** [comment]
It turns out that I need to split the `typeset` assignment to two parts:

    typeset -a prompt_pure_last_preprompt
    prompt_pure_last_preprompt=("$preprompt" "${(S%%)preprompt}")

Now it works as expected, thank you for the help!

**Comment by mafredri** [comment]
Ahaa, interesting. What version of zsh do you have? Also, I'll update my PR
to reflect this.

**Comment by Jerry-Ma** [comment]
I am using the zsh in the fedora 22 repository.

```
$ zsh --version
zsh 5.0.8 (x86_64-redhat-linux-gnu)
```

**Comment by mafredri** [comment]
Interesting, I can reproduce on `zsh 5.0.8 (x86_64-apple-darwin15.0)`. I pushed a new commit to the PR that fixes this.

**Comment by mafredri** [comment]
Hey @Jerry-Ma, has #214 been working well for you? I just revisited this and found that the `dircycle` update could be improved a bit:

```zsh

prompt_pure_spontaneous_update() {
	prompt_pure_check_git_arrows
	vcs_info
	prompt_pure_async_tasks
	prompt_pure_preprompt_render
}

insert-cycledleft () {
	emulate -L zsh
	setopt nopushdminus

	builtin pushd -q +1 &>/dev/null || true
	prompt_pure_spontaneous_update 
}
zle -N insert-cycledleft

insert-cycledright () {
	emulate -L zsh
	setopt nopushdminus

	builtin pushd -q -0 &>/dev/null || true
	prompt_pure_spontaneous_update
}
zle -N insert-cycledright
```

With the above, the current git branch, arrow status, etc will also be updated when hopping between directories :).

**Comment by Jerry-Ma** [comment]
Thank you @mafredri , your previous patch worked for me. I was transiting from my old F22 to a fresh new F24 system and I haven't set up my zsh yet, but will try out your improved `dircycle` as soon as I get there.
