### ISSUE TITLE
Hyperterm space issue

### ISSUE THREAD

**Issue by mxstbr** [sindresorhus/pure#217]
When using pure in hyperterm there's three rows in between output and the next input field which seems excessive:

![screen shot 2016-07-25 at 14 19 49](https://cloud.githubusercontent.com/assets/7525670/17101115/02257b5a-5273-11e6-8dcf-da15a4beea4b.png)

(confirmed in devtools that those are three `x-rows` in between the output and the input field)

Is this planned, and if not, how can we fix this?

**Comment by mafredri** [comment]
I'm pretty sure this is a configuration issue. I don't use HyperTerm, but I've tried it and I do not have this issue. Are you using `0.6.0`?

To investigate further, I would appreciate it If you could provide a minimum zsh configuration that reproduces the issue.

I would also advice to review any HyperTerm configurations / plugins you have enabled.

**Comment by mxstbr** [comment]
I'm using the `hyperterm-spacegray` theme and have `hypercmd` installed, otherwise my `hyperterm` config is standard.

My zsh config is pretty small, so I'll just paste the full one:

```zsh
export ZSH=/Users/a2517/.oh-my-zsh
ZSH_THEME="pure"

plugins=(git)

export PATH="$PATH:/opt/local/bin:/opt/local/sbin:/Users/a2517/.rvm/gems/ruby-2.0.0-p598/bin:/Users/a2517/.rvm/gems/ruby-2.0.0-p598@global/bin:/Users/a2517/.rvm/rubies/ruby-2.0.0-p598/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/MacGPG2/bin:/Library/TeX/texbin:/Users/a2517/.rvm/bin:/usr/local/texlive/2015/bin/x86_64-darwin"

source $ZSH/oh-my-zsh.sh

source /Users/a2517/.npm-run.plugin.zsh/npm-run.plugin.zsh
source ~/.oh-my-zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

function t() {
  tree -I '.git|node_modules|bower_components|.DS_Store' --dirsfirst --filelimit 15 -L ${1:-3} -aC $2
}

function copy() {
  rsync -aPHE $1 $2
}

export NVM_DIR="/Users/a2517/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

. /Users/a2517/.z.sh

# added by travis gem
[ -f /Users/a2517/.travis/travis.sh ] && source /Users/a2517/.travis/travis.sh
```

**Comment by mafredri** [comment]
With omz in the mix, this could be pretty much anything 😭 . First things first, did you follow the installation steps for `oh-my-zsh`? It comes bundled with a `pure` theme, but that theme is very far from this one.

**Comment by mxstbr** [comment]
> With omz in the mix, this could be pretty much anything

Damn, alright. What other zsh… how'd you even call that?… distro? do you recommend?

Yes, I followed the installation instructions, see:

![screen shot 2016-07-25 at 15 00 23](https://cloud.githubusercontent.com/assets/7525670/17102149/899e4da0-5278-11e6-990d-60c781bee909.png)

> First things first, did you follow the installation steps for oh-my-zsh? It comes bundled with a pure theme, but that theme is very far from this one.

I'm about 99% sure it's this pure theme that I'm seeing.

**Comment by mafredri** [comment]
Hmm, judging from the output there, pure.zsh-theme is a folder, or a symlink to a folder? It should be a symlink to the pure.zsh file inside the pure folder.

**Comment by mxstbr** [comment]
I copy and pasted the `pure.zsh` file to the `.oh-my-zsh/custom/themes/pure.zsh-themes` folder. Should I symlink it from the original download place instead? I didn't think that would matter…

**Comment by mafredri** [comment]
What I meant is that pure.zsh-theme should not be a folder, it should be a file. E.g. mv pure.zsh pure.zsh-theme

**Comment by mxstbr** [comment]
That was it, it's now fixed! Thanks so much for the help @mafredri, seriously appreciated :pray:
