### ISSUE TITLE
Prompt char not showing and completition is borked

### ISSUE THREAD

**Issue by fedemp** [sindresorhus/pure#22]
I've just installed Arch a couple of days ago and still can't find what happened to the fat arrow of the prompt.
![2013-09-28-161606_1134x222_scrot](https://f.cloud.github.com/assets/735314/1231809/79f9315e-2872-11e3-8eb9-756e8ded2ba9.png)

On the left I'm running a tmux session and on the right it's just zsh.

Moreover, note how on pressing `tab` for completition, the characters or the word gets duplicated.

This does not happen in a ubuntu installation. Tried on urxvt (self compiled) and xterm but I always get that weird `â`

**Comment by sattes-faction** [comment]
To which value did you set the locale? I'm having the same issue - my prompt char is not correct, autocomplete works. locale gives me:

```
LANG=de_DE.UTF-8
LANGUAGE=
LC_CTYPE=de_DE.UTF-8
LC_NUMERIC="de_DE.UTF-8"
LC_TIME="de_DE.UTF-8"
LC_COLLATE="de_DE.UTF-8"
LC_MONETARY="de_DE.UTF-8"
LC_MESSAGES="de_DE.UTF-8"
LC_PAPER="de_DE.UTF-8"
LC_NAME="de_DE.UTF-8"
LC_ADDRESS="de_DE.UTF-8"
LC_TELEPHONE="de_DE.UTF-8"
LC_MEASUREMENT="de_DE.UTF-8"
LC_IDENTIFICATION="de_DE.UTF-8"
LC_ALL=
```

**Comment by fedemp** [comment]
Not sure by now. Only thing strange is that LC_ALL is not set.
