### ISSUE TITLE
Bash version?

### ISSUE THREAD

**Issue by anirudhb** [sindresorhus/pure#220]
Hi. I came across this project **today** and I really liked how it is. However, I really like Bash, but this is zsh only. Could we sometime make a bash/sh version? I will be happy to help.

**Comment by sindresorhus** [comment]
You're welcome to make a Bash [port](https://github.com/sindresorhus/pure#ports), but not something I'm interested in. This project uses a lot of powerful ZSH features, so wouldn't be easy to get everything right.

**Comment by anirudhb** [comment]
@sindresorhus Is it okay if I make a PR?

**Comment by sindresorhus** [comment]
If you mean a link to your Bash port, then yes if it's good. If you mean a Bash port itself, then no.
