### ISSUE TITLE
how add pyenv virtual environment display?

### ISSUE THREAD

**Issue by gatspy** [sindresorhus/pure#221]
now ,i use pure theme and prezto, this theme how to support the work of pyenv?

**Comment by mafredri** [comment]
Here's something I quickly hacked together which should work assuming you have initialized `pyenv` in your shell (`eval "$(pyenv init -)").

```shell
precmd() {
    if [[ -n $PYENV_SHELL ]]; then
        local version
        version=${(@)$(pyenv version)[1]}
        if [[ $version = system ]]; then
            PROMPT="%(?.%F{magenta}.%F{red})❯%f "
        else
            PROMPT="(pyenv $version) %(?.%F{magenta}.%F{red})❯%f "
        fi
    fi
}
```

1. We check if `pyenv` has been initialized (the `$PYENV_SHELL` parameter has been set)
2. We get active the pyenv version by running `pyenv version`. With `(@)` we are turning the output into an array and with `[1]` we fetch the first element.
3. If the active python is the `system` version, we just use the default prompt. If it's not system, we prefix the prompt with it.

---

I think this is perhaps something we even could support in `pure`, what are your thoughts on the matter @sindresorhus? I'm not entirely sure on how to present the information, this is what it looks like now, but I think we can do better if we decide to support it:

![](https://www.dropbox.com/s/qi23omy94nmp9u9/Screenshot%202016-07-30%2018.42.23.png?dl=1)

**Comment by gatspy** [comment]
This is indeed a good idea, thanks @mafredri

**Comment by sindresorhus** [comment]
Sure, looks simple enough.

**Comment by z0rc** [comment]
The proposed approach is way too heavy (two forks). You can just check for presence of `PYENV_VERSION` shell var and output it if it's set.

But given that there are multiple tools to manage virtualenvs, I'd propose to check for `VIRTUAL_ENV` and output it as `${VIRTUAL_ENV##*/}` to show only last folder from pull path stored in that variable.

**Comment by mafredri** [comment]
Sorry for taking so long to get back to you on this @z0rc, I'm aware the reference implementation here is not very efficient, and would be implemented differently in pure.

I'm not entirely confident what you're suggesting would work, though. As far as I can tell, the `PYENV_VERSION` env var does not get set by itself, example:

```
~
❯ eval "$(pyenv init -)"

~
❯ python --version
Python 2.7.12

~
❯ typeset -p PYENV_VERSION
typeset: no such variable: PYENV_VERSION

~
❯ cd derp

~/derp
❯ python --version
Python 2.7

~/derp
❯ typeset -p PYENV_VERSION
typeset: no such variable: PYENV_VERSION

~/derp
❯ cat .python-version
2.7
```

Also, what is this `VIRTUAL_ENV` var you're talking about? I have no such thing 😄. Maybe you're referring to a different virtualenv implementation (not `pyenv`)?

**Comment by z0rc** [comment]
Well, things got mixed up right from the topic. Yeah, there are two features the pyenv mostly used for. 

First is shell wrapper for python interpreter. Here I still suggest stick to `PYENV_VERSION`. If it isn't set, than we're using the `system` version whatever it is, no need to indicate this. Otherwise we can just output what is in `PYENV_VERSION`, as it's always set when user actually changed python version via pyenv.

Second feature is `pyenv-virtualenv`, it's a pyenv plugin to create virtualenvs. And I assumed this is what @gatspy asked for. Virtualenvs created by pyenv don't differ from other virtualevs created by `virtualenv`, `virtualenvwarapper` or something else. When virtualenv is active it's worth checking the `VIRTUAL_ENV` var.

**Comment by mafredri** [comment]
> Well, things got mixed up right from the topic. Yeah, there are two features the pyenv mostly used for.

No worries, and thanks for clarifying.

> as it's always set when user actually changed python version via pyenv.

I beg to differ, did you see my example? I had activated pyenv, and had a local version (for folder `derp`) set to `2.7`. It used the pyenv `2.7` python, but no env var was set.

>  When virtualenv is active it's worth checking the `VIRTUAL_ENV` var.

Alright, great.

**Comment by z0rc** [comment]
> I beg to differ, did you see my example? I had activated pyenv, and had a local version (for folder derp) set to 2.7. It used the pyenv 2.7 python, but no env var was set.

Oh, right, I haven't tested exactly this case. `PYENV_VERSION` is set only with `pyenv shell`, but remains unset when activated via `.python-version` file.

**Comment by mafredri** [comment]
This is exactly why my first approach used `$(pyenv version)` to avoid including pyenv logic in pure (PS. it only uses one fork on our side, but `pyenv` isn't exactly cautious with forking, so it's actually more than two). It's much more robust and compatible with past and future versions of `pyenv`.

This is one reason I'd prefer to perform these checks in an async worker, but that comes with it's own set of problems. On the other hand, the fork penalty is something only `pyenv` users would have to pay and might be acceptable (as it's minuscule).

**Comment by mafredri** [comment]
Since `pyenv` supports setting `VIRTUAL_ENV` (at least in some cases) I don't think we should add explicit support for `pyenv` in Pure. There are so many flavors, like `pipenv` and what-not.

And since we support `VIRTUAL_ENV` creating a wrapper is trivial, my example in https://github.com/sindresorhus/pure/issues/221#issuecomment-236372279 could be adapted to just set `VIRTUAL_ENV=$version` instead of messing with `PROMPT`.

With that, I'm closing this issue.

**Comment by notsaman** [comment]
@SiddharthPant @mafredri 
Could I get some assistance on that? My issue is that Pure only shows `.venv`. While that is technically the name of the environment, Bash (or other themes) show the directory like `[work-dir]` instead, which is much more useful for my use cases.

**Comment by mafredri** [comment]
@notsaman since you're using `pyenv` that shouldn't be an issue, in `pyenv` you can have actual names for the environments, no? As for Pure, custom virtualenv names may be solvable by extending `zstyle` configuration but nobody is working on that at the moment.

**Comment by notsaman** [comment]
@mafredri  Thanks for the quick response! :)
Yup, custom names are possible, but not supported by our setup (our makefile just names them `venv` for every separate project, i.e. I'd have to manually change it for every project I'm on). 
I was looking to just apply the standard zsh/bash behaviour to Pure where it just shows the working directory of the virualenv. Is there anything I can change in `pure.zsh` for that? To be completely honest I'm a bit lost when it comes to shell scripts.

**Comment by mafredri** [comment]
I thought `pyenv` environments were kept outside of the parent/workdir, e.g. in `$HOME/.pyenv`? It's easy to change it to the parent directory but we can't make that assumption for all users.

https://github.com/sindresorhus/pure/blob/ff356fa2c7ea745bc4bc56a98632bac55c6c74a1/pure.zsh#L221

```diff
diff --git pure.zsh pure.zsh
index 271c1cc..f523c49 100644
--- pure.zsh
+++ pure.zsh
@@ -218,7 +218,7 @@ prompt_pure_precmd() {
 	# When VIRTUAL_ENV_DISABLE_PROMPT is empty, it was unset by the user and
 	# Pure should take back control.
 	if [[ -n $VIRTUAL_ENV ]] && [[ -z $VIRTUAL_ENV_DISABLE_PROMPT || $VIRTUAL_ENV_DISABLE_PROMPT = 12 ]]; then
-		psvar[12]="${VIRTUAL_ENV:t}"
+		psvar[12]="${VIRTUAL_ENV:h:t}"
 		export VIRTUAL_ENV_DISABLE_PROMPT=12
 	fi
 
```

**Comment by notsaman** [comment]
Might be something to try out on my personal machine...but you should be right.
For now this is exactly what I was looking for though, thank you so much! You guys got a tip jar or anything?
