### ISSUE TITLE
only autoload async if the function does not already exists

### ISSUE THREAD

**Issue by CircleCode** [sindresorhus/pure#223]
in some cases, async is already loaded when pure.zsh is sourced.
More, async could have been loaded by another way than autoload (for example, I would load it through [zplug](https://github.com/zplug/zplug).
In such a case, the autoload of async would fail and the prompt would not init correctly.

**Comment by mafredri** [comment]
Sorry, but could you clarify what the problem is? I'm not familiar whit zplug, how does it load it's modules?

I can't imagine the problem is in loading modules before pure tries to use autoload, you could even just `source` the async file before pure and it would work just fine.

**Comment by CircleCode** [comment]
I am checking with @b4b4r07 (zplug author) to give you an accurate answer
BTW, b4b4r07, do not hesitate to comment here ;-)
