### ISSUE TITLE
Escape shell variables in git branch prompt?

### ISSUE THREAD

**Issue by leoj3n** [sindresorhus/pure#224]
This is kind of a funny problem to have.

```sh
~/.zprezto/modules /var/folders/kb/ydt74z19765cv9vb86rwvcrr0000gn/T/zsh
❯ echo $TMPPREFIX
/var/folders/kb/ydt74z19765cv9vb86rwvcrr0000gn/T/zsh
```

Was curious to see what would happen if I made a git branch name that was a variable:

```sh
~/.zprezto/modules /var/folders/kb/ydt74z19765cv9vb86rwvcrr0000gn/T/zsh
❯ gbl
* $TMPPREFIX                03c5a6a Export $TMPPREFIX in non-login interactive shells
```

Is this the expected behavior or something that can/should be escaped?

**Comment by mafredri** [comment]
Heh, nice find, and thanks for reporting :)!

Honestly, this shouldn't be a problem since I don't know why on earth you would name a branch that, but there might be other edge cases as well, especially involving the `%`-sign.

Anyway, this shouldn't be a problem anymore with the fix I just pushed.

**Comment by davidmerrique** [comment]
@mafredri After 6cbd49a it's just printing `$vcs_info_msg_0_`

![screen shot 2016-08-25 at 10 04 52 am](https://cloud.githubusercontent.com/assets/867522/17972202/fad0eee2-6aab-11e6-8305-114553d3c964.png)

**Comment by mafredri** [comment]
@davidmerrique this should be fixed now, I was just testing to see whether or not anyone was using `master` 😜 😇.
