### ISSUE TITLE
Single line prompt? 

### ISSUE THREAD

**Issue by tyrollins** [sindresorhus/pure#228]
Thanks for pure prompt, I'm loving it! I am curious however, if there is a way to have the prompt be a single line prompt. 

Basically, instead of current directory etc... being above if it could be on the same line as the arrow? Wouldn't even know where to start with customizing... 

Cheers.

**Comment by mafredri** [comment]
We do not support single-line prompts in pure (and we probably never will), but if you're still interested, you should check out https://github.com/sindresorhus/pure/issues/109#issuecomment-148991334.

**Comment by To1ne** [comment]
@tyrollins @CrazyPython I've found a quick workaround to make Pure give a single line prompt.

Just add this to your `~/.zshrc`

```sh
prompt_newline=`echo "\u200B"`
```

The unicode character `\u200B` is a [zero-width space](https://en.wikipedia.org/wiki/Zero-width_space).

I haven't tested it thoroughly yet, but it seems to work.

@mafredri Do you consider adding this to the README?

**Comment by mafredri** [comment]
@To1ne indeed, single-line pure became much simpler with 4cdd0cf4f48d0c2064700c4fc60083bc0b3f6693. I don't think that your suggestion works quite as intended, though, at least in my terminal it's not represented as zero-width (shows space before path), furthermore, you could tell the terminal that it takes no space with `prompt_newline=$'%{\u200B%}'` but also this is insufficient.

One example of how to make it work properly would be:

```
prompt pure
prompt_newline='%666v'
PROMPT=" $PROMPT"
```

Why does this work? `%666v` expands to the contents of `$psvar[666]` (not like you will have it defined, right 😅?) thus creating a unique identifier (for removing preprompt during update).

Then we're adding an extra space to the `$PROMPT` initialised by pure, to make it more spacious.

<img width="272" alt="screenshot 2017-05-05 12 48 27" src="https://cloud.githubusercontent.com/assets/147409/25740894/294b9c20-3191-11e7-947f-b3ac1597f69f.png">

> Do you consider adding this to the README?

Not to the README, since this is not supported or as-intended, but maybe to the Wiki? There are a few hacks / tweaks there already.

**Comment by To1ne** [comment]
Added it to the wiki: https://github.com/sindresorhus/pure/wiki#single-line-prompt

**Comment by Skyearn** [comment]
> @To1ne indeed, single-line pure became much simpler with [4cdd0cf](https://github.com/sindresorhus/pure/commit/4cdd0cf4f48d0c2064700c4fc60083bc0b3f6693). I don't think that your suggestion works quite as intended, though, at least in my terminal it's not represented as zero-width (shows space before path), furthermore, you could tell the terminal that it takes no space with `prompt_newline=$'%{\u200B%}'` but also this is insufficient.
> 
> 如何使其正常工作的一个例子是：
> 
> ```
> prompt pure
> prompt_newline='%666v'
> PROMPT=" $PROMPT"
> ```
> 
> 为什么这有效？`%666v`扩展为`$psvar[666]`的内容（不像您那样定义它，对吗，😅？）因此创建一个唯一的标识符（用于在更新期间删除预提示符）
> 
> 然后，我们将在纯初始化的`$PROMPT`中添加额外的空间，使其更宽敞。
> 
> <img alt="截图 2017-05-05 12 48 27" width="272" src="https://cloud.githubusercontent.com/assets/147409/25740894/294b9c20-3191-11e7-947f-b3ac1597f69f.png">
> 
> > 你考虑将此添加到README中吗？
> 
> 不是对 README，因为这不支持或按预期，但可能对维基？那里已经有一些黑客/调整。

When I add this to my ~/.zshrc, it's work but something went wrong.
There is extra white line between two command lines. like this: 
<img width="606" alt="image" src="https://user-images.githubusercontent.com/29571915/113833866-bae2be80-97bc-11eb-8964-cbd96901617f.png">
I want to make it like your example, what should I do.
Thank you.

**Comment by Skyearn** [comment]
> @To1ne indeed, single-line pure became much simpler with [4cdd0cf](https://github.com/sindresorhus/pure/commit/4cdd0cf4f48d0c2064700c4fc60083bc0b3f6693). I don't think that your suggestion works quite as intended, though, at least in my terminal it's not represented as zero-width (shows space before path), furthermore, you could tell the terminal that it takes no space with `prompt_newline=$'%{\u200B%}'` but also this is insufficient.
> 
> One example of how to make it work properly would be:
> 
> ```
> prompt pure
> prompt_newline='%666v'
> PROMPT=" $PROMPT"
> ```
> 
> Why does this work? `%666v` expands to the contents of `$psvar[666]` (not like you will have it defined, right 😅?) thus creating a unique identifier (for removing preprompt during update).
> 
> Then we're adding an extra space to the `$PROMPT` initialised by pure, to make it more spacious.
> 
> <img alt="screenshot 2017-05-05 12 48 27" width="272" src="https://cloud.githubusercontent.com/assets/147409/25740894/294b9c20-3191-11e7-947f-b3ac1597f69f.png">
> 
> > Do you consider adding this to the README?
> 
> Not to the README, since this is not supported or as-intended, but maybe to the Wiki? There are a few hacks / tweaks there already.

When I add this to my ~/.zshrc, it's work but something went wrong.
There is extra white line between two command lines. like this:
<img width="606" alt="image" src="https://user-images.githubusercontent.com/29571915/114839263-26094200-9e08-11eb-9806-0ef701b596d4.png">

I want to make it like your example, what should I do.
Thank you.

**Comment by swaathi** [comment]
> Added it to the wiki: https://github.com/sindresorhus/pure/wiki#single-line-prompt

This is the updated link: https://github.com/sindresorhus/pure/wiki/Customizations,-hacks-and-tweaks#single-line-prompt
