### ISSUE TITLE
 What's your terminal?

### ISSUE THREAD

**Issue by Yetocome** [sindresorhus/pure#232]
How can this beautiful appearance be achieved? I mean how to hide the title bar. I cannot find any configuration to handle it in my terminals of OS X.
![screenshot](https://cloud.githubusercontent.com/assets/9162430/18617794/20bb0b70-7e0b-11e6-8f25-a3ae2b816080.png)

**Comment by kevva** [comment]
> In the screenshot you see Pure running in HyperTerm with the hyperterm-snazzy theme and Menlo font.
