### ISSUE TITLE
Preprompt not displayed!

### ISSUE THREAD

**Issue by Rawnly** [sindresorhus/pure#234]
Hello, i used this prompt for a long time, usually i never completly shut down my iMac, today i've installed an update and now my preprompt is not displayed! what this can be?

**Comment by unluisco** [comment]
I was about to post the same

a image:
![pure](https://cloud.githubusercontent.com/assets/6332263/18804526/cefcf7c0-81c1-11e6-8aba-53699595bba9.png)

**Comment by Rawnly** [comment]
I've 'fixed' it but not resolved, i've copied preprompt in the .zsh-theme file and called it in the prompt but is all in line... I have another file who is bigger but if i use it like a theme, it gives me that 

`prompt_pure_setup:11: async: function definition file not found
prompt_pure_async_tasks:3: command not found: async_start_worker
prompt_pure_async_tasks:4: command not found: async_register_callback` 

Here an image of my provisional fix: 


![schermata 2016-09-24 alle 02 18 34](https://cloud.githubusercontent.com/assets/16429579/18804589/35fac034-81fd-11e6-9e94-88fdce6187aa.png)

**Comment by mafredri** [comment]
That sounds very weird.

What did you update, macOS?

Could you both answer the following questions:

1. Are you using the latest version of pure?
2. Have you made any modifications to pure?
3. Have you tried following the instructions in the readme to reinstall
pure?
4. Are you using a zsh library, e.g. Oh-my-zsh or prezto?
5. Can you provide a minimum reproduction case? E.g. the shortest .zshrc
possible (nothing extra) that reproduces the issue?

**Comment by Rawnly** [comment]
I've update to Sierra, yes i have the latest, none modification except the "fix", now i'll try to reinstall, i use `zsh` `oh-my-zsh`,
my zshrc from line 1 to 14
`
fpath=( "$HOME/.zsh/functions" ${fpath[@]} )
# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=/Users/Rawnly/.oh-my-zsh

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes

autoload -U promptinit && promptinit

ZSH_THEME="pure"
`

**Comment by tjoskar** [comment]
@Rawnly, I had the same issue until I removed the `ZSH_THEME="pure"`-line and added:
```
autoload -U promptinit; promptinit
prompt pure
```

And suddenly everything was back to normal :)

**Comment by mafredri** [comment]
@Rawnly 

> I have another file who is bigger but if i use it like a theme, it gives me that
> ...

You need this bigger file, I'm quite sure, since it *is* pure. The fact that you get async errors when you try to use it tells me that the only thing missing is async from your `$fpath`.

Make sure you either `npm install --global pure-prompt` or follow the manual instructions in the readme to make sure async is in you `$fpath`.

I think we need to update the oh-my-zsh instructions, the [previous instructions](https://github.com/sindresorhus/pure/commit/67f4c213d295ee50b61b68cbd584dd19efcee273) were clearer.

**Comment by unluisco** [comment]
@mafredri solved with previous instructions 👍

**Comment by Rawnly** [comment]
@mafredri Thanks! Solved!

**Comment by mafredri** [comment]
Great, glad to hear it @Rawnly and @unluisco!
