### ISSUE TITLE
Different prompt character when exit is non-zero

### ISSUE THREAD

**Issue by wayneashleyberry** [sindresorhus/pure#237]
I'd love an option to use a different prompt character when the previous command exited with a non-zero code. Changing the color is great but it's too subtle with my current theme, almost indistinguishable. Instead I'd like to use `△` as a normal prompt character and `▲` for errors.

**Comment by sindresorhus** [comment]
> Changing the color is great but it's too subtle with my current theme, almost indistinguishable.

Sounds like you should rather fix your broken theme.

-

Everyone wants options for everything. If we had said yes to all requests, we would have dusins of options by now and a super complex code base.

**Comment by wayneashleyberry** [comment]
Fair enough :)

**Comment by sindresorhus** [comment]
@wayneashleyberry You could always fork this theme. The simple setup is just to cater for beginners. Most advanced users will want to customize it more heavily ;) There's also room for a fork that implements a lot more customizability. It's just not something I want to maintain.

**Comment by wayneashleyberry** [comment]
Yeah, I fully understand @sindresorhus. I guess the whole ethos behind Pure is that it's simple and well... pure :)

**Comment by mafredri** [comment]
@wayneashleyberry I'm with @sindresorhus on this, we don't really want yet another option. However, this is very easy for you do modify.

```
prompt pure
PROMPT='%(?.%F{magenta}T.%F{red}F)%f '
```

This would show `T` as a prompt and `F` on a non-zero exit. The reason it works is that pure only defines the `PROMPT` when it's initialised. As long as this doesn't change in the future, you won't need to fork :).

**Comment by sindresorhus** [comment]
@mafredri Can you add this tip to the wiki?

**Comment by mafredri** [comment]
@sindresorhus sure thing 👍 !

**Comment by mafredri** [comment]
Heh, it's essentially the first thing in the wiki already: [Show exit code of last command as a separate prompt character](https://github.com/sindresorhus/pure/wiki#show-exit-code-of-last-command-as-a-separate-prompt-character).

**Comment by wayneashleyberry** [comment]
haha, wow... my bad, I should've checked that out first!

**Comment by mafredri** [comment]
It's cool, I added an example above because I felt the one below was not clear enough (i.e. you don't have to modify `pure`).
