### ISSUE TITLE
precmd disappears on buffer clear

### ISSUE THREAD

**Issue by caarlos0** [sindresorhus/pure#239]
Screen clear (`clear` or `CTRL`+`L` on iTerm) works as expected:

![image](https://cloud.githubusercontent.com/assets/245435/19171942/c998d036-8bf5-11e6-8f98-8ebae3d77aa0.png)

But buffer clear (`CMD`+`K` on iTerm) doesn't:

![image](https://cloud.githubusercontent.com/assets/245435/19171958/daa819ae-8bf5-11e6-8046-8abf71d58705.png)

Is there a way we could fix this?

**Comment by mafredri** [comment]
Easily? Unfortunately no :(.

What you're looking for is the behaviour that could be achieved with `Ctrl + L` followed by `Cmd + Shift + K`. That's not a very pleasant key combination to type, however.

Problem: iTerm does not inform us that `Cmd + K` has been pressed.

Solution: We can hack around it

**Solution 1**: Would be optimal, but does not work properly for some reason unbeknownst to me

1. Go to iTerm Preferences > Keys > Add a new key mapping
2. Set Shortcut to: `Cmd+k`
3. Action: Send Hex Code
4. `0x1B 0x63 0x1B 0x5B 0x33 0x4A 0x0C` which translates to `^[c^[[3J<FORM FEED>`

This only seems to clear the screen (`^[c`), but not perform the clearing of the buffer (`^[[3J`). Also, form feed seems to be required for anything to happen (`0x0C`), no idea why or how to get this to work properly.

**Solution 2**: This works, but only when the prompt is visible (e.g. a command cannot be running)

Modify iTerm key mappings:

1. Go to iTerm Preferences > Keys > Add a new key mapping
2. Set Shortcut to: `Cmd+k`
3. Action: Send Hex Code
4. `0x1B 0x4B` which translates to `^[K`

And add this to your `.zshrc`:

```shell
clear_cmd_k() {
	print -n '\ec\e[3J'
	prompt_pure_preprompt_render precmd
	zle .reset-prompt
}
zle -N clear_cmd_k
bindkey "\eK" clear_cmd_k
```

**Comment by caarlos0** [comment]
@mafredri well, seem like too much of a hack to bother..  

Thanks anyways 👍

**Comment by forivall** [comment]
This is why I use [a command for this](https://github.com/forivall/dotfiles/blob/bc9061f/plugins/unsorted/unsorted.plugin.zsh#L12-L20) that does the right thing:tm:.

**Comment by mafredri** [comment]
@forivall unless I'm mistaken, your example doesn't solve the issue of `Cmd+K` not re-rendering the prompt. The example you provided uses a shell command, which in turn redraws the prompt after it has executed.

**Comment by forivall** [comment]
> The example you provided uses a shell command, which in turn redraws the prompt after it has executed.
Exactly. I'm not saying that this is the solution, but that this what I do, which works around the issue.
