### ISSUE TITLE
Async worker failing or locking up?

### ISSUE THREAD

**Issue by Gizmotoy** [sindresorhus/pure#240]
I recently switched to pure and love it so far, but I've noticed that the asynchronous worker for git repos seems to be failing at some point.  It doesn't appear consistent, but after 3-4 hours with a particular terminal open the worker is always broken, at least on my system.

To go into more detail:  the worker updates the git status on the prompt.  Over time, the prompt "locks up" and will, for example, continuously display dirty even though the repo is clean.  If I open a new terminal, that new terminal's prompt reports clean, while the long-running prompt still shows dirty.

Perhaps some kind of watchdog to restart the worker is in order?

The worker doesn't seem to be a separate process I can find in 'ps', but if there's something I can do to help track this down please let me know.  Observed on Centos 7.1.

**Comment by Gizmotoy** [comment]
Thanks for the really fast response!

Maybe there's something subtle I haven't noticed, but my git branch is always grey.  I haven't seen a color.  It gets an asterisk when dirty, and the push/pull arrows are in color, but I haven't observed color branch names.  It is entirely possible "git status" could occasionally take over 2 seconds, it's a remote server.

Simply setting PURE_GIT_DELAY_DIRTY_CHECK=0 for a terminal that was already misbehaving didn't immediately resolve the issue.  I've started a couple new terminals with that parameter set and will monitor them today.

zsh --version
zsh 5.0.2 (x86_64-redhat-linux-gnu)

**Comment by mafredri** [comment]
> Thanks for the really fast response!

You're welcome ^_^.

> Maybe there's something subtle I haven't noticed, but my git branch is always grey. I haven't seen a color.

Pure has a feature where the dirty result is cached (for delay time) when git status is taking a long time (over 2s), the git color turns red instead of gray in this instance. Doesn't sound like this is your problem since the prompt remains gray.

> Simply setting PURE_GIT_DELAY_DIRTY_CHECK=0 for a terminal that was already misbehaving didn't immediately resolve the issue.

It should work immediately (if it's the problem), but just in case you can also try: `unset prompt_pure_git_last_dirty_check_timestamp`.

---

I suppose you're not able to update to a newer version of zsh? With zsh 5.2 zsh-async can use a much more robust way to communicate with the prompt.

**Comment by sindresorhus** [comment]
@mafredri Maybe we should just require ZSH 5.2?

**Comment by Gizmotoy** [comment]
Honestly, I hadn't looked into zsh versions until you asked for it in your comment.  Centos bundles 5.0.2, which looks to be four years old.  Ouch.

There's been a lot of development since 5.2 in December.  Not sure if I should use tagged 5.2, or if I should just use latest from git.  What do you guys generally use?

**Comment by sindresorhus** [comment]
I would recommend the latest stable version, 5.2.

**Comment by mafredri** [comment]
@sindresorhus the oldest version of zsh I use pure on is zsh `4.3.17 (x86_64-unknown-linux-gnu)` (an old server), I think it would be a shame to state that the latest version is a hard requirement in this regard (it works even on older versions). I wouldn't mind recommending `5.2` *for the best experience* though.

@Gizmotoy let us know whether or not you still experience the issue on `5.2`, if it's still a problem we should probably migrate this issue over to the `zsh-async` issue tracker for further discussion.

**Comment by sindresorhus** [comment]
@mafredri Why not just upgrade ZSH?

**Comment by mafredri** [comment]
@sindresorhus, don't get me wrong, I mostly use zsh 5.2. If I use an older version it's because a server is either too old (doesn't have up-to-date packages) or not under my control. In these cases it would be tedious (and not much benefit) to compile it manually (assuming a toolchain is present).

**Comment by mafredri** [comment]
@sindresorhus and I'm not really thinking about myself here, I meant it would be a shame towards those who are stuck (for whatever reason) on an older version.

**Comment by sindresorhus** [comment]
Ok. Let's at least add a strong recommendation in the readme.

**Comment by Gizmotoy** [comment]
I didn't want to report in too soon on this, but I'm on my second full day of running under zsh 5.2 and have yet to encounter the issue.  I'm cautiously optimistic that the upgrade fixed the issue I was encountering.

**Comment by Gizmotoy** [comment]
To follow up:  I've been using this for several days now on 5.2 and it's been rock solid.  By contrast, I fired up another host with 5.0.2 and was able to replicate the issue on a different machine.

So it does seem to be related to the zsh version.  Thanks for the suggestions.

**Comment by mafredri** [comment]
Glad to hear @Gizmotoy! It's unfortunate that we don't know exactly what the reason was that made you experience the issue, but there's a fair chance it was due to kill-signals / traps being used. Those issues were fixed in versions `5.1` and `5.1.1` of zsh.

I'll close this now and make a note for myself to update the readme with a recommendation for zsh 5.2.
