### ISSUE TITLE
Async: Function Definition File Not Found

### ISSUE THREAD

**Issue by nickcorona** [sindresorhus/pure#242]
Hi, I get the following error message when I try to load Pure via zplug in my Zsh shell:
`prompt_pure_setup:13: async: function definition file not found`

**Comment by tjfwalker** [comment]
What was the solution to this issue?

**Comment by mafredri** [comment]
@tjfwalker I'm just going to be blunt and say RTFM. This error appears when you don't have async in your `$fpath`.
