### ISSUE TITLE
Is it support private repo?

### ISSUE THREAD

**Issue by kepbod** [sindresorhus/pure#243]
Does it support private repo? If so, how do I need to set the password. BTW, I use the two-step validation in github.

**Comment by mafredri** [comment]
I use pure with private repos all the time, but, pure only runs `git` and expects your system to handle the rest.

You should check out the GitHub documentation: [Adding a new SSH key to your GitHub account](https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account/).
