### ISSUE TITLE
Unicode character looks jagged

### ISSUE THREAD

**Issue by nickcorona** [sindresorhus/pure#246]
I'm using urxvt as my terminal on arch linux with font, Droid Sans Mono. I have anti-aliasing enabled, but the Unicode character is appearing jagged, and I can't figure out why.

Any ideas?
![2016-11-05-164916_132x181_scrot](https://cloud.githubusercontent.com/assets/7490453/20033494/ca964aba-a377-11e6-8bf1-f5a753e3147d.png)

**Comment by sindresorhus** [comment]
That has nothing to do with this theme, though. It's your terminal or OS. Maybe try another font to eliminate that as a cause.
