### ISSUE TITLE
White background-color over white text

### ISSUE THREAD

**Issue by alberto2000** [sindresorhus/pure#249]
I don't know if this is an issue with Pure or with the Snazzy theme:

![Screenshot](https://i.imgsafe.org/b7859cf4e2.png)

There are situations where white text is put on white background. I'm using Hyperterm, Zsh shell, Oh My Zsh, Pure and Snazzy. Any idea on this?

**Comment by mafredri** [comment]
I see you also opened up an issue on the `hyper-snazzy` issue tracker (https://github.com/sindresorhus/hyper-snazzy/issues/12). I'm 100% confident this is not a `pure` issue so closing this here.
