### ISSUE TITLE
Lots of extra space between lines?

### ISSUE THREAD

**Issue by nloding** [sindresorhus/pure#250]
I'm sure I screwed something up. How do I fix the amount of blank space seen in this screenshot? I'm using iTerm2 on macOS. I had oh-my-zsh installed with the pygmalion theme prior to finding this, and, as far as I remember, didn't change anything other than the theme. The only changes to my .zshrc file were the `prompt` command from the instructions and setting the theme to "pure."

**Update** this is only for oh-my-zsh. I switched to Prezto and it works like magic. I'll just stick with Prezto for now, but looks like something is goofed with the oh-my-zsh implementation?

<img width="822" alt="screen shot 2016-11-21 at 4 03 08 pm" src="https://cloud.githubusercontent.com/assets/328425/20500608/2bff1d16-b004-11e6-9995-62a900b70fbb.png">

**Comment by sindresorhus** [comment]
Did you use the oh-my-zsh bundled Pure theme or did you follow the [oh-my-zsh instructions](https://github.com/sindresorhus/pure#oh-my-zsh) in the readme?

**Comment by nloding** [comment]
Per the instructions in the readme, I symlink'd the file in this repo to `custom/themes` and used that.

**Comment by mafredri** [comment]
How about if you follow the old instructions for oh-my-zsh from https://github.com/sindresorhus/pure/commit/67f4c213d295ee50b61b68cbd584dd19efcee273 ?

**Comment by nloding** [comment]
That looks the same, just leaving out the `asynch.zsh` file. Am I missing something? Happy to uninstall Prezto and go back to oh my zsh to test if it makes sense.

**Comment by mafredri** [comment]
They're not the same, the old instructions remove the "pure" theme that ships with oh my zsh, it's not the same one as this one.

**Comment by nloding** [comment]
Oh, duh, I was reading the green lines, not what was removed. I blame the holiday. I can attempt that and report back later.

**Comment by mkykode** [comment]
@nloding where you able to remove the spaces? @sindresorhus @mafredri I followed all the correct instructions but I get these huge spaces in between prompts. I'm using hyper terminal with hyper-snazzy theme. On the inspector for hyper, there are extra x-rows created. There are extra lines between the git paths and the prompt as well.

![i](https://cloud.githubusercontent.com/assets/670135/21250552/00f99fba-c2fb-11e6-91af-845702d6b549.png)

**Comment by nloding** [comment]
@mkykode honestly I haven't gone back to oh-my-zsh and tested. It works fine on macOS Sierra with iTerm 2 and Prezto, FWIW.

**Comment by mkykode** [comment]
@nloding thank, I'm using hyper terminal. I re-installed and I'm only getting 1 extra space now. That's how it's supposed to be?
![space](https://cloud.githubusercontent.com/assets/670135/21254432/3f634142-c31a-11e6-9da7-dc2f2fa86a4a.png)

**Comment by nloding** [comment]
@mkykode magic! I tried using Hyper but couldn't get all the features I wanted working. G'luck to you!

**Comment by mafredri** [comment]
Looks to me like everyone's problem's are solved here 😄. Closing this now, feel free to open a new issue if you're still having problems with Pure.
