### ISSUE TITLE
Spaces between prompts

### ISSUE THREAD

**Issue by thewinger** [sindresorhus/pure#257]
Hi, I'm not sure if pure prompt in iTerm2 with zsh is showing as expected

![screen shot 2016-12-07 at 18 46 11](https://cloud.githubusercontent.com/assets/121455/20979512/8fd2ac4e-bcad-11e6-9409-a1ef6adc7f9a.png)

I think the bottom blue download is the ¿result? of the command just before
![image](https://cloud.githubusercontent.com/assets/121455/20979527/a34efe30-bcad-11e6-8af0-10674fbeed80.png)

But I don't know why here is showing 2 downloads, blue and gray

![image](https://cloud.githubusercontent.com/assets/121455/20979563/bf40445a-bcad-11e6-98a6-a80d98e640b7.png)

**Comment by thewinger** [comment]
- zsh version: zsh 5.0.8 (x86_64-apple-darwin15.0)
- iTerm2 version: Build 3.0.20161205-nightly
- Hyper version none
- Pure version: last. Installed yesterday with `$ npm install --global pure-prompt` and adding to .zshrc
```
autoload -U promptinit; promptinit
prompt pure
ZSH_THEME = "pure"
````

- No zsh framework
- Minimum zshrc that reproduces the issue
```
# Path to your oh-my-zsh installation.
export ZSH=/Users/win/.oh-my-zsh
autoload -U promptinit; promptinit
prompt pure
ZSH_THEME="pure"
export PATH=$HOME/bin:/usr/local/bin:$PATH
source $ZSH/oh-my-zsh.sh
```

**Comment by mafredri** [comment]
> No zsh framework

Ah but you are using oh-my-zsh (it's a framework). Due to oh-my-zsh bundling a pure theme that is not pure, you're not really using pure right now. Could you try following the instructions from [here](https://github.com/sindresorhus/pure/tree/74dbfba33ec31c50b3b41071d13a01e7c0de6517#oh-my-zsh)? The link is to an older version of the readme with a more complete set of oh-my-zsh instructions.

**Comment by mafredri** [comment]
You could also change your `zshrc` to this:

```shell
export ZSH=/Users/win/.oh-my-zsh
ZSH_THEME=""  # do not use a oh-my-zsh theme
export PATH=$HOME/bin:/usr/local/bin:$PATH
source $ZSH/oh-my-zsh.sh

autoload -U promptinit; promptinit
prompt pure
```

I haven't tested this, but I think it should work.

**Comment by thewinger** [comment]
Changed zshrc to that and now it looks as it should

![screen shot 2016-12-07 at 20 43 35](https://cloud.githubusercontent.com/assets/121455/20983726/d9487a24-bcbd-11e6-9846-4d7c6feb8146.png)


Thank you very much and sorry for wasting your time

**Comment by mafredri** [comment]
No worries, glad it's working now =)!
