### ISSUE TITLE
Current Directory text duplicated!

### ISSUE THREAD

**Issue by veggiedefender** [sindresorhus/pure#264]
### General information

- Pure version: 1.4.1
- ZSH version: 5.3 (x86_64-unknown-linux-gnu)
- Terminal program & version: Gnome Terminal 3.22.1 and XTerm 327
- Operating system: Arch
- ZSH framework: oh my zsh

I have:
- [ x ] Tested with another terminal program and can reproduce the issue: 
- [ x ] Followed the [Integration](https://github.com/sindresorhus/pure#integration) instructions for my framework

### Problem description

I'm not sure if this is an issue with zsh or pure, but at the top where it shows the current directory, it's duplicated, with the second one in light gray.
![Screenshot](http://i.imgur.com/Jc1lmU2.png?1)

### Reproduction steps

Not sure how to reproduce, maybe just update everything?

### My `.zshrc`:

```
ZSH=/usr/share/oh-my-zsh/

ZSH_THEME="pure"

DISABLE_AUTO_UPDATE="true"

plugins=(git colored-man-pages)

ZSH_CACHE_DIR=$HOME/.oh-my-zsh-cache
if [[ ! -d $ZSH_CACHE_DIR ]]; then
  mkdir $ZSH_CACHE_DIR
fi

setopt correct

autoload -U promptinit; promptinit
prompt pure

export EDITOR=nvim

source $ZSH/oh-my-zsh.sh
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
```

**Comment by mafredri** [comment]
Looks a lot like #257. Which would indicate that the oh-my-zsh theme "pure" is conflicting with our pure (they're not the same) theme. You could try the suggestion in #257 to fix the issue.

**Comment by mafredri** [comment]
Also, the integration guide for omz in the readme has been updated. You should check it out.

**Comment by veggiedefender** [comment]
Thank you! It works perfectly now <3
