### ISSUE TITLE
No git branch name autocomplete

### ISSUE THREAD

**Issue by vdclouis** [sindresorhus/pure#266]
### General information

- Pure version: 1.4.1
- ZSH version: 5.3
- Terminal program & version: Hyper 1.0.0
- Operating system: macOS Sierra 10.12.3
- ZSH framework: none

I have:
- [x] Tested with another terminal program and can reproduce the issue: 
- [x] Followed the [Integration](https://github.com/sindresorhus/pure#integration) instructions for my framework

### Problem description
No autocompletion for git branch names.
When pressing the `TAB` key it autocompletes with the files/folders from the current directory.

### Reproduction steps

1. `cd` to a git folder
2. change branch `git checkout <something>`
3. no autocompletion

### My `.zshrc`:

```shell
autoload -Uz promptinit; promptinit

PURE_PROMPT_SYMBOL="⚡️"

# set pure theme
prompt pure

# set syntax highlighting
source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# set auto suggestions
source /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh

# set up z
. /usr/local/etc/profile.d/z.sh

# set aliases
source $HOME/.aliases

# set nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" # This loads nvm

# exports
source $HOME/.exports
```

**Comment by mafredri** [comment]
This is not a Pure issue, it does not affect autocompletion in any way. You could start with, as per the documentation of zsh syntax hilighting, moving it to the end of your zshrc, see if it helps.

Out of curiousity, can you only reproduce when pure is enabled?

**Comment by vdclouis** [comment]
found it.

added this to my `.zshrc`
```
autoload -Uz compinit promptinit
compinit
promptinit
```
