### ISSUE TITLE
Prompt symbol not being evaluated

### ISSUE THREAD

**Issue by wayneashleyberry** [sindresorhus/pure#276]
### General information

- Pure version: 3dd645970e2cdb8bb17d628b13626afadf46741f
- ZSH version: zsh 5.3.1 (x86_64-apple-darwin15.6.0)
- Terminal program & version: iTerm 2 Build 3.0.13
- Operating system: macOS Sierra 10.12.2
- ZSH framework: antibody

I have:

- [x] Tested with another terminal program and can reproduce the issue: Terminal
- [x] Followed the [Integration](https://github.com/sindresorhus/pure#integration) instructions for my framework

### Problem description

Updating pure to 3dd645970e2cdb8bb17d628b13626afadf46741f causes the symbol prompt to not be evaluated.

The issue was introduced in https://github.com/sindresorhus/pure/commit/3dd645970e2cdb8bb17d628b13626afadf46741f, reverting the commit fixes the problem.

![screen shot 2017-01-19 at 12 10 43 pm](https://cloud.githubusercontent.com/assets/727262/22102494/50fa9db0-de40-11e6-9267-c324056b0c22.png)

### Reproduction steps

1. `antibody update`

### My `.zshrc`:

```shell
source <(antibody init)
antibody bundle mafredri/zsh-async
antibody bundle wayneashleyberry/pure
antibody bundle zsh-users/zsh-syntax-highlighting
```

**Comment by mafredri** [comment]
Thanks for the report, issue has been acknowledged in https://github.com/sindresorhus/pure/pull/274#issuecomment-273609541, however, I'm not entirely sure why this is an issue. Pure attempts to set `prompt_subst` via `prompt_opts`.

Have you modified, by any chance, `prompt_opts` or set/unset the `prompt_subst` option via `(un)setopt` in your zsh configuration?

Actually, it seems `antibody` does something weird here when initializing, I can reproduce the issue with your `.zshrc` but I cannot reproduce when doing the steps manually.

**Comment by ltartari** [comment]
I'm having the same issue, with my prompt looking like:
```
~
${PURE_PROMPT_SYMBOL:-❯} 
```

Here goes my `.zshrc` (abridged for clarity) and `.antigenrc` files:
```
#!/bin/zsh

source $(brew --prefix)/share/antigen/antigen.zsh
antigen init .antigenrc
```

```
#!/bin/zsh

antigen bundles <<EOBUNDLES
  compleat
  git-extras
  git-flow
  osx
  zsh-users/zsh-syntax-highlighting

  mafredri/zsh-async
  sindresorhus/pure
EOBUNDLES

antigen apply
```

**Comment by mafredri** [comment]
@ltartari since antigen also sources the files and does not use `promptinit` I believe the fix for you would be `setopt prompt_subst` as well.

I've taken a quick look at how to solve this, and this comes to mind as one possible solution:

```diff
diff --git a/pure.zsh b/pure.zsh
index 54719b7..dbb0dc4 100644
--- a/pure.zsh
+++ b/pure.zsh
@@ -332,8 +332,16 @@ prompt_pure_setup() {
 	# if output doesn't end with a newline
 	export PROMPT_EOL_MARK=''
 
+	local autoload_name=$1; shift
+
 	prompt_opts=(subst percent)
 
+	# check if pure was autoloaded as prompt_pure_setup or sourced.
+	if [[ $autoload_name != prompt_pure_setup ]]; then
+		# borrowed from `promptinit`, set the pure prompt options when sourced.
+		setopt noprompt{bang,cr,percent,subst} "prompt${^prompt_opts[@]}"
+	fi
+
 	zmodload zsh/datetime
 	zmodload zsh/zle
 	zmodload zsh/parameter
@@ -371,4 +379,4 @@ prompt_pure_setup() {
 	PROMPT='%(?.%F{magenta}.%F{red})${PURE_PROMPT_SYMBOL:-❯}%f '
 }
 
-prompt_pure_setup "$@"
+prompt_pure_setup $0 "$@"
```

Maybe there are better ways to detect if `autoload`ed via `promptinit` or `source`d, though?

**Comment by ltartari** [comment]
```
~
${PURE_PROMPT_SYMBOL:-❯} setopt prompt_subst
                                                                                                                                                       
~
❯ 
```

Works like magic, @mafredri . Thanks! ❤️

**Comment by wayneashleyberry** [comment]
Thanks everyone for sorting this out so quickly 👏
