### ISSUE TITLE
Remove white Lines ?

### ISSUE THREAD

**Issue by llmdev** [sindresorhus/pure#279]
![captura de tela 2017-01-19 as 20 52 45](https://cloud.githubusercontent.com/assets/25234963/22128817/8c3c43e4-de89-11e6-86e8-8d51ebc925f7.png)

how to remove white lines ??

**Comment by mafredri** [comment]
Pure doesn't have extra lines like this, I would appreciate it if you filled out the issue template so that we can narrow down your issue.

**Comment by llmdev** [comment]
![captura de tela 2017-01-21 as 18 14 39](https://cloud.githubusercontent.com/assets/25234963/22177476/8371d8fa-e005-11e6-8f7f-56d0a7e52a8f.png)

Line Breaking Theme

**Comment by mafredri** [comment]
Please open a new issue and provide the information that is asked for.
