### ISSUE TITLE
Breaking Line Pure theme ZSH

### ISSUE THREAD

**Issue by llmdev** [sindresorhus/pure#280]
Help remove lines...

![captura de tela 2017-01-21 as 18 14 39](https://cloud.githubusercontent.com/assets/25234963/22177508/7ec637b4-e006-11e6-8715-70427b445ede.png)

My .zshrc
`
ZSH_THEME=pure

autoload -U promptinit; promptinit
prompt pure
alias vim='mvim -v`

**Comment by llmdev** [comment]
![captura de tela 2017-01-21 as 18 26 26](https://cloud.githubusercontent.com/assets/25234963/22177537/254e0d32-e007-11e6-9813-c6fd6d4ce40e.png)
Time Script  Breaking Lines...

**Comment by mafredri** [comment]
I saw mention of oh-my-zsh before you edited the issue. Please follow the oh-my-zsh integration instructions for pure: https://github.com/sindresorhus/pure#oh-my-zsh

What you're seeing is the oh-my-zsh theme `pure` conflicting with out pure, these are not the same.

**Comment by mafredri** [comment]
I believe #250 is related (it had no resolution though; user switched from oh-my-zsh to prezto).

**Comment by mafredri** [comment]
I hope you got pure working @llmdev.

I'm closing this as a oh-my-zsh issue which should be resolved by following the integration steps in the readme. Feel free to reopen if this is still an issue for you.
