### ISSUE TITLE
Occasionally can't git pull when switching branches

### ISSUE THREAD

**Issue by Hilzu** [sindresorhus/pure#283]
### General information

- Pure version: 1.5.0
- ZSH version:  5.3.1 (x86_64-apple-darwin16.3.0)
- Terminal program & version: iTerm2 3.0.13
- Operating system: macOS Sierra 10.12.3
- ZSH framework: none

I have:
- [x] Tested with another terminal program and can reproduce the issue: Terminal.app
- [ ] Followed the [Integration](https://github.com/sindresorhus/pure#integration) instructions for my framework

### Problem description

Occasionally when switching branches and immediately trying to `git pull` the command fails. It's most likely caused by the async git functionality trying to fetch changes at the same time.

### Reproduction steps

```
~/code/stuff branch*
❯ g co master
Switched to branch 'master'
Your branch is behind 'origin/master' by 3 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)

~/code/stuff master* ⇣
❯ g pl
fatal: Cannot rebase onto multiple branches.

~/code/stuff master* ⇣
❯ g pl
First, rewinding head to replay your work on top of it...
Fast-forwarded master to ed79db49234bda7334cfcd6a2c1dc1c4983b502e.
```

### My `.zshrc`:

```shell
autoload -U promptinit; promptinit
prompt pure

alias g=git
```

**Comment by mafredri** [comment]
Yikes, that's annoying. Is there any more information you can provide me, e.g. related git configuration (e.g. pull.rebase comes to mind, perhaps others?), repository size, etc? 

I've not encountered this myself, but I'll see if I can reproduce.

**Comment by mafredri** [comment]
Thanks for the extra info, now, I haven't gotten around to reproducing this yet, but I have an idea as to what might be the cause.

In [pure.zsh#L84](https://github.com/sindresorhus/pure/blob/fcd942622d39d611419947507b6b004b540d7287/pure.zsh#L84) we check if the user executed git `pull` or `fetch` (explicitly) and cancel async tasks if the command matches one of those.

At this point the zsh alias is already expanded (so we know `g` = `git`), however pure does not know of git aliases (e.g. `pl` =`pull`).

Can you still reproduce if you change `(pull|fetch)` to `(pl|pull|fetch)`?

**Comment by Hilzu** [comment]
After testing it for a while the change seems to fix the problem.

I guess the easiest fix for me would be to define `pl` as a zsh alias instead of a git alias. Too bad there doesn't seem to be a way to define `g pl` as the alias (with the space) for symmetry with the rest of my git aliases.

**Comment by mafredri** [comment]
Thanks for confirming, @Hilzu. I actually have an idea on how we can fix this issue for you and anyone else in your situation.

The fix involves us parsing the git aliases once whenever we enter a new git directory via `git config --get-regexp "^alias\."` and looking for pull/fetch aliases. From this we could then construct a custom pattern instead of just `(pull|fetch)`.
