### ISSUE TITLE
Pure prompt not listed after being installed (maxOS Sierra)

### ISSUE THREAD

**Issue by rafek** [sindresorhus/pure#284]
I installed zsh via homebrew and have it under `/usr/local/bin/zsh`.

My `$fpath` is:

```/usr/local/share/zsh/site-functions /usr/local/Cellar/zsh/5.3.1/share/zsh/functions```

`prompt -l` gives me the following (after checking options in `.zshrc` if they comply to whatever posted under issues already):

```
RafBook-Pro% prompt -l
Currently available prompt themes:
adam1 adam2 bart bigfade clint elite2 elite fade fire off oliver pws redhat suse walters zefram
```

Any clue what I might be doing wrong? Thanks.

**Comment by mafredri** [comment]
How did you install pure, via npm? If so you should have a symlink at /usr/local/share/zsh/site-functions/prompt_pure_setup pointing to pure.

You're not seeing pure listed in the prompts because prompt_pure_setup is missing from your fpath.

**Comment by rafek** [comment]
I installed pure with `npm i -g pure-prompt`:

```
RafBook-Pro% npm ls -g --depth=0
/usr/local/lib
├── generator-electron@1.20.0
├── gulp@3.9.1
├── npm@4.0.5
├── pure-prompt@1.5.0
└── yo@1.8.5
```

And you're right, there's no `prompr_pure_setup` in my `fpath`:

```
RafBook-Pro% ls /usr/local/share/zsh/site-functions/  
_brew		_brew_cask
```

Same result is after I uninstall pure and install it again.

**Comment by mafredri** [comment]
What is the output from the installation, did you get an error message?

**Comment by rafek** [comment]
OK, got it. Indeed npm was spitting out some errors. Needed to go with a manual process. All's fine now. Thanks!

**Comment by mafredri** [comment]
Glad you got it sorted! Hoping situations such as your will be slightly improved by https://github.com/sindresorhus/pure/issues/282#issuecomment-276661578.
