### ISSUE TITLE
fatal: Not a git repository (or any of the parent directories): .git

### ISSUE THREAD

**Issue by alextrastero** [sindresorhus/pure#286]
### General information

- Pure version: latest
- ZSH version: 5.0.8
- Terminal program & version: xterm 327
- Operating system: macOS Sierra 10.12.1
- ZSH framework: oh-my-zsh

I have:
- [x] Tested with another terminal program and can reproduce the issue: 
- [x] Followed the [Integration](https://github.com/sindresorhus/pure#integration) instructions for my framework

### Problem description
```sh
fatal: Not a git repository (or any of the parent directories): .git
```

### Reproduction steps

1. open terminal

### My `.zshrc`:

PURE_GIT_PULL=0
ZSH_THEME="pure"

```zsh

```

**Comment by mafredri** [comment]
Why do you think this is related to Pure? I don't see how this error message could be coming from Pure.

Have you tried the second option in integrating with `oh-my-zsh`?:

1. Set `ZSH_THEME=""` in your `.zshrc` to disable oh-my-zsh themes.
2. Follow the Pure [Install](#install) instructions.

**Comment by alextrastero** [comment]
ups, forgot to close this, it stopped happening after a restart. I wasn't sure what `pure` was doing under the hood, that's why I submitted the issue.

**Comment by mafredri** [comment]
Alright cool, glad it's solved 👍
