### ISSUE TITLE
.zshrc:1: no such file or directory: //adding

### ISSUE THREAD

**Issue by alistaircolling** [sindresorhus/pure#288]
### General information

- Pure version: 1.8.1
- ZSH version: 5.3.1
- Alacritty, iTerm2, Terminal
- Operating system: macOS 10.10.5
- ZSH framework: oh-my-zsh

I have:
- [YES] Tested with another terminal program and can reproduce the issue: 
- [YES] Followed the [Integration](https://github.com/sindresorhus/pure#integration) instructions for my framework

### Problem description
When I open any terminal window I get this line of text displaying at the top of the window:
`/Users/alistair/.zshrc:1: no such file or directory: //adding`

### Reproduction steps

1.Open a terminal window

```
export ZSH=/Users/alistair/.oh-my-zsh
export PATH="$PATH:$HOME/.cargo/bin"

ZSH_THEME=""

plugins=(git aws brew osx tmux git-open)
source $ZSH/oh-my-zsh.sh

 if [[ -n $SSH_CONNECTION ]]; then
   export EDITOR='vim'
 else
   export EDITOR='nvim'
 fi


 alias zshconfig="mate ~/dotfiles/.zshrc"
 alias ohmyzsh="mate ~/dotfiles/.oh-my-zsh"
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=pink'

# Prefix to use when saving original versions of bound widgets
ZSH_AUTOSUGGEST_ORIGINAL_WIDGET_PREFIX=autosuggest-orig-

ZSH_AUTOSUGGEST_STRATEGY=default
```

**Comment by mafredri** [comment]
The error quite obviously hints at something wrong with your `.zshrc` file. What does a `ls -l /Users/alistair/.zshrc` say?

**Comment by alistaircolling** [comment]
Sorry! 😊 Seems pretty obvious now, the first line of my .zshrc should have been commented.
Thanks :)

**Comment by davcruz007** [comment]
having same issue. It just started today out of nowhere.

**Comment by mafredri** [comment]
@davcruz007 please open a new issue and provide us with some more information.
