### ISSUE TITLE
For use Pure, need Hyper?

### ISSUE THREAD

**Issue by adrianoresende** [sindresorhus/pure#294]
`In the screenshot you see Pure running in Hyper with the hyper-snazzy theme and Menlo font.`
This pure need Hyper?

**Comment by mafredri** [comment]
Hyper is not necessary, you can use any terminal emulator. For instance, on macOS you could use iTerm2, Terminal, etc. On linux, take your pick :-).

**Comment by mikeerickson** [comment]
@adrianoresende nope, it works with any terminal app (I personally use iTerm2 and looks fabulous)
