### ISSUE TITLE
Random line showing up on the prompt.

### ISSUE THREAD

**Issue by shahzeb1** [sindresorhus/pure#295]
### General information

- Pure version: 1.5.1
- ZSH version: 5.2
- Terminal program & version: Hyper 1.2.1
- Operating system: mac OS 10.12
- ZSH framework: oh-my-zsh

I have:
- [x] Tested with another terminal program and can reproduce the issue: 
- [X] Followed the [Integration](https://github.com/sindresorhus/pure#integration) instructions for my framework

### Problem description
After finally getting the the theme to work, a random line keeps getting printed to the terminal. 
![hyper2](https://cloud.githubusercontent.com/assets/1383831/23085012/0d69eea2-f51a-11e6-863d-a7183a32b838.png)

### Reproduction steps

1. Open hyper.
2. `$ cd` into a folder which has git enabled.

### My `.zshrc`:

```shell
export ZSH=/Users/[username]/.oh-my-zsh
source /Users/[username]/.bash_profile
ZSH_THEME="pure"
autoload -U promptinit; promptinit
prompt pure
```

**Comment by mafredri** [comment]
Since you are loading pure manually you should set `ZSH_THEME=""` to disable oh my zsh themes.

**Comment by shahzeb1** [comment]
![hyper3](https://cloud.githubusercontent.com/assets/1383831/23088331/626168f2-f530-11e6-815b-1a8e8b3e608f.png)

@mafredri: So I got rid of "pure" so it's just `ZSH_THEME=""`. Now that line is gone, but instead of just the ❯ being the `PURE_PROMPT_SYMBOL`, I get the whole string. I've manually set my `PURE_PROMPT_SYMBOL=❯` but it didn't fix anything.

**Comment by mafredri** [comment]
Remove `source /Users/[username]/.bash_profile`. It's likely changing PS1.

**Comment by shahzeb1** [comment]
@mafredri : Just tried that to no avail. 😞 

It's so frustrating. If I use `ZSH_THEME="pure"` then the first random line pops up, but if I manually initialize the theme, then the prompt symbol isn't right. 

Here is the output of running `$ cat .zshrc | awk '!/^#/'`:

> export ZSH=/Users/shahzeb/.oh-my-zsh
autoload -U promptinit; promptinit
PURE_PROMPT_SYMBOL="❯"
prompt pure
plugins=(git)
source $ZSH/oh-my-zsh.sh

**Comment by mafredri** [comment]
You're missing the line from my first post in there. Set it before sourcing oh my zsh

**Comment by shahzeb1** [comment]
Now the .zshrc looks like this:

>export ZSH=/Users/shahzeb/.oh-my-zsh
ZSH_THEME=""
autoload -U promptinit; promptinit
PURE_PROMPT_SYMBOL="❯"
prompt pure
plugins=(git)
source $ZSH/oh-my-zsh.sh

Still has the same appearance as the second screenshot.

**Comment by mafredri** [comment]
Maybe oh-my-zsh sets the PS1 as well, try this ordering:

```zsh
export ZSH=/Users/shahzeb/.oh-my-zsh
ZSH_THEME=""
plugins=(git)
source $ZSH/oh-my-zsh.sh

autoload -U promptinit; promptinit
prompt pure
```

Also, I removed the symbol setting because you do not need to set it. It's not having an effect since your `PS1` (same as `PROMPT`) variable is being replaced by something after Pure is initialized.

**Comment by shahzeb1** [comment]
It worked! 😄
