### ISSUE TITLE
Preprompt not showing

### ISSUE THREAD

**Issue by tolosa** [sindresorhus/pure#297]
Hi guys!

I used this prompt from a long time without any issues on my Mac. However, a few days ago I tried to copy my current configuration to a new linux machine, and everything worked but the preprompt is not showing anymore, like this:

![screenshot from 2017-02-23 15-49-11](https://cloud.githubusercontent.com/assets/219579/23275275/a88cd218-f9e4-11e6-8539-510da75190e7.png)

Note that it appears when I enter to a git folder.

I'm using oh-my-zsh, with ZSH version 5.2. The pure version is the one bundled with oh-my-zsh (latest version, recently updated.) I'm sharing [my `.zshrc` file](https://gist.github.com/tolosa/8ec7158c71be5d835f8a0087c9af98b3) and `.oh-my-zsh` directory between the two computers, storing that in Google Drive with symlinks to the files.

This issue looks a lot like #234, but I couldn't solve it with that instructions. Sorry if I'm asking an obvious question, I don't know enough about ZSH to troubleshoot this myself.

Love your work! Thanks a lot for the help.

**Comment by mafredri** [comment]
Oh-my-zsh has never bundled our Pure, and it still does not. To use Pure you must follow the installation instructions in the readme. I'm a bit short on time right now, but there are a lot of issues similar to yours if you [search for oh-my-zsh](https://github.com/sindresorhus/pure/issues?utf8=✓&q=oh-my-zsh). Hope that helps.
