### ISSUE TITLE
Command duplicated on tab completion with oh-my-zsh and Hyper

### ISSUE THREAD

**Issue by ycho1015** [sindresorhus/pure#300]
### General information

- Pure version: latest
- ZSH version: 5.3.1
- Terminal program & version: Hyper 1.2.1.1527
- Operating system: macOS Sierra 10.12.13
- ZSH framework: oh-my-zsh, zsh 5.3.1

I have:
- [x] Tested with another terminal program and can reproduce the issue: 
- [x] Followed the [Integration](https://github.com/sindresorhus/pure#integration) instructions for my framework

### Problem description

I have completely wiped out everything and did a new installation because of duplicate cp problem and here is what I am getting.
<img width="669" alt="2017-02-24 7 19 20" src="https://cloud.githubusercontent.com/assets/22088039/23325826/5e85009a-fac6-11e6-8d72-22a11f33b193.png">

### Reproduction steps

1. Deleted everything to start over
2. Followed Integration for oh-my-zsh

Here is my reinstallation process that I just did

```shell
$ mkdir ~/.oh-my-zsh/functions
$ ln -s  "$PWD/pure.zsh" ~/.oh-my-zsh/functions/prompt_pure_setup
$ ln -s "$PWD/async.zsh" ~/.oh-my-zsh/functions/async
$ ln -s "$PWD/pure.zsh" ~/.oh-my-zsh/custom/pure.zsh-theme
$ ln -s "$PWD/async.zsh" ~/.oh-my-zsh/custom/async.zsh

$ ln -s "$PWD/pure.zsh" /usr/local/share/zsh/site-functions/prompt_pure_setup
$ ln -s "$PWD/async.zsh" /usr/local/share/zsh/site-functions/async
```
### My `.zshrc`:

```shell
export PATH=$HOME/bin:/usr/local/bin:$PATH
export ZSH=/Users/yoon/.oh-my-zsh
ZSH_THEME="pure"
autoload -U promptinit; promptinit
prompt pure
plugins=(git)
source $ZSH/oh-my-zsh.sh
```

### My `.hyper.js`:
```shell
shell: '/usr/local/bin/zsh'
plugins: ['hyper-snazzy']
```

**Comment by ycho1015** [comment]
tried #295. 
get an error for not being able to read file and duplicate cd issue
<img width="678" alt="2017-02-24 7 33 53" src="https://cloud.githubusercontent.com/assets/22088039/23326047/30ef2ec4-fac8-11e6-9d3b-cfd6c72287a3.png">

'.zshrc'
'''shell
export ZSH=/Users/yoon/.oh-my-zsh
ZSH_THEME=""
plugins=(git)
source $ZSH/oh-my-zsh.sh

autoload -U promptinit; promptinit
prompt pure
....

**Comment by ycho1015** [comment]
without pure in
ZSH_THEME=""

duplicate cd issue is gone but prompt symbol is missing

<img width="361" alt="2017-02-24 7 36 41" src="https://cloud.githubusercontent.com/assets/22088039/23326098/93a72bde-fac8-11e6-9063-6dacdc7d4170.png">

`.zshrc`
```shell
export PATH=$HOME/bin:/usr/local/bin:$PATH
export ZSH=/Users/yoon/.oh-my-zsh
ZSH_THEME=""
autoload -U promptinit; promptinit
prompt pure
plugins=(git)
source $ZSH/oh-my-zsh.sh
```

**Comment by ycho1015** [comment]
I ended up facing the same problem..

<img width="205" alt="2017-02-24 8 13 24" src="https://cloud.githubusercontent.com/assets/22088039/23326639/b6725382-facd-11e6-845f-eac846171a15.png">

`.zshrc`
```shell
export ZSH=/Users/yoon/.oh-my-zsh
ZSH_THEME=""
export PATH=$HOME/bin:/usr/local/bin:$PATH
source $ZSH/oh-my-zsh.sh
autoload -U promptinit; promptinit
prompt pure
plugins=(git)
```

**Comment by mafredri** [comment]
Regarding your reinstallation process you should only do **one** of:

```
$ ln -s  "$PWD/pure.zsh" ~/.oh-my-zsh/functions/prompt_pure_setup
$ ln -s "$PWD/async.zsh" ~/.oh-my-zsh/functions/async
```
or
```
$ ln -s "$PWD/pure.zsh" ~/.oh-my-zsh/custom/pure.zsh-theme
$ ln -s "$PWD/async.zsh" ~/.oh-my-zsh/custom/async.zsh
```
or
```
$ ln -s "$PWD/pure.zsh" /usr/local/share/zsh/site-functions/prompt_pure_setup
$ ln -s "$PWD/async.zsh" /usr/local/share/zsh/site-functions/async
```

Personally I recommend against the middle variant, since OMZ contains the *fake* pure theme that conflicts with ours, which is a big reason for headache for both our users and us.

I also recommend (assuming **not** using the middle variant with `.zsh-theme`) that you use this as your `.zshrc`, exactly as written (order might be important):

```zsh
# Setup oh-my-zsh
export ZSH=/Users/yoon/.oh-my-zsh
ZSH_THEME=""  # Disable themes
plugins=(git)
source $ZSH/oh-my-zsh.sh

# Load the pure theme
autoload -U promptinit; promptinit
prompt pure
```

---

Now from what you've reported here, I gather you still have the duplicate cd problem in Hyper?

First step, try disabling oh-my-zsh, here's the entire contents of your `.zshrc`:

```zsh
fpath+=(~/.oh-my-zsh/functions)  # This is just to make pure available in $fpath if linked here.

# Load the pure theme
autoload -U promptinit; promptinit
prompt pure
```

Can you still reproduce the problem?

**Comment by ycho1015** [comment]
I have tried all solutions you mentioned but I still get the same problem.

This does not happen in regular terminal nor iterm2 but only in hyper. can it be a issue with hyper?

**Comment by ycho1015** [comment]
I figured it out 😂

The issue came from my mac's primary language set up in Korean. After changing back to English, duplicated command disappeared. It must have been the encoding issue with hyper terminal.

Thanks for the help though!

**Comment by mafredri** [comment]
Awesome, glad you figured it out 😊.

**Comment by elvis-macak** [comment]
meet the same problem but fixed after setting this in .zshrc
```
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
```

still thanks for figure out the problem, it should be a general issue

**Comment by wrfly** [comment]
if still doesn't work, can try this as well (after adding those envs):

```
apt-get install -y locales \
    && dpkg-reconfigure locales \
    && locale-gen en_US.UTF-8
```

**Comment by gabyx** [comment]
For docker do the following before install on Debian:

 ```shell
# Set the locale
RUN apt-get install -y locales && \
    dpkg-reconfigure locales && \
    locale-gen en_US.UTF-8

ENV LANG=en_US.UTF-8 \
    LC_ALL=en_US.UTF-8

```

**Comment by TinaHeiligers** [comment]
For anyone who's experiencing the same issue lately, https://github.com/sindresorhus/pure/issues/300#issuecomment-386371460 fixed it on my machine (MacBook Pro, macOS Catalina, v10.15.7).
