### ISSUE TITLE
Feature request | arrow prompt ❯ color

### ISSUE THREAD

**Issue by fazlearefin** [sindresorhus/pure#303]
The arrow prompt `❯` color for normal (`$? -eq 0`) and not normal (`$? -ne 0`) is not very obvious. I suggest you use grey or green for the arrow prompt when normal (`$? -eq 0`).

**Comment by fazlearefin** [comment]
For this to happen, the only change required is to replace `magenta` with `green` in `pure.zsh`

```
- PROMPT='%(?.%F{magenta}.%F{red})${PURE_PROMPT_SYMBOL:-❯}%f '
+ PROMPT='%(?.%F{green}.%F{red})${PURE_PROMPT_SYMBOL:-❯}%f '
```

**Magenta** and **red** are not good combinations as on some color schemes it is a bit difficult to tell them apart. **Green** and **red** should be easy to spot.

**Comment by sindresorhus** [comment]
I don't want a green prompt character. That looks boring. How about we instead change the error color to yellow?

**Comment by fazlearefin** [comment]
Changing the error color to yellow is fine with me.

**Comment by mikeerickson** [comment]
@sindresorhus @fazlearefin Yes, I agree as well on yellow.   That is a biggest enough difference imo

**Comment by fazlearefin** [comment]
I can make the change and raise a pull request if that helps get this change to the repo quicker.

**Comment by mafredri** [comment]
I'm not a fan to switching the color to yellow, too close to green (== OK). And it does look quite out of place.

Thoughts on #306?

**Comment by mafredri** [comment]
To demonstrate what it looks like for me:

![screenshot 2017-03-23 18 34 13](https://cloud.githubusercontent.com/assets/147409/24258761/6a004786-0ff7-11e7-804b-c950bcdd0b5c.png)

**Comment by fazlearefin** [comment]
@mafredri Depending on what theme you choose, the prompt colors vary.

About #306 , I see lots of references to previous issues where people have asked to change the prompt colors but no change has been done yet.

I guess the philosophy of the pure theme is to keep things very minimal. So to keep things minimal, I suggest having two variables `SUCCESS_PROMPT_COLOR` and `ERROR_PROMPT_COLOR` which can be set by the user if he/she wants to. If these variables are not set by the user, they default to the current `magenta` and `red` colors.

**Comment by anton-johansson** [comment]
What about using options for the two colors in `.zshrc`? They can default to the same values that are currently being used.

```
PURE_PROMPT_NORMAL_COLOR=green
PURE_PROMPT_ERROR_COLOR=red
```

**Comment by fazlearefin** [comment]
@sindresorhus Can we please make the the normal color `grey` until we find a suitable way to configure the prompt colors? `grey` is very different from `red` on most color schemes and also stands out of the way until error code is generated.
![screenshot](https://cloud.githubusercontent.com/assets/1625934/25324528/a85ae1d2-2909-11e7-895a-4ad5a5832f2a.png)

**Comment by will-stone** [comment]
This option would be great. Has this reached enough interest to be considered?

**Comment by mafredri** [comment]
@will-stone this is being considered, I think both me and @sindresorhus agree that we don't want new environment variables for configuring this, though. So using `zstyle` as proposed in #306 seems like the most likely candidate, I just haven't gotten around to it yet 😅.

This feature has been quite low-prio for me personally, so if anyone is interested to help, a proposal / PR is definitely welcomed. To start with, I think it makes sense to limit this to colorizing the prompt character only, in the future more colors customizations could be introduced, but let's see how it works first.

**Comment by fazlearefin** [comment]
I'll raise a PR if I get some time and manage to get it to work as proposed in #306 .

**Comment by alexozer** [comment]
How's this going?

**Comment by craftyguy** [comment]
I hope it's still going. It's very hard for my eyes to differentiate between the default color (magenta-ish) and the error color (red), considering the prompt character is really thin/small.

**Comment by disrupted** [comment]
@craftyguy +1 same here
