### ISSUE TITLE
Feature Request: Option to always show username and host

### ISSUE THREAD

**Issue by urbantrout** [sindresorhus/pure#309]
It would be really nice, to have an option to always show username and host. Right now they are only visible over a SSH connection. But my problem is, that I SSH into my server as non-root user and then "su" into root. And when I do that, there is no username nor host displayed.

PS: Thank you for this brilliant theme!

**Comment by mafredri** [comment]
Apologies for the delay in getting back to you.

I'm not sure we want to introduce this as an option thought. We wish to keep Pure with as few options as possible, I also believe your use-case is somewhat special.

At least in the current implementation (and I see no reason to change it at this point in time) you should be able to add this to you root users `.zshrc`:

```
prompt pure

# Override Pure username to include user@host.
prompt_pure_username='%F{white}%n%f%F{242}@%m%f'
```

We only set this variable during prompt init, so it can be overridden at any point afterwards.

**Comment by urbantrout** [comment]
Thanks for your reply!

Will try that later.
