### ISSUE TITLE
Pulling a branch during the async commit check throws error

### ISSUE THREAD

**Issue by dcalhoun** [sindresorhus/pure#312]
### General information

- Pure version: 1.5.1
- ZSH version: 5.2
- Terminal program & version: Hyper 1.3.1 (1.3.1.1628)
- Operating system: macOS Sierra 10.12.4 (16E195)
- ZSH framework: [thoughtbot/dotfiles](https://github.com/thoughtbot/dotfiles), [dcalhoun/dotfiles](https://github.com/dcalhoun/dotfiles)

I have:
- [ ] Tested with another terminal program and can reproduce the issue: 
- [x] Followed the [Integration](https://github.com/sindresorhus/pure#integration) instructions for my framework

***NOTE:** I'll try to test another terminal later.*

### Problem description
Running `git pull` while the asynchronous asynchronous check for un-pushed/un-pulled commits for a branch causes the following error:

```
~/Sites/web/[REDACTED] staging
❯ g pull
error: cannot lock ref 'refs/remotes/origin/staging': is at ba8818edddb1da129d22e019fb4e9812c77a5949 but expected ed6b450ee192d423da39cf3855f67294b73eb330
From github.com:[REDACTED]/[REDACTED]
 ! ed6b450e..ba8818ed  staging    -> origin/staging  (unable to update local ref)
```

### Reproduction steps

1. Switch to a branch that has changes in its `origin` copy.
2. Before the asynchronous check for un-pushed/un-pulled commits finishes, run `git pull`.
3. The above error should show up.

### My `.zshrc`:

***NOTE:** I'll try to pair this down later if I can.*

```shell
# Add Yarn's global bin to path
export PATH="$(yarn global bin):$PATH"

# Do not record commands beginning with a space
setopt hist_ignore_space

# Source plugins
source ~/dotfiles-local/zsh/completion/tmuxinator.zsh
source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Setup pure prompt https://git.io/6LHDOw
fpath+=('/usr/local/share/zsh/site-functions')
autoload -U promptinit; promptinit
prompt pure

# Load nvm
export NVM_DIR='/Users/[REDACTED]/.nvm'
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

# Case insensitive auto-complete
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'

# Bind up and down keys to history-search
bindkey '^[[A' history-beginning-search-backward
bindkey '^[[B' history-beginning-search-forward

# Bind custom clear screen to preserve multi-line prompt
function clear_multi_line_prompt () {
  zle push-input
  BUFFER=' clear'
  zle accept-line
  zle reset-prompt
}

zle -N clear_multi_line_prompt
bindkey '\C-l' clear_multi_line_prompt
```

### Possible Solution
Not sure if you can prevent this error, but displaying a loading indicator during the asynchronous check for un-pushed/un-pulled commits might be helpful.

**Comment by mafredri** [comment]
I see your using an old version of Pure, could you try `1.5.2`? Detection of git aliases was improved in that release.

I also see you're doing `g pull`, is `g` an alias to `git` or is it a separate command? If it's a separate command, that's the issue.

Pure tries to detect if you're performing conflicting git operations, and [this block of code](https://github.com/sindresorhus/pure/blob/3a08df333d1a32b5be610f3cb688d5c773b8c650/pure.zsh#L83-L90) should trigger, stopping all async work that pure is doing.

**Comment by dcalhoun** [comment]
I've upgrade to `1.5.2`. I'll play with it some more to see if it improves.

Ah, ok. I suppose [it is a separate command](https://github.com/thoughtbot/dotfiles/blob/09d54d448c0d70f2e404e7610cac1d5314f76593/zsh/functions/g)? Does that rule out all possibilities of it working correctly or is there still hope?

**Comment by mafredri** [comment]
As is, it will not work, sorry :(. You could inject the Pure check into your `g` function.

```zsh
g() {
  if [[ $# -gt 0 ]]; then
    if [[ $* =~ (.*\ )?($prompt_pure_git_fetch_pattern)(\ .*)?$ ]]; then
      # we must flush the async jobs to cancel our git fetch in order
      # to avoid conflicts with the user issued pull / fetch.
      async_flush_jobs 'prompt_pure'
    fi
    git "$@"
  else
    git status
  fi
}
```

It would of course not receive updates, much sadness ☹️.

**Comment by dcalhoun** [comment]
Alright. Thank you for the all help. 😄

**Comment by AndreasBoehm** [comment]
Hi, i do have the same issue but with a slightly different setup. 

I use [git up](https://github.com/aanand/git-up) to keep my repositories up-to-date. Because its not an alias pure is not able to catch this.

by adding "up" to *$prompt_pure_git_fetch_pattern* within prompt_pure_setup i was able to get rid of this problems but i wanted to ask if there is a cleaner solution?

Thanks! :)

**Comment by mafredri** [comment]
@AndreasBoehm I can come up with two alternatives (a third would be putting `up` into Pure, but that's something I'd like to avoid).

It looks like git-up is no longer maintained, and the official documentation suggests this:

```console
$ git config --global alias.up 'pull --rebase --autostash'
```

The above would fix the issue without modifying pure.

You could also *override* the `prompt_pure_async_git_aliases` function by defining it after pure has been loaded, e.g.:

```shell
prompt pure
prompt_pure_async_git_aliases() {
    print up
}
```

This would always return "up" as an alias and would never check for any other custom aliases.

**Comment by AndreasBoehm** [comment]
HI @mafredri ,

thanks for the quick response.

I support you denying option 3 because Pure should not be adopted to the needs of a single user :)

The official documentation is not exactly true thats why i can not use the alias, but thanks for pointing it out.

I totally missed to *override* this function, i did it as explained and it works like charm! 

Thanks for your help on this! :)
