### ISSUE TITLE
Git output overly verbose [newbie]

### ISSUE THREAD

**Issue by andig** [sindresorhus/pure#314]
### General information

- Pure version: current
- ZSH version: 5.2
- Terminal program & version: Hyper 1.0 
- Operating system: macOS Sierra 10.12
- ZSH framework: oh-my-zsh

I have:
- [x] Tested with another terminal program and can reproduce the issue: iTerm2 
- [x] Followed the [Integration](https://github.com/sindresorhus/pure#integration) instructions for my framework

### Problem description

The output of git branch and status appear to be overly verbose. I'd like to get rid of the secondary output after the command result and before the new prompt:

````
~/Documents/htdocs/vz feature-sql-optimizer*
❯ ls
COPYING              bs.sh                htdocs               node_modules         test
INSTALL              composer.json        import.sh            package.json         vendor
README.md            composer.lock        info.php             phpunit.xml          volkszaehler.db3
aggregate.sh         etc                  lib                  postgres.txt         vz.sublime-project
apc.php              gulpfile.js          misc                 ppm                  vz.sublime-workspace

 feature-sql-optimizer x/Users/andig/Documents/htdocs/vz*  

~/Documents/htdocs/vz feature-sql-optimizer*
````

### My `.zshrc`:

	export ZSH=/Users/andig/.oh-my-zsh

	autoload -U promptinit; promptinit
	prompt pure

	ZSH_THEME="pure"

	plugins=(git)

	source $ZSH/oh-my-zsh.sh

	source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

**Comment by mafredri** [comment]
The integration instructions in the readme give you two options for oh-my-zsh, and it seems you've chosen the manual install method (`promptinit` + `prompt pure`). This means you must disable oh-my-zsh themes with `ZSH_THEME=""`.

By setting `ZSH_THEME="pure"` you inadvertently enabled a theme that is bundled with oh-my-zsh and is named `pure`, it's not the same theme as our Pure. It also conflicts with our theme, causing what you're seeing :(.

**Comment by andig** [comment]
> The integration instructions in the readme give you two options for oh-my-zsh, and it seems you've chosen the manual install method (promptinit + prompt pure). This means you must disable oh-my-zsh themes with ZSH_THEME="".

Now you've got me really confused :O After npm install I've skipped to "Getting started" which asks to do the prompt thing?

I've also removed the theme now, but this also removed the pure prompt, only the colors are still there.

**Comment by mafredri** [comment]
Since you ticked the checkbox for having followed the framework specific install instructions, I assumed you had read up on the [oh-my-zsh integration](https://github.com/sindresorhus/pure#oh-my-zsh) instructions in the readme.

It mentions that `ZSH_THEME=""` must be set in your `.zshrc` when following default install instructions.

> I've also removed the theme now, [...]

What do you mean with removed the theme?

**Comment by andig** [comment]
> What do you mean with removed the theme?

I've set `ZSH_THEME=""` which then led me to https://github.com/sindresorhus/pure/issues/315

Thanks for all your help!
