### ISSUE TITLE
Newbie: Prompt not installed on OSX?

### ISSUE THREAD

**Issue by andig** [sindresorhus/pure#315]
This is a follow-up to https://github.com/sindresorhus/pure/issues/314. I've installed pure on OSX via NPM, set `ZSH_THEME=""` in `.zshrc` and added 

````
autoload -U promptinit; promptinit
prompt pure
````

While I'm getting the new color scheme, I don't get the new prompt. This will only happen if I manually run `prompt pure` on the command line:

````
~
andig@macbook-2:~% prompt pure

~
❯ 
````

Any idea why the `.zshrc` entries are not sufficient?

**Comment by mafredri** [comment]
The problem is that something in your `.zshrc` is overwriting the prompt (by assigning a new value to `PROMPT` or `PS1`) after you have initialized Pure. My best guess would be that oh-my-zsh is initializing a theme. This would happen if you source oh-my-zsh before `ZSH_THEME=""` has been set.

So make sure the order is right:

```zsh
ZSH_THEME=""
source ./path/to/omz
```

If it's already correct, then something else is overwriting Pure.

**Comment by andig** [comment]
It appears the order is right:

````
export ZSH=/Users/andig/.oh-my-zsh
autoload -U promptinit; promptinit
prompt pure
ZSH_THEME=""
plugins=(git)
source $ZSH/oh-my-zsh.sh
source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
````
So something else must be wrong :(

**Comment by andig** [comment]
It seems to be one of the additional `oh-my-zsh` config files:


	# Load all of the config files in ~/oh-my-zsh that end in .zsh
	# TIP: Add files you don't want in git to .gitignore
	for config_file ($ZSH/lib/*.zsh); do
	  custom_config_file="${ZSH_CUSTOM}/lib/${config_file:t}"
	  [ -f "${custom_config_file}" ] && config_file=${custom_config_file}
	echo $config_file
	#  source $config_file
	done

Couldn't find out yet which one though (or even how to enable/disable them apart from renaming):

	/Users/andig/.oh-my-zsh/lib/bzr.zsh
	/Users/andig/.oh-my-zsh/lib/clipboard.zsh
	/Users/andig/.oh-my-zsh/lib/compfix.zsh
	/Users/andig/.oh-my-zsh/lib/completion.zsh
	/Users/andig/.oh-my-zsh/lib/correction.zsh
	/Users/andig/.oh-my-zsh/lib/diagnostics.zsh
	/Users/andig/.oh-my-zsh/lib/directories.zsh
	/Users/andig/.oh-my-zsh/lib/functions.zsh
	/Users/andig/.oh-my-zsh/lib/git.zsh
	/Users/andig/.oh-my-zsh/lib/grep.zsh
	/Users/andig/.oh-my-zsh/lib/history.zsh
	/Users/andig/.oh-my-zsh/lib/key-bindings.zsh
	/Users/andig/.oh-my-zsh/lib/misc.zsh
	/Users/andig/.oh-my-zsh/lib/nvm.zsh
	/Users/andig/.oh-my-zsh/lib/prompt_info_functions.zsh
	/Users/andig/.oh-my-zsh/lib/spectrum.zsh
	/Users/andig/.oh-my-zsh/lib/termsupport.zsh
	/Users/andig/.oh-my-zsh/lib/theme-and-appearance.zsh

**Comment by mafredri** [comment]
You could start zsh with `zsh -x` (this enables XTRACE). You should see a whole lot out output printed to your terminal. You can go through this and search for `PS1=`, `PROMPT=` or `prompt=`. Should give you a hint as to where prompt is being overwritten =).

**Comment by andig** [comment]
You're a genius and here's the culprit: `~/.oh-my-zsh/lib/theme-and-appearance.zsh`

````
# Apply theming defaults
PS1="%n@%m:%~%# "
````

With that line removed I'm fine. Does that need to go into the integration instructions (different order of things)?

**Comment by mafredri** [comment]
Great =)!

> [...] Does that need to go into the integration instructions (different order of things)?

Absolutely, I was unaware that oh-my-zsh did this by default.

A correct order in your case would then be:

```zsh
export ZSH=/Users/andig/.oh-my-zsh
ZSH_THEME=""
plugins=(git)
source $ZSH/oh-my-zsh.sh
autoload -U promptinit; promptinit
prompt pure
source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
```
