### ISSUE TITLE
Newbie Question: Fail to install on macOS Sierra

### ISSUE THREAD

**Issue by dunkarooftop** [sindresorhus/pure#316]
I am new to this zsh world, I installed the zsh from homebrew then installed oh-my-zsh

After that I was trying to install "Pure-prompt" but run into the fallowing error. Did some googling but couldn't figure it out. Can someone shine me a light. Thanks !

zsh 5.3.1 (x86_64-apple-darwin16.3.0)
git version 2.11.0 (Apple Git-81)

```
Dunks-iMac:~ dunk$ npm i -g pure-prompt

> pure-prompt@1.5.2 postinstall /usr/local/lib/node_modules/pure-prompt
> PURE_DEST=/usr/local/share/zsh/site-functions npm run --silent postinstall-link && exit 0; PURE_DEST="$PWD/functions" npm run postinstall-link && npm run postinstall-fail-instructions

/usr/local/lib
└── pure-prompt@1.5.2 
```

**Comment by mafredri** [comment]
There's no error in the npm install, could you clarify?

**Comment by dunkarooftop** [comment]
You are right it installed correct, I was not sure what I was doing. After Set ZSH_THEME="pure" in my .zshrc file. looks nice in "iTerm" but how do I set it up in "Hyper" ? Thanks for the help, learning and experimenting here.

**Comment by anvil008** [comment]
Try initialising the prompt at the end of the  .zshrc file.

```
# .zshrc
autoload -U promptinit; promptinit
prompt pure
```

**Comment by dunkarooftop** [comment]
Yes, this does fix the problem. Thank you for the help !!
