### ISSUE TITLE
Promt initialization in prezto does not work

### ISSUE THREAD

**Issue by tleunen** [sindresorhus/pure#318]
How does it work to make zpresto use pure?

I have enable `pure` in my zpreztorc file:
```
zstyle ':prezto:module:prompt' theme 'pure'
```

But without these lines, it doesn't work.
```
autoload -U promptinit; promptinit
prompt pure
```

**Comment by mafredri** [comment]
Readme updated in c5876d3c4bc733ac6acdf3f96c17eaef7b242b62.
