### ISSUE TITLE
Virtualenv name no longer shown in prompt

### ISSUE THREAD

**Issue by rif** [sindresorhus/pure#320]
### General information

- Pure version: 4cdd0cf
- ZSH version: 5.3.1
- Terminal program & version: rxvt-unicode 9.22, sakura 3.3.4
- Operating system: arch linux
- ZSH framework: zgen

I have:
- [ x] Tested with another terminal program and can reproduce the issue: 
- [] Followed the [Integration](https://github.com/sindresorhus/pure#integration) instructions for my framework

### Problem description
The python virtualenv name used to be printed in the prompt after the activation using virtualenvwarapper, not it stopped working

### Reproduction steps

1. create a virtualenv
2. activate it
3. virtualenv name should appear in prompt

### My `.zshrc`:
```shell
zgen load mafredri/zsh-async
zgen load sindresorhus/pure
```

**Comment by mafredri** [comment]
Pure has never officially supported virtualenvs (e.g. #254) but it has worked since Pure used to handle the preprompt differently, now the preprompt is part of `PROMPT` (or `PS1`) which means the virtualenv is being set, but is cut off afterwards:

For example, this is what the prompt looks like after sourcing the virtualenv:

```
PS1=$'(my_virtualenv) \n%{\C-M%}%F{blue}%~%f %F{242}${prompt_pure_vcs_info[branch]}${prompt_pure_git_dirty}%f %F{cyan}${prompt_pure_git_arrows}%f\n%{\C-M%}%(?.%F{magenta}.%F{red})${PURE_PROMPT_SYMBOL:-❯}%f '
```

But what happens afterwards is that Pure cuts away the excess (everything before the last newline):

```
PS1=$'(?.%F{magenta}.%F{red})${PURE_PROMPT_SYMBOL:-❯}%f '
```

And then adds a new, clean preprompt.

I'll try to do something about this soon, in the meanwhile, here's a patch you could use that should bring back old behavior:

```patch
diff --git a/pure.zsh b/pure.zsh
index 78e048f..11adf7c 100644
--- a/pure.zsh
+++ b/pure.zsh
@@ -178,6 +178,9 @@ prompt_pure_precmd() {
 	# preform async git dirty check and fetch
 	prompt_pure_async_tasks
 
+	psvar[12]=
+	[[ -n $VIRTUAL_ENV ]] && psvar[12]="${VIRTUAL_ENV:t}"
+
 	# print the preprompt
 	prompt_pure_preprompt_render "precmd"
 
@@ -427,6 +430,9 @@ prompt_pure_setup() {
 	# Prevent percentage showing up if output doesn't end with a newline.
 	export PROMPT_EOL_MARK=''
 
+	# Disallow virtualenvs from updating the prompt.
+	export VIRTUAL_ENV_DISABLE_PROMPT=1
+
 	prompt_opts=(subst percent)
 
 	# borrowed from promptinit, sets the prompt options in case pure was not
@@ -463,7 +469,7 @@ prompt_pure_setup() {
 	[[ $UID -eq 0 ]] && prompt_pure_username='%F{white}%n%f%F{242}@%m%f'
 
 	# prompt turns red if the previous command didn't exit with 0
-	PROMPT='%(?.%F{magenta}.%F{red})${PURE_PROMPT_SYMBOL:-❯}%f '
+	PROMPT='%(12V.(${psvar[12]}) .)%(?.%F{magenta}.%F{red})${PURE_PROMPT_SYMBOL:-❯}%f '
 }
 
 prompt_pure_setup "$@"
```

**Comment by rif** [comment]
thanks, I confirm the patch is bringing the virtualenv name back.
I'll monitor your commits to remove the patch once you push a permanent fix.

BTW, I am using your prompt for more than two years now, it's exactly what I like in a prompt :)

Great work! 🥇

**Comment by mafredri** [comment]
> thanks, I confirm the patch is bringing the virtualenv name back.

Thanks for testing! However, I think we might take another approach (for now) with #321. In the future, Pure should support virtualenvs by itself, assuming we can land on a decision. If you have any input on how we should do this integration, feel free to check out #254.

It makes me happy to hear that Pure is exactly what you want 😄 , and I'm sure sindresorhus feels the same way!

**Comment by seemethere** [comment]
This was happening to me too, I thought I was going crazy.

**Comment by mafredri** [comment]
Yeah, sorry about that, don't wish to drive anyone into crazy-town 😅.

Fix is now merged, there should be no more sudden breakage once we officially add virtualenv support.
