### ISSUE TITLE
Set terminal window title temporarily by latexmk

### ISSUE THREAD

**Issue by kiryph** [sindresorhus/pure#324]
As a user of pure (configured through [zim](https://github.com/Eriner/zim)), the terminal window title is set by the prompt pure:

> - Shows the current path in the title and the current folder & command when a process is running.

I use the program [`latexmk`](http://ctan.org/pkg/latexmk) with the option `-pvc` which means it watches the tex file for changes and automatically starts a latex compilation if needed.

The tool latexmk can be configured by a perl script `latexmkrc` where you can put according to its documentation following functions, to change the terminal window title to report if it runs a compilation, successfully finished or failed:

```perl
$compiling_cmd = "xdotool search --name \"%D\" set_window --name \"%D compiling\"";
$success_cmd = "xdotool search --name \"%D\" set_window --name \"%D OK\"";
$failure_cmd = "xdotool search --name \"%D\" set_window --name \"%D FAILURE\"";
```
(http://mirrors.ctan.org/support/latexmk/latexmk.pdf#page=21)

Right now, they do not work.

I am on macOS 10.11 using iTerm2 v3.0.15 with zsh 5.0.8 (x86_64-apple-darwin15.0), zim (following master branch with last commit https://github.com/Eriner/zim/commit/4ad8f8db8e36b9eb9c58e92b8d7d48308f14f34a) and pure is on commit (217d56b). Of course there is no xdotool on macOS, however, the terminal title can be set by other means: either AppleScript or by the shell.

Could pure help/enable to setup the title by latexmk?

**Comment by mafredri** [comment]
I don't fully understand your setup here, but does it work with e.g:

```
$compiling_cmd = "print -n '\e]0;%D compiling\a'";
```

?

I don't think we want to support anything so specific as `latexmkrc` in Pure, but I'm quite sure you should be able to get this working without modifications to Pure.

**Comment by kiryph** [comment]
Thanks for your response.

My current problem has nothing to do with latexmk in particular, but how can I in general adjust the terminal window title temporarily.

Your suggested command does not work and I am not sure which part is reponsible for this.

If I run zsh via `zsh -f`, your command works.

zim itself suggests using the variable `ztermtitle`:
```sh
~/.zim master
❯ ag ztermtitle
modules/environment/init.zsh
52:if (($+ztermtitle)); then
55:      precmd() { print -Pn "\e]0;${ztermtitle}\a" }

modules/environment/README.md
8:Uses `.zimrc` defined `${ztermtitle}` variable to set the terminal title, if defined.

templates/zimrc
54:ztermtitle='%n@%m:%~'
```

However, as far as I understand, I can only set this variable in a init file. I am not interested in adjusting it in a shell init script but when the shell has already been started and I want to return to the default value when latexmk has finished.

My current suspicion is the `precmd()` which dynamically adjusts the terminal title which immediately overwrites the value of your command.
```sh
~/.zim master
❯ ag precmd  
modules/environment/init.zsh
55:      precmd() { print -Pn "\e]0;${ztermtitle}\a" }
56:      precmd  # we execute it once to initialize the window title

modules/prompt/external-themes/pure/async.zsh
76:	zsh_hooks=(chpwd periodic precmd preexec zshexit zshaddhistory)

modules/prompt/external-themes/pure/pure.zsh
104:	[[ -n ${prompt_pure_cmd_timestamp+x} ]] && [[ $1 != precmd ]] && return
157:	if [[ $1 != precmd ]] && [[ $prompt_pure_last_prompt != $expanded_prompt ]]; then
165:prompt_pure_precmd() {
180:	prompt_pure_preprompt_render "precmd"
182:	# remove the prompt_pure_cmd_timestamp, indicating that precmd has completed
447:	add-zsh-hook precmd prompt_pure_precmd
```

**Comment by mafredri** [comment]
Yes, pure sets the title during both when starting a command and before displaying the prompt, this is as intended.

If you wish to temporarily or completely opt out of this behavior, there's a workaround / hack in https://github.com/sindresorhus/pure/pull/164#issue-107687118. Keep in mind it's not officially supported and might break at any point 😉.

**Comment by kiryph** [comment]
This looks exactly what I was looking for.

However, configuring latexmk correctly is not that easy.

Naively, one could try:
```perl
$compiling_cmd = 'orig_set_title="$(whence -f prompt_pure_set_title)";pure_restore_set_title() { eval "$orig_set_title" }; prompt_pure_set_title() { print -n "\e]0;%D compiling\a" }';
$success_cmd = "prompt_pure_set_title() { print -n '\e]0;%D OK\a' };pure_restore_set_title";
$failure_cmd = "prompt_pure_set_title() { print -n '\e]0;%D FAILED\a' };pure_restore_set_title";
```

However, the perl script invokes `/bin/sh` and not the zsh shell latexmk is running in.

```
$compiling_cmd = 'echo "$0"'
```
shows
```
sh
```
as output.

In order to get the correct original pure zsh function, following works

```
orig_set_title="$(zsh -i -c \'whence -f prompt_pure_set_title\')";
```

Since this is written in zsh, restoring should also do the z shell.
```
pure_restore_set_title() { zsh -i -c \`eval "$orig_set_title"\' };
```

BTW:
escaping hell can be reduced by setting `$quote_filenames = 0;` otherwise there are additional double quotes around `%D`.

With following defintions in latexmkrc:
```perl
$quote_filenames = 0;
$compiling_cmd = 'orig_set_title="$(zsh -i -c \'whence -f prompt_pure_set_title\')";pure_restore_set_title() { zsh -i -c \'eval "$orig_set_title"\' };prompt_pure_set_title() { print -n "\e]0;%D compiling\a" }';
$success_cmd = 'prompt_pure_set_title() { print -n "\e]0;%D OK\a" };pure_restore_set_title';
$failure_cmd = 'prompt_pure_set_title() { print -n "\e]0;%D FAILED\a" };pure_restore_set_title';
```
I get following output:
```
❯ latexmk -pvc filename.tex
Latexmk: This is Latexmk, John Collins, 19 Jan. 2017, version: 4.52c.
Viewing pdf
------------
Running 'orig_set_title="$(zsh -i -c 'whence -f prompt_pure_set_title')";pure_restore_set_title() { zsh -i -c 'eval "$orig_set_title"' };prompt_pure_set_title() { print -n "\e]0;filename.pdf compiling\a" }'
------------
sh: -c: line 1: syntax error: unexpected end of file
Latexmk: All targets (filename.pdf) are up-to-date
Latexmk: I have not found a previewer that is already running.
   So I will start it for 'filename.pdf'
------------
For rule 'view', running '&if_source(  )' ...
------------
Running 'start open -a Skim  poissons_ratio_vs_bulk_over_shear_all_condensed_matter.pdf'
------------
------------
Running 'prompt_pure_set_title() { print -n "\e]0;filename.pdf OK\a" };pure_restore_set_title'
------------
sh: -c: line 1: syntax error: unexpected end of file

=== Watching for updated files. Use ctrl/C to stop ...
```

As you can see there are issues regarding correct shell syntax. I am not too experienced with this.

If you can easily see what is going wrong, I would be happy to get a hinter. Otherwise, I will give up right now.

**Comment by mafredri** [comment]
@kiryph my original suggestion should work fine with latexmk since it's constantly running, this means that Pure will not interfere with it's title until you press Ctrl+C. That was the idea at least, did you try this? In other words, as long as a command is running, Pure will not modify the title.

To use the `print`, however, you still need to run it in `zsh` or find a `sh` / `bash` alternative:

```
$compiling_cmd = "zsh -c \"print -n '\e]0;%D compiling\a'\""
```

**Comment by kiryph** [comment]
@mafredri Thank you very much. That was easier than expected:

```perl
$compiling_cmd = 'zsh -c "print -n \"\e]0;%D compiling\a\""';
$success_cmd = 'zsh -c "print -n \"\e]0;%D OK\a\""';
$failure_cmd = 'zsh -c "print -n \"\e]0;%D FAILED\a\";"';
```

### success_cmd
Note, the success command can be misleading: if you stepped over errors messages and do not resolve them, latexmk will run successfully the next time because all checksums are the same and will not compile which would return the error again. I do not know, if latexmk offers a possibililty to mark the texfile as erroneous and on the next run latexmk can report correctly that one must resolve outstanding errors by changing the texfile.

### failure_cmd
Also note about the failure command: latex/latexmk runs by default in interactive mode, that means as soon as an error shows up, a prompt is shown where the user can do something about it. However, this means latexmk status is still on compiling and it will not invoke the $failure_cmd. However, if you like to be informed you can do following:
1. Invoke latexmk with `latexmk -pvc -interaction=nonstopmode -halt-on-error` and e.g. add call the bell which will tell you that something went wrong:
```
$failure_cmd = 'zsh -c "print -n \"\e]0;%D FAILED\a\";tput bel;"';
```
or send a message to the notification center of macOS by `osascript -e 'display notification "Compilation %D failed." with title "latexmk FAILED"'`
2. A second possibility is to use a feature of iTerm2.app which detects the latex prompt `^\?` and runs a Trigger:
![trigger-iterm2 app](https://cloud.githubusercontent.com/assets/371756/25812932/31ebfc4c-3418-11e7-8058-d0be0b564b39.png)
