### ISSUE TITLE
Directory disappears when clearing (CMD+K)

### ISSUE THREAD

**Issue by vebjorni** [sindresorhus/pure#329]
When using CMD+K for clearing the terminal the blue directory info disappears as in the image below. I am using Hyper terminal v1.3.3.

<img width="638" alt="screen shot 2017-06-30 at 14 01 00" src="https://user-images.githubusercontent.com/9068991/27734737-92501782-5d9c-11e7-95ce-97b60766e734.png">

I don't know if this is a zsh thing or Pure thing tho.

**Comment by mafredri** [comment]
Cmd+K is not part of either Pure or Zsh, it's a Hyper feature (`Edit > Clear`). I can't reproduce this with Hyper v1.3.3 with either Pure v1.5.2 or current master though. Pre-prompt is always left visible.

My guess is that either a Hyper plugin, or your zsh configuration is causing this behavior?

**Comment by mafredri** [comment]
Actually, it seems in Hyper `Cmd+K` simply issues `Ctrl+L` (clear screen, part of Zsh). So you have a custom clear screen widget?

**Comment by vebjorni** [comment]
Using `clear` works fine, but `Ctrl+L` or `Cmd+K` does not work. I do not have a custom clear screen widget. My zsh and oh-my-zsh is pretty standard.

**Comment by mafredri** [comment]
If `Ctrl+L` is not working, then either something is overriding or disabling it in your zshrc or a Hyper plugin/config is doing it.

We can't really help you with that, but feel free to post your solution when you find it, or re-open if you discover that there is a problem with Pure.

**Comment by vebjorni** [comment]
I meant that `Ctrl+L` is working and clearing the screen, but it also clears the preprompt. Using `clear` does not clear the prepromt. Thanks anyway and will post the solution if I find it.

**Comment by mafredri** [comment]
Ah, I misunderstood. Still, I can't reproduce this issue in Hyper. The preprompt is never cleared for me. Maybe oh-my-zsh is the cause, I don't use any framework.

For comparison, on iTerm the preprompt will be cleared by `Cmd+K`, this is as it should be and there's nothing that can be done about it (it's how iTerm works). But `Cmd+K` in Hyper is simply an alias to `Ctrl+L`, very different from iTerm.

**Comment by vebjorni** [comment]
It probably was oh-my-zsh. I uninstall it (realized that I really don't need it) and now `Cmd+K` and `Ctrl+L` clears as intended. Thanks @mafredri!
