### ISSUE TITLE
[HELP] Can't install the theme correctly.

### ISSUE THREAD

**Issue by brijeshjain13** [sindresorhus/pure#339]
### General information

- Pure version: 1.5.2 (latest clone)
- ZSH version: 5.1.1
- Terminal program & version: Gnome terminal (default terminal of ubuntu)
- Operating system: Ubuntu 16.04.2 LTS
- ZSH framework: oh-my-zsh

### Reproduction steps

1. First cloned the repo
2. ln -s "$PWD/pure.zsh" /usr/local/share/zsh/site-functions/prompt_pure_setup
3. ln -s "$PWD/async.zsh" /usr/local/share/zsh/site-functions/async
4. Added fpath=( "$HOME/.zfunctions" $fpath ) to .zshrc
5. ln -s "$PWD/pure.zsh" "$HOME/.zfunctions/prompt_pure_setup"
6. ln -s "$PWD/async.zsh" "$HOME/.zfunctions/async"
7. Change to ZSH_THEME="refined" in .zshrc

### My `.zshrc`:

fpath=( "$HOME/.zfunctions" $fpath )
export ZSH=/home/vicky/.oh-my-zsh
ZSH_THEME="refined"

Link to the current looking terminal: http://imgur.com/zC4tBkq. Can't solve it, please help.

**Comment by mafredri** [comment]
Don't set `ZSH_THEME="refined"`, refined has nothing to do with Pure.

You should set `ZSH_THEME=""` and follow the regular install instructions for Pure.

Good luck!
