### ISSUE TITLE
Use `typeset -g` for global variables in functions

### ISSUE THREAD

**Issue by kutsan** [sindresorhus/pure#345]
### General information

- Pure version: HEAD 4082418e4feffd876e0f666aa5cfbd7d3360ed16
- ZSH version: 5.4.1
- ZSH framework: -

### Problem description

Please use `declare -g` ( or `typeset -g`, it's the same) to declaring global variables in functions. So, people who set `setopt WARN_CREATE_GLOBAL` won't get warning like such:

```
prompt_pure_check_cmd_exec_time:3: scalar parameter prompt_pure_cmd_exec_time created globally in function prompt_pure_check_cmd_exec_time
prompt_pure_check_cmd_exec_time:4: scalar parameter PURE_CMD_MAX_EXEC_TIME created globally in function prompt_pure_check_cmd_exec_time
prompt_pure_precmd:6: scalar parameter prompt_pure_cmd_timestamp created globally in function prompt_pure_precmd
prompt_pure_async_tasks:7: scalar parameter prompt_pure_async_init created globally in function prompt_pure_async_tasks
prompt_pure_preprompt_render:63: scalar parameter prompt_pure_last_prompt created globally in function prompt_pure_preprompt_render
```

### Reproduction steps

1. Wrote `setopt WARN_CREATE_GLOBAL` in `.zshrc`.
2. Reload `.zshrc`.
3. Errors appeared.

**Comment by mafredri** [comment]
Thanks, it's a good suggestion. I was in the process of changing this at some point, but it lies dormant in one of my git stashes 😛. I'll fix this soon!

**Comment by kutsan** [comment]
Thanks! Please do that `setopt WARN_NESTED_VAR` too.

**Comment by mafredri** [comment]
I'll consider it, but I'm not making any promises. These warn options are mostly useful for development and shouldn't be enabled in day-to-day use (IMO). Sometimes setting nested vars is the wanted effect.

**Comment by kutsan** [comment]
Well, you can still use nested vars if you want to with `typeset -g`, and it won't make it global, it just suprese the error. Consider this example.

```sh
setopt WARN_NESTED_VAR

function toplevel() {
	local foo="in toplevel"
	nested
}

function nested() {
	echo $foo # "in toplevel"

	foo="in nested" # nested:3: scalar parameter foo set in enclosing scope in function nested in nested

	declare -g foo="in nested"
	declare -g bar="global"

	echo $foo # "in nested"
}

toplevel

echo $foo # ""
echo $bar # "global"

```

**Comment by mafredri** [comment]
Just pushed #347, can you confirm that it fixes your issues with `warn_create_global`? I opted for doing nothing about `warn_nested_var` although I'm not totally against it, but I would need to understand / see how making the changes necessary improves the code.

**Comment by kutsan** [comment]
Thanks! It looks okay now, all of my errors are gone.

**Comment by kutsan** [comment]
@mafredri 

https://github.com/sindresorhus/pure/blob/a95d55cc7d3a73fc562ac11e23c26113ed6d58cf/pure.zsh#L402

I get errors about this variable.

**Comment by mafredri** [comment]
Thanks for the report @kutsan, pushed a fix to master. Missed this one because I didn't have any unpushed/pulled commits when I tested this.

**Comment by kutsan** [comment]
No problem! Thanks for quick fix! I really appreciate it.

**Comment by kutsan** [comment]
By the way, the reason why it took so long to realize that it's because prompt was redrawing itself before I saw that error. Somehow, it appeared when I am messing with tmux panes. I would have told you if I saw that before. So, I'm sorry.

**Comment by mafredri** [comment]
There’s absolutely no need to be sorry. It was good that this was caught now. 🙂

**Comment by kutsan** [comment]
And again.

![](https://i.imgur.com/7ZTUgy8.jpg)

I think you need to silence them with:

```sh
local match=
local mbegin=
local mend=
```

**Comment by mafredri** [comment]
@kutsan thanks, fix is live on master!
