### ISSUE TITLE
Does pure sanitize the git branch string of a repository before displaying it?

### ISSUE THREAD

**Issue by DictumMortuum** [sindresorhus/pure#346]
From [this](http://www.oilshell.org/blog/2017/09/19.html) blog post:

> In short, many developers display the current git branch in their bash prompt (including me). An attacker could create a branch name that would cause git-prompt.sh to execute arbitrary code:
> Here's a proof a concept:
> - https://github.com/njhartwell/pw3nage
> (Note: I didn't try this code.)

**Comment by mafredri** [comment]
Pure should be safe. We do not sanitize, but we also do not perform substitution multiple times which guards against e.g. `pw3nage`. It's something we keep in mind when making changes.

Security issues like these are taken seriously though, so if you find any, please report them 🙂!
