### ISSUE TITLE
Remove the pre-prompt

### ISSUE THREAD

**Issue by vebjorni** [sindresorhus/pure#348]
Hi.

I tried looking for a similar question, but couldn't find any.

How can I modify pure.zsh to remove the pre-prompt that shows current directory and git branch?

Thanks!

**Comment by mafredri** [comment]
Why would you use Pure without the prerompt?

**Comment by vebjorni** [comment]
I am using the hyper-statusline plugin and the pre-prompt then become redundant for me.

**Comment by mafredri** [comment]
The preprompt also shows: username/host, and execution time which would be lost if you remove the preprompt. It sounds like you're better of with starting from scratch or using a different prompt since you are not using any of Pure's features.

**Comment by vebjorni** [comment]
Ahh, didn’t think of it that way, thanks!
