### ISSUE TITLE
clearing the screen eats the first line

### ISSUE THREAD

**Issue by deadc0de6** [sindresorhus/pure#355]
### General information

- Pure version: 1.5.2
- ZSH version: 5.3.1
- Terminal program & version: rxvt-256color v9.22
- Operating system: debian stretch
- ZSH framework: prezto

I have:
- [x] Tested with another terminal program and can reproduce the issue: xterm, terminator

### Problem description

When clearing the screen with `CTRL+l` the first line of the prompt gets eaten. When using `clear` it doesn't.

### Reproduction steps

1. `CTRL-l`

### My `.zshrc`:

N/A

**Comment by mafredri** [comment]
I can't reproduce this issue. I've tried with a clean prezto setup (only ran `prompt pure` afterwards) in rxvt-unicode 9.22 and xterm.

Could you:
1. Try changing the font, does it have any effect?
2. Make sure `^C` sent to the terminal, e.g. no changes in `~/.xinputrc`
3. Try updating to zsh 5.4.2?
4. Try Pure without prezto to make sure there are no conflicting settings.

Assuming you have the tools, step 3 is easy even if it's not available in your package manager:

```
curl -L https://downloads.sourceforge.net/project/zsh/zsh/5.4.2/zsh-5.4.2.tar.gz | gzip -d | tar -xf - && cd zsh-5.4.2 && ./configure --prefix="$PWD/build" && mkdir build && make && make install && ./build/bin/zsh
```

**Comment by deadc0de6** [comment]
Thanks!

Changing fonts doesn't have any effect. I can also reproduce that on arch linux with termite, xterm and urxvt (with zsh 5.4.2).

I have nothing in my `~/.xinputrc`.

I noticed that other two-lines prompts on pretzo like [garrett](https://github.com/chauncey-garrett/zsh-prompt-garrett) and `superlinh` also eat the first line with `CLTR+l` while `geddie`, `fade` or `bigfade` for example don't.

I'll test pure without pretzo to see if it changes something.

It might well be linked to my configs but I'm unable to finger which one is affecting the prompt like this.

**Comment by deadc0de6** [comment]
opened an issue on pretzo related to this: https://github.com/sorin-ionescu/prezto/issues/1487

**Comment by deadc0de6** [comment]
@belak gave a potential reason for the issue here: https://github.com/sorin-ionescu/prezto/issues/1487#issuecomment-336807769

**Comment by deadc0de6** [comment]
so using the master branch works but raises an error
```
❯ echo 'test'
test

~
❯ 
prompt_pure_async_callback:10: bad set of key/value pairs for associative array

~
❯ 
```

I have then two questions:

* any idea what the error is and how to fix it ?
* will you release a new version of pure handling `CTRL+l` correctly or should I temporarly move to the master branch ?

thanks for your help

**Comment by mafredri** [comment]
@deadc0de6 sorry for being so slow getting back to you. I've just pushed a new release of Pure, hopefully it will sort out your issues. If anything is still acting up, let me know (e.g. the `prompt_pure_async_callback` function).

**Comment by deadc0de6** [comment]
Thanks ! I can confirm that version 1.6.0 does not eat the first line with `CTRL+l` anymore.

**Comment by samuelecioni** [comment]
For me this is happening again.

**Comment by mafredri** [comment]
@samuelecioni please open a new issue. We'll also need to know more about your setup, so e.g. your .zshrc. It would be very helpful if you can try to remove stuff from your zshrc until you have the least amount of code that reproduces the issue.
