### ISSUE TITLE
Space between start line?

### ISSUE THREAD

**Issue by jacc** [sindresorhus/pure#359]
Really sorry to not follow the format, I figured it was a cosmetic issue and not a bug.

Is there any reason that after installing Pure there would be a space between the start up line?\

My .zshrc is as shown:

```shell
fpath+=($fpath '/usr/local/lib/node_modules/pure-prompt/functions')
autoload -U promptinit; promptinit
prompt pure
```

Using Hyper on macOS.

**Comment by mafredri** [comment]
I'm not certain I understand what you're asking, but if it's what I think it is, does https://github.com/sindresorhus/pure/issues/233 answer your question?

**Comment by jacc** [comment]
looks like this: https://cdn.jack.ga/term.png

**Comment by jacc** [comment]
yeah @mafredri #233 didn't answer my question, sorry

**Comment by mafredri** [comment]
Sorry, I still don’t see it, screenshot looks ok to me. What exactly is the problem?

**Comment by angganegara** [comment]
@mafredri I have this problem as well. check my screenshot, hopefully it's clear? https://imgur.com/a/vp8zD

I think this is intentional?

**Comment by mafredri** [comment]
@angganegara I don't think that's the same issue, the answer to why it's like that lies in #233.

**Comment by angganegara** [comment]
Ah ok thanks for pointing that out. It doesn't really bother me either way.

**Comment by jacc** [comment]
@mafredri just wondering, because the terminal in the screenshot for Pure doesn't look like that, figured that there was something wrong with my computer. thank you!

**Comment by mafredri** [comment]
@jacc to me your screenshot is identical to the Pure screenshot in the readme (where it matters anyway, and when it comes to Pure behavior). If you want an answer you need to properly explain what part seems wrong / out of place.

**Comment by mafredri** [comment]
Closing due to age/lack of updates. Feel free to re-open if there’s something left to discuss.
