### ISSUE TITLE
Output of widget gets cut off

### ISSUE THREAD

**Issue by Alok** [sindresorhus/pure#361]
Posting on here because disabling the prompt stops the issue.

```zsh
ls-widget() {
  # Command gets drawn in prompt region, so we force a newline to make it readable. 
  echo
  ls
  zle redisplay
}
```

The last line of the output often isn't printed.

**Comment by sindresorhus** [comment]
Is this with the latest version (1.6.0)? Can you try this commit https://github.com/sindresorhus/pure/commit/03a81d07d14ecd55a2ebffbb220fe7b501b26ed6 and see if it's still an issue?

**Comment by Alok** [comment]
I'm using the async-render-fix branch

**Comment by Alok** [comment]
That commit still shows the issue. If I mash the keybinding for this widget, it shows the missing lines flickering past, but they disappear.

**Comment by mafredri** [comment]
You need to make room for the prompt. Redisplay will render it in-place which means moving upwards to erase the previous prompt. Adding two newlines should fix your issue.

```zsh
ls-widget() {
  print
  ls
  print $'\n'
  zle redisplay
}
```
