### ISSUE TITLE
Tab completion eats the two-lines prompt

### ISSUE THREAD

**Issue by deadc0de6** [sindresorhus/pure#362]
### General information

- Pure version: 1.6.0
- ZSH version: 5.3.1
- Terminal program & version: urxvt v9.22
- Operating system: Debian/stretch
- ZSH framework: prezto

I have:
- [x] Tested with another terminal program and can reproduce the issue

### Problem description

Auto-completion eats the two-lines prompt.

### Reproduction steps

1. type a command, for example `ls<space>`
2. type `tab` to complete
3. the two lines prompt gets eaten

before:
![before](https://user-images.githubusercontent.com/8973919/32157629-e33fbaaa-bd44-11e7-8355-81506427bba5.png)

after:
![after](https://user-images.githubusercontent.com/8973919/32157642-fa883f7a-bd44-11e7-8a7b-a14274ad9291.png)

this does not happen when issuing `cd /tm<tab>` for example.

**Comment by deadc0de6** [comment]
Also this only happens with version 1.6.0 as version 1.5.2 is not affected

**Comment by mafredri** [comment]
I can't reproduce this at least in my setup, I'll try to reproduce with prezto later. Can you test if this is reproducible in zsh 5.4.2?

**Comment by deadc0de6** [comment]
it works correctly on zsh 5.4.2 with 1.6.0 and pretzo

**Comment by deadc0de6** [comment]
I'll have to get latest version of zsh then, thanks for your help !

**Comment by mafredri** [comment]
I had a hunch that this was the case, I managed to reproduce with zsh-5.3.1 and prezto. The offender is the `expand-or-complete-with-indicator` widget, part of the `editor` module. You should be able to keep using zsh 5.3.1 if you comment out [these two lines](https://github.com/sorin-ionescu/prezto/blob/4b0ecffacadec6c9553be894cdcd36ecafac7662/modules/editor/init.zsh#L366-L367).

Not sure why it works in zsh-5.4.2 though `¯\_(ツ)_/¯`.

**Comment by deadc0de6** [comment]
ok cool, thanks I'll try that :+1:
