### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by gatspy** [sindresorhus/pure#367]
prompt_pure_preprompt_render:53: command not found: git_info_for_prompt

### General information

- Pure version: 1.6.0
- ZSH version: 5.4.2
- Terminal program & version: iTerm 3.0.15
- Operating system: macOS Sierra 10.12.6
- ZSH framework: antibody

**Comment by mafredri** [comment]
This error is not coming from Pure. I suspect you have modified PS1/PROMPT manually or some plugin is doing it.

Searching for `git_info_for_prompt` should provide some clues.
