### ISSUE TITLE
ZSH not automatically starting after Pure installation

### ISSUE THREAD

**Issue by jacc** [sindresorhus/pure#369]
I figure I didn't need to follow the format for something so small, but ever since installing Pure, I have to manually run `zsh` to boot into ZSH. I just restored my computer but my old terminal used to automatically boot into ZSH. What am I doing wrong?

**Comment by mafredri** [comment]
I’m pretty sure this is related to you restore, not to Pure. You need to change your users default shell. But you’ve not really given any information here, otherwise I might’ve been able to give a better hint. 

Good luck!
