### ISSUE TITLE
Cursor jumps few lines up, when hitting tab to complete.

### ISSUE THREAD

**Issue by vbauerster** [sindresorhus/pure#372]
When I type `cd` then hit <kbd>Tab</kbd> to view suggestions, the cursor suddenly jumps few lines up.

[![Screen_Shot_2017-11-26_at_12.25.18.png](https://s25.postimg.org/h9fvls94v/Screen_Shot_2017-11-26_at_12.25.18.png)](https://postimg.org/image/w5eetdkjf/)

  - ZSH version: `zsh 5.4.2 (x86_64-apple-darwin17.0.0)`
  - OS information: `macOS 10.13.1 (17B48)`
  - ZSH version: `zsh 5.4.2 (x86_64-apple-darwin17.0.0)`
  - Terminal program & version: `iTerm Build 3.1.5.beta.2`, same in Terminal.app
  - Operating system: `macOS 10.13.1 (17B48)`
  - ZSH framework: `prezto`

Regarding `pure` versions:

I can confirm the issue appears in 4cdd0cf.
Before that commit, it's ok.

At first I've [reported](https://github.com/sorin-ionescu/prezto/issues/1512) it to `prezto`, but looks like problem in `pure` theme.

So far I've checked out to tag `v1.5.2`, as workaround.

**Comment by mafredri** [comment]
Have you tried master? If not, could you? This commit might fix your issue a3b22b242d2e4bc8d7e989c47e49a4bf03d7e2ab. Keep in mind this also requires the lastest zag-a sync, so you might need to update that as well.

**Comment by vbauerster** [comment]
Switching to master a3b22b2 didn't help. How do I check/update zag-a sync?

**Comment by mafredri** [comment]
Sorry, that was supposed to be zsh-async (not zag-a sync), thanks autocorrect.

**Comment by vbauerster** [comment]
The issue still persist, despite `prezto` framework have upgraded zsh async module to tag `v1.6.0` recently.

**Comment by mafredri** [comment]
Alright, then I believe https://github.com/sindresorhus/pure/issues/362 could be related. Can you try the suggested workaround in https://github.com/sindresorhus/pure/issues/362#issuecomment-340508207?

**Comment by vbauerster** [comment]
I confirm commenting out `expand-or-complete-with-indicator` fixed the problem.

**Comment by mafredri** [comment]
Ok, that's great (and bad) news. Great that we know how to avoid it, but bad as in I don't have a solution for this. The problem likely stems from the fact that Pure is a multi-line prompt (includes newlines in `$PROMPT`) and prezto is calling `zle redisplay` while completion is active. I believe this state confuses ZLE and might actually be a bug in Zsh (e.g. cursor outside editing buffer and prompt is multi-line).

**Comment by mafredri** [comment]
This should now be fixed, as per https://github.com/sorin-ionescu/prezto/issues/1512.
