### ISSUE TITLE
How to get rid of PROMPT

### ISSUE THREAD

**Issue by bzd111** [sindresorhus/pure#374]
General information

Pure version: 1.5.2
ZSH version: 5.0.2
Operating system: CentOS Linux release 7.4.1708 (Core)

I have installed Pure,but PS1 and PROMPT is not some with screenshot.png .
How to modify can be consistent with your.

![pure](https://user-images.githubusercontent.com/18071885/33669175-b1feea78-dadc-11e7-876e-ab3030b18614.jpg)

**Comment by aoc** [comment]
It seems you're using oh-my-zsh. Did you follow integration instructions from the readme?

### [oh-my-zsh](https://github.com/robbyrussell/oh-my-zsh)

1. Set `ZSH_THEME=""` in your `.zshrc` to disable oh-my-zsh themes.
2. Follow the Pure [Install](#install) instructions.

**NOTE:** `oh-my-zsh` overrides the prompt so Pure must be activated *after* `source $ZSH/oh-my-zsh.sh`.

**Comment by mafredri** [comment]
Closing due to age.
