### ISSUE TITLE
Prompt eats output

### ISSUE THREAD

**Issue by yevhen-m** [sindresorhus/pure#377]
### General information

- Pure version: 1.6.0
- ZSH version: 5.4.2
- Terminal program & version: iTerm 3.1.5
- Operating system: macOS Sierra 10.12.6
- ZSH framework: prezto

### Problem description
Prompt eats up output without trailing newline:
<img width="310" alt="screen shot 2018-01-14 at 16 00 13" src="https://user-images.githubusercontent.com/10185058/34916632-1bec3f0a-f944-11e7-94ed-160ff8210f45.png">

**Comment by mafredri** [comment]
Please see #376.

**Comment by belak** [comment]
We recently pushed a fix to prezto. If you're still seeing problems with the latest prezto commit, please let me know and we can continue to investigate.

**Comment by yevhen-m** [comment]
@belak thanks. My issue has been solved.
