### ISSUE TITLE
Hostname not showing in the window title after sudo su -

### ISSUE THREAD

**Issue by joscherrer** [sindresorhus/pure#382]
### General information

- Pure version: 1.6.0
- ZSH version: 5.0.2
- Terminal program & version: PuTTY 0.70 & KiTTY 0.70
- Operating system: Windows 10
- ZSH framework: oh-my-zsh

### Problem description

The window's title doesn't show the hostname when sudoing from a user.

### Reproduction steps

1. Connect to a server with a regular user
2. sudo su -
3. The hostname is not showing anymore in the window title

With a regular user :
![image](https://user-images.githubusercontent.com/37024758/37054871-6e8a31f4-2180-11e8-92bf-0dae4c0d93e2.png)

After sudo su - :
![image](https://user-images.githubusercontent.com/37024758/37054917-96451358-2180-11e8-8ad5-3be461b4e564.png)

### My `.zshrc`:

```shell
autoload -U promptinit; promptinit
prompt pure
```

**Comment by mafredri** [comment]
Pure detects that it's running on a remote host by checking the `$SSH_CONNECTION` environment variable. There's no way to detect it after `sudo su -` because it cleans out the environment variables.

Not sure there's anything we can do here. But I can leave it open for a while in case anyone else has any ideas.

**Comment by joscherrer** [comment]
I have two ideas for this problem :

1. In the /etc/sudoers file, manually add the SSH_CONNECTION variable to env_keep, but it's specific to every server and it might not be done by pure as it seems a bit intrusive :
`Defaults env_keep +=SSH_CONNECTION`
 It can be done by editing the file with visudo or creating a file in /etc/sudoers.d to add the line
2. Check the SSH connection with who am i instead of SSH_CONNECTION:
`if [[ $(who am i) =~ \([-a-zA-Z0-9\.]+\)$ ]] ; then echo SSH; else echo no; fi`
 But it seems like it's not working with tmux and the regex should be redone to match also IPv6 addresses : [Source](https://unix.stackexchange.com/questions/9605/how-can-i-detect-if-the-shell-is-controlled-from-ssh)

Both solutions work perfectly for my problem

**Comment by mafredri** [comment]
@joscherrer thanks for the suggestions.

1. This is definitely something our users can do, but it's not something we should recommend or even suggest (IMO, no theme should ask you to make changes to sudoers)
2. A good suggestion, but I wonder how cross-platform it is. At least on Debian/macOS the outputs differ (albeit both end with IP `(0.0.0.0)`).

macOS: `maf      ttys003  Mar 12 23:57 	(192.168.X.X)`
Debian: `maf      pts/7        2018-03-12 23:57 (192.168.X.X)`

In principle we *could* try to parse `who am i` once, when Pure is initialized and `$SSH_CONNECTION` is not set. The downside of this is that we're "slowing down" the initial startup of Pure (for the most common use case) by opening a subshell we didn't need to.

**Comment by mafredri** [comment]
@joscherrer I would be happy if you could give #393 a try!
