### ISSUE TITLE
This SYMBOL does not appear ❯

### ISSUE THREAD

**Issue by MAPESO** [sindresorhus/pure#385]
@sindresorhus 

 

### General information

- Pure version: command not found: pure-prompt
- ZSH version: 5.3
- Terminal program & version: Hyper Canary 14
- Operating system: macOS Sierra 10.13.3
- ZSH framework: none

### Problem description
I have already done all the steps to install it, but the sibolo does not appear :/
### Reproduction steps

1. npm install --global pure-prompt
2. vim .zshrc

### My `.zshrc`:

```shell
autoload -U promptinit; promptinit
prompt pure
ZSH_THEME=""
```
![screen shot 2018-03-19 at 224238](https://user-images.githubusercontent.com/16585386/37636403-a0c507c4-2bc7-11e8-826c-7334fbe03719.png)

**Comment by sindresorhus** [comment]
Please follow the issue template: https://github.com/sindresorhus/pure/blob/master/.github/issue_template.md :)

**Comment by MAPESO** [comment]
@sindresorhus done 😄

**Comment by mafredri** [comment]
> ZSH framework: none

Are you sure you're not using oh-my-zsh? Pure must be initialized *after* oh-my-zsh as per the note in the readme.

**Comment by MAPESO** [comment]
@mafredri if I have it installed :)

![screen shot 2018-03-20 at 014120](https://user-images.githubusercontent.com/16585386/37641592-00f9e78c-2be0-11e8-9838-7bc2d2be4c58.png)

**Comment by MAPESO** [comment]
@sindresorhus @mafredri  I've been trying to solve this problem for hours

**Comment by salmanulfarzy** [comment]
It's loading `prompt_purity_setup` and not `prompt_pure_setup`. Please make sure you have `prompt_pure_setup` under `/usr/local/share/zsh/site-functions`

**Comment by MAPESO** [comment]
@salmanulfarzy could you help me install the files :(
