### ISSUE TITLE
How to set color for path and git info?

### ISSUE THREAD

**Issue by julenpardo** [sindresorhus/pure#389]
The default colors are really dark for by terminal background. After searching for a while in the issues and making some tries I wasn't able to figure it out.

Thanks in advance and thank you for the awesome project.

**Comment by sudo-nice** [comment]
I think, colors are not customizable at the moment. Relevant issue: https://github.com/sindresorhus/pure/issues/306

**Comment by julenpardo** [comment]
@sudo-nice Thanks for your response.

I thought it would be possible since in the screenshot of the README the path info looks definitively brighter than what I see in my terminal (which actually doesn't fit very well with my color scheme).

![https://github.com/sindresorhus/pure/raw/master/screenshot.png](https://github.com/sindresorhus/pure/raw/master/screenshot.png)

And in my terminal:

![zsh](https://user-images.githubusercontent.com/12843626/39690755-7a887642-51db-11e8-84f9-d1504f1c3acd.png)

**Comment by davidparsson** [comment]
@julenpardo, the README also says:
> In the screenshot you see Pure running in Hyper with the hyper-snazzy theme and Menlo font.

The snazzy theme modifies the default colors of the terminal.

**Comment by alecsgone** [comment]
@julenpardo how do you get the `cd` highlight with green ? (I was able to match the colors with iterm2 but `cd` or other commands don't appear to be highlighted) 

![screen shot 2018-08-12 at 2 37 37 pm](https://user-images.githubusercontent.com/1099589/44005710-65d1edec-9e3d-11e8-99af-d59798001e5b.png)

**Comment by davidparsson** [comment]
@alecsgone, from the readme:

> To have commands colorized as seen in the screenshot, install zsh-syntax-highlighting.
