### ISSUE TITLE
Duplication of the first letter on tab completion

### ISSUE THREAD

**Issue by ahmedelgabri** [sindresorhus/pure#39]
After upgrading to Mavericks I'm having this problem that when I try to autocomplete a command it duplicates the first letter of it.

`$ g<tab>` becomes `$ ggit` instead of `$ git` & when I click backspace the first letter stays like this `$ g`

When I removed Pure everything worked normally.

So, how can I fix this?

**Comment by DaZzz** [comment]
If anyone is having this problem in iTerm 3.0 here is what I did to fix it. Go to `iTerm Preferences > Profiles > Text` and tick `Use Unicode Version 9 Width`. 

![image](https://user-images.githubusercontent.com/2707291/32367050-c47508be-c091-11e7-892d-efbfde8a7e24.png)
