### ISSUE TITLE
Shows the current path

### ISSUE THREAD

**Issue by gregcousin126** [sindresorhus/pure#394]
is there a way to remove "Shows the current path" feature to have more space in terminal?

**Comment by mafredri** [comment]
You don't wish to know which directory you're in? What would you show instead?

If long names are a problem, you could consider: [Create aliases for really long directory paths](https://github.com/sindresorhus/pure/wiki#create-aliases-for-really-long-directory-paths).

**Comment by gregcousin126** [comment]
no it’s just the space jumps that are a bit large so i’m trying to reduce the most anount of space. Figured i could do without the path or the extra space under the current command line. that is if there is an option for that?

**Comment by mafredri** [comment]
Sorry, you can't hide the path. It's an integral part of Pure. I'm curious, what features are you using Pure for if you want to change it so drastically?

But if all you want to do is save some vertical space, you can try the [Single-line prompt](https://github.com/sindresorhus/pure/wiki#single-line-prompt) (keep in mind, this is a hack and could break in the future).

**Comment by gregcousin126** [comment]
Oh perfect, that was exactly what i was looking for! Pure is really cool! thank you again!
