### ISSUE TITLE
Make it easier to integrate with Prezto

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/pure#4]
Some possible improvements I could do: https://gist.github.com/OliverJAsh/832d49faf47ed7b0fc51

@OliverJAsh can you walk me through which changes you had to do to make it work? Some of them looks like just preferences.
- I like the usage of zsh-hooks instead of overriding precmd and preexec. It was already one my list. But built-in zsh stuff has a tendency to be slow. So I need to perf test it first.
- Can you explain these?

```
setopt LOCAL_OPTIONS                                                           
  unsetopt XTRACE KSH_ARRAYS                                                     
  prompt_opts=(cr percent subst)
```
- I'm considering removing this so the theme can be used unmodified for those that prefer that. It could just be a exported variable. What do you think?

```
DEFAULT_USERNAME='Oliver'
```
- I'm also considering switching this out with git parsing as that unfortunately and ironically is much faster:

```
zstyle ':vcs_info:*' enable git # You can add hg too if needed: `git hg`
  zstyle ':vcs_info:git*' formats ' %b'
  zstyle ':vcs_info:git*' actionformats ' %b|%a'
```
- Any reason you wrapped this in a function?

```
prompt_pure_setup "$@"
```

**Comment by kevinSuttle** [comment]
I've never used prezto, but now all of a sudden I'm getting this, instead of my pure prompt. Notice the blue arrow.

![screen shot 2015-03-16 at 10 36 43 am](https://cloud.githubusercontent.com/assets/95672/6669743/8e14ce46-cbc8-11e4-8719-0781bd9e3886.png)

**Comment by kevva** [comment]
How does your `.zshrc` look?

**Comment by kevva** [comment]
Does `pure` show when you're running `prompt -l`?

**Comment by kevinSuttle** [comment]
@kevva Nevermind. Somehow my Node installation got nuked. I blame, well, it was me. :)

**Comment by kevva** [comment]
Happy it's working again :)
