### ISSUE TITLE
Trying to apply changes to pure prompt results in two different prompt

### ISSUE THREAD

**Issue by rp510** [sindresorhus/pure#409]
### General information

- Pure version: 1.7.0
- ZSH version: 5.5.1 (x86_64-apple-darwin15.6.0)
- Terminal program & version: iterm2
- Operating system:  macOS El Capitan 10.11.6
- ZSH framework: oh-my-zsh

### Problem description
I am trying to apply [changes](https://joshdick.net/2017/06/08/my_git_prompt_for_zsh_revisited.html) to my pure-prompt but It results in two separate prompt as such:
![image](https://user-images.githubusercontent.com/24259160/40249173-049516f2-5a87-11e8-99a0-9457323f85a6.png)

I kinda know whats happening, basically it is applying the configs from pure.zsh and then also the edits I make to .zshrc. I tried to append to PROMPT but I don't think I have as much knowledge with bash or zsh to make this work. What is the best way to just use the changes I have in .zshrc and not have the default prompt being displayed also? Sorry if this is really obvious, I am just new to bash and zsh, also I am loving Pure and it'd be amazing if this works. Thank you

### Reproduction steps

1. Keep the defaults for pure.zsh
2. Add the below changes to .zshrc

### My `.zshrc`:

```
ZSH_THEME=""
source $ZSH/oh-my-zsh.sh
autoload -U promptinit; promptinit
prompt pure

setopt prompt_subst
autoload -U colors && colors # Enable colors in prompt

# Echoes a username/host string when connected over SSH (empty otherwise)
ssh_info() {
  [[ "$SSH_CONNECTION" != '' ]] && echo '%(!.%{$fg[red]%}.%{$fg[yellow]%})%n%{$reset_color%}@%{$fg[green]%}%m%{$reset_color%}:' || echo ''
}

# Echoes information about Git repository status when inside a Git repository
git_info() {

  # Git branch/tag, or name-rev if on detached head
  local GIT_LOCATION=${$((git symbolic-ref -q HEAD || git name-rev --name-only --no-undefined --always HEAD) 2> /dev/null)#(refs/heads/|tags/)}

  if [ -n "$GIT_LOCATION" ]; then

    local AHEAD="%{$fg[red]%}⇡NUM%{$reset_color%}"
    local BEHIND="%{$fg[cyan]%}⇣NUM%{$reset_color%}"
    local MERGING="%{$fg[magenta]%}⚡︎%{$reset_color%}"
    local UNTRACKED="%{$fg[red]%}●%{$reset_color%}"
    local MODIFIED="%{$fg[yellow]%}●%{$reset_color%}"
    local STAGED="%{$fg[green]%}●%{$reset_color%}"

    local -a DIVERGENCES
    local -a FLAGS

    local NUM_AHEAD="$(git log --oneline @{u}.. 2> /dev/null | wc -l | tr -d ' ')"
    if [ "$NUM_AHEAD" -gt 0 ]; then
      DIVERGENCES+=( "${AHEAD//NUM/$NUM_AHEAD}" )
    fi

    local NUM_BEHIND="$(git log --oneline ..@{u} 2> /dev/null | wc -l | tr -d ' ')"
    if [ "$NUM_BEHIND" -gt 0 ]; then
      DIVERGENCES+=( "${BEHIND//NUM/$NUM_BEHIND}" )
    fi

    local GIT_DIR="$(git rev-parse --git-dir 2> /dev/null)"
    if [ -n $GIT_DIR ] && test -r $GIT_DIR/MERGE_HEAD; then
      FLAGS+=( "$MERGING" )
    fi

    if [[ -n $(git ls-files --other --exclude-standard 2> /dev/null) ]]; then
      FLAGS+=( "$UNTRACKED" )
    fi

    if ! git diff --quiet 2> /dev/null; then
      FLAGS+=( "$MODIFIED" )
    fi

    if ! git diff --cached --quiet 2> /dev/null; then
      FLAGS+=( "$STAGED" )
    fi

    local -a GIT_INFO
    GIT_INFO+=( "\033[38;5;15m±" )
    [ -n "$GIT_STATUS" ] && GIT_INFO+=( "$GIT_STATUS" )
    [[ ${#DIVERGENCES[@]} -ne 0 ]] && GIT_INFO+=( "${(j::)DIVERGENCES}" )
    [[ ${#FLAGS[@]} -ne 0 ]] && GIT_INFO+=( "${(j::)FLAGS}" )
    GIT_INFO+=( "\033[38;5;15m$GIT_LOCATION%{$reset_color%}" )
    echo "${(j: :)GIT_INFO}"

  fi

}

# Use ❯ as the non-root prompt character; # for root
# Change the prompt character color if the last command had a nonzero exit code
PROMPT+='
$(ssh_info)%{$fg[magenta]%}%~%u $(git_info)
%(?.%{$fg[blue]%}.%{$fg[red]%})%(!.#.❯)%{$reset_color%} '
```

```shell
autoload -U promptinit; promptinit
prompt pure
```

**Comment by mafredri** [comment]
Hey @rp510. There's no simple way for you to accomplish what you're trying to do without modifying the Pure source code.

An added benefit from modifying the Pure source is that you could perform your `git_info` check asynchronously, making the prompt faster. Your current implementation will slow it down somewhat because it will wait for the result from all those commands before rendering the prompt (more apparent with large git repos).

In the future we might provide better ways to hook into Pure to make modifications, perhaps even add new parts to the preprompt, but it's just abstract thoughts in my head and nobody is working on a proposal for that.

**Comment by rp510** [comment]
I was hoping to not mess with the source code but looks like that's what I will have to do. Thanks for your suggestion @mafredri I will try to incorporate it best way I can knowing I have absolutely no experience with bash scripting

**Comment by mafredri** [comment]
Hehe, not to mention that zsh is a bit different from bash as well ;).

The most relevant function for you is [prompt_pure_preprompt_render](https://github.com/sindresorhus/pure/blob/2e4879390e9ae7c7a1c945628b5faaefd25827c9/pure.zsh#L116), specifically, you want to modify the `preprompt_parts` array.

I hope the source can work well enough as documentation for you, good luck! If you're stuck on something, I might be around on Gitter every now-and-a-then.

**Comment by rp510** [comment]
Thank you, I got most of it working but might not be the best
implementation. I will share what I have
