### ISSUE TITLE
Conda environment name is not shown

### ISSUE THREAD

**Issue by Aerotow** [sindresorhus/pure#411]
### General information

- Pure version: newest via antigen
- ZSH version: 5.5.1
- Terminal program & version: iTerm 3.1.6
- Operating system: macOS Sierra 10.13.3
- ZSH framework: antigen

I have:
- [x] Tested with another terminal program and can reproduce the issue: 
- [x] Followed the [Integration](https://github.com/sindresorhus/pure#integration) instructions for my framework

### Problem description
The name of a conda environment is not visible. Works with therealklanni/purity
I would love to use your version, but I use conda like every two minutes :/
<img width="348" alt="screen shot 2018-06-05 at 18 49 12" src="https://user-images.githubusercontent.com/6004064/40990442-2a45b6e0-68f1-11e8-9f0b-79670de33693.png">

**Comment by masonlr** [comment]
This process worked for me:

1. Ensure that the system version of python is active (i.e. not anaconda. To do this you may need to temporarily remove the anaconda `PATH` modifications from your `.zshrc` file).

2. Install the theme via node package manager

    ```
    brew install node
    npm install --global pure-prompt
    ```

3. Add the following to your `.zshrc` file
    
    ```
    autoload -U promptinit; promptinit
    prompt pure
    ```

4. Restore the anaconda `PATH` modifications in your `.zshrc` file.

![image](https://user-images.githubusercontent.com/5828176/41647788-2a4fc5d4-746f-11e8-8b40-53818193390a.png)

**Comment by Aerotow** [comment]
Thanks a million!

**Comment by mafredri** [comment]
I don't know what Conda is, but I'm glad you got it working @Aerotow, thanks @masonlr!

**Comment by shihan9** [comment]
pure works well with virtualenv, but not for conda. Pure is installed from zplug on my mbp. any solution except the above workaround? thanks. @mafredri

**Comment by mafredri** [comment]
@shihan9 nothing that I'm aware of.

I tried to investigate this a bit by analyzing the anaconda source code (`etc/profile.d/conda.sh` and `conda/activate.py`). We could theoretically add support for anaconda environments (similar to virtualenv) but I found no proper facilities for disabling prompt updates by `conda`. There's a setting, `context.changeps1`, that could disable prompt updates, but I have no idea how to set it. And I also don't know for sure exactly what environment variables `conda` makes available (I'm only guessing).

Either way, I don't use `conda` and I don't plan on installing it for the purpose of investigating this further. So this is as much as I'll investigate into supporting it, but I would be happy to accept a PR that adds support for it.

**Comment by shihan9** [comment]
@mafredri thanks for your answer. sorry, I am not familiar with prompt projects and how they work.

I have taken a look at the source code of `therealklanni/purity` as it is working for conda, but I did not find any code relevant to virtual environment.

**Comment by VincentMatthys** [comment]
Adding the following
```bash
if [[ -n $CONDA_PROMPT_MODIFIER ]]; then
    psvar[12]="$CONDA_PROMPT_MODIFIER"
```
seems to work to support conda

**Comment by minhoolee** [comment]
For me, it was `CONDA_DEFAULT_ENV` that is set when activating a conda environment
```zsh
if [[ -n $CONDA_DEFAULT_ENV ]]; then
    psvar[12]="$CONDA_DEFAULT_ENV"
fi
```

**Comment by mafredri** [comment]
@yl1991 it was in v1.9.0 (See https://github.com/sindresorhus/pure/pull/440)
