### ISSUE TITLE
prompt not working..

### ISSUE THREAD

**Issue by shibumi** [sindresorhus/pure#416]
### General information

- Pure version: https://github.com/sindresorhus/pure/commit/37fc76d8a74b98a9fbcc697ca7efd600e669311e
- ZSH version: 5.5.1-1
- Terminal program & version: termite 13-3
- Operating system: Arch Linux
- ZSH framework: No Framework.

I have:
- [X] Tested with another terminal program and can reproduce the issue: 
- [X] Followed the [Integration](https://github.com/sindresorhus/pure#integration) instructions for my framework

### Problem description
There is no prompt theme `pure`. No idea what I am doing wrong.

### Reproduction steps
`.zshrc`:
`fpath=( "$HOME/.zfunctions" $fpath )`

`$ ls ~/.zfunctions`
`async.zsh pure.zsh`

`autoload -U promptinit; promptinit; prompt pure`
```
[chris@motoko ~]$ autoload -U promptinit; promptinit
prompt pure
Usage: prompt <options>
Options:
    -c              Show currently selected theme and parameters
    -l              List currently available prompt themes
    -p [<themes>]   Preview given themes (defaults to all)
    -h [<theme>]    Display help (for given theme)
    -s <theme>      Set and save theme
    <theme>         Switch to new theme immediately (changes not saved)

Use prompt -h <theme> for help on specific themes.
```

**Comment by mafredri** [comment]
It’s just the wrong names. Rename to: `.zfunctions/async` and `.zfunctions/prompt_pure_setup`.
