### ISSUE TITLE
Uninstall pure

### ISSUE THREAD

**Issue by huyvohcmc** [sindresorhus/pure#421]
I installed pure using `npm install -g pure-prompt` and now want to remove it from my computer. When I do `npm uninstall -g pure-prompt` and reset my zsh, there's an error shows up:
```
prompt_pure_setup:17: async: function definition file not found
```
So I guess npm didn't delete pure's symlinks, so I deleted it:
```
rm /usr/local/share/zsh/site-functions/prompt_pure_setup
rm /usr/local/share/zsh/site-functions/async
```
But now I get this:
```
prompt_pure_setup:17: async: function definition file not found
prompt_pure_async_tasks:5: command not found: async_start_worker
prompt_pure_async_tasks:6: command not found: async_register_callback
```
**Edit:** I also installed purer, a prompt based from pure, and some how `purer-promt-setup` is a symlink to pure. I removed purer and re-installed it again and everything's fine now.

**Comment by darek1024** [comment]
@huyvohcmc I have the same issues, have you found the solution?

**Comment by huyvohcmc** [comment]
Sorry I forgot how I fixed it
