### ISSUE TITLE
New line before prompt

### ISSUE THREAD

**Issue by Hum4n01d** [sindresorhus/pure#422]
### General information

- Pure version: 1.7.0
- ZSH version: zsh 5.3 (x86_64-apple-darwin17.0)
- Terminal program & version: iTerm 3.1.7 and Terminal 2.8.2
- Operating system: macOS High Sierra 10.13.6
- ZSH framework: oh-my-zsh

I have:
- [x] Tested with another terminal program and can reproduce the issue: <!— e.g. iTerm, etc. -->
- [x] Followed the [Integration](https://github.com/sindresorhus/pure#integration) instructions for my framework

### Problem description

There is a new line before my prompt in both iTerm and the native mac terminal.

iTerm:
![screen shot 2018-07-26 at 12 16 32 am](https://user-images.githubusercontent.com/17228477/43247322-2e37555c-9069-11e8-9f9c-52786ffbd67c.png)

Terminal (the tilda is there, just bad color, don’t use the app anymore):
![screen shot 2018-07-26 at 12 16 24 am](https://user-images.githubusercontent.com/17228477/43247325-31fe7184-9069-11e8-8009-e803e3bac73a.png)

### Reproduction steps

1. Open a new terminal window

### My `.zshrc`:

```shell
autoload -U promptinit; promptinit
prompt pure
```

**Comment by Hum4n01d** [comment]
This may be related:
![screen shot 2018-07-26 at 12 18 06 am](https://user-images.githubusercontent.com/17228477/43247377-670ebe74-9069-11e8-812d-178aa28c69f8.png)

It seems that my `$PS1` has a newline before the prompt (never changed it though)

**Comment by mafredri** [comment]
Sorry, this is as intended, or rather, see https://github.com/sindresorhus/pure/issues/233#issuecomment-248549416 as to why we can't do anything about it.

**Comment by Hum4n01d** [comment]
@mafredri Why does the screenshot in the readme not have a newline? I reproduced the same scenario with pure prompt, hyper, and hyper-snazzy and it looks like this:

![screen shot 2018-08-12 at 6 55 01 pm](https://user-images.githubusercontent.com/17228477/44009498-3cba7ba8-9e61-11e8-8eb5-8b292dd7b6f7.png)


compared to

![screen shot 2018-08-12 at 6 54 42 pm](https://user-images.githubusercontent.com/17228477/44009495-2fa4cfb8-9e61-11e8-831f-d64fab5d65f1.png)

**Comment by mafredri** [comment]
@Hum4n01d the newline has scrolled out of view.

**Comment by Hum4n01d** [comment]
Isn't that a bit misleading?

**Comment by mafredri** [comment]
@Hum4n01d I’m afraid I don’t see the issue, I doubt there was any intent to mislead or misrepresent the fact in that screenshot.

I’ve already explained why we can’t do anything about it. Why do you still see this as such an issue?

**Comment by Hum4n01d** [comment]
I understand the problem, I am simply pointing out that it is misleading to hide a problem with the project, I likely wouldn't have installed pure if I'd known about this

**Comment by Hum4n01d** [comment]
At the same time, I've gotten used to it and I like the prompt personally 🤷‍♂️

**Comment by mafredri** [comment]
I think I understand where you’re coming from now. You see this as a problem whereas I would not classify it as one. In my view it’s a small improvement that we, unfortunately, can’t make. As such I did not think the screenshot hid anything.

I’m glad you still gave it a chance and didn’t let it turn you away from Pure though. 😊

**Comment by Pablo1107** [comment]
At least it would be could if could add a margin to the left of the prompt so it wouldn't look so bad. :P

**Comment by mafredri** [comment]
@Pablo1107 you mean like this?

```
PROMPT="  $PROMPT"
eval "$(echo "${$(whence -f prompt_pure_preprompt_render)/\%~/  %~}")"
```

😝

**Comment by mafredri** [comment]
Hmm, it was supposed to indent both `¯\_(ツ)_/¯`...
<img width="748" alt="image" src="https://user-images.githubusercontent.com/147409/50781636-967e9b80-12ae-11e9-8b39-9cda08848477.png">

Glad you found a workaround anyhow :). If you want a margin though, I suggest looking at terminals that support margin / padding.
