### ISSUE TITLE
Color of Python virtualenv segment is incorrect under tmux

### ISSUE THREAD

**Issue by lyndsysimon** [sindresorhus/pure#425]
### General information

- Pure version: `master` (`5976e54a7b02e4be34649fa43b7f0e53b139355f`)
- ZSH version: 5.5.1 (x86_64-apple-darwin17.5.0)
- Terminal program & version:
  - Hyper 2.0.0
  - iTerm2 3.1.7
  - Terminal.app 2.8.2 (404)
- Operating system: macOS High Sierra 10.13.6
- ZSH framework: N/A

I have:
- [x] Tested with another terminal program and can reproduce the issue: 
- [x] Followed the [Integration](https://github.com/sindresorhus/pure#integration) instructions for my framework

### Problem description

The Python virtualenv segment of the prompt shows as light grey (using `hyper-snazzy`) normally, which appears to be the correct behavior. If tmux is running, that segment is white.

In Terminal.app with default settings, those colors are grey and black, respectively.

### Reproduction steps

1. activate a virtual environment in a shell session
2. active a virtual environment in a shell session running in tmux

### My `.zshrc`:

My dot files are on [GitLab](http://gitlab.com/lyndsysimon/dotfiles/tree/master/zsh).

**Comment by mafredri** [comment]
I believe you should be seeing this issue with the color of git branches as well?

You should see the correct color if you add this to your `.tmux.conf`:

```
set -g default-terminal screen-256color
```

Not sure if there's anything we can do to fix this. Technically the `TERM` environment variable will differ (one is `screen`, the other is `screen-256color`), but I'm not sure if we can do anything or even rely on that. Maybe prompt the user or revert to a "safe" color range? But then, prompting the user is not very nice, Pure should stay out of the way.

**Comment by lyndsysimon** [comment]
Unfortunately, git branch don't display for me at the moment - I believe that issue is already tracked by someone else so I've not reported it separately.

Thanks for the reply - I'm closing this issue, and I agree, it's not something within pure's purview to deal with gracefully handling degraded color capabilities. That's zsh's job :)
