### ISSUE TITLE
Parse Error

### ISSUE THREAD

**Issue by lucaseverett** [sindresorhus/pure#433]
With the 1.8.0 files, I get the following error when starting ZSH after completing a manual setup on macOS High Sierra.

prompt_pure_setup:8: parse error near `\n'

After reverting to the files from the 1.7.0 release ZSH starts without any issues.

**Comment by mafredri** [comment]
Could you provide more details? Zsh version? How are you activating pure (e.g. your zshrc), etc. 

Please follow the issue template in the future, these questions are there for a reason.

**Comment by lucaseverett** [comment]
I downloaded the changes after your last commit and it's working now. Thanks.

**Comment by mafredri** [comment]
Glad it works now! Mysterious issue, I really had no idea where to start with this one 😅.

**Comment by Ashniu123** [comment]
I also faced this issue just now and the way I fixed it was to **clone the repo** instead of `wget`ing the 2 files.
