### ISSUE TITLE
There is any way to show only the last directory not the full path?

### ISSUE THREAD

**Issue by rafaeldevsquad** [sindresorhus/pure#437]

**Comment by fuadnafiz98** [comment]
> Hey @rafaeldevsquad, it's not possible, at least not at this time. To achieve this you could fork this repo and change the following line: [pure.zsh#L118](https://github.com/sindresorhus/pure/blob/9325fe60f8857ae089146176c2fa73384507dfc3/pure.zsh#L118).

What should I write ?
