### ISSUE TITLE
Option to hide hostname during ssh

### ISSUE THREAD

**Issue by huyvohcmc** [sindresorhus/pure#441]
I personally don't want to show hostname while connecting through ssh, because if so then it's not pure anymore. Would like to know if you guys are open for a PR to control the hostname visibility via an environment variable.

**Comment by mafredri** [comment]
Hi @huyvohcmc, how would instead indicate that you are connected to a remote machine? Or do you not consider it important information?

We're a bit vary of introducing new options, typically they amass and you end up with a wall of options. If this really bothers you you can remove the username by typing `prompt_pure_state[username]=` into the terminal (although that's an internal variable, so no compatibility guarantees!).
