### ISSUE TITLE
Wide cursor for VI command mode.

### ISSUE THREAD

**Issue by yrammos** [sindresorhus/pure#445]
### General information

This is a feature request, not a bug report.

Unless there is a straightforward method for extending the plugin on the user end, it would be wonderful to have an option for displaying a thick block cursor in VI command mode. The code I used to use before migrating to pure was:

```bash
function zle-keymap-select {
         if [[ ${KEYMAP} == vicmd ]] ||
                 [[ $1 = 'block' ]]; then
         echo -ne '\e[1 q'

         elif [[ ${KEYMAP} == main ]] ||
                 [[ ${KEYMAP} == viins ]] ||
                 [[ ${KEYMAP} = '' ]] ||
                 [[ $1 = 'beam' ]]; then
         echo -ne '\e[5 q'
         fi
}
zle -N zle-keymap-select
# use beam shape cursor on startup
echo -ne '\e[5 q'
# use beam shape cursor for each new prompt
preexec() {
        echo -ne '\e[5 q'
}
```

Just an idea. Thanks for an excellent plugin.

**Comment by sudo-nice** [comment]
It's already [possible].

[possible]: https://github.com/kutsan/dotfiles/blob/master/.zsh/config/prompt.zsh

**Comment by sindresorhus** [comment]
I've added it to the wiki: https://github.com/sindresorhus/pure/wiki#wide-cursor-for-vi-command-mode
