### ISSUE TITLE
Prompt fails to switch to VI command mode in Ubuntu 16.04.5 LTS.

### ISSUE THREAD

**Issue by yrammos** [sindresorhus/pure#446]
### General information

- Pure version: 1.
- ZSH version: 5.6.2
- Terminal program & version: iTerm
- Operating system: Ubuntu 16.04.5 LTS
- ZSH framework: zplug

I have:
- [x] Tested with another terminal program and can reproduce the issue: 
- [x] Followed the [Integration](https://github.com/sindresorhus/pure#integration) instructions for my framework

### Problem description

Prompt fails to switch to the VI command mode variant (❮) in my Ubuntu setup.

With an equivalent `.zshrc` file  (i.e. a file with no relevant differences), and the same terminal and fonts, everything works fine on the macos side.

### Reproduction steps

1.
2.
3.

### My `.zshrc`:
```shell
# >-> >-> >-> >-> >-> >-> zplug <-< <-< <-< <-< <-< <-<
# zplug initialization
export ZPLUG_HOME=~/.zplug
source $ZPLUG_HOME/init.zsh

# plugins and commands
# autocompletions,  history, devtools
zplug "zsh-users/zsh-history-substring-search"
zplug "zsh-users/zsh-completions"
zplug "zsh-users/zsh-autosuggestions"
zplug "plugins/git", from:oh-my-zsh
zplug "lukechilds/zsh-better-npm-completion", defer:2
zplug "plugins/pip", from:oh-my-zsh
zplug "plugins/gpg-agent", from:oh-my-zsh
# colors
zplug "zdharma/fast-syntax-highlighting"
zplug "chrissicool/zsh-256color"
zplug "ael-code/zsh-colored-man-pages"
# commands and shortcuts
zplug "mafredri/zsh-async", from:github

zplug "b4b4r07/enhancd", use:init.sh
# prompts and theming
zplug sindresorhus/pure, use:pure.zsh, from:github, as:theme
# key bindings
zplug "plugins/vi-mode", from:oh-my-zsh
zplug "hcgraf/zsh-sudo"


# source plugins and add commands to $PATH
zplug load
# >-> >-> >-> >-> >-> >-> <-< <-< <-< <-< <-< <-<

# enhancd settings
export ENHANCD_FILTER=fzy
export ENHANCD_DOT_SHOW_FULLPATH=1
export ENHANCD_DISABLE_DOT=1
export ENHANCD_DISABLE_HYPHEN=1

bindkey -M vicmd '\M-\t' autosuggest-accept

# prompting
autoload -U promptinit; promptinit
prompt pure

# vi key bindings
bindkey -v
bindkey '^r' history-incremental-search-backward  # Now using zsh-history-search-multi-word
bindkey '^R' history-incremental-pattern-search-backward
bindkey 'jk' vi-cmd-mode
bindkey 'kj' vi-cmd-mode
bindkey -r '^[' # remove default binding of escape key
bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'l' vi-forward-char
bindkey -M menuselect 'j' vi-down-line-or-history
bindkey -M menuselect '^I' accept-line
bindkey -M listscroll '^I' accept-line
bindkey -M vicmd 'k' history-substring-search-up
bindkey -M vicmd 'j' history-substring-search-down
```

**Comment by dustinspecker** [comment]
I'm having the same issue on 16.04. Using the same conf it works on Ubuntu 18.10 and version of Pure.

@yrammos Have you had any luck figuring this out? Not sure I know enough to begin debugging something like this.

**Comment by dustinspecker** [comment]
Thank you @mafredri! I completely overlooked the Zsh version. 🤦‍♂️

**Comment by olejorgenb** [comment]
I had the same problem using zsh 5.6.2 (NixOS) 

My issue was that I had redefined zle-keymap-select to update the cursor shape on keymap changes. I changed that to use the widget hook, and the prompt indicator started working.

**Comment by mafredri** [comment]
Thanks for the input @olejorgenb, I'm glad you found a solution for your issue and perhaps it can help others too!

I'm closing this now as two potential solutions have been discussed in this issue. If this is still an issue for you @yrammos, feel free to re-open (although some additional info / minimal reproduction config would be useful).
