### ISSUE TITLE
[Question] A better approach to do an async feature to RPROMPT

### ISSUE THREAD

**Issue by sinetoami** [sindresorhus/pure#448]
I'm trying to implement an asynchronous feature to put in the RPROMPT. In short, I'm trying to get language versions and set them up in RPROMPT as [alien-minimal](https://github.com/eendroroy/alien-minimal) does. I did. But I'm not sure if I did it in the best way. So, I want some advice about how doing this.

I coded something like:

```
# pure/pure.zsh
prompt_pure_preprompt_render() {
  ....
  PROMPT="${(j..)ps1}"
  RPROMPT="${pure_langs}"
  ....
}

prompt_pure_precmd() {
  ...
  prompt_pure_async_langs_task
}

prompt_pure_async_langs() {
  setopt localoptions noshwordsplit
  command echo ${#PURE_LANG_VERSION[*]}
}

prompt_pure_async_langs_task() {
  setopt localoptions noshwordsplit
  if [[ -n ${#PURE_LANG_VERSION[@]} ]]; then
    async_start_worker "prompt_pure_langs" -n
    async_register_callback "prompt_pure_langs" prompt_pure_async_langs_callback
  fi

  async_job "prompt_pure_langs" prompt_pure_async_langs
}

prompt_pure_async_langs_callback() {
  setopt localoptions noshwordsplit
  local job=$1 code=$2 output=$3 exec_time=$4 next_pending=$6

  if [[ -n $output ]]; then
    typeset -g purien_langs=$(prompt_pure_langs_compose)
    prompt_pure_preprompt_render
    zle reset-prompt
  fi
}

# ~/.zshrc
export PURE_LANG_VERSION=( ruby python )
```
It's a brief of what I did. But, what can I do to make this code better?

Thanks!

**Comment by mafredri** [comment]
Hi, sorry for the long delay. We can't really provide support in modifying Pure / using zsh-async here. But mostly I'd say you're on the right path. I would, however, move `prompt_pure_langs_compose` out of the callback and into the function that's running asynchronously. I'm assuming that's the one that might take a while and as the code is now, it's not really taking advantage of the async behavior.

**Comment by sinetoami** [comment]
@mafredri , thanks for your answer!
