### ISSUE TITLE
Can't install PurePrompt 

### ISSUE THREAD

**Issue by Pevia** [sindresorhus/pure#449]
I will start by saying that i'm quite a newbie so i apologize in advance if what i will write will be just stupid.
So I was trying to install the Pure Promt with the line:
`npm install --global pure-prompt
`

And this is what i got back

> pure-prompt@1.8.0 postinstall /usr/local/lib/node_modules/pure-prompt
> PURE_DEST=/usr/local/share/zsh/site-functions npm run --silent postinstall-link && exit 0; PURE_DEST="$PWD/functions" npm run postinstall-link && npm run postinstall-fail-instructions

glob error { [Error: EACCES: permission denied, scandir '/var/root/.npm/_logs']
  stack:
   'Error: EACCES: permission denied, scandir \'/var/root/.npm/_logs\'',
  errno: -13,
  code: 'EACCES',
  syscall: 'scandir',
  path: '/var/root/.npm/_logs' }
npm ERR! path /var/root/.npm/_logs
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall scandir
npm ERR! Error: EACCES: permission denied, scandir '/var/root/.npm/_logs'
npm ERR!  { [Error: EACCES: permission denied, scandir '/var/root/.npm/_logs']
npm ERR!   stack:
npm ERR!    'Error: EACCES: permission denied, scandir \'/var/root/.npm/_logs\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'scandir',
npm ERR!   path: '/var/root/.npm/_logs' }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).
glob error { [Error: EACCES: permission denied, scandir '/var/root/.npm/_logs']
  stack:
   'Error: EACCES: permission denied, scandir \'/var/root/.npm/_logs\'',
  errno: -13,
  code: 'EACCES',
  syscall: 'scandir',
  path: '/var/root/.npm/_logs' }

> pure-prompt@1.8.0 postinstall-link /usr/local/lib/node_modules/pure-prompt
> mkdir -p "$PURE_DEST" && ln -sf "$PWD/pure.zsh" "$PURE_DEST/prompt_pure_setup" && ln -sf "$PWD/async.zsh" "$PURE_DEST/async"

mkdir: /usr/local/lib/node_modules/pure-prompt/functions: Permission denied
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pure-prompt@1.8.0 postinstall-link: `mkdir -p "$PURE_DEST" && ln -sf "$PWD/pure.zsh" "$PURE_DEST/prompt_pure_setup" && ln -sf "$PWD/async.zsh" "$PURE_DEST/async"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pure-prompt@1.8.0 postinstall-link script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! code ELIFECYCLE
npm ERR! errno 243
npm ERR! pure-prompt@1.8.0 postinstall: `PURE_DEST=/usr/local/share/zsh/site-functions npm run --silent postinstall-link && exit 0; PURE_DEST="$PWD/functions" npm run postinstall-link && npm run postinstall-fail-instructions`
npm ERR! Exit status 243
npm ERR!
npm ERR! Failed at the pure-prompt@1.8.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/root/.npm/_logs/2018-12-02T11_12_01_113Z-debug.log

Can anyone help with that?

**Comment by Pevia** [comment]
SOLVED

i just needed to change the ownership of the  node_modules in /usr/local/lib/node_modules/

**Comment by hsusanoo** [comment]
I'm having the same issue, how did you solve it ?

**Comment by guotingchaopr** [comment]
-- Me too. I only  followed the instrction for the first step.-- 

```bash
sudo  npm i -g pure-prompt
```
Always return the error message  is ` Permission denied`

**Comment by guotingchaopr** [comment]
@Pevia Did yout  sloved the problem ?

**Comment by hoony9x** [comment]
```shell
$ sudo npm install -g pure-prompt --unsafe-perm
```

Above command will solve this problem.
BUT, I'm not sure it is okay to install with `--unsafe-perm` option.

For more information about `--unsafe-perm`, please check [this article](https://geedew.com/What-does-unsafe-perm-in-npm-actually-do/).
