### ISSUE TITLE
Git action status is stuck at `cherry-or-revert​`

### ISSUE THREAD

**Issue by To1ne** [sindresorhus/pure#457]
### General information

- Pure version: 1.8.0
- ZSH version: 5.6.2 (x86_64-debian-linux-gnu)
- Terminal program & version: GNOME Terminal 3.30.0
- Operating system: Debian buster/sid
- ZSH framework: none

I have:
- [ ] Tested with another terminal program and can reproduce the issue: 
- [ ] Followed the [Integration](https://github.com/sindresorhus/pure#integration) instructions for my framework

### Problem description

My prompt is stuck at git action status `cherry-or-revert`.

I've switched branches, no change. I've done an interactive rebase, and it changes to `rebase-i`, but after that rebase it goes back to `cherry-or-revert`.

### Reproduction steps

I have no clue. It only happens in one of my local repos.

### My `.zshrc`:

```shell
export PS1="%c ❯"

autoload -U promptinit; promptinit
prompt pure

prompt_newline=$(echo -n "\u200B")
```

I'm using the hack to put everything on 1 line (from https://github.com/sindresorhus/pure/issues/228), but I don't think that's related. Something in my git repo is causing this. I'm happy to just manually change/delete a file, but I'm failing to find which one.

**Comment by To1ne** [comment]
@hmps That's awesome, I searched around a bit, but couldn't find it.

Thank you so much!

**Comment by footios** [comment]
git revert --abort still does the job
