### ISSUE TITLE
Getting error: no such pty command: _async_test

### ISSUE THREAD

**Issue by rcdailey** [sindresorhus/pure#463]
I'm following [this guide](https://medium.com/@borekb/zsh-via-msys2-on-windows-3964a943b1ce) for using ZSH on Windows via MINGW64. My `.zshrc` looks like this:

```sh
source ~/antigen.zsh
antigen use oh-my-zsh
antigen bundle mafredri/zsh-async
antigen bundle sindresorhus/pure
antigen bundle zsh-users/zsh-completions
antigen apply
```

I get these errors:

```
(zpty):zpty:12: can't open pseudo terminal: bad file descriptor
async_init:zpty:14: no such pty command: _async_test
/c/Users/robert/Nextcloud/Development/Home/Robert/.antigen/bundles/sindresorhus/pure/pure.zsh: line 566: prompt${^prompt_opts[@]}: bad substitution
```

How do I get past this error?

**Comment by sindresorhus** [comment]
Looks like a duplicate of https://github.com/sindresorhus/pure/issues/210

**Comment by rcdailey** [comment]
Thanks for the information. I will move back to bash then.

**Comment by mafredri** [comment]
@rcdailey if you still want to give it a chance you might be interested in https://github.com/sindresorhus/pure/issues/439. Given it has had some success Pure might get Windows compatibility via a zsh-async update in the future, but I can’t make any promises 😅.
