### ISSUE TITLE
macOS Mojave install help~~!

### ISSUE THREAD

**Issue by hanjool** [sindresorhus/pure#465]
sudo npm install --global pure-prompt
Password:

> pure-prompt@1.9.0 postinstall /usr/local/lib/node_modules/pure-prompt
> PURE_DEST=/usr/local/share/zsh/site-functions npm run --silent postinstall-link && exit 0; PURE_DEST="$PWD/functions" npm run postinstall-link && npm run postinstall-fail-instructions

ln: /usr/local/share/zsh/site-functions/prompt_pure_setup: Permission denied

> pure-prompt@1.9.0 postinstall-link /usr/local/lib/node_modules/pure-prompt
> mkdir -p "$PURE_DEST" && ln -sf "$PWD/pure.zsh" "$PURE_DEST/prompt_pure_setup" && ln -sf "$PWD/async.zsh" "$PURE_DEST/async"

mkdir: /usr/local/lib/node_modules/pure-prompt/functions: Permission denied
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pure-prompt@1.9.0 postinstall-link: `mkdir -p "$PURE_DEST" && ln -sf "$PWD/pure.zsh" "$PURE_DEST/prompt_pure_setup" && ln -sf "$PWD/async.zsh" "$PURE_DEST/async"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pure-prompt@1.9.0 postinstall-link script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pure-prompt@1.9.0 postinstall: `PURE_DEST=/usr/local/share/zsh/site-functions npm run --silent postinstall-link && exit 0; PURE_DEST="$PWD/functions" npm run postinstall-link && npm run postinstall-fail-instructions`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pure-prompt@1.9.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by LitoMore** [comment]
You could follow the [manually install](https://github.com/sindresorhus/pure#manually) section.

**Comment by mafredri** [comment]
We don't support installation via `sudo npm install`, however, if you choose to ignore the dragons, you can try the suggestion here: 
https://github.com/sindresorhus/pure/issues/352#issuecomment-340887995

Previous issues related to sudo install: #352, #342, #341, #282, #176.
