### ISSUE TITLE
Can I make it look only when the return value is not 0?

### ISSUE THREAD

**Issue by black7375** [sindresorhus/pure#466]
In the wiki content..

## Show exit code of all (piped) commands in RPROMPT
![image](https://user-images.githubusercontent.com/25581533/53695005-73c5ba80-3df9-11e9-8a6e-261afda5c0c9.png)

I did not want it to be displayed in normal conditions.  
(return 0)

So, I tried this code
```
precmd_pipestatus() {
	RPROMPT="${(j.|.)pipestatus}"
        if [ "$RPROMPT"==0 ]; then
            RPROMPT=""
        fi
}
add-zsh-hook precmd precmd_pipestatus
```
But RPROMPT doesn't display in every state.
Can I make it look only when the return value is not 0?

**Comment by mafredri** [comment]
I don't mind helping you out but I want you to keep in mind that this issue tracker isn't a support forum. It's meant for issues with Pure, and the Wiki is just for fun tricks that can be done with it 😄.

In code snippet you posted above, you've almost got it. It's just that your if-statement is not valid shell syntax, which results in it always being true. It's the same as writing:

```sh
if [ "1==0" ]; then ...
```

There, `"1==0"` is a non-empty string, and thus true. You need to add spaces, in which case you also can't use double `==` when using single `[`. I recommend always using the double `[[`-variant as it's more powerful and has less warts (note that `sh` does not technically support `[[`, but on many systems `sh` is not true `sh` and it works anyway).

So, if you re-write it:

```sh
if [[ $RPROMPT = 0 ]]; then ...
```

you should have some more success 😄.

**Comment by black7375** [comment]
I am sorry to make an issue without thinking.
I will not do that in the future.
