### ISSUE TITLE
Pure Icon different on other Os'es

### ISSUE THREAD

**Issue by svliantiss** [sindresorhus/pure#471]
I have used your pure theme for my dotfiles setup and it's been working magically,
but when I updated my Mac machine with it, the > sign which looks so clean and is the main reason for using the theme is a _.

Do you have any idea on how to fix it. (see the screenshots below)
# MacOs
![image](https://user-images.githubusercontent.com/38691414/56920355-47f64680-6ac3-11e9-9b93-6bfc3135e1cd.png)
#Ubuntu 
![image](https://user-images.githubusercontent.com/38691414/56920494-a7545680-6ac3-11e9-9c60-f118316593b4.png)

**Comment by davidparsson** [comment]
The one that's not working is probably using a font where that character is not present.

**Comment by svliantiss** [comment]
I figured it out it was because of the way my color in iTerm2 was set. Wierdly enough the font was not the problem.
