### ISSUE TITLE
question: how to change the color of the prompt? 

### ISSUE THREAD

**Issue by ssh352** [sindresorhus/pure#478]
the dark blue color is very hard to read with default iTerm settings under Mac osx. 

<img width="569" alt="Screen Shot 2019-06-20 at 12 56 30 PM" src="https://user-images.githubusercontent.com/41779116/59819555-f5b30280-935a-11e9-84f1-8942ba79a775.png">

**Comment by sindresorhus** [comment]
You can fix your blue color in the iTerm preferences.
