### ISSUE TITLE
Long prompt path when using macOS Catalina

### ISSUE THREAD

**Issue by mvllow** [sindresorhus/pure#483]
### General information

- Pure version: latest release
- ZSH version: 5.7.1 (x86_64-apple-darwin19.0)
- Terminal program & version: Hyper 3.0.1-canary.4, Hyper 3.0.2 (stable), VSCode integrated terminal latest
- Operating system: macOS Catalina dev beta 2
- ZSH framework: none

I have:
- [x] Tested with another terminal program and can reproduce the issue: 
- [ ] Followed the [Integration](https://github.com/sindresorhus/pure#integration) instructions for my framework

### Problem description

When using Hyper or VSCode integrated terminal and the tab is opened (via `hypercwd` for Hyper) already in a directory outside of the default root, the prompt path is longer than expected. I believe macOS Catalina changed some directory patterns and is prefixed with `/System/Volumes/Data/`. This is not an issue in default Terminal app, however.

If this does not seem to be an issue with Pure, feel free to remove.

### Reproduction steps

1. Open Hyper and navigate to a directory (with plugin `hypercwd`)
2. New tab

OR

1. Open folder in VSCode
2. Open integrated terminal

<img width="832" alt="Screen Shot 2019-07-02 at 1 46 42 PM" src="https://user-images.githubusercontent.com/1474821/60535382-f5f3bc00-9cd1-11e9-8b7c-6de6c8e85482.png">

(Expected prompt is `~/dev/papayawhip`)

### My `.zshrc`:

```shell
autoload -U promptinit; promptinit
prompt pure
```

**Comment by wanecek** [comment]
Maybe [the section "create-aliases-for-really-long-directory-paths"](https://github.com/sindresorhus/pure/wiki#create-aliases-for-really-long-directory-paths) in the Wiki can be of help? :)

**Comment by mafredri** [comment]
Thanks for the early report. I have a hard time believing this is a Pure issue though. The home = ~ is a shell feature and the only way I see it would behave weird is if there’s something wrong with the environment configuration. What’s the value of `$HOME` in each terminal?

**Comment by mvllow** [comment]
This is my output (first line being part of the prompt)
```sh
/System/Volumes/Data/Users/not/dev/papayawhip
❯ echo $HOME
/Users/not
```

I reset my computer often, and do not configure much of anything. Both Hyper and Pure are fresh installed on a new copy of macOS Catalina.

Seeing how this issue occurs in two electron based apps (only, as far as I can tell), that may be the problem and unrelated to Pure.

**Comment by mvllow** [comment]
This appears to be fixed now, either via an update or was something I was doing wrong. Thanks!
