### ISSUE TITLE
Can I display the full path when a process is running?

### ISSUE THREAD

**Issue by natesilva** [sindresorhus/pure#484]
### General information

- Pure version: 1.10.3
- ZSH version: 5.3
- Terminal program & version: macOS Terminal 2.9.5
- Operating system: macOS Mojave 10.14.5
- ZSH framework: nope

### Problem description

Can I show the full path of the current folder while a process is running?

Currently I do see the full path when I’m at the prompt, but if I start a process then the path is shortened to just the last element of the path.

Because of this, Terminal doesn’t open to the current folder when I open a new tab (Cmd-T). I guess it must extract the path from the current tab’s title, and if it’s not a complete path it won’t work.

**Comment by natesilva** [comment]
It’s working in macOS 10.15 Catalina.

**Comment by mafredri** [comment]
Nothing better than issues that resolve themselves, eih 😄? Thanks for reporting @natesilva and keeping us updated!
