### ISSUE TITLE
Pure's git features stop working if /usr/local/bin is in my PATH

### ISSUE THREAD

**Issue by ianchesal** [sindresorhus/pure#487]
### General information

- Zsh: zsh 5.7.1 (x86_64-apple-darwin18.2.0)
- Operating system: Mac OS X 10.14.6 (18G84)
- Terminal program: iTerm.app (3.2.9)
- Git: git version 2.22.0
- Pure state:
	- username: `''`
	- prompt: `❯`
	- version: `1.10.3`
- Virtualenv: `export VIRTUAL_ENV_DISABLE_PROMPT=12`
- Prompt: `typeset -g PROMPT=$'%F{${prompt_pure_colors[path]}}%~%f
%}%(12V.%F{$prompt_pure_colors[virtualenv]}%12v%f .)%(?.%F{$prompt_pure_colors[prompt:success]}.%F{$prompt_pure_colors[prompt:error]})${prompt_pure_state[prompt]}%f '`
- Detected frameworks: None

I have:
- [* ] Tested with another terminal program and can reproduce the issue: the problem is the same in iTerm2 and in Terminal.app

### Problem description

If I put `/usr/local/bin` in my `PATH` in zsh, the git portion of the pure prompt ceases to work. I don't get the branch name or the dirty flag in the prompt.

I can't for the life of me figure out what might be causing it to break.

Can you offer any advice? I'd very much appreciate your insights.

I did add the line suggested in #435 to `prompt_pure_setup` and running `/usr/local/bin/zsh -x` I do see remarkably different output when `/usr/local/bin` is in the path, but I don't see a 

The contents of `/usr/local/bin` is controlled entirely by Homebrew. My installed packages are: https://gist.github.com/ianchesal/1623c8d1ada5262b934b1019df189183

I've tried using `/bin/zsh` and `/usr/bin/git` by simply doing a `brew remove zsh git` but the problem persists. It's something in `/usr/local/bin` that's messing this up but I can't for the life of me figure out what it might be.

### Reproduction steps

With `/usr/local/bin` in my PATH here is what I see:

<img width="1333" alt="Screen Shot 2019-07-25 at 11 15 01 PM" src="https://user-images.githubusercontent.com/291808/61930247-10683080-af32-11e9-850b-92c11515383b.png">

Without `/usr/local/bin` in my PATH here is what I see:

<img width="1333" alt="Screen Shot 2019-07-25 at 11 20 18 PM" src="https://user-images.githubusercontent.com/291808/61930506-caf83300-af32-11e9-92d1-b57723d87e79.png">

### My `.zshrc`:

I can recreate the problem with the ultra-minimal `.zshrc`:

```shell
autoload -Uz compinit
compinit

export PATH=/usr/local/bin:${PATH}

autoload -U promptinit
promptinit
prompt pure
```

**Comment by ianchesal** [comment]
I wiped Homebrew, reinstalled it and then did an ultra-minimal package install of:

```
❯ brew list --versions
gettext 0.20.1
git 2.22.0_1
jemalloc 5.2.0
libtermkey 0.22
libuv 1.30.1
libvterm 726
luajit 2.0.5
msgpack 3.2.0
ncurses 6.1
neovim 0.3.8
pcre 8.43
pcre2 10.33
unibilium 2.0.0
zsh 5.7.1
```

And _now_ the prompt is working correctly. So it's a package in my Homebrew list that's causing it to break. I'll add them back one and at a time and see which one it is.

**Comment by ianchesal** [comment]
Well, I'm stumped. I went package by package, re-installing and test the zsh prompt in a fresh shell along the way and it works just fine. No issues at all. Something must have gotten messed up in Homebrew package land but I can't for the life of me figure out what it was.

**Comment by ianchesal** [comment]
Finally figured it out: it was the `cat` function I had made that swaps out `cat` for [bat](https://github.com/sharkdp/bat) if it's installed (and it was). Using `bat` in place of `cat` prevents the git branch and dirty status from working in the prompt.

Leaving this comment as a breadcrumb for people from the future.

**Comment by o6uoq** [comment]
@ianchesal not all heroes wear capes! Thank you for finding this. They should put this somewhere in their known issues/documentation. Thank you again! 🙏🏼

**Comment by mafredri** [comment]
@o6uoq thanks for the reminder. I've already fixed this in zsh-async base branch but it hasn't been tagged nor bundled in Pure yet.

PS. Would you mind testing https://github.com/mafredri/zsh-async/commit/0f3b27b9ce3a1566d4393a6191b859ecb29b55b9 to see if it fixes the bat issues?

**Comment by ahmedelgabri** [comment]
> Finally figured it out: it was the `cat` function I had made that swaps out `cat` for [bat](https://github.com/sharkdp/bat) if it's installed (and it was). Using `bat` in place of `cat` prevents the git branch and dirty status from working in the prompt.
> 
> Leaving this comment as a breadcrumb for people from the future.

I just had the same issue, I can confirm that this fixed it for me.
