### ISSUE TITLE
How to disable/remove git information

### ISSUE THREAD

**Issue by Cottser** [sindresorhus/pure#489]
Not sure if this is a documentation or feature request, but I'm looking into removing the git info from pure's prompt and just using the recently-added status bar in iTerm 3.3+.

I've searched issues and poked around, tried some small changes to the code but can't figure it out. Thanks in advance for any pointers.

**Comment by bricewge** [comment]
The following will do the trick:
```sh
prompt_pure_async_tasks() { }
```
Beware that it is a hack; it isn't supported and may break.
In the long https://github.com/sindresorhus/pure/issues/460 need to be solved to configure this behavior properly.

**Comment by Cottser** [comment]
Thank you!

**Comment by bricewge** [comment]
#497 is related.
