### ISSUE TITLE
Branch name not updating after some usage

### ISSUE THREAD

**Issue by donifer** [sindresorhus/pure#490]
### General information

- Pure version: 1.10.3
- ZSH version: 5.7.1
- Terminal program & version: Alacritty 0.3.3
- Operating system: macOS 10.14.6 
- ZSH framework: zplug

I have:
- [x] Tested with another terminal program and can reproduce the issue: iTerm
- [x] Followed the [Integration](https://github.com/sindresorhus/pure#integration) instructions for my framework

### Problem description
After a while (maybe a couple of days?) of working on a repository when I switch to a different branch the branch name gets stuck with the previous name:

For example:
```
~/dev/test branchB
❯ git branch
branchB
* master
```

### Reproduction steps

1. Use a repo for a while and switch branches until it happens

**Comment by mafredri** [comment]
This is probably related to #455, it’s very hard to track down as it happens so rarely and there doesn’t seem to be a pattern to it.

**Comment by donifer** [comment]
Yep definitely related, sorry for the duplicate.
