### ISSUE TITLE
Display git user name

### ISSUE THREAD

**Issue by Norfeldt** [sindresorhus/pure#492]
This theme is beautiful!

I just started doing some pair coding and found find it very useful if I could have/hack it to show the user name in the `.gitconfig`.

Is this possible?

**Comment by mafredri** [comment]
Sorry, this feel through the cracks. I wonder if you ever managed to hack this in? If we ever get #460 implemented, this should be possible to do fairly cleanly. For the moment being though, you could add the following line:

```zsh
	info[user]=$(git config --get user.email)
```

here: https://github.com/sindresorhus/pure/blob/7f1e473c15216a19a1df9a868e3facbf61981fee/pure.zsh#L273

And then modify `prompt_pure_preprompt_render` to add it to `preprompt_parts`.

Alternatively, you could utilize the right prompt (`RPROMPT`) to display it independent of Pure.

```zsh
RPROMPT='$(git config --local --get user.email 2>/dev/null)'
```
