### ISSUE TITLE
Turn off command execution time?

### ISSUE THREAD

**Issue by flaugher** [sindresorhus/pure#496]
I just discovered the Pure prompt and like it a lot.  However, I was wondering if there is any way to turn off the command execution time all together?  I don't find it very useful and feel it can clutter up an other nice, minimalist prompt.  I tried setting PURE_CMD_MAX_EXEC_TIME=0 in hopes that that might be a hidden setting to disable it but it wasn't.

Thanks!

**Comment by sindresorhus** [comment]
Setting it to `0` does the opposite of what you want as it means it will always be shown. You could set it to a very high number instead.

**Comment by pasteley** [comment]
Looking for flag to disable it at all in order to save some computational resources

**Comment by mafredri** [comment]
@pasteley disabling it all-together would not make a dent in terms of computational resources. The check to see if it's enabled or not would even it out.

**Comment by romkatv** [comment]
@pasteley Do you want to save computational resources because something is slow or for the sake of our planet? If the former, could you mention what is slow? If the latter, thank you!

**Comment by mafredri** [comment]
Closing due to age.
