### ISSUE TITLE
Volta compatibility?

### ISSUE THREAD

**Issue by MichalBryxi** [sindresorhus/pure#498]
### General information

- Pure version: 1.10.3
- ZSH version: 5.7.1
- Terminal program & version:  iTerm 3.x
- Operating system: OSX 10.14.6
- ZSH framework: oh-my-zsh

I have:
- [x] Tested with another terminal program and can reproduce the issue: 
- [x] Followed the [Integration](https://github.com/sindresorhus/pure#integration) instructions for my framework

### Problem description

When trying to install pure via [volta](https://docs.volta.sh/guide/#how-does-it-work):
```
volta install pure-prompt
```

I get:
```
error: Package has no executables to install.

Please verify the requested package name.
```

### Reproduction steps

1. volta install pure-prompt

### My `.zshrc`:

N/A

Apparently the fix can be done following change in `package.json`: 

<img width="208" alt="Screenshot 2019-09-17 at 19 01 36" src="https://user-images.githubusercontent.com/847473/65067113-ad1cdc80-d97d-11e9-8756-42cc6e4bab97.png">

**Comment by sindresorhus** [comment]
> Volta is a hassle-free way to manage your **JavaScript command-line tools.**

We only use `npm` as it's an easy and working way to get Pure installed. Why do you need Pure to work with Volta? Can you not just use `npm`?

**Comment by MichalBryxi** [comment]
I'm new to volta, so not sure if there is different solution, but I got: 

```
❯ npm install --global pure-prompt
Volta error: Global package installs are not supported.

Use `volta install pure-prompt` to add a package to your toolchain (see `volta help install` for more info).
```

But in case anyone else bumps into this, the [manual installation](https://github.com/sindresorhus/pure#manually) is a way to quick-fix this.

I thought having the non-git way working would be better.

**Comment by MichalBryxi** [comment]
Just bumped into a thread on [volta github](https://github.com/volta-cli/volta/issues/557) to find out their recommended solution:

```sh
VOLTA_UNSAFE_GLOBAL=1 yarn global add pure-prompt
```

@sindresorhus volta is quite favored solution for people that have to deal with environments that use multiple node versions. Similar to `nvm`. But since they install individual `node` versions into the global namespace, they also have to manage globally installed packages as they might break if you change global version of `node`. But since the solution mentioned above works, I'm going to close this one. Thanks for your time.
