### ISSUE TITLE
How do I use light color variants with zstyle?

### ISSUE THREAD

**Issue by rfgamaral** [sindresorhus/pure#501]
I don't want to specify the color by hex code, I'd prefer to use names and the README only mentions the default 8 colors. How do you use the other 8, light, variants?

I tried `zstyle :prompt:pure:path color lightblue`, for instance, but it didn't work.

Is this not possible?

**Comment by mafredri** [comment]
If it's supported by ZSH, you should be able to use it.

**Comment by rfgamaral** [comment]
> .

Are you saying my example above should work? Because that line changed the path to white...

**Comment by mafredri** [comment]
No, what I'm saying is that using a name, instead of number, must be supported by ZSH. Otherwise it will not work, we don't create these named colors in Pure.

Please read through the [Colors](https://github.com/sindresorhus/pure#colors)-section in the Pure readme, and the linked section from the ZSH manual as well.

**Comment by mafredri** [comment]
I guess I should've just replied that it's not possible, but I was unsure if it's possible to create custom color aliases or not 😄.

My recommendation, find out a good hex match you want, define your own associative color array (`typeset -A mycolors=(lightblue #9dd6f9)`), and then use them via `zstyle :prompt:pure:path color $mycolors[lightblue]`.

**Comment by rfgamaral** [comment]
Based on ZSH documentation, I can't specify more than those 8 colors by name, used numbers from [this chart](https://upload.wikimedia.org/wikipedia/commons/1/15/Xterm_256color_chart.svg) instead.

So, this fixed my issue: `zstyle :prompt:pure:path color 12`.

Thank you @mafredri 🙏
