### ISSUE TITLE
.zshrc prompt pure doesn't work 

### ISSUE THREAD

**Issue by rjain15** [sindresorhus/pure#504]
### General information

- Pure version: 1.11.0
- ZSH version: zsh 5.7.1 (x86_64-apple-darwin19.0)

- Terminal program & version: 
mac terminal
- Operating system: 
macOS Catalina 10.15
- ZSH framework: 
none

I have:
- [ ] Tested with another terminal program and can reproduce the issue: 
- [ ] Followed the [Integration](https://github.com/sindresorhus/pure#integration) instructions for my framework

### Problem description
I have added the pure theme to my .zsh/pure location, and followed the steps as listed in the doc
autoload -U promptinit; promptinit
fpath+=("$HOME/.zsh/pure")
prompt pure

---
When I start a new shell, it seems the pure theme is not loaded, I get this error from prompt (which says the pure theme is not in the fpath) 
Last login: Thu Oct 17 12:56:21 on ttys000
Usage: prompt <options>
Options:
    -c              Show currently selected theme and parameters
    -l              List currently available prompt themes
    -p [<themes>]   Preview given themes (defaults to all)
    -h [<theme>]    Display help (for given theme)
    -s <theme>      Set and save theme
    <theme>         Switch to new theme immediately (changes not saved)

Use prompt -h <theme> for help on specific themes.

-
If I source .zshrc, then it works. So I am wondering why in the first place is it not able to find the theme. 
if I do prompt -l , I don't see pure

Currently available prompt themes:
adam1 adam2 bart bigfade clint default elite2 elite fade fire off oliver pws redhat restore suse walters zefram

After I source .zshrc, I can see prompt -l list out pure
~
❯ prompt -l    
Currently available prompt themes:
adam1 adam2 bart bigfade clint default elite2 elite fade fire off oliver pws redhat restore suse walters zefram pure

### Reproduction steps

1. Install pure theme on catalina using manual (git clone) in .zsh/pure location
2. Modify the .zshrc to load pure theme. 
3. Execute the shell 

### My `.zshrc`:

autoload -U promptinit; promptinit
fpath+=("$HOME/.zsh/pure")

prompt pure

```shell
autoload -U promptinit; promptinit
prompt pure
```

**Comment by mafredri** [comment]
Do you perhaps have git symlinks turned off? Is e.g. `prompt_pure_setup` present in the checked out repo?

**Comment by rjain15** [comment]
Yes,  I see the prompt_pure_setup

```
❯ ls -al ~/.zsh/pure 
total 360
drwxr-xr-x  18 rajesh  staff    576 Oct 17 12:38 .
drwxr-xr-x   3 rajesh  staff     96 Oct 17 12:38 ..
-rw-r--r--   1 rajesh  staff    175 Oct 17 12:38 .editorconfig
drwxr-xr-x  12 rajesh  staff    384 Oct 17 12:38 .git
-rw-r--r--   1 rajesh  staff     19 Oct 17 12:38 .gitattributes
drwxr-xr-x   4 rajesh  staff    128 Oct 17 12:38 .github
-rw-r--r--   1 rajesh  staff     19 Oct 17 12:38 .npmrc
drwxr-xr-x   3 rajesh  staff     96 Oct 17 12:38 arch
lrwxr-xr-x   1 rajesh  staff      9 Oct 17 12:38 async -> async.zsh
-rw-r--r--   1 rajesh  staff  16605 Oct 17 12:38 async.zsh
-rw-r--r--   1 rajesh  staff   1109 Oct 17 12:38 license
-rw-r--r--   1 rajesh  staff   1250 Oct 17 12:38 package.json
lrwxr-xr-x   1 rajesh  staff      8 Oct 17 12:38 prompt_pure_setup -> pure.zsh
lrwxr-xr-x   1 rajesh  staff      8 Oct 17 12:38 pure.plugin.zsh -> pure.zsh
-rw-r--r--   1 rajesh  staff  24305 Oct 17 12:38 pure.zsh
-rw-r--r--   1 rajesh  staff  12462 Oct 17 12:38 readme.md
-rw-r--r--   1 rajesh  staff  24844 Oct 17 12:38 screenshot-title-cmd.png
-rw-r--r--   1 rajesh  staff  72121 Oct 17 12:38 screenshot.png
```

**Comment by mafredri** [comment]
Ok, I missed the part about it working after sourcing `.zshrc`, it seems something is amiss there, not Pure related per-se.

What you posted under `My .zshrc:` confuses me a bit, there seems to be duplicate lines and some of it is in code blocks, some not.

As a general FYI, you should never need to source `~/.zshrc` manually, if something changes when it's sourced a second time, it means there's a problem in it.

**Comment by LePips** [comment]
Same problem, but installed through npm. New machine, so it's a pretty clean install

**Comment by mafredri** [comment]
@LePips it would be helpful if you could provide more info, same that is requested when creating a new issue. Right now we can’t reproduce the issue and we don’t really have anything to go on.

**Comment by LePips** [comment]
Sorry, here's my info. My problem is not the exact same as OP, but still have a problem with installing:

- ZSH version: zsh 5.3 (x86_64-apple-darwin18.0)
- Pure version: 1.11.0 (installed via npm)
- Terminal program and version: iTerm 2 build 3.3.6
- Operating system: macOS Mojave 10.14.5

**Problem**
I followed the instructions for npm install and added the required: 

```autoload -U promptinit; promptinit
prompt pure```

to the end of my `.zshrc` file.

The pure prompt shows up for `prompt -l` properly, but when the terminal is launched it shows a red line prompt (indicating a failure) and takes a very long while (might not be related to this issue) to load.

**Reproduce**
Install pure via npm and add

``````autoload -U promptinit; promptinit
prompt pure```

to the bottom of your `.zshrc` file.

Source `.zshrc` or restart shell

**Comment by rjain15** [comment]
I am closing this issue, as I delete my .zsh directory and installed pure using npm and it worked.
