### ISSUE TITLE
Manual install steps don't work

### ISSUE THREAD

**Issue by callumlocke** [sindresorhus/pure#507]
### General information

- Pure version: master
- ZSH version: 5.7.1
- Terminal program & version: iTerm
- Operating system: macOS Sierra
- ZSH framework: None

I have:
- [x] Tested with another terminal program and can reproduce the issue: 
- [x] Followed the [Integration](https://github.com/sindresorhus/pure#integration) instructions for my framework

### Problem description

The instructions seem to be wrong.

### Reproduction steps

1. Try following the instructions for manual installation, then open a new terminal.
2. You don't see the pure prompt.

### My `.zshrc`:

```shell
autoload -U promptinit; promptinit
prompt pure
```

### Notes

As far as I can tell, the third and final command in the manual installation steps (`fpath+=("$HOME/.zsh/pure")`) only updates the `fpath` variable locally, in the current terminal session. So I tried inserting this line in my `.zshrc` instead (before `autoload...` etc), and this seems to make it work. Not sure if this is the correct approach, but if so, the instructions should be updated to explain that you need to put the `fpath+=` line in your `.zshrc` file.

**Comment by mafredri** [comment]
Step 2 of the manual instructions inform you to put the `fpath` line into your `.zshrc`. Do you have a proposal for improving the instructions if they're unclear?

**Comment by eric1980** [comment]
The line `fpath+=("$HOME/.zsh/pure")` is in the same code block as the repository clone instructions, rather that in the following .zshrc code block in Getting started. I made exactly the same mistake as @callumlocke.

It's a minor thing, but moving the `fpath+=("$HOME/.zsh/pure")` instruction would make it a bit clearer.
