### ISSUE TITLE
Git info can't update while using bindkey to change directory. 

### ISSUE THREAD

**Issue by kevinhwang91** [sindresorhus/pure#508]
I use to https://github.com/skywind3000/z.lua to change my recent directories.  Code like that:
```
fzf-zlua-widget() {
    local dir=$(z -- 2>&1 | fzf --height 25% | awk '{print $2}')
    if [[ -n $dir ]]; then
        cd $dir
    fi
    local ret=$?
    zle reset-prompt
    return $ret
}
zle -N fzf-zlua-widget
bindkey "^G" fzf-zlua-widget
```

I had tried adding debug code inside `prompt_pure_precmd` and `prompt_pure_preexec` to generate log. I can see the log in stdout what I expect except using bindkey to change directory.
I think the hooks mentioned above can not detect the events inside the widget.

**Comment by mafredri** [comment]
You need to also trigger the git info in Pure since it doesn’t know the directory changed.

See here: https://github.com/mafredri/zeet/blob/dcd84902c423e4768c067674208f02dcb234718b/dircycle.zsh

But keep in mind. This is not an officially supported method, so it could break in the future.

**Comment by kevinhwang91** [comment]
> You need to also trigger the git info in Pure since it doesn’t know the directory changed.
> 
> See here: https://github.com/mafredri/zeet/blob/dcd84902c423e4768c067674208f02dcb234718b/dircycle.zsh
> 
> But keep in mind. This is not an officially supported method, so it could break in the future.
> 
> Edit: Rather, the issue is changing directory without triggering a new prompt. Pure doesn’t, IIRC, use the cwd hook (although it probably could), and even then I’m not 100% sure it would fire under this circumstance.

Thanks. To invoke `prompt_pure_async_tasks`  inside widget works fine.
