### ISSUE TITLE
Use Pure from a oh-my-zsh them file for my dotfiles.

### ISSUE THREAD

**Issue by christophrumpel** [sindresorhus/pure#511]
### General information

- Pure version: 1.11
- ZSH version: 5.7.1
- Terminal program & version:  iTerm 3.3.6
- Operating system: macOS Catalina 10.15.1
- ZSH framework: oh-my-zsh

I have:
- [x] Tested with another terminal program and can reproduce the issue: Terminal
- [ ] Followed the [Integration](https://github.com/sindresorhus/pure#integration) instructions for my framework

### Problem description

I get these errors after every command:

```
prompt_pure_async_tasks:11: command not found: async_worker_eval
prompt_pure_async_tasks:30: command not found: async_job
```

I want to use the wonderful pure theme for my oh-my-zsh setup which I setup with my dot files. (https://github.com/christophrumpel/dotfiles) That's why I want  to use a pure theme file from my repo instead of installing it.

From what I read is this setup a problem due to async pure calls? Is there a better how I can integrate pure in my oh-my-zsh setup to that I can install everything automatically my dot files script?

### Reproduction steps

1. Create a pure.zsh-theme file in the oh-my-zsh themes folder
2. Copy the content of pure.zsh into the theme file
3. Set the ZSH theme to pure

### My `.zshrc`:

```
# Path to your dotfiles installation.
export DOTFILES=$HOME/.dotfiles

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="pure"

HIST_STAMPS="dd/mm/yyyy"
ZSH_CUSTOM=$DOTFILES

plugins=(git laravel5 composer osx gitfast zsh-autosuggestions)

# Activate Oh-My-Zsh
source $ZSH/oh-my-zsh.sh

prompt_context() {
  if [[ "$USER" != "$DEFAULT_USER" || -n "$SSH_CLIENT" ]]; then
    prompt_segment black default "%(!.%{%F{yellow}%}.)$USER"
  fi
}

# ....


export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

**Comment by kkreative** [comment]
@christophrumpel  I have had the same line being printed to my terminal on one of my computers.  
`prompt_pure_async_tasks:11: command not found: async_worker_eval`

Were you able to come up with a solution?  I've been digging around but I'm a novice terminal user.

**Comment by christophrumpel** [comment]
Hey @kkreative,

it turned out that these commands are zsh command that you cannot run from a shell script. I fixed it like this: https://github.com/sindresorhus/pure/issues/512
