### ISSUE TITLE
Shrink the path in the prompt

### ISSUE THREAD

**Issue by antmordel** [sindresorhus/pure#514]
I would love to have the option of shrinking the path in the prompt. For example:
```
~/work/workspaceResearch/maudechain master*
```
Will become:
```
~/w/w/maudechain master*
```

**Comment by sindresorhus** [comment]
For what purpose? Screens are wide, so it's not like long paths cannot fit.

And it looks a bit ambiguous. What if you have two top-level directories starting with `w`?

**Comment by antmordel** [comment]
It is true. In ZSH we can use the `hash` function to achieve similar behavior. I'm closing the issue since it is not relevant anymore. thanks a lot @sindresorhus !
