### ISSUE TITLE
enable pure theme in zim framework will produce two conda base env name on prompt

### ISSUE THREAD

**Issue by yetangye** [sindresorhus/pure#515]
The detail problem description is here:
https://github.com/zimfw/zimfw/issues/346

**Comment by mafredri** [comment]
Pure has built-in support for displaying the conda environment, but conda tries to modify the prompt defined by Pure, you need to use the following option to avoid double display:

```
conda config --set changeps1 False
```

**Comment by yetangye** [comment]
Got it, Thanks!

**Comment by ericbn** [comment]
@mafredri, maybe pure could set the conda config automatically instead of users having to configure it manually, same as pure does with `VIRTUAL_ENV_DISABLE_PROMPT` for python's venv for example.

**Comment by mafredri** [comment]
@ericbn we don't want to modify our users configuration without their knowledge. However, I discovered today that there indeed is an environment variable we could use, `CONDA_CHANGEPS1=no`. A quick test showed that it does not apply retroactively, so I'm not sure at what point `conda` listens to it, but it does work if it's set before `conda` is loaded. It's definitely we could define when the prompt is initialized and hope that it has a positive effect.

**Comment by yetangye** [comment]
> @ericbn we don't want to modify our users configuration without their knowledge. However, I discovered today that there indeed is an environment variable we could use, `CONDA_CHANGEPS1=no`. A quick test showed that it does not apply retroactively, so I'm not sure at what point `conda` listens to it, but it does work if it's set before `conda` is loaded. It's definitely we could define when the prompt is initialized and hope that it has a positive effect.

Yeah, I tested, In .zimrc, the lines below also works!
```
export CONDA_CHANGEPS1=no
zprompt_theme='pure'
```
