### ISSUE TITLE
Font Issue "Arrow not working!"

### ISSUE THREAD

**Issue by annata83** [sindresorhus/pure#522]
#### System report (output of `prompt_pure_system_report`):
- Zsh: GNU bash, version 5.0.11(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law. (/bin/bash)
- Operating system: Linux (#1 SMP PREEMPT Thu, 05 Dec 2019 12:29:40 +0000)
- Terminal program: unknown (unknown)
- Tmux: yes
- Git: git version 2.24.1
- Pure state:
    - username: `''`
    - prompt: `❯`
    - version: `1.11.0`
- PROMPT: `export PROMPT=$'%F{${prompt_pure_colors[path]}}%~%f %F{242}${prompt_pure_vcs_info[branch]}%F{218}${prompt_pure_git_dirty}%f
%{
%}%(12V.%F{$prompt_pure_colors[virtualenv]}%12v%f .)%(?.%F{$prompt_pure_colors[prompt:success]}.%F{$prompt_pure_colors[prompt:error]})${prompt_pure_state[prompt]}%f '`
- Colors: `typeset -g -A prompt_pure_colors=( [execution_time]=yellow [git:action]=242 [git:arrow]=cyan [git:branch]=242 [git:branch:cached]=red [git:dirty]=218 [host]=242 [path]=blue [prompt:continuation]=242 [prompt:error]=red [prompt:success]=magenta [user]=242 [user:root]=default [virtualenv]=242 )`
- Virtualenv: `export VIRTUAL_ENV_DISABLE_PROMPT=12`
- Conda: `export CONDA_CHANGEPS1=no`
- Detected frameworks: Zplugin
#### I have:

- [ ] Tested with another terminal program and can reproduce the issue: 
- [ ] Followed the [integration](https://github.com/sindresorhus/pure#integration) instructions for my framework

### Problem description

The arrow font doesn't work

### Reproduction steps
Plain first time install of zpluing, thru .zshrc with 
# Load the pure theme, with zsh-async library that's bundled with this:

```
zplugin ice pick"async.zsh" src"pure.zsh"
zplugin light sindresorhus/pure
```

### My `.zshrc`:

```
### Added by Zplugin's installer
source "$HOME/.zplugin/bin/zplugin.zsh"
autoload -Uz _zplugin
(( ${+_comps} )) && _comps[zplugin]=_zplugin
### End of Zplugin installer's chunk

# Load the pure theme, with zsh-async library that's bundled with it.
zplugin ice pick"async.zsh" src"pure.zsh"
zplugin light sindresorhus/pure

```

![pic-full-191212-0034-54](https://user-images.githubusercontent.com/18301363/70680516-4c005e80-1c77-11ea-864f-8e961d374f15.png)

**Comment by mafredri** [comment]
Hi, you try changing your terminal font or changing the symbol Pure uses for the prompt `PURE_PROMPT_SYMBOL=>`. It should show up if your font supports it.

If that doesn't help, maybe your terminal or tmux doesn't support unicode characters?

**Comment by annata83** [comment]
Yeah, It seems to be a Urxvt rendering issue. Thanks

**Comment by JoshuaCrewe** [comment]
@annata83 did you figure out how to fix this? 

When I get a fresh linux install and boot up Urxvt with this prompt I get a missing character. Installing `ttf-devaju` renders a janky character. Installing `nerd-fonts-complete` will render something as well but it looks weird. Like taller than it should be.
