### ISSUE TITLE
Prompt doesn't appear anymore

### ISSUE THREAD

**Issue by yimmt** [sindresorhus/pure#523]
#### System report (output of `prompt_pure_system_report`):

```
- Zsh: zsh 5.7.1 (x86_64-pc-linux-gnu)
- Operating system: Linux (#1 SMP PREEMPT Tue, 24 Dec 2019 04:36:53 +0000)
- Terminal program:  Kitty
- Git: git version 2.24.1
- Pure state:
	- username: `''`
	- prompt: `❯`
	- version: `1.10.3`
- Virtualenv: `export VIRTUAL_ENV_DISABLE_PROMPT=12`
- Prompt: `typeset -g PROMPT=$'%F{${prompt_pure_colors[path]}}%~%f
%{
%}%(12V.%F{$prompt_pure_colors[virtualenv]}%12v%f .)%(?.%F{$prompt_pure_colors[prompt:success]}.%F{$prompt_pure_colors[prompt:error]})${prompt_pure_state[prompt]}%f '`
- Detected frameworks: None
```

#### I have:

- [ ] Tested with another terminal program and can reproduce the issue: 
- [x] Followed the [integration](https://github.com/sindresorhus/pure#integration) instructions for my framework

### Problem description
My git prompt stopped appearing after updating my system. I don't know what's fully wrong but I hope someone might have this issue or may know my problem. Everything was working before; my prompt included my branch and also if there are changes to commit( the *). However, now neither of those appear. 

### Reproduction steps

1. Git prompt never appears anymore. Tried it on almost every single git project that I have by cd. 

### My `.zshrc`:
My .zshrc is minimal. It only contains the aliases with COMPLETE_ALIASES, and exporting env variables. I source my antibody plugins and it only contains zsh-autosuggestions, pure, and zsh-completions. Everything was working before. I think some dependency update broke pure.

**Comment by yimmt** [comment]
Just wanted to add that my node directory also doesn't work anymore.

**Comment by romkatv** [comment]
What's the output of `git status` in a directory where you expect Git prompt to appear?

**Comment by yimmt** [comment]
![image](https://user-images.githubusercontent.com/34635512/71560484-7e140d80-2a38-11ea-9bbb-d4f1a91e5698.png)
Here is an example of a git repository. Notice how the branch doesn't appear anymore and it doesn't recognize if it's dirty or not.

**Comment by romkatv** [comment]
Yep, seems broken. If `git status` works, I would expect Pure to show Git info in prompt.

**Comment by ehutzelman** [comment]
I'm seeing similar issues to this, but sporadically. Most of the time it works, but sometimes it will fail to update the branch status on the prompt or show the previous branch when checking out a new branch. If I close the terminal out and restart, it shows the correct information again.

**Comment by jvega** [comment]
In .zshrc (oh-myzsh) I disabling/enabling the `git` plugin and it works again

**Comment by marciobarrios** [comment]
> In .zshrc (oh-myzsh) I disabling/enabling the `git` plugin and it works again

Didn't work for me, with disabling you mean just commenting the line in the .zshrc file?

**Comment by romkatv** [comment]
`git` plugin in Oh My Zsh simply defines a bunch of aliases. It cannot affect Pure in any way.

**Comment by yimmt** [comment]
Just want to remind everyone that I have nothing else in zshrc other than autocompletions and aliases.

**Comment by jvega** [comment]
> `git` plugin in Oh My Zsh simply defines a bunch of aliases. It cannot affect Pure in any way.

I know that but I just toggle it  git plugin and works for me

> Didn't work for me, with disabling you mean just commenting the line in the .zshrc file?

no, just delete it from plugin list and put it again

also I uninstall it from `npm` and install it with `yarn`

**Comment by Freyskeyd** [comment]
I've the same issue here... anyone found a solution?

**Comment by romkatv** [comment]
> I've the same issue here... anyone found a solution?

This issue stems from zsh-async. Sometimes the background process dies and no one seems to know why. All themes that use zsh-async are affected. See https://github.com/mafredri/zsh-async/issues/33 and https://github.com/sindresorhus/pure/issues/455. The latter issue links to a patch that attempts to detect background job crashes and to recover from them. It doesn't fix the underlying problem that leads to crashes in the first place. The only reliable solution right now is to use a theme that doesn't utilize zsh-async.

**Comment by mafredri** [comment]
For everyone affected by this issue, please give #543 a spin.
