### ISSUE TITLE
Automatic fetch does not update all branches

### ISSUE THREAD

**Issue by 0xC0FFEE** [sindresorhus/pure#529]
### General information

Since #473 (#518) the automatic fetch does not update all branches anymore.

This change silently broke my workflow, as I used to rely on the previous functionality to automatically update other branches as well. This is particularly useful when rebasing onto `origin/master` on a regular basis, as all remote changes were fetched automatically. Now this doesn't work anymore as only the active branch is fetched.

Would it be possible to make this configurable? I can image I'm not the only person relying on the previous behavior and changing default behavior is really unexpected IMHO.

### Problem description

Default fetch behavior has been altered without a way to restore previous behavior.

### Workaround

Revert to 957e07101a1c14502d32a25d9fd327c83098bf3c.

**Comment by mafredri** [comment]
Thanks for raising the issue. I also preferred the old functionality, I haven't really noticed any performance gains from the new method and Pure seemed more responsive before, especially when switching branches.

I think it would be ideal to revert the default behavior to what it was before (most users will benefit from this) and provide an option to only fetch the active branch. Thoughts @sindresorhus?

**Comment by sindresorhus** [comment]
> I think it would be ideal to revert the default behavior to what it was before (most users will benefit from this) and provide an option to only fetch the active branch. Thoughts @sindresorhus?

👍

**Comment by ericcaclewis** [comment]
www.true.net
