### ISSUE TITLE
Bug: Git stash shows during git action

### ISSUE THREAD

**Issue by camsteffen** [sindresorhus/pure#532]
The git stash symbol shows during an interactive rebase or a merge (with conflicts). This happens even when I have not opted into the git stash symbol.

**Comment by camsteffen** [comment]
Related #462

**Comment by sindresorhus** [comment]
// @carhartl

**Comment by carhartl** [comment]
Funny, I had thought about that earlier. Looking into it!

**Comment by carhartl** [comment]
So in general we don't want the symbol to appear during an action, correct?

**Comment by camsteffen** [comment]
> So in general we don't want the symbol to appear during an action, correct?

My bug title might be misleading. I think it should appear if the feature is enabled and there is a stash.

**Comment by camsteffen** [comment]
I just noticed your commit message which notes that the arrows are not shown during a git action. So maybe it makes since to also not show the stash symbol. But I think the stash symbol is still relevant during a git action. Sorry for all the comments!
