### ISSUE TITLE
How can i remove the extra new line?

### ISSUE THREAD

**Issue by benyitzhaki** [sindresorhus/pure#534]
![Screen Shot 2020-02-25 at 12 40 26](https://user-images.githubusercontent.com/2536651/75239914-2c83c700-57cc-11ea-9d4d-cd02191a566c.png)

is there an option to remove the extra new line that is added?

thanks

**Comment by adrianord** [comment]
He's commented on it here https://github.com/sindresorhus/pure/pull/526#issuecomment-583774870
But can be patched locally like this https://github.com/sindresorhus/pure/issues/509#issuecomment-571439009
