### ISSUE TITLE
Hostname visible when using locally on wsl.

### ISSUE THREAD

**Issue by upedd** [sindresorhus/pure#541]
#### System report (output of `prompt_pure_system_report`):

```
- Zsh: zsh 5.4.2 (x86_64-ubuntu-linux-gnu) (/usr/bin/zsh)
- Operating system: Linux (#476-Microsoft Fri Nov 01 16:53:00 PST 2019)
- Terminal program: unknown (unknown)
- Tmux: no
- Git: git version 2.17.1
- Pure state:
    - username: `%F{$prompt_pure_colors[user:root]}%n%f%F{$prompt_pure_colors[host]}@%m%f`
    - prompt: `❯`
    - version: `1.11.0`
- PROMPT: `typeset -g PROMPT=$'%F{$prompt_pure_colors[user:root]}%n%f%F{$prompt_pure_colors[host]}@%m%f %F{${prompt_pure_colors[path]}}%~%f
%}%(12V.%F{$prompt_pure_colors[virtualenv]}%12v%f .)%(?.%F{$prompt_pure_colors[prompt:success]}.%F{$prompt_pure_colors[prompt:error]})${prompt_pure_state[prompt]}%f '`
- Colors: `typeset -g -A prompt_pure_colors=( execution_time yellow git:action 242 git:arrow cyan git:branch 242 git:branch:cached red git:dirty 218 git:stash cyan host 242 path blue prompt:continuation 242 prompt:error red prompt:success magenta user 242 user:root default virtualenv 242 )`
- Virtualenv: `export VIRTUAL_ENV_DISABLE_PROMPT=12`
- Conda: `export CONDA_CHANGEPS1=no`
- Detected frameworks: Oh My Zsh
    - Oh My Zsh:
        - Plugins: git, nvm
```
#### I have:

- [x] Followed the [integration](https://github.com/sindresorhus/pure#integration) instructions for my framework
- [X] Tested with another terminal program and can reproduce the issue: 

### Problem description

When using windows wsl hostname is showing even when using locally.

### Reproduction steps

1. Install ubuntu for wsl.
2. Install ohmyzsh.
3. Install pure using manual instructions.

### My `.zshrc`:

```
export ZSH="/root/.oh-my-zsh"

ZSH_THEME=""

ZSH_DISABLE_COMPFIX=true

plugins=(git nvm)

source $ZSH/oh-my-zsh.sh

fpath+=$HOME/.zsh/pure
autoload -U promptinit; promptinit
prompt pure
```
![image](https://user-images.githubusercontent.com/56954025/78760963-34fe1e80-7982-11ea-8c2a-4cb00a07e1fb.png)

**Comment by mafredri** [comment]
Hi, this is pretty much as intended. We always show the username (and hostname) when the user is `root`. Have you considered using a non-root user in WSL? (Not sure if this is possible as I have no experience with it.)

**Comment by upedd** [comment]
Now it's looks like this: 
![image](https://user-images.githubusercontent.com/56954025/78777882-a0ec8100-799a-11ea-84c8-7b379cb38132.png)

**Comment by mafredri** [comment]
@upedd That's not pure, though. Looks like a bash theme.

**Comment by upedd** [comment]
Exactly same behavior on hyper:
![image](https://user-images.githubusercontent.com/56954025/78781581-d005f100-79a0-11ea-85bd-ed7c21389717.png)

**Comment by mafredri** [comment]
Please switch to `zsh` and use Pure for the user `uped`, what you're posting screenshots of is most likely `bash` with some theme not related to Pure.

**Comment by upedd** [comment]
Nvm powerlevel10k pure is not bugged.

**Comment by mafredri** [comment]
So far you did not show any bug, and from what I can tell, p10k behaves the same as Pure.
