### ISSUE TITLE
Disable tab title and git options

### ISSUE THREAD

**Issue by tysun** [sindresorhus/pure#548]
Hi

I only want the prompt and the virtualenvironment options. I do not want the tab title and I do not need the git options. 

I commented out the call to the `prompt_pure_async_tasks` function and two calls to the `prompt_pure_set_title` function and all seems ok. 

Is there anything else I should know? 

Thanks.

**Comment by mafredri** [comment]
I think your approach is fine, there nothing that I can think of that you need to know. But truth be told, it may be easier for you (maintenance wise) to just select the parts of Pure you like and make a lightweight theme out of it.
