### ISSUE TITLE
Cannot install pure-prompt with npm install!

### ISSUE THREAD

**Issue by shrihanDev** [sindresorhus/pure#554]
#### Other information

- Pure version: __Cannot install, so no version__
- ZSH version: Latest, as of 19-7-2020
- Terminal program & version: (e.g. Hyper 1.0.0, iTerm 3.0.0, xterm 327, other?) Cygwin
- Operating system: (e.g. macOS Mojave 10.13.1) Windows
- ZSH framework: (e.g. oh-my-zsh, prezto, antigen, antibody, zplug, other?) oh-my-zsh

#### I have:

- [ ] Tested with another terminal program and can reproduce the issue: 
- [x] Followed the [integration](https://github.com/sindresorhus/pure#integration) instructions for my framework

### Problem description
I followed the steps to install using ```npm install --global pure-prompt``` but it throws an error in Cygwin + ZSH + OhMyZsh

### Reproduction steps

1. Go to homepage of pure
2. Run the command  ```npm install --global pure-prompt``` : copy and paste
3. Get an error: 
```
> pure-prompt@1.12.0 postinstall C:\Users\AnotherUser.APPLE.000\AppData\Roaming\npm\node_modules\pure-prompt
> PURE_DEST=/usr/local/share/zsh/site-functions npm run --silent postinstall-link && exit 0; PURE_DEST="$PWD/functions" npm run postinstall-link && npm run postinstall-fail-instructions

'PURE_DEST' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pure-prompt@1.12.0 postinstall: `PURE_DEST=/usr/local/share/zsh/site-functions npm run --silent postinstall-link && exit 0; PURE_DEST="$PWD/functions" npm run postinstall-link && npm run postinstall-fail-instructions`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pure-prompt@1.12.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\AnotherUser.APPLE.000\AppData\Roaming\npm-cache\_logs\2020-07-19T10_08_29_841Z-debug.log
```
#### Screenshot: 
![Capture](https://user-images.githubusercontent.com/54971391/87872826-7ff3ed00-c9d9-11ea-92a3-a1b68d91b61c.PNG)
 
### My `.zshrc`:
NOTE: I can't install pure so no .zshrc!

**Comment by mafredri** [comment]
It looks like the NPM installation scripts aren't behaving like shell scripts as they do on e.g. macOS or Linux systems. Especially the environment variable is being interpreted as a command.

We'd be happy to fix this but unfortunately I don't have a Windows system to test on, and it also needs to work cross-platform. If anyone has any ideas here I'm all ears.

Thoughts on how to fix this:

- Prefix pure PURE_DEST with the `env`, but will it be available?
- Run the commands inside a shell interpreter like Bash, sh, etc, but what's available and guaranteed to work on all platforms?
- Detect OS and run separate commands, but we still need to figure out what works on Cygwin

For the time being, I would suggest the [Manual](https://github.com/sindresorhus/pure#manually) install method to you.

**Comment by shrihanDev** [comment]
> ...Prefix pure PURE_DEST with the `env`, but will it be available?
BTW, How to do that?

**Comment by shrihanDev** [comment]
And wait, can I install a Node.js version of macOS/Linux to somewhere near Cygwin?

**Comment by shrihanDev** [comment]
So I installed it "MANUALLY". It again throws an error: 
![Capture](https://user-images.githubusercontent.com/54971391/87875179-0403a000-c9ed-11ea-86f8-cfe01b71df13.PNG)

**Comment by mafredri** [comment]
What does your `.zshrc` look like? If there's nothing weird going on there, I'm afraid I can't be of much assistance. It looks like Zsh isn't working as it should. I have no experience with Cygwin and it has had issues in the past, see e.g. #439 and #141.

**Comment by shrihanDev** [comment]
So I installed powerlevel10k and they gave me the pure prompt! I am very happy now because I have a fully beautiful terminal! 

`$issue_state="closed"`
