### ISSUE TITLE
how to change position user@host, path and prompt:continuation

### ISSUE THREAD

**Issue by und3fined** [sindresorhus/pure#555]
Hi team,

In document show a pattern `user@host ~path git exe_time ...`
But in my prompt show `~path user@host ...`

So, how to change position any item in prompt?

**Comment by mafredri** [comment]
It should be resolved if you update Pure to the latest version.

**Comment by und3fined** [comment]
> It should be resolved if you update Pure to the latest version.

Thanks for reply, after i read the source code or pure.
This is my prompt
<img width="849" alt="Screen Shot 2020-08-03 at 16 46 14" src="https://user-images.githubusercontent.com/2163878/89169985-38f52280-d5a9-11ea-8041-cf8fd7594300.png">
