### ISSUE TITLE
`Prompt Pure` Fails in macOS Catalina

### ISSUE THREAD

**Issue by james-prado** [sindresorhus/pure#557]
### General information

- Pure version: 1.12.0
- ZSH version: 5.7.1
- Terminal program & version:  Hyper 3.0.2, and the default terminal app
- Operating system: macOS Catalina 10.15.6
- ZSH framework: none

#### I have:

- [x] Tested with another terminal program and can reproduce the issue: 
- [x] Followed the [integration](https://github.com/sindresorhus/pure#integration) instructions for my framework

### Problem description

`pure` is not available as a prompt theme

```
james.prado@MBPalti7 ~ % prompt -l
Currently available prompt themes:
adam1 adam2 bart bigfade clint default elite2 elite fade fire off oliver pws redhat restore suse walters zefram
```

### Reproduction steps

1. `npm install --global pure-prompt`
2. Follow the [Getting Started instructions](https://github.com/sindresorhus/pure#getting-started)

### My `.zshrc`:

```
autoload -U promptinit; promptinit 
prompt pure
```
### My `$fpath`:

```
echo $fpath
/usr/local/share/zsh/site-functions /usr/share/zsh/site-functions /usr/share/zsh/5.7.1/functions
```

**Comment by james-prado** [comment]
[Reinstalling `pure-prompt`](https://github.com/sindresorhus/pure/issues/116#issuecomment-333879864) worked, idk why though

**Comment by mafredri** [comment]
@james-prado did you perhaps open a new terminal in between? What may have happened is that (a) you installed pure but zsh did not yet know about the new file (b) then you opened a new terminal and zsh found out about Pure (c) then you reinstalled Pure which had no effect since the problem was solved in b.

**Comment by james-prado** [comment]
@mafredri I made sure to open a new terminal only after installing pure and modifying my `.zshrc` file.
