### ISSUE TITLE
Tab completion artifacts in container

### ISSUE THREAD

**Issue by brutalgg** [sindresorhus/pure#561]
#### System report (output of `prompt_pure_system_report`):
```prompt_pure_system_report:3: command not found: --version
- Zsh:  ()
- Operating system: Linux (#1 SMP Tue May 26 11:42:35 UTC 2020)
- Terminal program: unknown (unknown)
- Tmux: no
- Git: git version 2.20.1
- Pure state:
    - username: `''`
    - prompt: `$'�'$'�'$'�'`
    - version: `1.11.0`
- PROMPT: `typeset -g PROMPT=$'%F{${prompt_pure_colors[path]}}%~%f
%}%(12V.%F{$prompt_pure_colors[virtualenv]}%12v%f .)%(?.%F{$prompt_pure_colors[prompt:success]}.%F{$prompt_pure_colors[prompt:error]})${prompt_pure_state[prompt]}%f '`
- Colors: `typeset -g -A prompt_pure_colors=( [execution_time]=yellow [git:action]=yellow [git:arrow]=cyan [git:branch]=242 [git:branch:cached]=red [git:dirty]=218 [git:stash]=cyan [host]=242 [path]=blue [prompt:continuation]=242 [prompt:error]=red [prompt:success]=magenta [user]=242 [user:root]=default [virtualenv]=242 )`
- Virtualenv: `export VIRTUAL_ENV_DISABLE_PROMPT=12`
- Conda: `export CONDA_CHANGEPS1=no`
- Detected frameworks: None
```

#### I have:

- [ ] Tested with iTerm and Mac Terminal and can reproduce the issue
- [ ] Tested the Zsh autocomplete system without pure and confirmed the issue was not present

### Problem description
When using tab complete in a container environment with pure the tab completion leaves artifacts of text prior to the tab on screen. Ex.
```
~
❯ c c
c_rehash                   chmem                      comparguments              compvalues
capsh                      chmod                      compaudit                  continue
```

### Reproduction steps

1. Clone https://github.com/brutalgg/dotfiles
2. Build provided docker container eg. ```docker build -t dot /PATH/TO/REPO```
3. Attempt tabcomplete in container eg ```docker run --rm -it dot /bin/zsh```

### My `.zshrc`:
```
# .zshrc for 5.7.1
fpath+=("$HOME/.zsh/pure")
autoload -U promptinit; promptinit
autoload -Uz compinit && compinit -i
prompt pure
```

**Comment by mafredri** [comment]
This seems to be an issue with locales / UTF-8, which is required for the default Pure prompt character. For instance, if you update your Dockerfile to do the following:

```
apt install -y locales
echo en_US.UTF-8 UTF-8 >>/etc/locale.gen
dpkg-reconfigure locales
```

And also make sure the new locale is enabled:

```
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
```

This should fix the issue, it may be possible to simplify it though. Alternatively you could use a simple prompt character:

```
export PURE_PROMPT_SYMBOL='>'
```
