### ISSUE TITLE
Adding Git Short Hash to Prompt

### ISSUE THREAD

**Issue by Brandon-G-Tripp** [sindresorhus/pure#572]
I am looking to add the Short Hash of the current commit I am checking out. I have not found any information in the docs or in the various issues. Is there an easy way to add this to the prompt?

**Comment by mafredri** [comment]
I'm not sure what you're looking for. What is the behavior you're seeing, what would you like to see instead, etc?

My guess is that you'd want to change one of these values: https://github.com/sindresorhus/pure/blob/dfc8062c64df8821eaec7d741c75f3cee20d37e3/pure.zsh#L268-L269

You can look up zsh `vcs_info` documentation to figure out what options are available.

**Comment by Brandon-G-Tripp** [comment]
I will dig around that documentation thank you. I am looking to have a shortened version of the current Git commit Hash displayed in the prompt. I did not see a feature to add that directly in with the pure prompt setup. I have tried adding it in the .zshrc but it does not seem to integrate with the Pure theme.
