### ISSUE TITLE
Error message on every command: _zsh_autosuggest_highlight_reset:3: maximum nested function level reached; increase FUNCNEST?

### ISSUE THREAD

**Issue by diegosanz** [sindresorhus/pure#574]
#### System report (output of `prompt_pure_system_report`):

- Zsh: zsh 5.8 (x86_64-pc-linux-gnu) (/usr/bin/zsh)
- Operating system: Linux (5.8.16-2-MANJARO #1 SMP PREEMPT Mon Oct 19 11:33:03 UTC 2020 x86_64 GNU/Linux)
- Terminal program: unknown (unknown)
- Tmux: no
- Git: git version 2.28.0
- Pure state:
    - username: `''`
    - prompt: `❯`
    - version: `1.13.0`
- zsh-async version: `1.8.4`
- PROMPT: `typeset -g PROMPT=$'%F{${prompt_pure_colors[path]}}%~%f
%}%(12V.%F{$prompt_pure_colors[virtualenv]}%12v%f .)%(?.%F{$prompt_pure_colors[prompt:success]}.%F{$prompt_pure_colors[prompt:error]})${prompt_pure_state[prompt]}%f '`
- Colors: `typeset -g -A prompt_pure_colors=( [execution_time]=yellow [git:action]=yellow [git:arrow]=cyan [git:branch]=242 [git:branch:cached]=red [git:dirty]=218 [git:stash]=cyan [host]=242 [path]=blue [prompt:continuation]=242 [prompt:error]=red [prompt:success]=magenta [user]=242 [user:root]=default [virtualenv]=242 )`
- TERM: `export TERM=xterm-256color`
- Virtualenv: `export VIRTUAL_ENV_DISABLE_PROMPT=1`
- Conda: `export CONDA_CHANGEPS1=no`
- Detected frameworks: None

#### Other information
- Pure version: 1.13.0
- ZSH version: 5.8 (x86_64-pc-linux-gnu)
- Terminal program & version: konsole 20.08.1
- Operating system: Linux Manjaro (kernel 5.8.16)
- ZSH framework: zim 1.3.2

#### I have:

- [ x] Tested with another terminal program and can reproduce the issue: hyper
- [ x] Followed the [integration](https://github.com/sindresorhus/pure#integration) instructions for my framework

### Problem description

On every command y recive this message: `_zsh_autosuggest_highlight_reset:3: maximum nested function level reached; increase FUNCNEST?`

### Reproduction steps

1. Install zim manually: https://github.com/sindresorhus/pure#zim
2. Install pure with: https://github.com/sindresorhus/pure#zim
3. Close and open the terminal
4. Execute any command, por example: `cd`

### My `.zshrc`:

Is the zim .zshrc file by default:

``` zsh
setopt HIST_IGNORE_ALL_DUPS

bindkey -e

WORDCHARS=${WORDCHARS//[\/]}

ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets)


if [[ ${ZIM_HOME}/init.zsh -ot ${ZDOTDIR:-${HOME}}/.zimrc ]]; then
  # Update static initialization script if it's outdated, before sourcing it
  source ${ZIM_HOME}/zimfw.zsh init -q
fi
source ${ZIM_HOME}/init.zsh

bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

zmodload -F zsh/terminfo +p:terminfo
if [[ -n ${terminfo[kcuu1]} && -n ${terminfo[kcud1]} ]]; then
  bindkey ${terminfo[kcuu1]} history-substring-search-up
  bindkey ${terminfo[kcud1]} history-substring-search-down
fi

bindkey '^P' history-substring-search-up
bindkey '^N' history-substring-search-down
bindkey -M vicmd 'k' history-substring-search-up
bindkey -M vicmd 'j' history-substring-search-down
```

**Comment by mafredri** [comment]
This doesn't look like a Pure issue, perhaps you can take a look at what order `zsh-autosuggest` and `pure` is being activated?

**Comment by diegosanz** [comment]
Hi @mafredri , I'm not sure how to check if `zsh-autosuggest` is working. I can confirm that `pure` is working because the prompt changes.

In `.zimrc` I have this line: `zmodule sindresorhus/pure --source async.zsh --source pure.zsh`.
If I comment replace it by `zmodule sindresorhus/pure --source async.zsh`, removing `--source pure.zsh` it works.

`FUNCNEST` it's a variable system, right? If I execute `echo $FUNCNEST` it returns `500`. Should I increase it?

**Comment by mafredri** [comment]
I was referring to the fact that the error you are seeing comes from `zsh-autosuggest`, so look at how you are loading that. Perhaps you need to do it after Pure, or something.

**Comment by diegosanz** [comment]
I found my error. My `.zimrc` was the original created by zim, with the following content:

```
# Start configuration added by Zim install {{{
# -------
# Modules
# -------

# Sets sane Zsh built-in environment options.
zmodule environment
# Provides handy git aliases and functions.
zmodule git
# Applies correct bindkeys for input events.
zmodule input
# Sets a custom terminal title.
zmodule termtitle
# Utility aliases and functions. Adds colour to ls, grep and less.
zmodule utility

#
# Prompt
#
# Exposes git repository status information to prompts.
zmodule git-info
# A customizable version of steeef's prompt theme.
zmodule steeef

# Additional completion definitions for Zsh.
zmodule zsh-users/zsh-completions
# Enables and configures smart and extensive tab completion.
# completion must be sourced after zsh-users/zsh-completions
zmodule completion
# Fish-like autosuggestions for Zsh.
zmodule zsh-users/zsh-autosuggestions
# Fish-like syntax highlighting for Zsh.
# zsh-users/zsh-syntax-highlighting must be sourced after completion
zmodule zsh-users/zsh-syntax-highlighting
# Fish-like history search (up arrow) for Zsh.
# zsh-users/zsh-history-substring-search must be sourced after zsh-users/zsh-syntax-highlighting
zmodule zsh-users/zsh-history-substring-search
# }}} End configuration added by Zim install
```

I replaced the line `zmodule steeef` by `zmodule sindresorhus/pure --source async.zsh --source pure.zsh` and it works perfectly.

Thank you @mafredri for your help!
