### ISSUE TITLE
Way to ignore some git repository

### ISSUE THREAD

**Issue by memeplex** [sindresorhus/pure#577]
Sorry for using this issue to ask a question, but I don't know of a proper place to ask.

Usually my home directory is a git repository with tons of untracked files and a handful of tracked dotfiles.

I would like to remove any indication of this repository in pure.

Is there any way to achieve that? What do you suggest?

Thanks.

**Comment by mafredri** [comment]
Hi, you could achieve this quite easily by doing a small change to the Pure source code:

```diff
diff --git pure.zsh pure.zsh
index 57bb054..b732555 100644
--- pure.zsh
+++ pure.zsh
@@ -268,7 +268,9 @@ prompt_pure_async_vcs_info() {
 	zstyle ':vcs_info:git*' formats '%b' '%R' '%a'
 	zstyle ':vcs_info:git*' actionformats '%b' '%R' '%a'
 
-	vcs_info
+	if [[ $HOME != $(git rev-parse --show-toplevel 2>/dev/null) ]]; then
+		vcs_info
+	fi
 
 	local -A info
 	info[pwd]=$PWD
```

There may be other, and better ways, but this was a quick hack, you could look at the zsh `vcs_info` documentation to see if there's a way to do it that way. Currently we have no way to define that a git repository should be ignored, but we do avoid performing `git fetch` in `$HOME`.

**Comment by memeplex** [comment]
Thanks for the tip! I opted for a different solution which puts the git repository "aside" the folder hierarchy, something like:

```
alias home="git --git-dir $HOME/.git-home --work-tree=$HOME"
```

This play better with other software, not only pure.

**Comment by aheckler** [comment]
I was able to achieve this by adding a line to `.zshrc`:

`zstyle ':vcs_info:*:*:Adam' formats "%0.0r"`

... where `Adam` is of course my username. Source:

https://unix.stackexchange.com/questions/494090/how-can-i-disable-vcs-info-for-a-specific-repository

I'm not 100% sure this is the ideal/proper way, but it does cause my `$HOME` dotfiles repo to be ignored, but other repos nested inside $HOME work OK.

<img width="327" alt="Screenshot taken on 2021-12-16 at 12 02 08 UTC@2x" src="https://user-images.githubusercontent.com/5512652/146368168-1d432c5f-ea9e-40b0-ba1c-d69257cd2a21.png">
