### ISSUE TITLE
set default theme faield

### ISSUE THREAD

**Issue by hermitcai** [sindresorhus/pure#580]
### General information

i set after
![image](https://user-images.githubusercontent.com/45086633/104120306-c4e95280-5370-11eb-9af0-ecf4340bcc18.png)
why this title bar color
not like  default
![image](https://user-images.githubusercontent.com/45086633/104120319-dc284000-5370-11eb-8aa0-5caf304207e1.png)

#### I have:

- [ ] Tested with another terminal program and can reproduce the issue: 
- [ ] Followed the [integration](https://github.com/sindresorhus/pure#integration) instructions for my framework

### Reproduction steps

1.
2.
3.

**Comment by mafredri** [comment]
The screenshot uses a different terminal and color theme -- there's a difference between prompt theme and terminal color. For instance, if Pure informs a terminal to use "blue", the terminal itself decides which type of blue.

Check out the [Tips-section](https://github.com/sindresorhus/pure#tips) in the readme for re-creating the same look.
