### ISSUE TITLE
Dirty submodules ignored if PURE_GIT_UNTRACKED_DIRTY=1

### ISSUE THREAD

**Issue by dc46and2** [sindresorhus/pure#582]
### General information
If `PURE_GIT_UNTRACKED_DIRTY=0`, then the prompt will show the repo is dirty if submodules are dirty. However, if `PURE_GIT_UNTRACKED_DIRTY=1` (the default), then dirty submodules are ignored. I would prefer that dirty submodules are never ignored.

#### System report (output of `prompt_pure_system_report`):

- Zsh: zsh 5.8 (x86_64-ubuntu-linux-gnu) (/usr/bin/zsh)
- Operating system: Linux (4.4.0-19041-Microsoft #488-Microsoft Mon Sep 01 13:43:00 PST 2020 x86_64 GNU/Linux)
- Terminal program: unknown (unknown)
- Tmux: no
- Git: git version 2.25.1
- Pure state:
    - username: `''`
    - prompt: `'$'`
    - version: `1.13.0`
- zsh-async version: `1.8.4`
- PROMPT: `typeset -g PROMPT=$'%F{${prompt_pure_colors[path]}}%~%f
%}%(12V.%F{$prompt_pure_colors[virtualenv]}%12v%f .)%(?.%F{$prompt_pure_colors[prompt:success]}.%F{$prompt_pure_colors[prompt:error]})$prompt_pure_state[prompt]}%f '`
- Colors: `typeset -g -A prompt_pure_colors=( [execution_time]=yellow [git:action]=yellow [git:arrow]=cyan [git:branch]=242 [git:branchcached]=red [git:dirty]=218 [git:stash]=cyan [host]=242 [path]=blue [prompt:continuation]=242 [prompt:error]=red [prompt:success]=magena [user]=242 [user:root]=default [virtualenv]=242 )`
- TERM: `export TERM=xterm-256color`
- Virtualenv: `export VIRTUAL_ENV_DISABLE_PROMPT=12`
- Conda: `export CONDA_CHANGEPS1=no`
- Detected frameworks: Oh My Zsh
    - Oh My Zsh:
        - Plugins: git, svn-fast-info, colored-man-pages

#### Other information
This patch fixes the issue for me, but maybe there was a good reason you were ignoring submodules?

```diff
diff --git a/pure.zsh b/pure.zsh
index 271c1cc..646f5e6 100644
--- a/pure.zsh
+++ b/pure.zsh
@@ -291,7 +291,7 @@ prompt_pure_async_git_dirty() {
    if [[ $untracked_dirty = 0 ]]; then
        command git diff --no-ext-diff --quiet --exit-code
    else
-       test -z "$(GIT_OPTIONAL_LOCKS=0 command git status --porcelain --ignore-submodules -u${untracked_git_mode})"
+       test -z "$(GIT_OPTIONAL_LOCKS=0 command git status --porcelain -u${untracked_git_mode})"
    fi

    return $?
```

**Comment by mafredri** [comment]
Hmm, this behavior is very confusing, we should at least have them behave the same way (either add `--ignore-submodules` to `git diff` or, as suggested, remove from `git status`).

The reason submodules are ignored is at least in part for performance reasons, see #102 for history.

Thoughts @sindresorhus?

**Comment by sindresorhus** [comment]
I don't use submodules, so I don't have strong feelings about it. As long as it doesn't affect performance too much, I'm fine with including it.
