### ISSUE TITLE
Simple question hopefully with simple answer

### ISSUE THREAD

**Issue by o6uoq** [sindresorhus/pure#585]
New to Pure and am wondering if there is a quick way before I start editing `pure.zsh` to enable `username@hostname` in the first line of my prompt?

Current Example:
`~/test branch*`
`❯ `

Wanted:
`name@hostname ~/test branch*`
 `❯ `

**Comment by sindresorhus** [comment]
From the readme:

> Username and host only displayed when in an SSH session or a container.

Displaying it otherwise is just noise.

**Comment by o6uoq** [comment]
Right, but I don't care if it's noise -- I want to know if it's possible as a flag/option before I edit `pure.zsh`

**Comment by mafredri** [comment]
It's not possible via configuration, although I could see a use case for it outside of just preference (i.e. sometimes it may be impossible to detect e.g. the SSH connection or similar).

But modifying Pure should be pretty easy, if you want it to always be displayed you can replace all of these lines:

https://github.com/sindresorhus/pure/blob/b83ad6dcb0726feec1cce550d84fc710e2ef7912/pure.zsh#L649-L689

With just:

```zsh
username='%F{$prompt_pure_colors[user]}%n%f'"$hostname"
```

**Comment by dkiyatkin** [comment]
You can init pure like this:
```
local container=lxc
autoload -U promptinit; promptinit
prompt pure
```
That worked for me.

**Comment by o6uoq** [comment]
No Longer Required

**Comment by mafredri** [comment]
@dkiyatkin that's not a supported method and can break at any moment. Just FYI and for anyone else reading it.
