### ISSUE TITLE
command not found: prompt when I use pure single-line-prompt with zinit.

### ISSUE THREAD

**Issue by Skyearn** [sindresorhus/pure#587]
If you can't load Pure to create a system report, please report the following information:

- Pure version: 1.16.0
- ZSH version: 5.8
- Terminal program & version:Terminal 2.11(440) (e.g. Hyper 1.0.0, iTerm 3.0.0, xterm 327, other?)
- Operating system: 11.3(e.g. macOS Mojave 10.13.1)
- ZSH framework: zinit (e.g. oh-my-zsh, prezto, antigen, antibody, zplug, other?)
-->

### Problem description
It’s work fine until I add `prompt pure
prompt_newline='%666v'
PROMPT=" $PROMPT"`to  ~/.zshrc.
I got this error:command not found: prompt

### Reproduction steps

1.add `prompt pure
prompt_newline='%666v'
PROMPT=" $PROMPT"`to  ~/.zshrc.
2.restart terminal

### My `.zshrc`:
```export HOMEBREW_BOTTLE_DOMAIN=https://mirrors.ustc.edu.cn/homebrew-bottles
export PATH="/usr/local/opt/icu4c/bin:$PATH"
export PATH="/usr/local/opt/icu4c/sbin:$PATH"
export LDFLAGS="-L/usr/local/opt/icu4c/lib"
export CPPFLAGS="-I/usr/local/opt/icu4c/include"

### Added by Zinit's installer
if [[ ! -f $HOME/.zinit/bin/zinit.zsh ]]; then
    print -P "%F{33}▓▒░ %F{220}Installing %F{33}DHARMA%F{220} Initiative Plugin Manager (%F{33}zdharma/zinit%F{220})…%f"
    command mkdir -p "$HOME/.zinit" && command chmod g-rwX "$HOME/.zinit"
    command git clone https://github.com/zdharma/zinit "$HOME/.zinit/bin" && \
        print -P "%F{33}▓▒░ %F{34}Installation successful.%f%b" || \
        print -P "%F{160}▓▒░ The clone has failed.%f%b"
fi

source "$HOME/.zinit/bin/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

zinit ice compile'(pure|async).zsh' pick'async.zsh' src'pure.zsh'
zinit light sindresorhus/pure

prompt pure
prompt_newline='%666v'
PROMPT=" $PROMPT"

zinit light zdharma/fast-syntax-highlighting
zinit ice lucid wait='0' atload='_zsh_autosuggest_start'
zinit load zsh-users/zsh-autosuggestions

# Load a few important annexes, without Turbo
# (this is currently required for annexes)
zinit light-mode for \
    zinit-zsh/z-a-rust \
    zinit-zsh/z-a-as-monitor \
    zinit-zsh/z-a-patch-dl \
    zinit-zsh/z-a-bin-gem-node

### End of Zinit's installer chunk
```

**Comment by mafredri** [comment]
The `prompt` command is part of `promptinit`, but I don't see it initialized anywhere in your `zshrc`. Try adding this:

```
autoload -U promptinit; promptinit
```

**Comment by Skyearn** [comment]
Thank you, it's work. and  reply so fast. Thank you again.

**Comment by gbaranski** [comment]
Hello, I'm trying the exactly same config as you, but `pure prompt` returns help page, `prompt -l` also doesn't show `pure`. However `pure` works. 
Pure version: `1.13`, for some reason I can't install Pure using zinit in version higher than that.
OS: Arch Linux: 5.11
