### ISSUE TITLE
How does vi mode work? 

### ISSUE THREAD

**Issue by Sleepful** [sindresorhus/pure#588]
Is it different from OMZ vi-mode?

It seems I can't stay in normal mode for more than 1 keystroke.

The vi mode indicator doesn't change either.

**Comment by mafredri** [comment]
We can't really help you unless you fill out the issue template, I have questions that would've been answered by doing so.

> Is it different from OMZ vi-mode?

I don't know about vi-mode in OMZ, we simply support showing the indicator and don't make assumption about how our users want to use vi-mode.
