### ISSUE TITLE
How can I do to remove extra white line between two command lines when I set single-line prompts.

### ISSUE THREAD

**Issue by Skyearn** [sindresorhus/pure#589]
#### System report (output of `prompt_pure_system_report`):
- Zsh: zsh 5.8 (x86_64-apple-darwin20.0) (/bin/zsh)
- Operating system: macOS 11.3 (20E5224a)
- Terminal program: Apple_Terminal (440)
- Tmux: no
- Git: git version 2.24.3 (Apple Git-128)
- Pure state:
    - username: `''`
    - prompt: `❯`
    - version: `1.16.0`
- zsh-async version: `1.8.4`
- PROMPT: `typeset -g PROMPT='%F{${prompt_pure_colors[path]}}%~%f%666v %(12V.%F{$prompt_pure_colors[virtualenv]}%12v%f .)%(?.%F{$prompt_pure_colors[prompt:success]}.%F{$prompt_pure_colors[prompt:error]})${prompt_pure_state[prompt]}%f '`
- Colors: `typeset -g -A prompt_pure_colors=( [execution_time]=yellow [git:action]=yellow [git:arrow]=cyan [git:branch]=242 [git:branch:cached]=red [git:dirty]=218 [git:stash]=cyan [host]=242 [path]=blue [prompt:continuation]=242 [prompt:error]=red [prompt:success]=magenta [user]=242 [user:root]=default [virtualenv]=242 )`
- TERM: `export TERM=xterm-256color`
- Virtualenv: `export VIRTUAL_ENV_DISABLE_PROMPT=12`
- Conda: `export CONDA_CHANGEPS1=no`
- Detected frameworks: None

#### I have:
Just a display problem.

### Problem description
I set ~/.zshrc as https://github.com/sindresorhus/pure/issues/228 for single-line prompts, then this caused a new problem, there are extra white line between two command lines. and I have no way to solve this problem.

It's mine:
![](https://user-images.githubusercontent.com/29571915/114839263-26094200-9e08-11eb-9806-0ef701b596d4.png)

I want change it like this:
![](https://cloud.githubusercontent.com/assets/147409/25740894/294b9c20-3191-11e7-947f-b3ac1597f69f.png)

### Reproduction steps

1.Add prompt pure
prompt_newline='%666v'
PROMPT=" $PROMPT" to ~/.zshrc
2.source ~/.zshrc
3.

### My `.zshrc`:
export HOMEBREW_BOTTLE_DOMAIN=https://mirrors.ustc.edu.cn/homebrew-bottles
export PATH="/usr/local/opt/icu4c/bin:$PATH"
export PATH="/usr/local/opt/icu4c/sbin:$PATH"
export LDFLAGS="-L/usr/local/opt/icu4c/lib"
export CPPFLAGS="-I/usr/local/opt/icu4c/include"

eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

source "$HOME/.zinit/bin/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

autoload -U promptinit; promptinit
prompt pure
prompt_newline='%666v'
PROMPT=" $PROMPT"

zinit ice lucid wait'!0'
zinit light zdharma/fast-syntax-highlighting

zinit ice lucid wait'!0'
zinit light zsh-users/zsh-autosuggestions

zinit light-mode for \
    zinit-zsh/z-a-rust \
    zinit-zsh/z-a-as-monitor \
    zinit-zsh/z-a-patch-dl \
    zinit-zsh/z-a-bin-gem-node

bindkey "\e[1~" beginning-of-line
bindkey "\e[4~" end-of-line
bindkey "\e[5~" beginning-of-history
bindkey "\e[6~" end-of-history

bindkey "\e[8~" end-of-line
bindkey "\e[7~" beginning-of-line
bindkey "\eOH" beginning-of-line
bindkey "\eOF" end-of-line
bindkey "\e[H" beginning-of-line
bindkey "\e[F" end-of-line
bindkey '^i' expand-or-complete-prefix

bindkey -s "^[Op" "0"
bindkey -s "^[On" "."
bindkey -s "^[OM" "^M"
bindkey -s "^[Oq" "1"
bindkey -s "^[Or" "2"
bindkey -s "^[Os" "3"
bindkey -s "^[Ot" "4"
bindkey -s "^[Ou" "5"
bindkey -s "^[Ov" "6"
bindkey -s "^[Ow" "7"
bindkey -s "^[Ox" "8"
bindkey -s "^[Oy" "9"
bindkey -s "^[Ol" "+"
bindkey -s "^[Om" "-"
bindkey -s "^[Oj" "*"
bindkey -s "^[Oo" "/"

<!--
Please provide a minimal `.zshrc` that reproduces the issue.
Try to remove everything that that does not affect the issue, the fewer lines, the better.

**Comment by isagues** [comment]
#https://github.com/sindresorhus/pure/issues/509#issuecomment-571439009

**Comment by Skyearn** [comment]
prompt_newline='%666v'
PROMPT=" $PROMPT" to ~/.zshrc
print() {
  [ 0 -eq $# -a "prompt_pure_precmd" = "${funcstack[-1]}" ] || builtin print "$@";
}
