### ISSUE TITLE
Add option to disable pure completely

### ISSUE THREAD

**Issue by thompsonbrian** [sindresorhus/pure#590]
#### Feature request

Pure is a great minimalist theme.  However, I cannot find any simple way to disable pure completely if I want to switch back to another zsh theme, like the ones installed with oh-my-zsh.

It would be great if there were an option to disable pure completely, such as `DISABLE_PURE=[true/false]`.  Unfortunately, I don't have much time to develop this feature myself.  It'd probably be pretty simple if I looked at the code, but perhaps not.

Thank you for pure!

**Comment by msagarpatel** [comment]
Have you tried commenting out [these two lines](https://github.com/sindresorhus/pure#getting-started) in .zshrc? Then, just set `ZSH_THEME` to whatever you like _before_ `source $ZSH/oh-my-zsh.sh`. This is probably the best way to disable pure, and use another prompt.

Setting a `DISABLE_PURE` variable is probably gonna be messy (or infeasible) depending on how you want it to work.

**Comment by thompsonbrian** [comment]
Ah yes, I forgot to close this after I resolved it.  I basically did what you suggested.  Thanks for the tip!
