### ISSUE TITLE
confusion in installation

### ISSUE THREAD

**Issue by shobhitparvan** [sindresorhus/pure#595]
![Screenshot](https://user-images.githubusercontent.com/74949281/121048591-8f884a00-c7d4-11eb-91dd-77a90ac8f4d2.png)

was this suppose to happen?(in output.txt)[output.txt](https://github.com/sindresorhus/pure/files/6610277/output.txt)

What is the name of this theme you used in the screenshot?

**Comment by sindresorhus** [comment]
I think the error is pretty clear if you read it. The problem is with your npm installation. Try what it suggests. 

npm support: https://www.npmjs.com/support
