### ISSUE TITLE
Pure takes 100% of a single core

### ISSUE THREAD

**Issue by dcervenkov** [sindresorhus/pure#596]
#### System report (output of `prompt_pure_system_report`):

- Zsh: zsh 5.0.2 (x86_64-redhat-linux-gnu) (/bin/zsh)
- Operating system: Linux (3.10.0-1160.24.1.el7.x86_64 #1 SMP Thu Apr 8 19:51:47 UTC 2021 x86_64 GNU/Linux)
- Terminal program: unknown (unknown)
- Tmux: yes
- Git: git version 2.9.5
- Pure state:
    - username: `'%F{$prompt_pure_colors[user]}%n%f%F{$prompt_pure_colors[host]}@%m%f'`
    - prompt: `❯`
    - version: `1.13.0`
- zsh-async version: `1.8.4`
- PROMPT: `typeset PROMPT='%F{$prompt_pure_colors[user]}%n%f%F{$prompt_pure_colors[host]}@%m%f %F{${prompt_pure_colors[path]}}%~%f
%}%(12V.%F{$prompt_pure_colors[virtualenv]}%12v%f .)%(?.%F{$prompt_pure_colors[prompt:success]}.%F{$prompt_pure_colors[prompt:error]})${prompt_pure_state[prompt]}%f '`
- Colors: `typeset -A prompt_pure_colors
prompt_pure_colors=(execution_time yellow git:action yellow git:arrow cyan git:branch 242 git:branch:cached red git:dirty 218 git:stash cyan host 242 path blue prompt:continuation 242 prompt:error red prompt:success magenta user 242 user:root default virtualenv 242 )`
- TERM: `typeset -x TERM=screen-256color`
- Virtualenv: `typeset -x VIRTUAL_ENV_DISABLE_PROMPT=12`
- Conda: `typeset -x CONDA_CHANGEPS1=no`
- Detected frameworks: None

#### Other information

Not sure why the system report says that the pure version is 1.13.0 - I just clone the git repository and the `~/.zsh/pure/package.json` says 1.16.0.

#### I have:

- [x] Tested with another terminal program and can reproduce the issue: 
- [x] Followed the [integration](https://github.com/sindresorhus/pure#integration) instructions for my framework

### Problem description

Whenever I launch `zsh` it takes 100% of a single core. This happens only on one particular machine and is perfectly reproducible - it happens every time, all the time.

When I remove the `prompt pure` line from my `.zshrc`, idle `zsh` consumes no resources.

I ran `strace zsh` and after the initialization, I see a continuous stream of the following line:
```
poll([{fd=10, events=POLLIN}, {fd=12, events=POLLIN}], 2, -1) = 1 ([{fd=12, revents=POLLNVAL}])
```

### Reproduction steps

1. Launch `zsh`

### My `.zshrc`:

```sh
fpath+=$HOME/.zsh/pure                                                                                                                     
autoload -U promptinit; promptinit                                                                                                         
prompt pure  
```

**Comment by mafredri** [comment]
This is an issue with using zpty (via zsh-async) on 5.0.2. Unfortunately there’s not much we can do to fix the issue :/.

If possible I’d recommend updating to 5.1 or newer (preferably a lot newer).

https://github.com/mafredri/zsh-async/issues/12#issuecomment-387094843

One option would be to implement an alternative async mode as described here: https://github.com/mafredri/zsh-async/issues/24 but I haven’t had time to work on it.

I have some experimental and hacky branches that are very much WIP but may provide an improved experience on 5.0.2 or not work at all. Sorry, I can’t even remember what is in which branch: https://github.com/mafredri/zsh-async/branches

One of them doesn’t use zpty but no idea if it works on 5.0.2 and it’s not exactly on feature parity.

**Comment by dcervenkov** [comment]
Thanks for the speedy response! Oh, I see. As you can guess from the 3.10 kernel, this isn't a cutting edge machine, software-wise (university cluster). I'll try to compile a newer version of zsh myself and see how that goes. Feel free to close the issue as the problem is apparently well known and a workaround exists.
