### ISSUE TITLE
Is bold text supported?

### ISSUE THREAD

**Issue by nwaywood** [sindresorhus/pure#601]
I would like to make the `path` text bold. Is this possible?

I tried 

```
zstyle :prompt:pure:path color cyan:bold
```

as well as a few other variants but no luck

**Comment by nwaywood** [comment]
I got it working by changing line 138 to this:

`preprompt_parts+=('%B%F{${prompt_pure_colors[path]}}%~%f%b')`

going to keep this ticket open though in the hope that its possible to do through config somehow

**Comment by erusev** [comment]
> I got it working by changing line 138 to this:
> 
> `preprompt_parts+=('%B%F{${prompt_pure_colors[path]}}%~%f%b')`
> 
> going to keep this ticket open though in the hope that its possible to do through config somehow
> 
> Edit: nvm, I need to modify the script for other changes I want anyway so doing it via %B and %b is fine for me

Is this still the way to make `path` bold? Where do should I add the `preprompt_parts+=...` line?
