### ISSUE TITLE
brew specific installation instructions

### ISSUE THREAD

**Issue by moquette** [sindresorhus/pure#605]
### General information
I've successfully installed it using the manual method.  But where can I find specific installation instructions when using brew?

#### I have:

n/a
- [ ] Tested with another terminal program and can reproduce the issue: 
- [ ] Followed the [integration](https://github.com/sindresorhus/pure#integration) instructions for my framework

### Problem description
Unable to configure when installing with home brew.

### Reproduction steps

1. brew install pure
2. How do I configure using .zsh now?
3.

### My `.zshrc`:

The above example works fine with manual git clone method.  But the fails to work with brew method.

Thanks!

**Comment by mafredri** [comment]
The error output from the npm install has two suggestions, one is manual and the other is to update your `.zshrc` with the `fpath`, the latter should work for everybody and allows updates via `npm`.

That said, are you installing on an M1 Mac? If so see #584. I also just created #606 which may fix the issue (if you are on M1).

**Comment by mafredri** [comment]
I just re-read this and realized I missed the part about using `brew`. We don't actually maintain the `brew` install method, and as such can't really provide support for it. However, I imagine it should be available as a `prompt` after the `brew install`.

I.e. the full instruction would be:

```
brew install pure
autoload -Uz promptinit; prompt pure
```

The command `prompt -l` should show it listed. These are probably instructions that could/should be added to the Homebrew post-install for the pure formula.
