### ISSUE TITLE
async_worker_eval not found And bad set of key/value pairs in prompt_pure_async_callback

### ISSUE THREAD

**Issue by lalitaalaalitah** [sindresorhus/pure#608]
#### System report (output of `prompt_pure_system_report`):

- Zsh: zsh 5.8 (x86_64-apple-darwin20.0) (/bin/zsh)
- Operating system: macOS 11.5.2 (20G95)
- Terminal program: iTerm.app (3.4.9)
- Tmux: no
- Git: git version 2.33.0
- Pure state:
    - username: `''`
    - prompt: `❯`
    - version: `1.17.2`
- zsh-async version: ``
- PROMPT: `typeset -g PROMPT=$'%F{${prompt_pure_colors[path]}}%~%f
%{
%}%(12V.%F{$prompt_pure_colors[virtualenv]}%12v%f .)%(?.%F{$prompt_pure_colors[prompt:success]}.%F{$prompt_pure_colors[prompt:error]})${prompt_pure_state[prompt]}%f '`
- Colors: `typeset -g -A prompt_pure_colors=( [execution_time]=yellow [git:action]=yellow [git:arrow]=cyan [git:branch]=242 [git:branch:cached]=red [git:dirty]=218 [git:stash]=cyan [host]=242 [path]=blue [prompt:continuation]=242 [prompt:error]=red [prompt:success]=magenta [user]=242 [user:root]=default [virtualenv]=242 )`
- TERM: `export TERM=xterm-256color`
- Virtualenv: `export VIRTUAL_ENV_DISABLE_PROMPT=12`
- Conda: `export CONDA_CHANGEPS1=no`
- Detected frameworks: Oh My Zsh
    - Oh My Zsh:
        - Plugins: zsh-history-enquirer, git, bundler, dotenv, osx, rake, rbenv, ruby, python, zsh-syntax-highlightings, fzf, aws, zsh-completions, z
#### I have:

- [ x] Tested with another terminal program and can reproduce the issue: 
- [ x] Followed the [integration](https://github.com/sindresorhus/pure#integration) instructions for my framework

### Problem description

After updating to the latest version with brew, I'm seeing two errors. One is `prompt_pure_async_tasks:7: command not found: async_worker_eval` and other is `prompt_pure_async_callback:35: bad set of key/value pairs for associative array`.

### Reproduction steps

There are no specific steps. These errors are showing everytime.

### My `.zshrc`:

fpath+=("/usr/local/share/zsh/site-functions")
autoload -Uz promptinit
  promptinit
  prompt pure

**Comment by mafredri** [comment]
Homebrew isn't really a supported installation method, however, the error does look like an outdated version of zsh-async is being loaded from somewhere. I'd suggest going through all your `$fpath`s and verifying that there aren't multiple copies of zsh-async. Latest async in Homebrew is 1.8.5 which should have the `async_worker_eval` function.

Could perhaps also be caused by something in Oh-My-Zsh.

**Comment by lalitaalaalitah** [comment]
Nuked installs with Homebrew, tried npm install that also failed so nuked, manual install works as intended.
