### ISSUE TITLE
Installation on Raspberry Pi 4 running Ubuntu 20.04 LTS fails

### ISSUE THREAD

**Issue by pommetjehorlepiep** [sindresorhus/pure#610]
#### System report (output of `prompt_pure_system_report`):

```
rpi4% prompt_pure_system_report
zsh: command not found: prompt_pure_system_report
```

#### I have:

- [ ] Tested with another terminal program and can reproduce the issue: 
- [x] Followed the [integration](https://github.com/sindresorhus/pure#integration) instructions for my framework

### Problem description
- Does not work: `npm install --global pure-prompt`
```
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/pure-prompt
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules
npm ERR! code EACCES
npm ERR! syscall access
npm ERR! path /usr/local/lib/node_modules/pure-prompt
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules/pure-prompt'
npm ERR!  { [Error: EACCES: permission denied, access '/usr/local/lib/node_modules/pure-prompt']
npm ERR!   stack:
npm ERR!    'Error: EACCES: permission denied, access \'/usr/local/lib/node_modules/pure-prompt\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules/pure-prompt' }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
```
- Does not work: `sudo npm install --global pure-prompt`
```
[sudo] password for ....: 

> pure-prompt@1.17.2 postinstall /usr/local/lib/node_modules/pure-prompt
> if [[ -e /opt/homebrew/bin/zsh ]]; then PURE_DEST=/opt/homebrew/share/zsh/site-functions npm run --silent postinstall-link && exit 0; elif [[ -e /usr/local/bin/zsh ]]; then PURE_DEST=/usr/local/share/zsh/site-functions npm run --silent postinstall-link && exit 0; elif [[ -e /bin/zsh ]] || [[ -e /usr/bin/zsh ]]; then PURE_DEST=/usr/share/zsh/site-functions npm run --silent postinstall-link && exit 0; fi; PURE_DEST="$PWD/functions" npm run --silent postinstall-link && npm run --silent postinstall-fail-instructions

sh: 1: [[: not found
sh: 1: [[: not found
sh: 1: [[: not found
sh: 1: [[: not found
glob error { [Error: EACCES: permission denied, scandir '/root/.npm/_logs']
  errno: -13,
  code: 'EACCES',
  syscall: 'scandir',
  path: '/root/.npm/_logs' }
npm ERR! code ELIFECYCLE
npm ERR! errno 243
npm ERR! pure-prompt@1.17.2 postinstall: `if [[ -e /opt/homebrew/bin/zsh ]]; then PURE_DEST=/opt/homebrew/share/zsh/site-functions npm run --silent postinstall-link && exit 0; elif [[ -e /usr/local/bin/zsh ]]; then PURE_DEST=/usr/local/share/zsh/site-functions npm run --silent postinstall-link && exit 0; elif [[ -e /bin/zsh ]] || [[ -e /usr/bin/zsh ]]; then PURE_DEST=/usr/share/zsh/site-functions npm run --silent postinstall-link && exit 0; fi; PURE_DEST="$PWD/functions" npm run --silent postinstall-link && npm run --silent postinstall-fail-instructions`
npm ERR! Exit status 243
npm ERR! 
npm ERR! Failed at the pure-prompt@1.17.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
```
Because `/bin/sh` is symlinked by default to `/bin/dash`

- Does work: `sudo npm install --global --allow-root --unsafe-perm=true pure-prompt`
After changing symlinking `/bin/sh` to `/bin/bash`

```
sudo npm install --global pure-prompt --allow-root --unsafe-perm=true

> pure-prompt@1.17.2 postinstall /usr/local/lib/node_modules/pure-prompt
> if [[ -e /opt/homebrew/bin/zsh ]]; then PURE_DEST=/opt/homebrew/share/zsh/site-functions npm run --silent postinstall-link && exit 0; elif [[ -e /usr/local/bin/zsh ]]; then PURE_DEST=/usr/local/share/zsh/site-functions npm run --silent postinstall-link && exit 0; elif [[ -e /bin/zsh ]] || [[ -e /usr/bin/zsh ]]; then PURE_DEST=/usr/share/zsh/site-functions npm run --silent postinstall-link && exit 0; fi; PURE_DEST="$PWD/functions" npm run --silent postinstall-link && npm run --silent postinstall-fail-instructions

+ pure-prompt@1.17.2
updated 1 package in 5.833s
```

### Reproduction steps

See above

### My `.zshrc`:

```shell
# Pure prompt
autoload -U promptinit; promptinit

zstyle :prompt:pure:host      color 250
zstyle :prompt:pure:path      color green
zstyle :prompt:pure:user:root color red

prompt pure
# Pure prompt
```

**Comment by pommetjehorlepiep** [comment]
Although installed, pure theme not recognized
```
rpi4% prompt -l
Currently available prompt themes:
adam1 adam2 bart bigfade clint default elite2 elite fade fire off oliver pws redhat restore suse walters zefram
```

**Comment by mafredri** [comment]
In the past installing pure via npm as root hasn't been supported, however, with a recent change (#606) this was supposed to become possible, but it turns out the location of `site-functions` is not as I expected on Debian/Ubuntu.

I'll create a PR for improving the folder detection in the installer later today, on your part this will probably require removing the `/usr/share/zsh/site-functions` folder **if it has been created by npm install** (e.g. check the date).

**Comment by pommetjehorlepiep** [comment]
> In the past installing pure via npm as root hasn't been supported, however, with a recent change (#606) this was supposed to become possible, but it turns out the location of `site-functions` is not as I expected on Debian/Ubuntu.
> 
> I'll create a PR for improving the folder detection in the installer later today, on your part this will probably require removing the `/usr/share/zsh/site-functions` folder **if it has been created by npm install** (e.g. check the date).

Excellent! Thx.

**Comment by mafredri** [comment]
@pommetjehorlepiep didn't have time to create the PR before now, would you mind taking it for a spin (#611)? Checking out the repo and running `npm install` (as root, I suppose) should sufficiently simulate what happens during a regular install.

**Comment by pommetjehorlepiep** [comment]
> @pommetjehorlepiep didn't have time to create the PR before now, would you mind taking it for a spin (#611)? Checking out the repo/PR and running `npm install` (as root, I suppose) should sufficiently simulate what happens during a regular install.

Your change fixed the issue!

- First removed `/usr/share/zsh/site-functions` (as suggested above)
- Checked out code
- Applied the change as per #611 
- Ran as `root`:  `npm install --allow-root --unsafe-perm=true`  (from within the git repo directory)

> **Output:**
> ```
> rpi4# npm install --allow-root --unsafe-perm=true 
> 
> > pure-prompt@1.17.2 postinstall /tmp/pure
> > if [ -e /opt/homebrew/bin/zsh ]; then PURE_DEST=/opt/homebrew/share/zsh/site-functions npm run --silent postinstall-link && exit 0; elif [ -e /usr/local/bin/zsh ]; then PURE_DEST=/usr/local/share/zsh/site-functions npm run --silent postinstall-link && exit 0; elif [ -e /bin/zsh ] || [ -e /usr/bin/zsh ]; then for dest in /usr/share/zsh/site-functions /usr/local/share/zsh/site-functions; do if [ -d $dest ]; then PURE_DEST=$dest npm run --silent postinstall-link && exit 0; fi; done; fi; PURE_DEST="$PWD/functions" npm run --silent postinstall-link && npm run --silent postinstall-fail-instructions
> 
> up to date in 5.484s
> found 0 vulnerabilities
> ```
> 

- Exit & Login again ==>  SUCCESS!
- `prompt -l` now shows:  

```
❯ prompt -l
Currently available prompt themes:
pure adam1 adam2 bart bigfade clint default elite2 elite fade fire off oliver pws redhat restore suse walters zefram
```

Thanks for all your help and the quick fix @mafredri!
