### ISSUE TITLE
Creates extra zsh session for each real zsh session.

### ISSUE THREAD

**Issue by reportaman** [sindresorhus/pure#612]
### General information
After using this (via zinit method), doing ``ps -l`` in a tty reveals that each shell has an extra shell that gets created. Can that be avoided??

In the code listing below, ttys000 is the real tty of the terminal, and ttys001 is automatically created only if pure is used! 
```
~
❯ ps -l
  UID   PID  PPID        F CPU PRI NI       SZ    RSS WCHAN     S             ADDR TTY           TIME CMD
  501 42266 42265     4106   0  31  0 408301408   6176 -      Ss                  0 ttys000    0:00.37 -zsh
  501 42280 42266      106   0  16 15  4571824   2768 -      SNs+                0 ttys001    0:00.01 -zsh
```

#### I have:

- [x] Tested with another terminal program and can reproduce the issue: 
- [x] Followed the [integration](https://github.com/sindresorhus/pure#integration) instructions for my framework

### My `.zshrc`:

```shell
zinit ice pick"async.zsh" src"pure.zsh"
zinit light sindresorhus/pure
```

**Comment by mafredri** [comment]
This is expected behavior. The second process is a clone of the first one, created by `zpty`. It is the async worker (used by `zsh-async`). The only way to avoid this would be to destroy the worker after the work is done. But this would add a small delay every time a new worker needs to be started.
