### ISSUE TITLE
Disable path

### ISSUE THREAD

**Issue by Waxxx333** [sindresorhus/pure#617]
How can I disable the path above the prompt ?

**Comment by sindresorhus** [comment]
Pure does not have an option to disable showing the path. You are free to modify it as you see fit, but it's not something we want to officially support.

We have documented how to make the prompt a single line: https://github.com/sindresorhus/pure/wiki/Customizations,-hacks-and-tweaks#single-line-prompt

**Comment by Waxxx333** [comment]
Okay, thanks for the quick reply. I'll figure something out.
