### ISSUE TITLE
Warp terminal incompatibility 

### ISSUE THREAD

**Issue by wanbinkimoon** [sindresorhus/pure#650]
### General information
Warp terminal is a very cool tool and enable new feature in the terminal 
https://app.warp.dev/

I would love to use both pure and Warp but apparently there are some incompatibility issues 

#### System report (output of `prompt_pure_system_report`):

```
- Zsh: zsh 5.8.1 (x86_64-apple-darwin21.0) (/bin/zsh)
- Operating system: macOS 12.6 (21G115)
- Terminal program: WarpTerminal (v0.2022.11.14.14.55.stable_01)
- Tmux: no
- Git: git version 2.37.0 (Apple Git-136)
- Pure state:
    - username: `''`
    - prompt: `❯`
    - version: `1.20.1`
- zsh-async version: `1.8.5`
- PROMPT: ``
- Colors: `typeset -g -A prompt_pure_colors=( [execution_time]=yellow [git:action]=yellow [git:arrow]=cyan [git:branch]=242 [git:branch:cached]=red [git:dirty]=218 [git:stash]=cyan [host]=242 [path]=blue [prompt:continuation]=242 [prompt:error]=red [prompt:success]=magenta [suspended_jobs]=red [user]=242 [user:root]=default [virtualenv]=242 )`
- TERM: `export TERM=xterm-256color`
- Virtualenv: `export VIRTUAL_ENV_DISABLE_PROMPT=12`
- Conda: `export CONDA_CHANGEPS1=false`
- Detected frameworks: Oh My Zsh
    - Oh My Zsh:
        - Plugins: git, z, macos, brew, zsh-syntax-highlighting
```

#### I have:

- [x] Tried to apply `ZSH_THEME="pure"` in `~/.zshrc` 

### Problem description

This is how I would expect my prompt to look like (iterm 2) 
![Screenshot 2022-11-17 at 10 48 28](https://user-images.githubusercontent.com/10087639/202413209-e7a06998-fa10-4fdc-b819-d1030254754a.png)

this is how it looks on warp terminal
![Screenshot 2022-11-17 at 10 49 17](https://user-images.githubusercontent.com/10087639/202413429-317a0988-0995-49f4-85f4-60b788f4b981.png)
basically is missing every above the command line information 

### Reproduction steps

1. Install Warp `brew install warp` 
2. Apply custom prompt `cmd + shift + P` digit `prompt` and choose `Honor user's custom prompt (PS1)`

### Useful links 
- https://github.com/warpdotdev/Warp/discussions/422
- https://docs.warp.dev/features/prompt

### My `.zshrc`:
```
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="agnoster"
plugins=(git z macos brew zsh-syntax-highlighting)
source $ZSH/oh-my-zsh.sh
eval $(/opt/homebrew/bin/brew shellenv)
eval "$(direnv hook zsh)"
fpath+=/opt/homebrew/share/zsh/site-functions
autoload -U promptinit; promptinit
prompt pure
export PATH="$PATH:/Users/nicolabertelloni/Developer/flutter/bin"
export NVM_DIR="$HOME/.nvm"
[ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"  
[ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/
etc/bash_completion.d/nvm"  
```

**Comment by mafredri** [comment]
I think it would be better to open up a feature request for Warp in this instance. It's not that we're incompatible with Warp, it's Warp that's incompatible with us (and many other prompts).

Looking at their [compatibility table](https://docs.warp.dev/features/prompt#custom-prompt-compatibility-table) only a few prompts seems to be listed. They also [don't support multi-line prompts](https://docs.warp.dev/features/prompt#multi-line-and-right-sided-prompts) which is a requirement for Pure.
