### ISSUE TITLE
znap pull fails after update to macOS Ventura

### ISSUE THREAD

**Issue by igorkulman** [sindresorhus/pure#651]
#### System report (output of `prompt_pure_system_report`):

- Zsh: zsh 5.8.1 (x86_64-apple-darwin22.0) (/bin/zsh)
- Operating system: macOS 13.1 (22C65)
- Terminal program: iTerm.app (3.4.18)
- Tmux: no
- Git: git version 2.39.0
- Pure state:
    - username: `''`
    - prompt: `❯`
    - version: `1.20.4`
- zsh-async version: `1.8.4`
- PROMPT: `typeset -g PROMPT=$'%F{${prompt_pure_colors[path]}}%~%f %F{242}${prompt_pure_vcs_info[branch]}%F{218}${prompt_pure_git_dirty}%f
%{
%}%(12V.%F{$prompt_pure_colors[virtualenv]}%12v%f .)%(?.%F{$prompt_pure_colors[prompt:success]}.%F{$prompt_pure_colors[prompt:error]})${prompt_pure_state[prompt]}%f %{]133;B%}'`
- Colors: `typeset -g -A prompt_pure_colors=( [execution_time]=yellow [git:action]=yellow [git:arrow]=cyan [git:branch]=242 [git:branch:cached]=red [git:dirty]=218 [git:stash]=cyan [host]=242 [path]=cyan [prompt:continuation]=242 [prompt:error]=red [prompt:success]=green [suspended_jobs]=red [user]=242 [user:root]=default [virtualenv]=242 )`
- TERM: `export TERM=xterm-256color`
- Virtualenv: `export VIRTUAL_ENV_DISABLE_PROMPT=12`
- Conda: `export CONDA_CHANGEPS1=no`
- Detected frameworks: None

#### I have:

- [x] Tested with another terminal program and can reproduce the issue: 
- [x] Followed the [integration](https://github.com/sindresorhus/pure#integration) instructions for my framework

### Problem description

After updating to macOS Ventura `znap pull` fails for me with git errors

```zsh
❯ znap pull
From https://github.com/sindresorhus/pure
 * branch            main       -> FETCH_HEAD
BUG: run-command.c:1521: you must provide a non-zero number of processes!
From https://github.com/marlonrichert/zsh-autocomplete
 * branch            main       -> FETCH_HEAD
BUG: run-command.c:1521: you must provide a non-zero number of processes!
From https://github.com/zsh-users/zsh-autosuggestions
 * branch            master     -> FETCH_HEAD
BUG: run-command.c:1521: you must provide a non-zero number of processes!
From https://github.com/marlonrichert/zsh-snap
 * branch            main       -> FETCH_HEAD
BUG: run-command.c:1521: you must provide a non-zero number of processes!
From https://github.com/zsh-users/zsh-syntax-highlighting
 * branch            master     -> FETCH_HEAD
BUG: run-command.c:1521: you must provide a non-zero number of processes!
```

### Reproduction steps

1. znap pull

### My `.zshrc`:

```zsh
# zsnap
[[ -f ~/.zsh/zsh-snap/znap.zsh ]] ||
    git clone --depth 1 https://github.com/marlonrichert/zsh-snap.git ~/.zsh/zsh-snap

source ~/.zsh/zsh-snap/znap.zsh

# pure prompt
znap prompt sindresorhus/pure

# Zsh plugins
znap source zsh-users/zsh-syntax-highlighting
znap source zsh-users/zsh-autosuggestions

# Zsh settings
zle_bracketed_paste=()
zle_highlight+=(paste:none)

unsetopt prompt_cr prompt_sp

zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'

znap eval rbenv-init 'rbenv init -'
znap eval iterm2 'curl -fsSL https://iterm2.com/shell_integration/zsh'
```

**Comment by mafredri** [comment]
I don’t see any error originating from Pure here, the BUG lines originate from znap, I would recommend opening an issue over there.

If you think my conclusion is wrong, please provide additional details showing the issue from Pure.
