### ISSUE TITLE
Is it still supported or already deprecated?

### ISSUE THREAD

**Issue by iamtodor** [sindresorhus/pure#663]
Basically, what the title says I'm wondering whether the `pure` is still supported and maintained or is under deprecation in advance to some other prompt?

**Comment by sindresorhus** [comment]
It's fully supported. The lack of activity is just because it's quite mature.

**Comment by iamtodor** [comment]
@sindresorhus I see, thank you. Just to add the context to the question, I noticed a lot of issues are opened and the last commit was on June 25 :)
