### ISSUE TITLE
New blue chevron/triangle symbol after updating OhMyZsh

### ISSUE THREAD

**Issue by FynnZW** [sindresorhus/pure#665]
### General information
After updating OhMyZsh, there's now a new blue chevron and the end of each prompt (bottom left).
![Screen 2023-11-30 at 11 21 46@2x](https://github.com/sindresorhus/pure/assets/14918334/35de125e-d26b-4de9-9a9b-ba909997a801)

When I disable the pure theme, it's no longer there, so it seems to be coming from this theme.

<img width="263" alt="Screen 2023-11-30 at 11 27 36@2x" src="https://github.com/sindresorhus/pure/assets/14918334/8f2a5067-a676-407e-88cf-16fce2fa068c">  

(for example, 'agnoster' theme does not show it).

It's not so bad, but I really preferred the cleaner look before. 
Where does it come from? And is it possible to remove it again?

#### System report (output of `prompt_pure_system_report`):

- Zsh: zsh 5.9 (x86_64-apple-darwin22.0) (/bin/zsh)
- Operating system: macOS 13.4.1 (22F770820d)
- Terminal program: iTerm.app (3.4.22)
- Tmux: no
- Git: git version 2.39.2 (Apple Git-143)
- Pure state:
    - username: `''`
    - prompt: `❯`
    - version: `1.22.0`
- zsh-async version: `1.8.5`
- PROMPT: `typeset -g PROMPT=$'%F{${prompt_pure_colors[path]}}%~%f %F{242}${prompt_pure_vcs_info[branch]}%F{218}${prompt_pure_git_dirty}%f
%{
%}%(12V.%F{$prompt_pure_colors[virtualenv]}%12v%f .)%(?.%F{$prompt_pure_colors[prompt:success]}.%F{$prompt_pure_colors[prompt:error]})${prompt_pure_state[prompt]}%f '`
- Colors: `typeset -g -A prompt_pure_colors=( [execution_time]=yellow [git:action]=yellow [git:arrow]=cyan [git:branch]=242 [git:branch:cached]=red [git:dirty]=218 [git:stash]=cyan [host]=242 [path]=blue [prompt:continuation]=242 [prompt:error]=red [prompt:success]=magenta [suspended_jobs]=red [user]=242 [user:root]=default [virtualenv]=242 )`
- TERM: `export TERM=xterm-256color`
- Virtualenv: `export VIRTUAL_ENV_DISABLE_PROMPT=12`
- Conda: `export CONDA_CHANGEPS1=no`
- Detected frameworks: Oh My Zsh
    - Oh My Zsh:
        - Plugins: git, fzf, fd, autojump, zsh-syntax-highlighting

### Versions
OhMyZsh: master (418046e9)
Pure: v1.22

### My `.zshrc`:
(manual installation of pure)
```shell
fpath+=$HOME/.zsh/pure
autoload -U promptinit; promptinit
prompt pure
```

**Comment by mafredri** [comment]
I'm not sure why you're not seeing it in other themes, but this is an iTerm setting (Profiles -> Terminal -> Show mark indicators).

It's also weird how they appears on the empty line for you. For me they appear just in front of `❯` when enabled. Might be due to OMZ.

**Comment by FynnZW** [comment]
Great, that solved it! 
Yes, strange it only showed up in this theme. 
Thanks for the help
