### ISSUE TITLE
Doc Request: How to add & create new prompt status bits

### ISSUE THREAD

**Issue by nicktimko** [sindresorhus/pure#686]
If I want to create an additional snippet and add it to my prompt status, like the Git branch and other info, are there docs about doing so?

Is there a way without patching the changes it into the `pure.zsh` file (i.e. some sort of extension/plugin facility)?

**Comment by mafredri** [comment]
It’s currently not possible without modifying Pure. It’s something we’re interested in supporting, however, see https://github.com/sindresorhus/pure/issues/460.

I’m closing this as a duplicate.
