### ISSUE TITLE
Git push/pull arrows overlapping username when over SSH

### ISSUE THREAD

**Issue by ptamarit** [sindresorhus/pure#70]
This is how the prompt looks like for a repository ahead of its origin over SSH:
![pure-arrows-ssh](https://cloud.githubusercontent.com/assets/2046893/3138997/c48ddf90-e8bf-11e3-8482-a8b7c9c22c49.png)

I looks to me like `$prompt_pure_username` is completely ignored in `prompt_pure_string_length`, but I don't have enough shell scripting skills to fix it :(

**Comment by bentomas** [comment]
This might have happened where you typed your `ssh` command very quickly, and the arrow you're seeing is actually from the prompt above this one.

**Comment by ptamarit** [comment]
Hi,

Sorry for the late answer. I still have this issue, but if I'm the only then it's probably my fault :)
It still does the job though (I can immediately see that there are some changes upstream).

Thanks for the great theme BTW.

Cheers,
Pablo
