### ISSUE TITLE
Shell gets stuck in a loop if private git repo and using https without authentication

### ISSUE THREAD

**Issue by pgilad** [sindresorhus/pure#76]
Steps to reproduce: 
1. Use a git with https and no authentication (or cache of authentication)
2. Be in a **private** git repo. (where authentication is required for read)

Shell then asks for git username, but anything you enter is evaluated as a zsh command, meaning you can't even try to actually login.

I think that the solution would be to detect if user doesn't have read permissions in a git repo - and then don't try to async evaluate remote git status (for git pull/push).

Hope that makes sense... Ran into this issue in several colleagues workspace where they used https in private repos.

**Comment by bfred-it** [comment]
Yeah there seems to be an issue when git expects input:

![screen shot 2015-01-23 at 16 28 52](https://cloud.githubusercontent.com/assets/1402241/5877064/f613a96a-a31c-11e4-8dca-a70f5107540f.png)

![screen shot 2015-01-23 at 16 29 52](https://cloud.githubusercontent.com/assets/1402241/5877076/151228c8-a31d-11e4-974a-5bef814a6f8e.png)

Anything you type is considered a normal command, it doesn't answer the prompt.

**Comment by sindresorhus** [comment]
Not going to make it GitHub specific.

Pure is already running non-interactively so nothing should be prompted. Happy to receive a PR with a fix but I have no idea how to fix this.

**Comment by MoOx** [comment]
Maybe a comment in a FAQ section in the README is a start :) (quick fix: type git pull to auth)

**Comment by sindresorhus** [comment]
@MoOx Sure, if you care enough to do a PR.

**Comment by sindresorhus** [comment]
This has been fixed in git 2.3 :D

See: https://github.com/sindresorhus/pure/commit/f43ab97e1cf4a276b7a6e33eac055ee16610be15

**Comment by MoOx** [comment]
Very nice.

**Comment by fkirkholt** [comment]
I still get this error on my Mac with git version 2.3.5.

**Comment by dalymatthew** [comment]
Same here, running pure prompt 0.5.1 on Yosemite with git 2.3.5.

**Comment by mafredri** [comment]
@fkirkholt @dalymatthew are you sure you aren't resetting the `GIT_TERMINAL_PROMPT` environment variable after pure has been initialized? Mind checking

```shell
echo $GIT_TERMINAL_PROMPT
```
?

**Comment by dalymatthew** [comment]
```sh
~
λ echo $GIT_TERMINAL_PROMPT
0
```
My ~/.zshrc and ~/.zshrc.local are just stock grml, apart from the following in the latter:
```sh
autoload -U promptinit && promptinit
PURE_PROMPT_SYMBOL=λ
prompt pure
```
I double-checked and `GIT_TERMINAL_PROMPT` isn't getting reset anywhere.

**Comment by mafredri** [comment]
Well, then I'm out of ideas. Unable to reproduce.

**Comment by neonstalwart** [comment]
by running the commands in pure.zsh one at a time i found this one to be the one which prompts:

```sh
> command git -c gc.auto=0 fetch &>/dev/null
```

is it a git bug?

**Comment by mafredri** [comment]
@neonstalwart either `command git --version` is < 2.3 or `GIT_TERMINAL_PROMPT` is not set to zero. Besides that, `&>/dev/null` is supposed to swallow _all_ output, so no clue.

**Comment by neonstalwart** [comment]
@mafredri git version is 2.4 and GIT_TERMINAL_PROMPT is 0 - with that exact command above i see a prompt for a password.  i'm trying to make sense of it.

**Comment by mafredri** [comment]
Tried upgrading to 2.4.0, still cannot reproduce:
```shell
❯ GIT_TERMINAL_PROMPT=0 command git -c gc.auto=0 fetch
fatal: could not read Password for 'https://xxx@bitbucket.org': terminal prompts disabled
```

**Comment by neonstalwart** [comment]
so, in my case i think it was ssh which was prompting for the password.  my remote is actually `git@git.XXXXX.com:path/to/repo.git`

```sh
> GIT_TRACE=true GIT_TERMINAL_PROMPT=0 command git -c gc.auto=0 fetch
11:54:32.597755 git.c:348               trace: built-in: git 'fetch'
11:54:32.600003 run-command.c:347       trace: run_command: 'ssh' 'git@git.XXXXX.com' 'git-upload-pack '\''path/to/repo.git'\'''
Password:
```

updated ~/.ssh/config with the following and it stops prompting now
```
Host git.XXXXX.com
	KbdInteractiveAuthentication no
	ChallengeResponseAuthentication no
	PasswordAuthentication no
```

**Comment by bucaran** [comment]
I am not sure if this is exactly the same issue, but I was having a similar problem when running a `git clone` from one of my projects and was able to fix it using:

```fish
set -lx GIT_ASKPASS /bin/echo
```

which translated to bash gives

```
export GIT_ASKPASS=/bin/echo
```
