### ISSUE TITLE
Minimal zsh config with pure

### ISSUE THREAD

**Issue by hydrajump** [sindresorhus/pure#78]
`pure` is very nice, but I wish there was a minimal zsh config that not only included `pure`, but also other sane settings for history, colours and possibly other essentials.

This is what I currently have as a starting point on OS X,

`.zshrc`:
```shell
# For Homebrew
export PATH=/usr/local/bin:/usr/local/sbin:$PATH

fpath=( "$HOME/.zfunctions" $fpath )

# Initialise prompt system and choose "pure"
autoload -U promptinit && promptinit
prompt pure
```

`$HOME/.zfunctions`:
```shell
.zfunctions
├── prompt_pure_setup -> /Users/hydrajump/.zfunctions/pure/pure.zsh
└── pure
    ├── arch
    │   └── PKGBUILD
    ├── package.json
    ├── pure.plugin.zsh -> pure.zsh
    ├── pure.zsh
    ├── readme.md
    ├── screenshot-title-cmd.png
    └── screenshot.png

2 directories, 8 files
```

**Comment by sindresorhus** [comment]
I'm planning to publish my dotfiles which will be something like what you're asking.

You can subscribe to https://github.com/sindresorhus/todo/issues/11 to get notified.
