### ISSUE TITLE
Issue with a new git repo

### ISSUE THREAD

**Issue by MoOx** [sindresorhus/pure#91]
Step to reproduce:
- create a git repo

From point A (me)
- use "Setup on Desktop" button
- code some stuff

From point B (a friend that push something before me)
- setup too 
- push some code to the repo

From point A (me again, one day after)
- get back in the local repo with the pure prompt:

```console
~/Sync/Development/cssrecipes  
$ cd utils

~/Sync/Development/cssrecipes/utils master*  
$ prompt_pure_precmd:21: bad math expression: operand expected at `> 0 '
prompt_pure_precmd:22: bad math expression: operand expected at `> 0 '
```

Not sure what is causing the issue

**Comment by sindresorhus** [comment]
Hmm, I can't reproduce either.

Are you sure you're running the latest version from this repo? There are some outdated ports out there.

Can you also try the following:

```diff
-(( $(command git rev-list --right-only --count HEAD...@'{u}' 2>/dev/null) > 0 )) && arrows='⇣'
-(( $(command git rev-list --left-only --count HEAD...@'{u}' 2>/dev/null) > 0 )) && arrows+='⇡'
+(( $(command git rev-list --right-only --count HEAD...@'{u}' 2>/dev/null)0 > 0 )) && arrows='⇣'
+(( $(command git rev-list --left-only --count HEAD...@'{u}' 2>/dev/null)0 > 0 )) && arrows+='⇡'

**Comment by MoOx** [comment]
Didn't have time to reproduce right now. Feel free to close this, this can still be reopened if needed.
